/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Sat Jul 16 03:09:57 2016
 *                 Full Compile MD5 Checksum  c67432c6c20f2afbcffe6eac2d8ee82b
 *                     (minus title and desc)
 *                 MD5 Checksum               4f55c4aac1500ad6cc55490046d0d006
 *
 * lock_release:   r15414
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1066
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_CNTCONTROLBASE_H__
#define BCHP_CNTCONTROLBASE_H__

/***************************************************************************
 *CNTControlBase - CPU System Counter Control Base
 ***************************************************************************/
#define BCHP_CNTControlBase_CNTCR                0x00412000 /* [RW] CPU System Counter Control Register */
#define BCHP_CNTControlBase_CNTSR                0x00412004 /* [RO] CPU System Counter Status Register */
#define BCHP_CNTControlBase_CNTCV_LO             0x00412008 /* [RW] CPU System Counter Count Value Lower Register (Bits 31 to 0) */
#define BCHP_CNTControlBase_CNTCV_HI             0x0041200c /* [RW] CPU System Counter Count Value Upper Register (Bits 63 to 32) */
#define BCHP_CNTControlBase_CNTFID0              0x00412020 /* [RO] CPU System Counter Frequency ID Register 0 */
#define BCHP_CNTControlBase_CNTFID1              0x00412024 /* [RO] CPU System Counter Frequency ID Register 1 */
#define BCHP_CNTControlBase_CounterID0           0x00412fd0 /* [RO] CPU System Counter ID 0 Register */
#define BCHP_CNTControlBase_CounterID1           0x00412fd4 /* [RO] CPU System Counter ID 1 Register */
#define BCHP_CNTControlBase_CounterID2           0x00412fd8 /* [RO] CPU System Counter ID 2 Register */
#define BCHP_CNTControlBase_CounterID3           0x00412fdc /* [RO] CPU System Counter ID 3 Register */
#define BCHP_CNTControlBase_CounterID4           0x00412fe0 /* [RO] CPU System Counter ID 4 Register */
#define BCHP_CNTControlBase_CounterID5           0x00412fe4 /* [RO] CPU System Counter ID 5 Register */
#define BCHP_CNTControlBase_CounterID6           0x00412fe8 /* [RO] CPU System Counter ID 6 Register */
#define BCHP_CNTControlBase_CounterID7           0x00412fec /* [RO] CPU System Counter ID 7 Register */
#define BCHP_CNTControlBase_CounterID8           0x00412ff0 /* [RO] CPU System Counter ID 8 Register */
#define BCHP_CNTControlBase_CounterID9           0x00412ff4 /* [RO] CPU System Counter ID 9 Register */
#define BCHP_CNTControlBase_CounterID10          0x00412ff8 /* [RO] CPU System Counter ID 10 Register */
#define BCHP_CNTControlBase_CounterID11          0x00412ffc /* [RO] CPU System Counter ID 11 Register */

/***************************************************************************
 *CNTCR - CPU System Counter Control Register
 ***************************************************************************/
/* CNTControlBase :: CNTCR :: reserved0 [31:09] */
#define BCHP_CNTControlBase_CNTCR_reserved0_MASK                   0xfffffe00
#define BCHP_CNTControlBase_CNTCR_reserved0_SHIFT                  9

/* CNTControlBase :: CNTCR :: FCREQ [08:08] */
#define BCHP_CNTControlBase_CNTCR_FCREQ_MASK                       0x00000100
#define BCHP_CNTControlBase_CNTCR_FCREQ_SHIFT                      8
#define BCHP_CNTControlBase_CNTCR_FCREQ_DEFAULT                    0x00000000
#define BCHP_CNTControlBase_CNTCR_FCREQ_RESET_FREQ_ONE_HOT         0
#define BCHP_CNTControlBase_CNTCR_FCREQ_BASE_FREQ_ONE_HOT          1

/* CNTControlBase :: CNTCR :: reserved1 [07:02] */
#define BCHP_CNTControlBase_CNTCR_reserved1_MASK                   0x000000fc
#define BCHP_CNTControlBase_CNTCR_reserved1_SHIFT                  2

/* CNTControlBase :: CNTCR :: HDBG [01:01] */
#define BCHP_CNTControlBase_CNTCR_HDBG_MASK                        0x00000002
#define BCHP_CNTControlBase_CNTCR_HDBG_SHIFT                       1
#define BCHP_CNTControlBase_CNTCR_HDBG_DEFAULT                     0x00000000

/* CNTControlBase :: CNTCR :: EN [00:00] */
#define BCHP_CNTControlBase_CNTCR_EN_MASK                          0x00000001
#define BCHP_CNTControlBase_CNTCR_EN_SHIFT                         0
#define BCHP_CNTControlBase_CNTCR_EN_DEFAULT                       0x00000000

/***************************************************************************
 *CNTSR - CPU System Counter Status Register
 ***************************************************************************/
/* CNTControlBase :: CNTSR :: reserved0 [31:09] */
#define BCHP_CNTControlBase_CNTSR_reserved0_MASK                   0xfffffe00
#define BCHP_CNTControlBase_CNTSR_reserved0_SHIFT                  9

/* CNTControlBase :: CNTSR :: FCACK [08:08] */
#define BCHP_CNTControlBase_CNTSR_FCACK_MASK                       0x00000100
#define BCHP_CNTControlBase_CNTSR_FCACK_SHIFT                      8
#define BCHP_CNTControlBase_CNTSR_FCACK_DEFAULT                    0x00000000
#define BCHP_CNTControlBase_CNTSR_FCACK_RESET_FREQ_ONE_HOT         0
#define BCHP_CNTControlBase_CNTSR_FCACK_BASE_FREQ_ONE_HOT          1

/* CNTControlBase :: CNTSR :: reserved1 [07:02] */
#define BCHP_CNTControlBase_CNTSR_reserved1_MASK                   0x000000fc
#define BCHP_CNTControlBase_CNTSR_reserved1_SHIFT                  2

/* CNTControlBase :: CNTSR :: DBGH [01:01] */
#define BCHP_CNTControlBase_CNTSR_DBGH_MASK                        0x00000002
#define BCHP_CNTControlBase_CNTSR_DBGH_SHIFT                       1

/* CNTControlBase :: CNTSR :: reserved2 [00:00] */
#define BCHP_CNTControlBase_CNTSR_reserved2_MASK                   0x00000001
#define BCHP_CNTControlBase_CNTSR_reserved2_SHIFT                  0

/***************************************************************************
 *CNTCV_LO - CPU System Counter Count Value Lower Register (Bits 31 to 0)
 ***************************************************************************/
/* CNTControlBase :: CNTCV_LO :: CountValue [31:00] */
#define BCHP_CNTControlBase_CNTCV_LO_CountValue_MASK               0xffffffff
#define BCHP_CNTControlBase_CNTCV_LO_CountValue_SHIFT              0
#define BCHP_CNTControlBase_CNTCV_LO_CountValue_DEFAULT            0x00000000

/***************************************************************************
 *CNTCV_HI - CPU System Counter Count Value Upper Register (Bits 63 to 32)
 ***************************************************************************/
/* CNTControlBase :: CNTCV_HI :: CountValue [31:00] */
#define BCHP_CNTControlBase_CNTCV_HI_CountValue_MASK               0xffffffff
#define BCHP_CNTControlBase_CNTCV_HI_CountValue_SHIFT              0
#define BCHP_CNTControlBase_CNTCV_HI_CountValue_DEFAULT            0x00000000

/***************************************************************************
 *CNTFID0 - CPU System Counter Frequency ID Register 0
 ***************************************************************************/
/* CNTControlBase :: CNTFID0 :: CNTFID [31:00] */
#define BCHP_CNTControlBase_CNTFID0_CNTFID_MASK                    0xffffffff
#define BCHP_CNTControlBase_CNTFID0_CNTFID_SHIFT                   0
#define BCHP_CNTControlBase_CNTFID0_CNTFID_DEFAULT                 0x019bfcc0

/***************************************************************************
 *CNTFID1 - CPU System Counter Frequency ID Register 1
 ***************************************************************************/
/* CNTControlBase :: CNTFID1 :: CNTFID [31:00] */
#define BCHP_CNTControlBase_CNTFID1_CNTFID_MASK                    0xffffffff
#define BCHP_CNTControlBase_CNTFID1_CNTFID_SHIFT                   0
#define BCHP_CNTControlBase_CNTFID1_CNTFID_DEFAULT                 0x00000000

/***************************************************************************
 *CounterID0 - CPU System Counter ID 0 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID0 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID0_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID0_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID0_COUNTERID_DEFAULT           0x00000001

/***************************************************************************
 *CounterID1 - CPU System Counter ID 1 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID1 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID1_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID1_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID1_COUNTERID_DEFAULT           0x00000000

/***************************************************************************
 *CounterID2 - CPU System Counter ID 2 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID2 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID2_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID2_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID2_COUNTERID_DEFAULT           0x00000000

/***************************************************************************
 *CounterID3 - CPU System Counter ID 3 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID3 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID3_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID3_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID3_COUNTERID_DEFAULT           0x00000000

/***************************************************************************
 *CounterID4 - CPU System Counter ID 4 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID4 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID4_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID4_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID4_COUNTERID_DEFAULT           0x00000064

/***************************************************************************
 *CounterID5 - CPU System Counter ID 5 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID5 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID5_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID5_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID5_COUNTERID_DEFAULT           0x000000f3

/***************************************************************************
 *CounterID6 - CPU System Counter ID 6 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID6 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID6_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID6_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID6_COUNTERID_DEFAULT           0x0000000d

/***************************************************************************
 *CounterID7 - CPU System Counter ID 7 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID7 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID7_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID7_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID7_COUNTERID_DEFAULT           0x00000000

/***************************************************************************
 *CounterID8 - CPU System Counter ID 8 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID8 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID8_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID8_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID8_COUNTERID_DEFAULT           0x0000000d

/***************************************************************************
 *CounterID9 - CPU System Counter ID 9 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID9 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID9_COUNTERID_MASK              0xffffffff
#define BCHP_CNTControlBase_CounterID9_COUNTERID_SHIFT             0
#define BCHP_CNTControlBase_CounterID9_COUNTERID_DEFAULT           0x000000f0

/***************************************************************************
 *CounterID10 - CPU System Counter ID 10 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID10 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID10_COUNTERID_MASK             0xffffffff
#define BCHP_CNTControlBase_CounterID10_COUNTERID_SHIFT            0
#define BCHP_CNTControlBase_CounterID10_COUNTERID_DEFAULT          0x00000005

/***************************************************************************
 *CounterID11 - CPU System Counter ID 11 Register
 ***************************************************************************/
/* CNTControlBase :: CounterID11 :: COUNTERID [31:00] */
#define BCHP_CNTControlBase_CounterID11_COUNTERID_MASK             0xffffffff
#define BCHP_CNTControlBase_CounterID11_COUNTERID_SHIFT            0
#define BCHP_CNTControlBase_CounterID11_COUNTERID_DEFAULT          0x000000b1

#endif /* #ifndef BCHP_CNTCONTROLBASE_H__ */

/* End of File */
