/***************************************************************************
 *     Copyright (c) 2002-2013, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * $brcm_Workfile: $
 * $brcm_Revision: $
 * $brcm_Date: $
 *
 * Module Description:
 *
 * Revision History:
 *
 * $brcm_Log: $
 *
 ***************************************************************************/

#ifndef SPLASH_VDC_SETUP_H__
#define SPLASH_VDC_SETUP_H__

#include "splash_magnum.h"

/* for CFE to know the script loader version in compile time */
#define SPLASH_SCRIPT_LOADER_VER        2

/* basic info of a surface */
typedef struct
{
	int                    ihMemIdx;        /* this surface is allocated from *(phMem+ihMemIdx) */
	BPXL_Format            ePxlFmt;         /* pixel format */
    uint32_t               ulWidth;
    uint32_t               ulHeight;
    uint32_t               ulPitch;
	char                   bmpFile[256];    /* bmp file in splashgen */
} SplashSurfaceInfo;

/* basic info of a display */
typedef struct
{
	int                    iSurIdx;        /* uses surface buffer from *(phHeap+ihMemIdx) */
	BFMT_VideoFmt          eDspFmt;        /* display video format */
	uint32_t               ulRdcScratchReg0;
	uint32_t               ulRdcScratchReg1;
} SplashDisplayInfo;

typedef struct
{
    int TriggerHwNum;          /* The hardware position of the trigger */
    int SlotNum;               /* The RDMA slot correposponding to the trigger */
    int ListCountMaxIndex;     /* The Max Index of the ListCount Array */
    uint32_t *aListCountArray; /* The list count array pointer */
    uint32_t *aListArray;      /* The list array pointer */
}
SplashTriggerMap;

/* All data generated by splashgen */
typedef struct
{
    unsigned long ulNumMem;
    int iRulMemIdx;
    int iNumSurface;
    SplashSurfaceInfo* pSurfInfo;
    int iNumDisplay;
    SplashDisplayInfo* pDispInfo;
	int iNumTrigMap;
    SplashTriggerMap* pTrigMap;
	int nAulReg;
    uint32_t* pAulReg;
}
SplashData;

/* -----------------------------------------------------------------
 * note to CFE developer:
 * 1). each surface buffer must be located in the section controlled
 *     by the right memory controler. Otherwise you see black screen
 * 2). the order in the aulSurfaceBufOffset array must match
 *     g_SplashSurface in splash_vdc_rul_def.h
 */
/* PORT POINT: if we have more than 4 mem heaps or surfaces */
#define SPLASH_MAX_SURFACE     4
typedef struct
{
	BMEM_Handle  hRulMem; /* heap used by VDC for RULs, CFE can pass NULL */
	uint32_t     aulSurfaceBufOffset[SPLASH_MAX_SURFACE];
} SplashBufInfo;

#define BSPLASH_SURFACE_BUF_SIZE(pSur)   ((pSur)->ulHeight * (pSur)->ulPitch)
void splash_bvn_init  (
BREG_Handle hRegister, SplashBufInfo *pSplashBufInfo, SplashData* pSplashData);
void splash_bvn_uninit(BREG_Handle hRegister, SplashBufInfo *pSplashBufInfo);

#endif
