/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Nov 23 01:10:03 2017
 *                 Full Compile MD5 Checksum  9c249593c44f5a3709c1aa2deb2a32b9
 *                     (minus title and desc)
 *                 MD5 Checksum               bedd24dac2c620a65db09cca853e657e
 *
 * lock_release:   r_1255
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_UPG_MAIN_IRQ_H__
#define BCHP_UPG_MAIN_IRQ_H__

/***************************************************************************
 *UPG_MAIN_IRQ - UPG Main Level 2 Interrupt Enable/Status
 ***************************************************************************/
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS             0x002040a500 /* [RO][32] CPU interrupt Status Register */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS        0x002040a504 /* [RO][32] CPU interrupt Mask Status Register */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET           0x002040a508 /* [WO][32] CPU interrupt Mask Set Register */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR         0x002040a50c /* [WO][32] CPU interrupt Mask Clear Register */
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS             0x002040a510 /* [RO][32] PCI interrupt Status Register */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS        0x002040a514 /* [RO][32] PCI interrupt Mask Status Register */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET           0x002040a518 /* [WO][32] PCI interrupt Mask Set Register */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR         0x002040a51c /* [WO][32] PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: CPU_STATUS :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_reserved0_MASK                0xfffffff8
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_reserved0_SHIFT               3

/* UPG_MAIN_IRQ :: CPU_STATUS :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_SPARE_00_MASK                 0x00000004
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_SPARE_00_SHIFT                2
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_SPARE_00_DEFAULT              0x00000000

/* UPG_MAIN_IRQ :: CPU_STATUS :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_irb_MASK                      0x00000002
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_irb_SHIFT                     1
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_irb_DEFAULT                   0x00000000

/* UPG_MAIN_IRQ :: CPU_STATUS :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_gio_MASK                      0x00000001
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_gio_SHIFT                     0
#define BCHP_UPG_MAIN_IRQ_CPU_STATUS_gio_DEFAULT                   0x00000000

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: CPU_MASK_STATUS :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_reserved0_MASK           0xfffffff8
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_reserved0_SHIFT          3

/* UPG_MAIN_IRQ :: CPU_MASK_STATUS :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_SPARE_00_MASK            0x00000004
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_SPARE_00_SHIFT           2
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_SPARE_00_DEFAULT         0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_STATUS :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_irb_MASK                 0x00000002
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_irb_SHIFT                1
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_irb_DEFAULT              0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_STATUS :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_gio_MASK                 0x00000001
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_gio_SHIFT                0
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_STATUS_gio_DEFAULT              0x00000001

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: CPU_MASK_SET :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_reserved0_MASK              0xfffffff8
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_reserved0_SHIFT             3

/* UPG_MAIN_IRQ :: CPU_MASK_SET :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_SPARE_00_MASK               0x00000004
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_SPARE_00_SHIFT              2
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_SPARE_00_DEFAULT            0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_SET :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_irb_MASK                    0x00000002
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_irb_SHIFT                   1
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_irb_DEFAULT                 0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_SET :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_gio_MASK                    0x00000001
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_gio_SHIFT                   0
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_SET_gio_DEFAULT                 0x00000001

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: CPU_MASK_CLEAR :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_reserved0_MASK            0xfffffff8
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_reserved0_SHIFT           3

/* UPG_MAIN_IRQ :: CPU_MASK_CLEAR :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_SPARE_00_MASK             0x00000004
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_SPARE_00_SHIFT            2
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_SPARE_00_DEFAULT          0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_CLEAR :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_irb_MASK                  0x00000002
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_irb_SHIFT                 1
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_irb_DEFAULT               0x00000001

/* UPG_MAIN_IRQ :: CPU_MASK_CLEAR :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_gio_MASK                  0x00000001
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_gio_SHIFT                 0
#define BCHP_UPG_MAIN_IRQ_CPU_MASK_CLEAR_gio_DEFAULT               0x00000001

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: PCI_STATUS :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_reserved0_MASK                0xfffffff8
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_reserved0_SHIFT               3

/* UPG_MAIN_IRQ :: PCI_STATUS :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_SPARE_00_MASK                 0x00000004
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_SPARE_00_SHIFT                2
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_SPARE_00_DEFAULT              0x00000000

/* UPG_MAIN_IRQ :: PCI_STATUS :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_irb_MASK                      0x00000002
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_irb_SHIFT                     1
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_irb_DEFAULT                   0x00000000

/* UPG_MAIN_IRQ :: PCI_STATUS :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_gio_MASK                      0x00000001
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_gio_SHIFT                     0
#define BCHP_UPG_MAIN_IRQ_PCI_STATUS_gio_DEFAULT                   0x00000000

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: PCI_MASK_STATUS :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_reserved0_MASK           0xfffffff8
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_reserved0_SHIFT          3

/* UPG_MAIN_IRQ :: PCI_MASK_STATUS :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_SPARE_00_MASK            0x00000004
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_SPARE_00_SHIFT           2
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_SPARE_00_DEFAULT         0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_STATUS :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_irb_MASK                 0x00000002
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_irb_SHIFT                1
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_irb_DEFAULT              0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_STATUS :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_gio_MASK                 0x00000001
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_gio_SHIFT                0
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_STATUS_gio_DEFAULT              0x00000001

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: PCI_MASK_SET :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_reserved0_MASK              0xfffffff8
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_reserved0_SHIFT             3

/* UPG_MAIN_IRQ :: PCI_MASK_SET :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_SPARE_00_MASK               0x00000004
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_SPARE_00_SHIFT              2
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_SPARE_00_DEFAULT            0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_SET :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_irb_MASK                    0x00000002
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_irb_SHIFT                   1
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_irb_DEFAULT                 0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_SET :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_gio_MASK                    0x00000001
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_gio_SHIFT                   0
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_SET_gio_DEFAULT                 0x00000001

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_MAIN_IRQ :: PCI_MASK_CLEAR :: reserved0 [31:03] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_reserved0_MASK            0xfffffff8
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_reserved0_SHIFT           3

/* UPG_MAIN_IRQ :: PCI_MASK_CLEAR :: SPARE_00 [02:02] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_SPARE_00_MASK             0x00000004
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_SPARE_00_SHIFT            2
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_SPARE_00_DEFAULT          0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_CLEAR :: irb [01:01] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_irb_MASK                  0x00000002
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_irb_SHIFT                 1
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_irb_DEFAULT               0x00000001

/* UPG_MAIN_IRQ :: PCI_MASK_CLEAR :: gio [00:00] */
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_gio_MASK                  0x00000001
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_gio_SHIFT                 0
#define BCHP_UPG_MAIN_IRQ_PCI_MASK_CLEAR_gio_DEFAULT               0x00000001

#endif /* #ifndef BCHP_UPG_MAIN_IRQ_H__ */

/* End of File */
