/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Nov 23 01:10:02 2017
 *                 Full Compile MD5 Checksum  9c249593c44f5a3709c1aa2deb2a32b9
 *                     (minus title and desc)
 *                 MD5 Checksum               bedd24dac2c620a65db09cca853e657e
 *
 * lock_release:   r_1255
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_MPM_CPU_CTRL_H__
#define BCHP_MPM_CPU_CTRL_H__

/***************************************************************************
 *MPM_CPU_CTRL - CPU Control Registers
 ***************************************************************************/
#define BCHP_MPM_CPU_CTRL_REVID                  0x0020d82300 /* [RO][32] MPM Revision ID */
#define BCHP_MPM_CPU_CTRL_RESET_CTRL             0x0020d82304 /* [RW][32] Reset Control Register */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL             0x0020d82308 /* [RW][32] Clock Control Register */
#define BCHP_MPM_CPU_CTRL_PM_CTRL                0x0020d8230c /* [RW][32] Power Management Control Register */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL              0x0020d82310 /* [RW][32] Control Register */
#define BCHP_MPM_CPU_CTRL_SW_SPARE0              0x0020d82318 /* [RW][32] Software Spare Register 0 */
#define BCHP_MPM_CPU_CTRL_SW_SPARE1              0x0020d8231c /* [RW][32] Software Spare Register 1 */
#define BCHP_MPM_CPU_CTRL_SW_SPARE2              0x0020d82320 /* [RW][32] Software Spare Register 2 */
#define BCHP_MPM_CPU_CTRL_SW_SPARE3              0x0020d82324 /* [RW][32] Software Spare Register 3 */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_ADDR          0x0020d82328 /* [RO][32] RBUS Error Address */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_DATA          0x0020d8232c /* [RO][32] RBUS Error Write Data */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_XAC           0x0020d82330 /* [RO][32] RBUS Error Transaction */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL          0x0020d82334 /* [RW][32] RBUS Error Control */
#define BCHP_MPM_CPU_CTRL_SYS_ADDR_OFFSET        0x0020d82338 /* [RW][32] System Address Offset Register */
#define BCHP_MPM_CPU_CTRL_FLASH_MEM_ADDR_OFFSET  0x0020d8233c /* [RW][32] Flash Memory Address Offset Register */
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL            0x0020d82340 /* [RW][32] SPI debug select */
#define BCHP_MPM_CPU_CTRL_STATUS                 0x0020d82344 /* [RO][32] Status Register */

/***************************************************************************
 *REVID - MPM Revision ID
 ***************************************************************************/
/* MPM_CPU_CTRL :: REVID :: reserved0 [31:16] */
#define BCHP_MPM_CPU_CTRL_REVID_reserved0_MASK                     0xffff0000
#define BCHP_MPM_CPU_CTRL_REVID_reserved0_SHIFT                    16

/* MPM_CPU_CTRL :: REVID :: MAJOR [15:08] */
#define BCHP_MPM_CPU_CTRL_REVID_MAJOR_MASK                         0x0000ff00
#define BCHP_MPM_CPU_CTRL_REVID_MAJOR_SHIFT                        8

/* MPM_CPU_CTRL :: REVID :: MINOR [07:00] */
#define BCHP_MPM_CPU_CTRL_REVID_MINOR_MASK                         0x000000ff
#define BCHP_MPM_CPU_CTRL_REVID_MINOR_SHIFT                        0

/***************************************************************************
 *RESET_CTRL - Reset Control Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: RESET_CTRL :: reserved0 [31:03] */
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_reserved0_MASK                0xfffffff8
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_reserved0_SHIFT               3

/* MPM_CPU_CTRL :: RESET_CTRL :: UART_RESET [02:02] */
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_UART_RESET_MASK               0x00000004
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_UART_RESET_SHIFT              2
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_UART_RESET_DEFAULT            0x00000000

/* MPM_CPU_CTRL :: RESET_CTRL :: CPU_RESET_LEVEL [01:01] */
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_LEVEL_MASK          0x00000002
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_LEVEL_SHIFT         1
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_LEVEL_DEFAULT       0x00000000

/* MPM_CPU_CTRL :: RESET_CTRL :: CPU_RESET_ONE_SHOT [00:00] */
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_ONE_SHOT_MASK       0x00000001
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_ONE_SHOT_SHIFT      0
#define BCHP_MPM_CPU_CTRL_RESET_CTRL_CPU_RESET_ONE_SHOT_DEFAULT    0x00000000

/***************************************************************************
 *CLOCK_CTRL - Clock Control Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: CLOCK_CTRL :: reserved0 [31:05] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_reserved0_MASK                0xffffffe0
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_reserved0_SHIFT               5

/* MPM_CPU_CTRL :: CLOCK_CTRL :: DISABLE_USBC_CLOCK [04:04] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_USBC_CLOCK_MASK       0x00000010
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_USBC_CLOCK_SHIFT      4
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_USBC_CLOCK_DEFAULT    0x00000000

/* MPM_CPU_CTRL :: CLOCK_CTRL :: DISABLE_UART_CLOCK [03:03] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_UART_CLOCK_MASK       0x00000008
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_UART_CLOCK_SHIFT      3
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_UART_CLOCK_DEFAULT    0x00000000

/* MPM_CPU_CTRL :: CLOCK_CTRL :: DISABLE_MPM_SPI_CLOCK [02:02] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_MPM_SPI_CLOCK_MASK    0x00000004
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_MPM_SPI_CLOCK_SHIFT   2
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_MPM_SPI_CLOCK_DEFAULT 0x00000000

/* MPM_CPU_CTRL :: CLOCK_CTRL :: DISABLE_CPU_CLOCK [01:01] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_CPU_CLOCK_MASK        0x00000002
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_CPU_CLOCK_SHIFT       1
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_DISABLE_CPU_CLOCK_DEFAULT     0x00000000

/* MPM_CPU_CTRL :: CLOCK_CTRL :: reserved1 [00:00] */
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_reserved1_MASK                0x00000001
#define BCHP_MPM_CPU_CTRL_CLOCK_CTRL_reserved1_SHIFT               0

/***************************************************************************
 *PM_CTRL - Power Management Control Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: PM_CTRL :: reserved0 [31:02] */
#define BCHP_MPM_CPU_CTRL_PM_CTRL_reserved0_MASK                   0xfffffffc
#define BCHP_MPM_CPU_CTRL_PM_CTRL_reserved0_SHIFT                  2

/* MPM_CPU_CTRL :: PM_CTRL :: RELEASE_DPHY_STANDBY [01:01] */
#define BCHP_MPM_CPU_CTRL_PM_CTRL_RELEASE_DPHY_STANDBY_MASK        0x00000002
#define BCHP_MPM_CPU_CTRL_PM_CTRL_RELEASE_DPHY_STANDBY_SHIFT       1
#define BCHP_MPM_CPU_CTRL_PM_CTRL_RELEASE_DPHY_STANDBY_DEFAULT     0x00000000

/* MPM_CPU_CTRL :: PM_CTRL :: MPM_WAKEUP_SYSTEM [00:00] */
#define BCHP_MPM_CPU_CTRL_PM_CTRL_MPM_WAKEUP_SYSTEM_MASK           0x00000001
#define BCHP_MPM_CPU_CTRL_PM_CTRL_MPM_WAKEUP_SYSTEM_SHIFT          0
#define BCHP_MPM_CPU_CTRL_PM_CTRL_MPM_WAKEUP_SYSTEM_DEFAULT        0x00000000

/***************************************************************************
 *MISC_CTRL - Control Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: MISC_CTRL :: reserved0 [31:24] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved0_MASK                 0xff000000
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved0_SHIFT                24

/* MPM_CPU_CTRL :: MISC_CTRL :: SPARE_CTRL [23:16] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SPARE_CTRL_MASK                0x00ff0000
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SPARE_CTRL_SHIFT               16
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SPARE_CTRL_DEFAULT             0x0000000f

/* MPM_CPU_CTRL :: MISC_CTRL :: RBUS_TIMEOUT_SEL [15:12] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_RBUS_TIMEOUT_SEL_MASK          0x0000f000
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_RBUS_TIMEOUT_SEL_SHIFT         12
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_RBUS_TIMEOUT_SEL_DEFAULT       0x0000000a

/* MPM_CPU_CTRL :: MISC_CTRL :: reserved1 [11:11] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved1_MASK                 0x00000800
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved1_SHIFT                11

/* MPM_CPU_CTRL :: MISC_CTRL :: reserved2 [10:09] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved2_MASK                 0x00000600
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved2_SHIFT                9

/* MPM_CPU_CTRL :: MISC_CTRL :: MHL_TX_ON [08:08] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MHL_TX_ON_MASK                 0x00000100
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MHL_TX_ON_SHIFT                8
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MHL_TX_ON_DEFAULT              0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: WDOG_EN [07:07] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_WDOG_EN_MASK                   0x00000080
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_WDOG_EN_SHIFT                  7
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_WDOG_EN_DEFAULT                0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: SET_VALUE_OF_MPM_IMEM_VALID [06:06] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SET_VALUE_OF_MPM_IMEM_VALID_MASK 0x00000040
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SET_VALUE_OF_MPM_IMEM_VALID_SHIFT 6
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SET_VALUE_OF_MPM_IMEM_VALID_DEFAULT 0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: MPM_HELLO_WORLD [05:05] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MPM_HELLO_WORLD_MASK           0x00000020
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MPM_HELLO_WORLD_SHIFT          5
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_MPM_HELLO_WORLD_DEFAULT        0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: reserved3 [04:04] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved3_MASK                 0x00000010
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_reserved3_SHIFT                4

/* MPM_CPU_CTRL :: MISC_CTRL :: SELECT_FLASH_PINS [03:03] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_FLASH_PINS_MASK         0x00000008
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_FLASH_PINS_SHIFT        3
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_FLASH_PINS_DEFAULT      0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: SELECT_UART_PINS [02:02] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_UART_PINS_MASK          0x00000004
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_UART_PINS_SHIFT         2
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_SELECT_UART_PINS_DEFAULT       0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: HOSTIF_SEL [01:01] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_HOSTIF_SEL_MASK                0x00000002
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_HOSTIF_SEL_SHIFT               1
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_HOSTIF_SEL_DEFAULT             0x00000000

/* MPM_CPU_CTRL :: MISC_CTRL :: BLOCK_JTAG_ACCESS [00:00] */
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_BLOCK_JTAG_ACCESS_MASK         0x00000001
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_BLOCK_JTAG_ACCESS_SHIFT        0
#define BCHP_MPM_CPU_CTRL_MISC_CTRL_BLOCK_JTAG_ACCESS_DEFAULT      0x00000000

/***************************************************************************
 *SW_SPARE0 - Software Spare Register 0
 ***************************************************************************/
/* MPM_CPU_CTRL :: SW_SPARE0 :: SPARE [31:00] */
#define BCHP_MPM_CPU_CTRL_SW_SPARE0_SPARE_MASK                     0xffffffff
#define BCHP_MPM_CPU_CTRL_SW_SPARE0_SPARE_SHIFT                    0
#define BCHP_MPM_CPU_CTRL_SW_SPARE0_SPARE_DEFAULT                  0x00000000

/***************************************************************************
 *SW_SPARE1 - Software Spare Register 1
 ***************************************************************************/
/* MPM_CPU_CTRL :: SW_SPARE1 :: SPARE [31:00] */
#define BCHP_MPM_CPU_CTRL_SW_SPARE1_SPARE_MASK                     0xffffffff
#define BCHP_MPM_CPU_CTRL_SW_SPARE1_SPARE_SHIFT                    0
#define BCHP_MPM_CPU_CTRL_SW_SPARE1_SPARE_DEFAULT                  0x00000000

/***************************************************************************
 *SW_SPARE2 - Software Spare Register 2
 ***************************************************************************/
/* MPM_CPU_CTRL :: SW_SPARE2 :: SPARE [31:00] */
#define BCHP_MPM_CPU_CTRL_SW_SPARE2_SPARE_MASK                     0xffffffff
#define BCHP_MPM_CPU_CTRL_SW_SPARE2_SPARE_SHIFT                    0
#define BCHP_MPM_CPU_CTRL_SW_SPARE2_SPARE_DEFAULT                  0x00000000

/***************************************************************************
 *SW_SPARE3 - Software Spare Register 3
 ***************************************************************************/
/* MPM_CPU_CTRL :: SW_SPARE3 :: SPARE [31:00] */
#define BCHP_MPM_CPU_CTRL_SW_SPARE3_SPARE_MASK                     0xffffffff
#define BCHP_MPM_CPU_CTRL_SW_SPARE3_SPARE_SHIFT                    0
#define BCHP_MPM_CPU_CTRL_SW_SPARE3_SPARE_DEFAULT                  0x00000000

/***************************************************************************
 *RBUS_ERR_ADDR - RBUS Error Address
 ***************************************************************************/
/* MPM_CPU_CTRL :: RBUS_ERR_ADDR :: ADDR [31:00] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_ADDR_ADDR_MASK                  0xffffffff
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_ADDR_ADDR_SHIFT                 0

/***************************************************************************
 *RBUS_ERR_DATA - RBUS Error Write Data
 ***************************************************************************/
/* MPM_CPU_CTRL :: RBUS_ERR_DATA :: DATA [31:00] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_DATA_DATA_MASK                  0xffffffff
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_DATA_DATA_SHIFT                 0

/***************************************************************************
 *RBUS_ERR_XAC - RBUS Error Transaction
 ***************************************************************************/
/* MPM_CPU_CTRL :: RBUS_ERR_XAC :: reserved0 [31:01] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_XAC_reserved0_MASK              0xfffffffe
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_XAC_reserved0_SHIFT             1

/* MPM_CPU_CTRL :: RBUS_ERR_XAC :: XAC [00:00] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_XAC_XAC_MASK                    0x00000001
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_XAC_XAC_SHIFT                   0

/***************************************************************************
 *RBUS_ERR_CTRL - RBUS Error Control
 ***************************************************************************/
/* MPM_CPU_CTRL :: RBUS_ERR_CTRL :: reserved0 [31:01] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL_reserved0_MASK             0xfffffffe
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL_reserved0_SHIFT            1

/* MPM_CPU_CTRL :: RBUS_ERR_CTRL :: CLR [00:00] */
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL_CLR_MASK                   0x00000001
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL_CLR_SHIFT                  0
#define BCHP_MPM_CPU_CTRL_RBUS_ERR_CTRL_CLR_DEFAULT                0x00000000

/***************************************************************************
 *SYS_ADDR_OFFSET - System Address Offset Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: SYS_ADDR_OFFSET :: SYS_ADDR_OFFSET [31:00] */
#define BCHP_MPM_CPU_CTRL_SYS_ADDR_OFFSET_SYS_ADDR_OFFSET_MASK     0xffffffff
#define BCHP_MPM_CPU_CTRL_SYS_ADDR_OFFSET_SYS_ADDR_OFFSET_SHIFT    0
#define BCHP_MPM_CPU_CTRL_SYS_ADDR_OFFSET_SYS_ADDR_OFFSET_DEFAULT  0x00080000

/***************************************************************************
 *FLASH_MEM_ADDR_OFFSET - Flash Memory Address Offset Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: FLASH_MEM_ADDR_OFFSET :: FLASH_MEM_ADDR_OFFSET [31:00] */
#define BCHP_MPM_CPU_CTRL_FLASH_MEM_ADDR_OFFSET_FLASH_MEM_ADDR_OFFSET_MASK 0xffffffff
#define BCHP_MPM_CPU_CTRL_FLASH_MEM_ADDR_OFFSET_FLASH_MEM_ADDR_OFFSET_SHIFT 0
#define BCHP_MPM_CPU_CTRL_FLASH_MEM_ADDR_OFFSET_FLASH_MEM_ADDR_OFFSET_DEFAULT 0x00040000

/***************************************************************************
 *SPI_DBG_SEL - SPI debug select
 ***************************************************************************/
/* MPM_CPU_CTRL :: SPI_DBG_SEL :: reserved0 [31:03] */
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_reserved0_MASK               0xfffffff8
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_reserved0_SHIFT              3

/* MPM_CPU_CTRL :: SPI_DBG_SEL :: DISABLE_MSPI_FLUSH [02:02] */
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_DISABLE_MSPI_FLUSH_MASK      0x00000004
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_DISABLE_MSPI_FLUSH_SHIFT     2
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_DISABLE_MSPI_FLUSH_DEFAULT   0x00000000

/* MPM_CPU_CTRL :: SPI_DBG_SEL :: reserved1 [01:00] */
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_reserved1_MASK               0x00000003
#define BCHP_MPM_CPU_CTRL_SPI_DBG_SEL_reserved1_SHIFT              0

/***************************************************************************
 *STATUS - Status Register
 ***************************************************************************/
/* MPM_CPU_CTRL :: STATUS :: reserved0 [31:24] */
#define BCHP_MPM_CPU_CTRL_STATUS_reserved0_MASK                    0xff000000
#define BCHP_MPM_CPU_CTRL_STATUS_reserved0_SHIFT                   24

/* MPM_CPU_CTRL :: STATUS :: SPARE_STATUS [23:18] */
#define BCHP_MPM_CPU_CTRL_STATUS_SPARE_STATUS_MASK                 0x00fc0000
#define BCHP_MPM_CPU_CTRL_STATUS_SPARE_STATUS_SHIFT                18

/* MPM_CPU_CTRL :: STATUS :: STRAP_USBC_NO_PD [17:17] */
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_USBC_NO_PD_MASK             0x00020000
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_USBC_NO_PD_SHIFT            17

/* MPM_CPU_CTRL :: STATUS :: STRAP_MPM_RUNMODE_0 [16:16] */
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_MPM_RUNMODE_0_MASK          0x00010000
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_MPM_RUNMODE_0_SHIFT         16

/* MPM_CPU_CTRL :: STATUS :: reserved1 [15:06] */
#define BCHP_MPM_CPU_CTRL_STATUS_reserved1_MASK                    0x0000ffc0
#define BCHP_MPM_CPU_CTRL_STATUS_reserved1_SHIFT                   6

/* MPM_CPU_CTRL :: STATUS :: HOSTIF_ACCESSED_BY_JTAG [05:05] */
#define BCHP_MPM_CPU_CTRL_STATUS_HOSTIF_ACCESSED_BY_JTAG_MASK      0x00000020
#define BCHP_MPM_CPU_CTRL_STATUS_HOSTIF_ACCESSED_BY_JTAG_SHIFT     5

/* MPM_CPU_CTRL :: STATUS :: ACCESS_DISABLE [04:04] */
#define BCHP_MPM_CPU_CTRL_STATUS_ACCESS_DISABLE_MASK               0x00000010
#define BCHP_MPM_CPU_CTRL_STATUS_ACCESS_DISABLE_SHIFT              4

/* MPM_CPU_CTRL :: STATUS :: CHIP_IS_IN_S3 [03:03] */
#define BCHP_MPM_CPU_CTRL_STATUS_CHIP_IS_IN_S3_MASK                0x00000008
#define BCHP_MPM_CPU_CTRL_STATUS_CHIP_IS_IN_S3_SHIFT               3

/* MPM_CPU_CTRL :: STATUS :: MPM_IMEM_VALID [02:02] */
#define BCHP_MPM_CPU_CTRL_STATUS_MPM_IMEM_VALID_MASK               0x00000004
#define BCHP_MPM_CPU_CTRL_STATUS_MPM_IMEM_VALID_SHIFT              2

/* MPM_CPU_CTRL :: STATUS :: STRAP_MPM_FLASH_BOOT [01:01] */
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_MPM_FLASH_BOOT_MASK         0x00000002
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_MPM_FLASH_BOOT_SHIFT        1

/* MPM_CPU_CTRL :: STATUS :: STRAP_POWERUP_IN_S3 [00:00] */
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_POWERUP_IN_S3_MASK          0x00000001
#define BCHP_MPM_CPU_CTRL_STATUS_STRAP_POWERUP_IN_S3_SHIFT         0

#endif /* #ifndef BCHP_MPM_CPU_CTRL_H__ */

/* End of File */
