/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Nov 23 01:10:02 2017
 *                 Full Compile MD5 Checksum  9c249593c44f5a3709c1aa2deb2a32b9
 *                     (minus title and desc)
 *                 MD5 Checksum               bedd24dac2c620a65db09cca853e657e
 *
 * lock_release:   r_1255
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_BSP_GLB_CONTROL_H__
#define BCHP_BSP_GLB_CONTROL_H__

/***************************************************************************
 *BSP_GLB_CONTROL - BSP GLOBAL Control Register
 ***************************************************************************/
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION        0x002032d000 /* [RO][32] Revision Register */
#define BCHP_BSP_GLB_CONTROL_GLB_TIMER           0x002032d004 /* [RO][32] Timer */
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY            0x002032d008 /* [RO][32] Input Command Buffer Ready */
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY            0x002032d00c /* [RW][32] Output Command Buffer Ready */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS 0x002032d010 /* [RW][32] Host CPU Interrupt Status */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN    0x002032d014 /* [RW][32] Host CPU Interrupt Enable */
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS 0x002032d018 /* [RW][32] Host CPU Interrupt Status */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2          0x002032d020 /* [RW][32] Output Command Buffer 2 Loaded */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1          0x002032d024 /* [RW][32] Output Command Buffer 1 Loaded */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2          0x002032d028 /* [RW][32] Input Command Buffer 2 Loaded */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1          0x002032d02c /* [RW][32] Input Command Buffer 1 Loaded */
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR 0x002032d034 /* [RW][32] HOST to BSP Processor General Interrupt Trigger Register */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0           0x002032d038 /* [RW][32] Aegis Miscellaneous Control Configuration */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL 0x002032d040 /* [RW][32] Aegis JTAG Debug Control */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP    0x002032d04c /* [RW][32] ZZYZX Clock Stop */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR       0x002032d050 /* [RW][32] Download Error flags */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS    0x002032d054 /* [RO][32] Download Status flags */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR        0x002032d058 /* [RW][32] Challenge/Response Output Command Buffer Loaded */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR        0x002032d05c /* [RW][32] Challenge/Response Input Command Buffer Loaded */
#define BCHP_BSP_GLB_CONTROL_OTP_HASH_CRC        0x002032d060 /* [RO][32] OTP HASH CRC Register */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_hi 0x002032d064 /* [RO][32] Otp value v_PubOtpUniqueID_hi */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_lo 0x002032d068 /* [RO][32] Otp value v_PubOtpUniqueID_lo */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpOID         0x002032d06c /* [RO][32] Otp value v_PubOtpOID */
#define BCHP_BSP_GLB_CONTROL_v_Version           0x002032d070 /* [RO][32] Otp value v_Version */
#define BCHP_BSP_GLB_CONTROL_OTP_MSP_CRC         0x002032d074 /* [RO][32] MSP CRC Register */
#define BCHP_BSP_GLB_CONTROL_FW_FLAGS            0x002032d078 /* [RW][32] FW Error Flags */
#define BCHP_BSP_GLB_CONTROL_OTP_HASH2_CRC       0x002032d07c /* [RO][32] OTP HASH2 CRC Register */
#define BCHP_BSP_GLB_CONTROL_ASKM_STB_OwnerID    0x002032d080 /* [RO][32] Otp value ASKM_STB_OwnerID */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS            0x002032d084 /* [RW][32] HW Error Flags */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD      0x002032d088 /* [RW][32] Debug/EJTAG Password Data */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL 0x002032d08c /* [RW][32] Debug/EJTAG Password Ctrl/Status */
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_HI        0x002032d090 /* [RO][32] Otp value Poway_UID */
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_LO        0x002032d094 /* [RO][32] Otp value Poway_UID */
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY          0x002032d098 /* [RO][32] Poway Busy Register */
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER          0x002032d09c /* [RW][32] FW Error Flags */
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE          0x002032d0a0 /* [RW][32] SCPU Data Done */
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT        0x002032d0a4 /* [RW][32] SCPU Nonsecure Software Init register. */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET      0x002032d0a8 /* [RW][32] public ZZYZX software reset Register */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL          0x002032d0ac /* [RW][32] ZZYZX Control */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL      0x002032d0b0 /* [RW][32] ZZYZX RNG Control */

/***************************************************************************
 *GLB_REVISION - Revision Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_REVISION :: reserved0 [31:16] */
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_reserved0_MASK           0xffff0000
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_reserved0_SHIFT          16

/* BSP_GLB_CONTROL :: GLB_REVISION :: MAJOR_REV_NUMBER [15:08] */
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MAJOR_REV_NUMBER_MASK    0x0000ff00
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MAJOR_REV_NUMBER_SHIFT   8
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MAJOR_REV_NUMBER_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_REVISION :: MINOR_REV_NUMBER [07:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MINOR_REV_NUMBER_MASK    0x000000ff
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MINOR_REV_NUMBER_SHIFT   0
#define BCHP_BSP_GLB_CONTROL_GLB_REVISION_MINOR_REV_NUMBER_DEFAULT 0x00000000

/***************************************************************************
 *GLB_TIMER - Timer
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_TIMER :: TIMER [31:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_TIMER_TIMER_MASK                  0xffffffff
#define BCHP_BSP_GLB_CONTROL_GLB_TIMER_TIMER_SHIFT                 0
#define BCHP_BSP_GLB_CONTROL_GLB_TIMER_TIMER_DEFAULT               0x00000000

/***************************************************************************
 *GLB_IRDY - Input Command Buffer Ready
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_IRDY :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_reserved0_MASK               0xfffffff8
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_reserved0_SHIFT              3

/* BSP_GLB_CONTROL :: GLB_IRDY :: CMD_IDRY_CR [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY_CR_MASK             0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY_CR_SHIFT            2
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY_CR_DEFAULT          0x00000000

/* BSP_GLB_CONTROL :: GLB_IRDY :: CMD_IDRY2 [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY2_MASK               0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY2_SHIFT              1
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY2_DEFAULT            0x00000000

/* BSP_GLB_CONTROL :: GLB_IRDY :: CMD_IDRY1 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY1_MASK               0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY1_SHIFT              0
#define BCHP_BSP_GLB_CONTROL_GLB_IRDY_CMD_IDRY1_DEFAULT            0x00000000

/***************************************************************************
 *GLB_ORDY - Output Command Buffer Ready
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_ORDY :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_reserved0_MASK               0xfffffff8
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_reserved0_SHIFT              3

/* BSP_GLB_CONTROL :: GLB_ORDY :: CMD_ODRY_CR [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY_CR_MASK             0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY_CR_SHIFT            2
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY_CR_DEFAULT          0x00000000

/* BSP_GLB_CONTROL :: GLB_ORDY :: CMD_ODRY2 [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY2_MASK               0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY2_SHIFT              1
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY2_DEFAULT            0x00000000

/* BSP_GLB_CONTROL :: GLB_ORDY :: CMD_ODRY1 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY1_MASK               0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY1_SHIFT              0
#define BCHP_BSP_GLB_CONTROL_GLB_ORDY_CMD_ODRY1_DEFAULT            0x00000000

/***************************************************************************
 *GLB_HOST_INTR_STATUS - Host CPU Interrupt Status
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_HOST_INTR_STATUS :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_reserved0_MASK   0xfffffff8
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_reserved0_SHIFT  3

/* BSP_GLB_CONTROL :: GLB_HOST_INTR_STATUS :: OLOAD_CR_INT [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD_CR_INT_MASK 0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD_CR_INT_SHIFT 2
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD_CR_INT_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_HOST_INTR_STATUS :: OLOAD2_INT [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD2_INT_MASK  0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD2_INT_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD2_INT_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_HOST_INTR_STATUS :: OLOAD1_INT [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD1_INT_MASK  0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD1_INT_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_STATUS_OLOAD1_INT_DEFAULT 0x00000000

/***************************************************************************
 *GLB_HOST_INTR_EN - Host CPU Interrupt Enable
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_HOST_INTR_EN :: reserved0 [31:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN_reserved0_MASK       0xfffffffc
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN_reserved0_SHIFT      2

/* BSP_GLB_CONTROL :: GLB_HOST_INTR_EN :: HOST_INTR_STATUS_EN [01:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN_HOST_INTR_STATUS_EN_MASK 0x00000003
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN_HOST_INTR_STATUS_EN_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_GLB_HOST_INTR_EN_HOST_INTR_STATUS_EN_DEFAULT 0x00000000

/***************************************************************************
 *GLB_RAAGA_INTR_STATUS - Host CPU Interrupt Status
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_RAAGA_INTR_STATUS :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_reserved0_MASK  0xfffffff8
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_reserved0_SHIFT 3

/* BSP_GLB_CONTROL :: GLB_RAAGA_INTR_STATUS :: OLOAD_CR_INT [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD_CR_INT_MASK 0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD_CR_INT_SHIFT 2
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD_CR_INT_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_RAAGA_INTR_STATUS :: OLOAD2_INT [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD2_INT_MASK 0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD2_INT_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD2_INT_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_RAAGA_INTR_STATUS :: OLOAD1_INT [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD1_INT_MASK 0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD1_INT_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_GLB_RAAGA_INTR_STATUS_OLOAD1_INT_DEFAULT 0x00000000

/***************************************************************************
 *GLB_OLOAD2 - Output Command Buffer 2 Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_OLOAD2 :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: GLB_OLOAD2 :: CMD_OLOAD2 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2_CMD_OLOAD2_MASK            0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2_CMD_OLOAD2_SHIFT           0
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD2_CMD_OLOAD2_DEFAULT         0x00000000

/***************************************************************************
 *GLB_OLOAD1 - Output Command Buffer 1 Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_OLOAD1 :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: GLB_OLOAD1 :: CMD_OLOAD1 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1_CMD_OLOAD1_MASK            0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1_CMD_OLOAD1_SHIFT           0
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD1_CMD_OLOAD1_DEFAULT         0x00000000

/***************************************************************************
 *GLB_ILOAD2 - Input Command Buffer 2 Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_ILOAD2 :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: GLB_ILOAD2 :: CMD_ILOAD2 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2_CMD_ILOAD2_MASK            0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2_CMD_ILOAD2_SHIFT           0
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD2_CMD_ILOAD2_DEFAULT         0x00000000

/***************************************************************************
 *GLB_ILOAD1 - Input Command Buffer 1 Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_ILOAD1 :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: GLB_ILOAD1 :: CMD_ILOAD1 [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1_CMD_ILOAD1_MASK            0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1_CMD_ILOAD1_SHIFT           0
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD1_CMD_ILOAD1_DEFAULT         0x00000000

/***************************************************************************
 *HOST_TO_BSP_GENERAL_INTR - HOST to BSP Processor General Interrupt Trigger Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: HOST_TO_BSP_GENERAL_INTR :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR_reserved0_MASK 0xfffffffe
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR_reserved0_SHIFT 1

/* BSP_GLB_CONTROL :: HOST_TO_BSP_GENERAL_INTR :: HOST_TO_BSP_INTR [00:00] */
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR_HOST_TO_BSP_INTR_MASK 0x00000001
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR_HOST_TO_BSP_INTR_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_HOST_TO_BSP_GENERAL_INTR_HOST_TO_BSP_INTR_DEFAULT 0x00000000

/***************************************************************************
 *GLB_MISC0 - Aegis Miscellaneous Control Configuration
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_MISC0 :: reserved0 [31:17] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_reserved0_MASK              0xfffe0000
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_reserved0_SHIFT             17

/* BSP_GLB_CONTROL :: GLB_MISC0 :: OTP_DUMP_DONE [16:16] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_OTP_DUMP_DONE_MASK          0x00010000
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_OTP_DUMP_DONE_SHIFT         16
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_OTP_DUMP_DONE_DEFAULT       0x00000000

/* BSP_GLB_CONTROL :: GLB_MISC0 :: CONTROL_GENERAL_CFG2 [15:08] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_CONTROL_GENERAL_CFG2_MASK   0x0000ff00
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_CONTROL_GENERAL_CFG2_SHIFT  8
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_CONTROL_GENERAL_CFG2_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_MISC0 :: STRAP_SUNDRY_TESTMODE [07:04] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_SUNDRY_TESTMODE_MASK  0x000000f0
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_SUNDRY_TESTMODE_SHIFT 4
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_SUNDRY_TESTMODE_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_MISC0 :: ATE_SPARE [03:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_SPARE_MASK              0x00000008
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_SPARE_SHIFT             3
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_SPARE_DEFAULT           0x00000000

/* BSP_GLB_CONTROL :: GLB_MISC0 :: ATE_EN_FLAG [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_EN_FLAG_MASK            0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_EN_FLAG_SHIFT           2
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_ATE_EN_FLAG_DEFAULT         0x00000000

/* BSP_GLB_CONTROL :: GLB_MISC0 :: STRAP_TEST_DEBUG_EN [01:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_TEST_DEBUG_EN_MASK    0x00000003
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_TEST_DEBUG_EN_SHIFT   0
#define BCHP_BSP_GLB_CONTROL_GLB_MISC0_STRAP_TEST_DEBUG_EN_DEFAULT 0x00000000

/***************************************************************************
 *GLB_JTAG_DEBUG_CTRL - Aegis JTAG Debug Control
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_NOP_CONFIG_EN [31:31] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_NOP_CONFIG_EN_MASK 0x80000000
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_NOP_CONFIG_EN_SHIFT 31
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_NOP_CONFIG_EN_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: reserved0 [30:08] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_reserved0_MASK    0x7fffff00
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_reserved0_SHIFT   8

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_DISABLE_WATCHDOG_TIMER [07:07] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_WATCHDOG_TIMER_MASK 0x00000080
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_WATCHDOG_TIMER_SHIFT 7
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_WATCHDOG_TIMER_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_DISABLE_TIMER2 [06:06] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER2_MASK 0x00000040
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER2_SHIFT 6
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER2_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_DISABLE_TIMER1 [05:05] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER1_MASK 0x00000020
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER1_SHIFT 5
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER1_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_DISABLE_TIMER0 [04:04] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER0_MASK 0x00000010
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER0_SHIFT 4
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_TIMER0_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_BLOCK_BSECK_RESET [03:03] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BLOCK_BSECK_RESET_MASK 0x00000008
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BLOCK_BSECK_RESET_SHIFT 3
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BLOCK_BSECK_RESET_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_DISABLE_MEM_SCRUBBER [02:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_MEM_SCRUBBER_MASK 0x00000004
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_MEM_SCRUBBER_SHIFT 2
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_DISABLE_MEM_SCRUBBER_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_BSECK_CODE [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BSECK_CODE_MASK 0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BSECK_CODE_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_BSECK_CODE_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_JTAG_DEBUG_CTRL :: DEBUG_nROM_RAM_CFG [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_nROM_RAM_CFG_MASK 0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_nROM_RAM_CFG_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_GLB_JTAG_DEBUG_CTRL_DEBUG_nROM_RAM_CFG_DEFAULT 0x00000000

/***************************************************************************
 *ZZYZX_CLOCK_STOP - ZZYZX Clock Stop
 ***************************************************************************/
/* BSP_GLB_CONTROL :: ZZYZX_CLOCK_STOP :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_reserved0_MASK       0xfffffff8
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_reserved0_SHIFT      3

/* BSP_GLB_CONTROL :: ZZYZX_CLOCK_STOP :: POWAY_SLOW_CLOCK [02:02] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_POWAY_SLOW_CLOCK_MASK 0x00000004
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_POWAY_SLOW_CLOCK_SHIFT 2
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_POWAY_SLOW_CLOCK_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: ZZYZX_CLOCK_STOP :: ZZYZX_SLOW_CLOCK [01:01] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_SLOW_CLOCK_MASK 0x00000002
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_SLOW_CLOCK_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_SLOW_CLOCK_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: ZZYZX_CLOCK_STOP :: ZZYZX_CLOCK_STOP [00:00] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_CLOCK_STOP_MASK 0x00000001
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_CLOCK_STOP_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CLOCK_STOP_ZZYZX_CLOCK_STOP_DEFAULT 0x00000000

/***************************************************************************
 *GLB_DWNLD_ERR - Download Error flags
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_DWNLD_ERR :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR_reserved0_MASK          0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR_reserved0_SHIFT         1

/* BSP_GLB_CONTROL :: GLB_DWNLD_ERR :: DISASTER_RECOVER [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR_DISASTER_RECOVER_MASK   0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR_DISASTER_RECOVER_SHIFT  0
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_ERR_DISASTER_RECOVER_DEFAULT 0x00000000

/***************************************************************************
 *GLB_DWNLD_STATUS - Download Status flags
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_DWNLD_STATUS :: reserved0 [31:02] */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_reserved0_MASK       0xfffffffc
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_reserved0_SHIFT      2

/* BSP_GLB_CONTROL :: GLB_DWNLD_STATUS :: SECOND_STAGE_LOADED [01:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_LOADED_MASK 0x00000002
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_LOADED_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_LOADED_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: GLB_DWNLD_STATUS :: SECOND_STAGE [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_MASK    0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_SHIFT   0
#define BCHP_BSP_GLB_CONTROL_GLB_DWNLD_STATUS_SECOND_STAGE_DEFAULT 0x00000000

/***************************************************************************
 *GLB_OLOAD_CR - Challenge/Response Output Command Buffer Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_OLOAD_CR :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR_reserved0_MASK           0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR_reserved0_SHIFT          1

/* BSP_GLB_CONTROL :: GLB_OLOAD_CR :: CMD_OLOAD_CR [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR_CMD_OLOAD_CR_MASK        0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR_CMD_OLOAD_CR_SHIFT       0
#define BCHP_BSP_GLB_CONTROL_GLB_OLOAD_CR_CMD_OLOAD_CR_DEFAULT     0x00000000

/***************************************************************************
 *GLB_ILOAD_CR - Challenge/Response Input Command Buffer Loaded
 ***************************************************************************/
/* BSP_GLB_CONTROL :: GLB_ILOAD_CR :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR_reserved0_MASK           0xfffffffe
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR_reserved0_SHIFT          1

/* BSP_GLB_CONTROL :: GLB_ILOAD_CR :: CMD_ILOAD_CR [00:00] */
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR_CMD_ILOAD_CR_MASK        0x00000001
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR_CMD_ILOAD_CR_SHIFT       0
#define BCHP_BSP_GLB_CONTROL_GLB_ILOAD_CR_CMD_ILOAD_CR_DEFAULT     0x00000000

/***************************************************************************
 *OTP_HASH_CRC - OTP HASH CRC Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: OTP_HASH_CRC :: CRC [31:00] */
#define BCHP_BSP_GLB_CONTROL_OTP_HASH_CRC_CRC_MASK                 0xffffffff
#define BCHP_BSP_GLB_CONTROL_OTP_HASH_CRC_CRC_SHIFT                0

/***************************************************************************
 *v_PubOtpUniqueID_hi - Otp value v_PubOtpUniqueID_hi
 ***************************************************************************/
/* BSP_GLB_CONTROL :: v_PubOtpUniqueID_hi :: DATA [31:00] */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_hi_DATA_MASK         0xffffffff
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_hi_DATA_SHIFT        0

/***************************************************************************
 *v_PubOtpUniqueID_lo - Otp value v_PubOtpUniqueID_lo
 ***************************************************************************/
/* BSP_GLB_CONTROL :: v_PubOtpUniqueID_lo :: DATA [31:00] */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_lo_DATA_MASK         0xffffffff
#define BCHP_BSP_GLB_CONTROL_v_PubOtpUniqueID_lo_DATA_SHIFT        0

/***************************************************************************
 *v_PubOtpOID - Otp value v_PubOtpOID
 ***************************************************************************/
/* BSP_GLB_CONTROL :: v_PubOtpOID :: reserved0 [31:16] */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpOID_reserved0_MASK            0xffff0000
#define BCHP_BSP_GLB_CONTROL_v_PubOtpOID_reserved0_SHIFT           16

/* BSP_GLB_CONTROL :: v_PubOtpOID :: PubOtpOID [15:00] */
#define BCHP_BSP_GLB_CONTROL_v_PubOtpOID_PubOtpOID_MASK            0x0000ffff
#define BCHP_BSP_GLB_CONTROL_v_PubOtpOID_PubOtpOID_SHIFT           0

/***************************************************************************
 *v_Version - Otp value v_Version
 ***************************************************************************/
/* BSP_GLB_CONTROL :: v_Version :: Data [31:00] */
#define BCHP_BSP_GLB_CONTROL_v_Version_Data_MASK                   0xffffffff
#define BCHP_BSP_GLB_CONTROL_v_Version_Data_SHIFT                  0

/***************************************************************************
 *OTP_MSP_CRC - MSP CRC Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: OTP_MSP_CRC :: CRC [31:00] */
#define BCHP_BSP_GLB_CONTROL_OTP_MSP_CRC_CRC_MASK                  0xffffffff
#define BCHP_BSP_GLB_CONTROL_OTP_MSP_CRC_CRC_SHIFT                 0

/***************************************************************************
 *FW_FLAGS - FW Error Flags
 ***************************************************************************/
/* BSP_GLB_CONTROL :: FW_FLAGS :: FW_ERR [31:00] */
#define BCHP_BSP_GLB_CONTROL_FW_FLAGS_FW_ERR_MASK                  0xffffffff
#define BCHP_BSP_GLB_CONTROL_FW_FLAGS_FW_ERR_SHIFT                 0
#define BCHP_BSP_GLB_CONTROL_FW_FLAGS_FW_ERR_DEFAULT               0x00000000

/***************************************************************************
 *OTP_HASH2_CRC - OTP HASH2 CRC Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: OTP_HASH2_CRC :: CRC [31:00] */
#define BCHP_BSP_GLB_CONTROL_OTP_HASH2_CRC_CRC_MASK                0xffffffff
#define BCHP_BSP_GLB_CONTROL_OTP_HASH2_CRC_CRC_SHIFT               0

/***************************************************************************
 *ASKM_STB_OwnerID - Otp value ASKM_STB_OwnerID
 ***************************************************************************/
/* BSP_GLB_CONTROL :: ASKM_STB_OwnerID :: reserved0 [31:16] */
#define BCHP_BSP_GLB_CONTROL_ASKM_STB_OwnerID_reserved0_MASK       0xffff0000
#define BCHP_BSP_GLB_CONTROL_ASKM_STB_OwnerID_reserved0_SHIFT      16

/* BSP_GLB_CONTROL :: ASKM_STB_OwnerID :: OwnerID [15:00] */
#define BCHP_BSP_GLB_CONTROL_ASKM_STB_OwnerID_OwnerID_MASK         0x0000ffff
#define BCHP_BSP_GLB_CONTROL_ASKM_STB_OwnerID_OwnerID_SHIFT        0

/***************************************************************************
 *HW_FLAGS - HW Error Flags
 ***************************************************************************/
/* BSP_GLB_CONTROL :: HW_FLAGS :: reserved0 [31:09] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_reserved0_MASK               0xfffffe00
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_reserved0_SHIFT              9

/* BSP_GLB_CONTROL :: HW_FLAGS :: BSECK_READY [08:08] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BSECK_READY_MASK             0x00000100
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BSECK_READY_SHIFT            8
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BSECK_READY_DEFAULT          0x00000000

/* BSP_GLB_CONTROL :: HW_FLAGS :: BOOT_ROM_CRC [07:07] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BOOT_ROM_CRC_MASK            0x00000080
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BOOT_ROM_CRC_SHIFT           7
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_BOOT_ROM_CRC_DEFAULT         0x00000000

/* BSP_GLB_CONTROL :: HW_FLAGS :: DMA_END_STATE_MISMATCH [06:06] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_END_STATE_MISMATCH_MASK  0x00000040
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_END_STATE_MISMATCH_SHIFT 6
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_END_STATE_MISMATCH_DEFAULT 0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: DMA_STATE_MISMATCH [05:05] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_STATE_MISMATCH_MASK      0x00000020
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_STATE_MISMATCH_SHIFT     5
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_STATE_MISMATCH_DEFAULT   0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: DMA_CNT_MISMATCH [04:04] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_CNT_MISMATCH_MASK        0x00000010
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_CNT_MISMATCH_SHIFT       4
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_DMA_CNT_MISMATCH_DEFAULT     0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: KEYSHA_MISMATCH [03:03] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_KEYSHA_MISMATCH_MASK         0x00000008
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_KEYSHA_MISMATCH_SHIFT        3
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_KEYSHA_MISMATCH_DEFAULT      0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: SIG_MISMATCH [02:02] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SIG_MISMATCH_MASK            0x00000004
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SIG_MISMATCH_SHIFT           2
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SIG_MISMATCH_DEFAULT         0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: SHA_MISMATCH [01:01] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SHA_MISMATCH_MASK            0x00000002
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SHA_MISMATCH_SHIFT           1
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_SHA_MISMATCH_DEFAULT         0x00000001

/* BSP_GLB_CONTROL :: HW_FLAGS :: RAM_ENABLE [00:00] */
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_RAM_ENABLE_MASK              0x00000001
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_RAM_ENABLE_SHIFT             0
#define BCHP_BSP_GLB_CONTROL_HW_FLAGS_RAM_ENABLE_DEFAULT           0x00000000

/***************************************************************************
 *DEBUG_PASSWORD - Debug/EJTAG Password Data
 ***************************************************************************/
/* BSP_GLB_CONTROL :: DEBUG_PASSWORD :: DATA [31:00] */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_DATA_MASK              0xffffffff
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_DATA_SHIFT             0
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_DATA_DEFAULT           0x00000000

/***************************************************************************
 *DEBUG_PASSWORD_CTRL - Debug/EJTAG Password Ctrl/Status
 ***************************************************************************/
/* BSP_GLB_CONTROL :: DEBUG_PASSWORD_CTRL :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_reserved0_MASK    0xfffffff8
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_reserved0_SHIFT   3

/* BSP_GLB_CONTROL :: DEBUG_PASSWORD_CTRL :: DEBUG_PASSWORD_TYPE [02:02] */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_TYPE_MASK 0x00000004
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_TYPE_SHIFT 2
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_TYPE_DEFAULT 0x00000000
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_TYPE_PASSWORD_TYPE_DEBUG 0
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_TYPE_PASSWORD_TYPE_EJTAG 1

/* BSP_GLB_CONTROL :: DEBUG_PASSWORD_CTRL :: EJTAG_PASSWORD_PASS [01:01] */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_EJTAG_PASSWORD_PASS_MASK 0x00000002
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_EJTAG_PASSWORD_PASS_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_EJTAG_PASSWORD_PASS_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: DEBUG_PASSWORD_CTRL :: DEBUG_PASSWORD_PASS [00:00] */
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_PASS_MASK 0x00000001
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_PASS_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_DEBUG_PASSWORD_CTRL_DEBUG_PASSWORD_PASS_DEFAULT 0x00000000

/***************************************************************************
 *POWAY_UID_HI - Otp value Poway_UID
 ***************************************************************************/
/* BSP_GLB_CONTROL :: POWAY_UID_HI :: DATA [31:00] */
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_HI_DATA_MASK                0xffffffff
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_HI_DATA_SHIFT               0

/***************************************************************************
 *POWAY_UID_LO - Otp value Poway_UID
 ***************************************************************************/
/* BSP_GLB_CONTROL :: POWAY_UID_LO :: DATA [31:00] */
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_LO_DATA_MASK                0xffffffff
#define BCHP_BSP_GLB_CONTROL_POWAY_UID_LO_DATA_SHIFT               0

/***************************************************************************
 *POWAY_BUSY - Poway Busy Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: POWAY_BUSY :: reserved0 [31:02] */
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_reserved0_MASK             0xfffffffc
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_reserved0_SHIFT            2

/* BSP_GLB_CONTROL :: POWAY_BUSY :: SP_BUSY [01:01] */
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_SP_BUSY_MASK               0x00000002
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_SP_BUSY_SHIFT              1
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_SP_BUSY_DEFAULT            0x00000000

/* BSP_GLB_CONTROL :: POWAY_BUSY :: PKL_BUSY [00:00] */
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_PKL_BUSY_MASK              0x00000001
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_PKL_BUSY_SHIFT             0
#define BCHP_BSP_GLB_CONTROL_POWAY_BUSY_PKL_BUSY_DEFAULT           0x00000000

/***************************************************************************
 *FW_COUNTER - FW Error Flags
 ***************************************************************************/
/* BSP_GLB_CONTROL :: FW_COUNTER :: reserved0 [31:08] */
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER_reserved0_MASK             0xffffff00
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER_reserved0_SHIFT            8

/* BSP_GLB_CONTROL :: FW_COUNTER :: FW_CNT [07:00] */
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER_FW_CNT_MASK                0x000000ff
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER_FW_CNT_SHIFT               0
#define BCHP_BSP_GLB_CONTROL_FW_COUNTER_FW_CNT_DEFAULT             0x00000000

/***************************************************************************
 *SCPU_DDONE - SCPU Data Done
 ***************************************************************************/
/* BSP_GLB_CONTROL :: SCPU_DDONE :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: SCPU_DDONE :: CMD_SCPU_DDONE [00:00] */
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE_CMD_SCPU_DDONE_MASK        0x00000001
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE_CMD_SCPU_DDONE_SHIFT       0
#define BCHP_BSP_GLB_CONTROL_SCPU_DDONE_CMD_SCPU_DDONE_DEFAULT     0x00000000

/***************************************************************************
 *SCPU_SW_INIT - SCPU Nonsecure Software Init register.
 ***************************************************************************/
/* BSP_GLB_CONTROL :: SCPU_SW_INIT :: reserved0 [31:03] */
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_reserved0_MASK           0xfffffff8
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_reserved0_SHIFT          3

/* BSP_GLB_CONTROL :: SCPU_SW_INIT :: SCPU_SCB_INIT_REQ [02:02] */
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SCB_INIT_REQ_MASK   0x00000004
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SCB_INIT_REQ_SHIFT  2
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SCB_INIT_REQ_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: SCPU_SW_INIT :: SCPU_NMI [01:01] */
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_NMI_MASK            0x00000002
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_NMI_SHIFT           1
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_NMI_DEFAULT         0x00000000

/* BSP_GLB_CONTROL :: SCPU_SW_INIT :: SCPU_SW_INIT [00:00] */
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SW_INIT_MASK        0x00000001
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SW_INIT_SHIFT       0
#define BCHP_BSP_GLB_CONTROL_SCPU_SW_INIT_SCPU_SW_INIT_DEFAULT     0x00000001

/***************************************************************************
 *ZZYZX_SW_RESET - public ZZYZX software reset Register
 ***************************************************************************/
/* BSP_GLB_CONTROL :: ZZYZX_SW_RESET :: ZZYZX_PROTECT_PATN [31:01] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_PROTECT_PATN_MASK 0xfffffffe
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_PROTECT_PATN_SHIFT 1
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_PROTECT_PATN_DEFAULT 0x00000000

/* BSP_GLB_CONTROL :: ZZYZX_SW_RESET :: ZZYZX_SW_RST [00:00] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_SW_RST_MASK      0x00000001
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_SW_RST_SHIFT     0
#define BCHP_BSP_GLB_CONTROL_ZZYZX_SW_RESET_ZZYZX_SW_RST_DEFAULT   0x00000001

/***************************************************************************
 *ZZYZX_CTRL - ZZYZX Control
 ***************************************************************************/
/* BSP_GLB_CONTROL :: ZZYZX_CTRL :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL_reserved0_MASK             0xfffffffe
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL_reserved0_SHIFT            1

/* BSP_GLB_CONTROL :: ZZYZX_CTRL :: KTEACK [00:00] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL_KTEACK_MASK                0x00000001
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL_KTEACK_SHIFT               0
#define BCHP_BSP_GLB_CONTROL_ZZYZX_CTRL_KTEACK_DEFAULT             0x00000000

/***************************************************************************
 *ZZYZX_RNG_CTRL - ZZYZX RNG Control
 ***************************************************************************/
/* BSP_GLB_CONTROL :: ZZYZX_RNG_CTRL :: reserved0 [31:01] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL_reserved0_MASK         0xfffffffe
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL_reserved0_SHIFT        1

/* BSP_GLB_CONTROL :: ZZYZX_RNG_CTRL :: RNGEmpiricalTest [00:00] */
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL_RNGEmpiricalTest_MASK  0x00000001
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL_RNGEmpiricalTest_SHIFT 0
#define BCHP_BSP_GLB_CONTROL_ZZYZX_RNG_CTRL_RNGEmpiricalTest_DEFAULT 0x00000000

#endif /* #ifndef BCHP_BSP_GLB_CONTROL_H__ */

/* End of File */
