/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Sat Aug  1 03:10:08 2015
 *                 Full Compile MD5 Checksum  9095e7c50184516c43cebfda484f35c6
 *                     (minus title and desc)
 *                 MD5 Checksum               12de0e44f1435087f5630ef2cde72753
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_GENET_0_EXT_H__
#define BCHP_GENET_0_EXT_H__

/***************************************************************************
 *GENET_0_EXT
 ***************************************************************************/
#define BCHP_GENET_0_EXT_EPHY_CNTRL              0x20480080 /* [RW] EPHY Power Management Register */
#define BCHP_GENET_0_EXT_EPHY_STATUS             0x20480084 /* [RO] ENDT EMCG Control Register */
#define BCHP_GENET_0_EXT_TEST_CNTRL              0x20480088 /* [RW] Test Control Register */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL         0x2048008c /* [RW] RGMII OOB Control Register */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS         0x20480090 /* [RW] RGMII InBand Status Register */
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL         0x20480094 /* [RW] RGMII LED Control Register */
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL         0x20480098 /* [RW] GENET CORE CLOCK and GMII CLOCK SELECT Control Register */
#define BCHP_GENET_0_EXT_GPHY_CNTRL              0x2048009c /* [RW] GPHY Control Register */
#define BCHP_GENET_0_EXT_GPHY_STATUS             0x204800a0 /* [RO] GPHY Status Register */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL 0x204800a4 /* [RW] RGMII port RX Clock Delay Control Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA 0x204800a8 /* [RW] RGMII port ATE RX Control and Expected Data Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1 0x204800ac /* [RW] RGMII port ATE RX Expected Data 1 Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0   0x204800b0 /* [RO] RGMII port ATE RX Status 0 Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1   0x204800b4 /* [RO] RGMII port ATE RX Status 1 Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL      0x204800b8 /* [RW] RGMII port ATE TX Control Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0     0x204800bc /* [RW] RGMII port ATE TX Data 0 Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1     0x204800c0 /* [RW] RGMII port ATE TX Data 1 Register */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2     0x204800c4 /* [RW] RGMII port ATE TX Data 2 Register */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0  0x204800c8 /* [RW] RGMII Append TX Delay Control 0 Register */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1  0x204800cc /* [RW] RGMII Append TX Delay Control 1 Register */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0  0x204800d0 /* [RW] RGMII Append RX Delay Control 0 Register */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1  0x204800d4 /* [RW] RGMII Append RX Delay Control 1 Register */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2  0x204800d8 /* [RW] RGMII Append RX Delay Control 2 Register */

/***************************************************************************
 *EPHY_CNTRL - EPHY Power Management Register
 ***************************************************************************/
/* GENET_0_EXT :: EPHY_CNTRL :: reserved0 [31:31] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved0_MASK                 0x80000000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved0_SHIFT                31

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_phyad [30:26] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_phyad_MASK                0x7c000000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_phyad_SHIFT               26
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_phyad_DEFAULT             0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_cfg_refclk_freq_sel [25:24] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_freq_sel_MASK  0x03000000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_freq_sel_SHIFT 24
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_freq_sel_DEFAULT 0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_cfg_refclk_mux_sel [23:22] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_mux_sel_MASK   0x00c00000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_mux_sel_SHIFT  22
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_cfg_refclk_mux_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: reserved1 [21:21] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved1_MASK                 0x00200000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved1_SHIFT                21

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_phy_en [20:20] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_en_MASK       0x00100000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_en_SHIFT      20
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_en_DEFAULT    0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_phy_rd [19:19] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rd_MASK       0x00080000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rd_SHIFT      19
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rd_DEFAULT    0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_phy_sd [18:18] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_sd_MASK       0x00040000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_sd_SHIFT      18
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_sd_DEFAULT    0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_phy_rx [17:17] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rx_MASK       0x00020000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rx_SHIFT      17
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_rx_DEFAULT    0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_phy_tx [16:16] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_tx_MASK       0x00010000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_tx_SHIFT      16
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_phy_tx_DEFAULT    0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: reserved2 [15:15] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved2_MASK                 0x00008000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved2_SHIFT                15

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_test_en [14:14] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_en_MASK              0x00004000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_en_SHIFT             14
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_en_DEFAULT           0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: atest_25MHz_en [13:13] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_atest_25MHz_en_MASK            0x00002000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_atest_25MHz_en_SHIFT           13
#define BCHP_GENET_0_EXT_EPHY_CNTRL_atest_25MHz_en_DEFAULT         0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: energy_det_mask [12:12] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_energy_det_mask_MASK           0x00001000
#define BCHP_GENET_0_EXT_EPHY_CNTRL_energy_det_mask_SHIFT          12
#define BCHP_GENET_0_EXT_EPHY_CNTRL_energy_det_mask_DEFAULT        0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_standalone_mode [11:11] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_standalone_mode_MASK      0x00000800
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_standalone_mode_SHIFT     11
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_standalone_mode_DEFAULT   0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: ephy_test_mode [10:10] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_mode_MASK            0x00000400
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_mode_SHIFT           10
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ephy_test_mode_DEFAULT         0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: mdc_ex_clk_dis_ld [09:09] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_mdc_ex_clk_dis_ld_MASK         0x00000200
#define BCHP_GENET_0_EXT_EPHY_CNTRL_mdc_ex_clk_dis_ld_SHIFT        9
#define BCHP_GENET_0_EXT_EPHY_CNTRL_mdc_ex_clk_dis_ld_DEFAULT      0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: reset [08:08] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reset_MASK                     0x00000100
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reset_SHIFT                    8
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reset_DEFAULT                  0x00000000

/* GENET_0_EXT :: EPHY_CNTRL :: iddq_global_pwr [07:07] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_iddq_global_pwr_MASK           0x00000080
#define BCHP_GENET_0_EXT_EPHY_CNTRL_iddq_global_pwr_SHIFT          7
#define BCHP_GENET_0_EXT_EPHY_CNTRL_iddq_global_pwr_DEFAULT        0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: DLLBYP_PIN_F [06:06] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_DLLBYP_PIN_F_MASK              0x00000040
#define BCHP_GENET_0_EXT_EPHY_CNTRL_DLLBYP_PIN_F_SHIFT             6
#define BCHP_GENET_0_EXT_EPHY_CNTRL_DLLBYP_PIN_F_DEFAULT           0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: reserved3 [05:02] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved3_MASK                 0x0000003c
#define BCHP_GENET_0_EXT_EPHY_CNTRL_reserved3_SHIFT                2

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_dll [01:01] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_dll_MASK          0x00000002
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_dll_SHIFT         1
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_dll_DEFAULT       0x00000001

/* GENET_0_EXT :: EPHY_CNTRL :: ext_pwr_down_bias [00:00] */
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_bias_MASK         0x00000001
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_bias_SHIFT        0
#define BCHP_GENET_0_EXT_EPHY_CNTRL_ext_pwr_down_bias_DEFAULT      0x00000001

/***************************************************************************
 *EPHY_STATUS - ENDT EMCG Control Register
 ***************************************************************************/
/* GENET_0_EXT :: EPHY_STATUS :: reserved0 [31:08] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved0_MASK                0xffffff00
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved0_SHIFT               8

/* GENET_0_EXT :: EPHY_STATUS :: iddq_from_phy [07:07] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_iddq_from_phy_MASK            0x00000080
#define BCHP_GENET_0_EXT_EPHY_STATUS_iddq_from_phy_SHIFT           7
#define BCHP_GENET_0_EXT_EPHY_STATUS_iddq_from_phy_DEFAULT         0x00000000

/* GENET_0_EXT :: EPHY_STATUS :: energy_det [06:06] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_energy_det_MASK               0x00000040
#define BCHP_GENET_0_EXT_EPHY_STATUS_energy_det_SHIFT              6
#define BCHP_GENET_0_EXT_EPHY_STATUS_energy_det_DEFAULT            0x00000000

/* GENET_0_EXT :: EPHY_STATUS :: pll_lock [05:05] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_pll_lock_MASK                 0x00000020
#define BCHP_GENET_0_EXT_EPHY_STATUS_pll_lock_SHIFT                5
#define BCHP_GENET_0_EXT_EPHY_STATUS_pll_lock_DEFAULT              0x00000000

/* GENET_0_EXT :: EPHY_STATUS :: reserved1 [04:04] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved1_MASK                0x00000010
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved1_SHIFT               4

/* GENET_0_EXT :: EPHY_STATUS :: ephy_mac_cfg_test_mode [03:02] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_mode_MASK   0x0000000c
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_mode_SHIFT  2
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_mode_DEFAULT 0x00000000

/* GENET_0_EXT :: EPHY_STATUS :: ephy_mac_cfg_test_en [01:01] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_en_MASK     0x00000002
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_en_SHIFT    1
#define BCHP_GENET_0_EXT_EPHY_STATUS_ephy_mac_cfg_test_en_DEFAULT  0x00000000

/* GENET_0_EXT :: EPHY_STATUS :: reserved2 [00:00] */
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved2_MASK                0x00000001
#define BCHP_GENET_0_EXT_EPHY_STATUS_reserved2_SHIFT               0

/***************************************************************************
 *TEST_CNTRL - Test Control Register
 ***************************************************************************/
/* GENET_0_EXT :: TEST_CNTRL :: reserved0 [31:01] */
#define BCHP_GENET_0_EXT_TEST_CNTRL_reserved0_MASK                 0xfffffffe
#define BCHP_GENET_0_EXT_TEST_CNTRL_reserved0_SHIFT                1

/* GENET_0_EXT :: TEST_CNTRL :: un_used [00:00] */
#define BCHP_GENET_0_EXT_TEST_CNTRL_un_used_MASK                   0x00000001
#define BCHP_GENET_0_EXT_TEST_CNTRL_un_used_SHIFT                  0
#define BCHP_GENET_0_EXT_TEST_CNTRL_un_used_DEFAULT                0x00000000

/***************************************************************************
 *RGMII_OOB_CNTRL - RGMII OOB Control Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_OOB_CNTRL :: reserved0 [31:27] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved0_MASK            0xf8000000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved0_SHIFT           27

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: col_crs_mask [26:26] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_col_crs_mask_MASK         0x04000000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_col_crs_mask_SHIFT        26
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_col_crs_mask_DEFAULT      0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: rx_err_mask [25:25] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_err_mask_MASK          0x02000000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_err_mask_SHIFT         25
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_err_mask_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: lpi_count [24:20] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_lpi_count_MASK            0x01f00000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_lpi_count_SHIFT           20
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_lpi_count_DEFAULT         0x0000000f

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: tx_clk_stop_en [19:19] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_clk_stop_en_MASK       0x00080000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_clk_stop_en_SHIFT      19
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_clk_stop_en_DEFAULT    0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: tx_pause_en [18:18] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_pause_en_MASK          0x00040000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_pause_en_SHIFT         18
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_tx_pause_en_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: rx_pause_en [17:17] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_pause_en_MASK          0x00020000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_pause_en_SHIFT         17
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rx_pause_en_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: id_mode_dis [16:16] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_id_mode_dis_MASK          0x00010000
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_id_mode_dis_SHIFT         16
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_id_mode_dis_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: reserved1 [15:07] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved1_MASK            0x0000ff80
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved1_SHIFT           7

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: rgmii_mode_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rgmii_mode_en_MASK        0x00000040
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rgmii_mode_en_SHIFT       6
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_rgmii_mode_en_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: oob_dis [05:05] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_oob_dis_MASK              0x00000020
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_oob_dis_SHIFT             5
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_oob_dis_DEFAULT           0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: link [04:04] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_link_MASK                 0x00000010
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_link_SHIFT                4
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_link_DEFAULT              0x00000000

/* GENET_0_EXT :: RGMII_OOB_CNTRL :: reserved2 [03:00] */
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved2_MASK            0x0000000f
#define BCHP_GENET_0_EXT_RGMII_OOB_CNTRL_reserved2_SHIFT           0

/***************************************************************************
 *RGMII_IB_STATUS - RGMII InBand Status Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_IB_STATUS :: reserved0 [31:05] */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_reserved0_MASK            0xffffffe0
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_reserved0_SHIFT           5

/* GENET_0_EXT :: RGMII_IB_STATUS :: ib_status_ovrd [04:04] */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_ib_status_ovrd_MASK       0x00000010
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_ib_status_ovrd_SHIFT      4
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_ib_status_ovrd_DEFAULT    0x00000000

/* GENET_0_EXT :: RGMII_IB_STATUS :: link_decode [03:03] */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_link_decode_MASK          0x00000008
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_link_decode_SHIFT         3
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_link_decode_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_IB_STATUS :: duplex_decode [02:02] */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_duplex_decode_MASK        0x00000004
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_duplex_decode_SHIFT       2
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_duplex_decode_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_IB_STATUS :: speed_decode [01:00] */
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_speed_decode_MASK         0x00000003
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_speed_decode_SHIFT        0
#define BCHP_GENET_0_EXT_RGMII_IB_STATUS_speed_decode_DEFAULT      0x00000000

/***************************************************************************
 *RGMII_LED_CNTRL - RGMII LED Control Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_LED_CNTRL :: rgmii_led_on_cyc_count [31:16] */
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_on_cyc_count_MASK 0xffff0000
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_on_cyc_count_SHIFT 16
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_on_cyc_count_DEFAULT 0x00000670

/* GENET_0_EXT :: RGMII_LED_CNTRL :: rgmii_led_off_cyc_count [15:00] */
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_off_cyc_count_MASK 0x0000ffff
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_off_cyc_count_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_LED_CNTRL_rgmii_led_off_cyc_count_DEFAULT 0x00000670

/***************************************************************************
 *CLOCK_SEL_CNTRL - GENET CORE CLOCK and GMII CLOCK SELECT Control Register
 ***************************************************************************/
/* GENET_0_EXT :: CLOCK_SEL_CNTRL :: reserved0 [31:03] */
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_reserved0_MASK            0xfffffff8
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_reserved0_SHIFT           3

/* GENET_0_EXT :: CLOCK_SEL_CNTRL :: clk_sel [02:02] */
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_clk_sel_MASK              0x00000004
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_clk_sel_SHIFT             2
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_clk_sel_DEFAULT           0x00000000

/* GENET_0_EXT :: CLOCK_SEL_CNTRL :: core_clk_sel [01:01] */
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_core_clk_sel_MASK         0x00000002
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_core_clk_sel_SHIFT        1
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_core_clk_sel_DEFAULT      0x00000000

/* GENET_0_EXT :: CLOCK_SEL_CNTRL :: gmii_clk_sel [00:00] */
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_gmii_clk_sel_MASK         0x00000001
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_gmii_clk_sel_SHIFT        0
#define BCHP_GENET_0_EXT_CLOCK_SEL_CNTRL_gmii_clk_sel_DEFAULT      0x00000000

/***************************************************************************
 *GPHY_CNTRL - GPHY Control Register
 ***************************************************************************/
/* GENET_0_EXT :: GPHY_CNTRL :: reserved0 [31:16] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_reserved0_MASK                 0xffff0000
#define BCHP_GENET_0_EXT_GPHY_CNTRL_reserved0_SHIFT                16

/* GENET_0_EXT :: GPHY_CNTRL :: gphy_test_mode [15:14] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_mode_MASK            0x0000c000
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_mode_SHIFT           14
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_mode_DEFAULT         0x00000000

/* GENET_0_EXT :: GPHY_CNTRL :: gphy_test_en [13:13] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_en_MASK              0x00002000
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_en_SHIFT             13
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_test_en_DEFAULT           0x00000000

/* GENET_0_EXT :: GPHY_CNTRL :: gphy_phyad [12:08] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_phyad_MASK                0x00001f00
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_phyad_SHIFT               8
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_phyad_DEFAULT             0x00000001

/* GENET_0_EXT :: GPHY_CNTRL :: reserved1 [07:06] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_reserved1_MASK                 0x000000c0
#define BCHP_GENET_0_EXT_GPHY_CNTRL_reserved1_SHIFT                6

/* GENET_0_EXT :: GPHY_CNTRL :: gphy_reset [05:05] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_reset_MASK                0x00000020
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_reset_SHIFT               5
#define BCHP_GENET_0_EXT_GPHY_CNTRL_gphy_reset_DEFAULT             0x00000000

/* GENET_0_EXT :: GPHY_CNTRL :: ck25_dis [04:04] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_ck25_dis_MASK                  0x00000010
#define BCHP_GENET_0_EXT_GPHY_CNTRL_ck25_dis_SHIFT                 4
#define BCHP_GENET_0_EXT_GPHY_CNTRL_ck25_dis_DEFAULT               0x00000000

/* GENET_0_EXT :: GPHY_CNTRL :: cfg_iddq_global_pwr [03:03] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_global_pwr_MASK       0x00000008
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_global_pwr_SHIFT      3
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_global_pwr_DEFAULT    0x00000001

/* GENET_0_EXT :: GPHY_CNTRL :: cfg_force_dll_en [02:02] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_force_dll_en_MASK          0x00000004
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_force_dll_en_SHIFT         2
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_force_dll_en_DEFAULT       0x00000000

/* GENET_0_EXT :: GPHY_CNTRL :: cfg_ext_pwrdown [01:01] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_ext_pwrdown_MASK           0x00000002
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_ext_pwrdown_SHIFT          1
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_ext_pwrdown_DEFAULT        0x00000001

/* GENET_0_EXT :: GPHY_CNTRL :: cfg_iddq_bias [00:00] */
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_bias_MASK             0x00000001
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_bias_SHIFT            0
#define BCHP_GENET_0_EXT_GPHY_CNTRL_cfg_iddq_bias_DEFAULT          0x00000001

/***************************************************************************
 *GPHY_STATUS - GPHY Status Register
 ***************************************************************************/
/* GENET_0_EXT :: GPHY_STATUS :: reserved0 [31:07] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_reserved0_MASK                0xffffff80
#define BCHP_GENET_0_EXT_GPHY_STATUS_reserved0_SHIFT               7

/* GENET_0_EXT :: GPHY_STATUS :: gphy_lock_recovery_clk [06:06] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_gphy_lock_recovery_clk_MASK   0x00000040
#define BCHP_GENET_0_EXT_GPHY_STATUS_gphy_lock_recovery_clk_SHIFT  6
#define BCHP_GENET_0_EXT_GPHY_STATUS_gphy_lock_recovery_clk_DEFAULT 0x00000000

/* GENET_0_EXT :: GPHY_STATUS :: mac_gphy_cfg_test_mode [05:04] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_mac_gphy_cfg_test_mode_MASK   0x00000030
#define BCHP_GENET_0_EXT_GPHY_STATUS_mac_gphy_cfg_test_mode_SHIFT  4
#define BCHP_GENET_0_EXT_GPHY_STATUS_mac_gphy_cfg_test_mode_DEFAULT 0x00000000

/* GENET_0_EXT :: GPHY_STATUS :: i_gphy_cfg_test_en [03:03] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_i_gphy_cfg_test_en_MASK       0x00000008
#define BCHP_GENET_0_EXT_GPHY_STATUS_i_gphy_cfg_test_en_SHIFT      3
#define BCHP_GENET_0_EXT_GPHY_STATUS_i_gphy_cfg_test_en_DEFAULT    0x00000000

/* GENET_0_EXT :: GPHY_STATUS :: pll_lock [02:02] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_pll_lock_MASK                 0x00000004
#define BCHP_GENET_0_EXT_GPHY_STATUS_pll_lock_SHIFT                2
#define BCHP_GENET_0_EXT_GPHY_STATUS_pll_lock_DEFAULT              0x00000000

/* GENET_0_EXT :: GPHY_STATUS :: energy_det_apd [01:01] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_apd_MASK           0x00000002
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_apd_SHIFT          1
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_apd_DEFAULT        0x00000000

/* GENET_0_EXT :: GPHY_STATUS :: energy_det_masked [00:00] */
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_masked_MASK        0x00000001
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_masked_SHIFT       0
#define BCHP_GENET_0_EXT_GPHY_STATUS_energy_det_masked_DEFAULT     0x00000000

/***************************************************************************
 *RGMII_RX_CLOCK_DELAY_CNTRL - RGMII port RX Clock Delay Control Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: reserved0 [31:09] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_reserved0_MASK 0xfffffe00
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_reserved0_SHIFT 9

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: reset [08:08] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_reset_MASK     0x00000100
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_reset_SHIFT    8
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_reset_DEFAULT  0x00000000

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: dly_override [07:07] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_MASK 0x00000080
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_override_DEFAULT 0x00000001

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: dly_sel [06:06] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_MASK   0x00000040
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_SHIFT  6
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_dly_sel_DEFAULT 0x00000001

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: bypass [05:05] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_MASK    0x00000020
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_SHIFT   5
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_bypass_DEFAULT 0x00000001

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: iddq [04:04] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_MASK      0x00000010
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_SHIFT     4
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_iddq_DEFAULT   0x00000001

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: drng [03:02] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_drng_MASK      0x0000000c
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_drng_SHIFT     2
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_drng_DEFAULT   0x00000002

/* GENET_0_EXT :: RGMII_RX_CLOCK_DELAY_CNTRL :: ctri [01:00] */
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_MASK      0x00000003
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_SHIFT     0
#define BCHP_GENET_0_EXT_RGMII_RX_CLOCK_DELAY_CNTRL_ctri_DEFAULT   0x00000000

/***************************************************************************
 *RGMII_ATE_RX_CNTRL_EXP_DATA - RGMII port ATE RX Control and Expected Data Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: reserved0 [31:28] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_reserved0_MASK 0xf0000000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_reserved0_SHIFT 28

/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: ate_en [27:27] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_ate_en_MASK   0x08000000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_ate_en_SHIFT  27
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_ate_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: pkt_count_rst [26:26] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_pkt_count_rst_MASK 0x04000000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_pkt_count_rst_SHIFT 26
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_pkt_count_rst_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: good_count [25:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_good_count_MASK 0x03fc0000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_good_count_SHIFT 18
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_good_count_DEFAULT 0x00000004

/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: expected_data_1 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_1_MASK 0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_1_SHIFT 9
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_1_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_CNTRL_EXP_DATA :: expected_data_0 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_0_MASK 0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_0_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_CNTRL_EXP_DATA_expected_data_0_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_RX_EXP_DATA_1 - RGMII port ATE RX Expected Data 1 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_RX_EXP_DATA_1 :: reserved0 [31:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_reserved0_MASK    0xfffc0000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_reserved0_SHIFT   18

/* GENET_0_EXT :: RGMII_ATE_RX_EXP_DATA_1 :: expected_data_3 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_3_MASK 0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_3_SHIFT 9
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_3_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_EXP_DATA_1 :: expected_data_2 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_2_MASK 0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_2_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_EXP_DATA_1_expected_data_2_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_RX_STATUS_0 - RGMII port ATE RX Status 0 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_0 :: reserved0 [31:19] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_reserved0_MASK      0xfff80000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_reserved0_SHIFT     19

/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_0 :: rx_ok [18:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_rx_ok_MASK          0x00040000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_rx_ok_SHIFT         18
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_rx_ok_DEFAULT       0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_0 :: received_data_1 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_1_MASK 0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_1_SHIFT 9
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_1_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_0 :: received_data_0 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_0_MASK 0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_0_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_0_received_data_0_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_RX_STATUS_1 - RGMII port ATE RX Status 1 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_1 :: reserved0 [31:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_reserved0_MASK      0xfffc0000
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_reserved0_SHIFT     18

/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_1 :: received_data_3 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_3_MASK 0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_3_SHIFT 9
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_3_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_ATE_RX_STATUS_1 :: received_data_2 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_2_MASK 0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_2_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_ATE_RX_STATUS_1_received_data_2_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_TX_CNTRL - RGMII port ATE TX Control Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: reserved0 [31:28] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_reserved0_MASK         0xf0000000
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_reserved0_SHIFT        28

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: pkt_ipg [27:22] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_ipg_MASK           0x0fc00000
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_ipg_SHIFT          22
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_ipg_DEFAULT        0x0000000c

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: payload_length [21:11] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_payload_length_MASK    0x003ff800
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_payload_length_SHIFT   11
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_payload_length_DEFAULT 0x0000002e

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: pkt_cnt [10:03] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_cnt_MASK           0x000007f8
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_cnt_SHIFT          3
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_cnt_DEFAULT        0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: pkt_gen_en [02:02] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_gen_en_MASK        0x00000004
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_gen_en_SHIFT       2
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_pkt_gen_en_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: start_stop [01:01] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_MASK        0x00000002
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_SHIFT       1
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_CNTRL :: start_stop_ovrd [00:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_ovrd_MASK   0x00000001
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_ovrd_SHIFT  0
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_CNTRL_start_stop_ovrd_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_ATE_TX_DATA_0 - RGMII port ATE TX Data 0 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_TX_DATA_0 :: reserved0 [31:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_reserved0_MASK        0xfffc0000
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_reserved0_SHIFT       18

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_0 :: tx_data_1 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_1_MASK        0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_1_SHIFT       9
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_1_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_0 :: tx_data_0 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_0_MASK        0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_0_SHIFT       0
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_0_tx_data_0_DEFAULT     0x00000000

/***************************************************************************
 *RGMII_ATE_TX_DATA_1 - RGMII port ATE TX Data 1 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_TX_DATA_1 :: reserved0 [31:18] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_reserved0_MASK        0xfffc0000
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_reserved0_SHIFT       18

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_1 :: tx_data_3 [17:09] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_3_MASK        0x0003fe00
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_3_SHIFT       9
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_3_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_1 :: tx_data_2 [08:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_2_MASK        0x000001ff
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_2_SHIFT       0
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_1_tx_data_2_DEFAULT     0x00000000

/***************************************************************************
 *RGMII_ATE_TX_DATA_2 - RGMII port ATE TX Data 2 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_ATE_TX_DATA_2 :: ether_type [31:16] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_ether_type_MASK       0xffff0000
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_ether_type_SHIFT      16
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_ether_type_DEFAULT    0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_2 :: tx_data_5 [15:08] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_5_MASK        0x0000ff00
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_5_SHIFT       8
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_5_DEFAULT     0x00000000

/* GENET_0_EXT :: RGMII_ATE_TX_DATA_2 :: tx_data_4 [07:00] */
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_4_MASK        0x000000ff
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_4_SHIFT       0
#define BCHP_GENET_0_EXT_RGMII_ATE_TX_DATA_2_tx_data_4_DEFAULT     0x00000000

/***************************************************************************
 *RGMII_TX_DELAY_CNTRL_0 - RGMII Append TX Delay Control 0 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: reserved0 [31:28] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_reserved0_MASK     0xf0000000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_reserved0_SHIFT    28

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd3_del_ovrd_en [27:27] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_ovrd_en_MASK 0x08000000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_ovrd_en_SHIFT 27
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd3_del_sel [26:21] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_sel_MASK  0x07e00000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_sel_SHIFT 21
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd3_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd2_del_ovrd_en [20:20] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_ovrd_en_MASK 0x00100000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_ovrd_en_SHIFT 20
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd2_del_sel [19:14] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_sel_MASK  0x000fc000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_sel_SHIFT 14
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd2_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd1_del_ovrd_en [13:13] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_ovrd_en_MASK 0x00002000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_ovrd_en_SHIFT 13
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd1_del_sel [12:07] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_sel_MASK  0x00001f80
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_sel_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd1_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd0_del_ovrd_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_ovrd_en_MASK 0x00000040
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_ovrd_en_SHIFT 6
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_0 :: txd0_del_sel [05:00] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_sel_MASK  0x0000003f
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_sel_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_0_txd0_del_sel_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_TX_DELAY_CNTRL_1 - RGMII Append TX Delay Control 1 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: reserved0 [31:17] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_reserved0_MASK     0xfffe0000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_reserved0_SHIFT    17

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txclk_id_del_ovrd_en [16:16] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_ovrd_en_MASK 0x00010000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_ovrd_en_SHIFT 16
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txclk_id_del_sel [15:12] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_sel_MASK 0x0000f000
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_sel_SHIFT 12
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_id_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txclk_del_ovrd_en [11:11] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_ovrd_en_MASK 0x00000800
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_ovrd_en_SHIFT 11
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txclk_del_sel [10:07] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_sel_MASK 0x00000780
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_sel_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txclk_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txctl_del_ovrd_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_ovrd_en_MASK 0x00000040
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_ovrd_en_SHIFT 6
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_TX_DELAY_CNTRL_1 :: txctl_del_sel [05:00] */
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_sel_MASK 0x0000003f
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_sel_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_TX_DELAY_CNTRL_1_txctl_del_sel_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_RX_DELAY_CNTRL_0 - RGMII Append RX Delay Control 0 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: reserved0 [31:28] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_reserved0_MASK     0xf0000000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_reserved0_SHIFT    28

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd3_del_ovrd_en [27:27] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_ovrd_en_MASK 0x08000000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_ovrd_en_SHIFT 27
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd3_del_sel [26:21] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_sel_MASK  0x07e00000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_sel_SHIFT 21
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd3_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd2_del_ovrd_en [20:20] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_ovrd_en_MASK 0x00100000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_ovrd_en_SHIFT 20
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd2_del_sel [19:14] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_sel_MASK  0x000fc000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_sel_SHIFT 14
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd2_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd1_del_ovrd_en [13:13] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_ovrd_en_MASK 0x00002000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_ovrd_en_SHIFT 13
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd1_del_sel [12:07] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_sel_MASK  0x00001f80
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_sel_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd1_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd0_del_ovrd_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_ovrd_en_MASK 0x00000040
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_ovrd_en_SHIFT 6
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_0 :: rxd0_del_sel [05:00] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_sel_MASK  0x0000003f
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_sel_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_0_rxd0_del_sel_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_RX_DELAY_CNTRL_1 - RGMII Append RX Delay Control 1 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: reserved0 [31:28] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_reserved0_MASK     0xf0000000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_reserved0_SHIFT    28

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd7_del_ovrd_en [27:27] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_ovrd_en_MASK 0x08000000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_ovrd_en_SHIFT 27
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd7_del_sel [26:21] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_sel_MASK  0x07e00000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_sel_SHIFT 21
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd7_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd6_del_ovrd_en [20:20] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_ovrd_en_MASK 0x00100000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_ovrd_en_SHIFT 20
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd6_del_sel [19:14] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_sel_MASK  0x000fc000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_sel_SHIFT 14
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd6_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd5_del_ovrd_en [13:13] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_ovrd_en_MASK 0x00002000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_ovrd_en_SHIFT 13
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd5_del_sel [12:07] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_sel_MASK  0x00001f80
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_sel_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd5_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd4_del_ovrd_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_ovrd_en_MASK 0x00000040
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_ovrd_en_SHIFT 6
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_1 :: rxd4_del_sel [05:00] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_sel_MASK  0x0000003f
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_sel_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_1_rxd4_del_sel_DEFAULT 0x00000000

/***************************************************************************
 *RGMII_RX_DELAY_CNTRL_2 - RGMII Append RX Delay Control 2 Register
 ***************************************************************************/
/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: reserved0 [31:19] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_reserved0_MASK     0xfff80000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_reserved0_SHIFT    19

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxclk_del_ovrd_en [18:18] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_ovrd_en_MASK 0x00040000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_ovrd_en_SHIFT 18
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxclk_del_sel [17:14] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_sel_MASK 0x0003c000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_sel_SHIFT 14
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxclk_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxctl_neg_del_ovrd_en [13:13] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_ovrd_en_MASK 0x00002000
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_ovrd_en_SHIFT 13
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxctl_neg_del_sel [12:07] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_sel_MASK 0x00001f80
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_sel_SHIFT 7
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_neg_del_sel_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxctl_pos_del_ovrd_en [06:06] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_ovrd_en_MASK 0x00000040
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_ovrd_en_SHIFT 6
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_ovrd_en_DEFAULT 0x00000000

/* GENET_0_EXT :: RGMII_RX_DELAY_CNTRL_2 :: rxctl_pos_del_sel [05:00] */
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_sel_MASK 0x0000003f
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_sel_SHIFT 0
#define BCHP_GENET_0_EXT_RGMII_RX_DELAY_CNTRL_2_rxctl_pos_del_sel_DEFAULT 0x00000000

#endif /* #ifndef BCHP_GENET_0_EXT_H__ */

/* End of File */
