/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Tue Oct 10 01:11:42 2017
 *                 Full Compile MD5 Checksum  ea353cbbaf7534b1acfabe87187756c5
 *                     (minus title and desc)
 *                 MD5 Checksum               bd09f6ea4577b9d8ea88a425effe4ef4
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_MEMC_EDIS_0_0_H__
#define BCHP_MEMC_EDIS_0_0_H__

/***************************************************************************
 *MEMC_EDIS_0_0 - Enhanced Device Interface Stress (EDIS) Client 0 Registers
 ***************************************************************************/
#define BCHP_MEMC_EDIS_0_0_REV_ID                0x0001900800 /* [RO][32] Enhanced Device Interface Stress (EDIS) revision ID */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG             0x0001900804 /* [CFG][32] Control Triggers for actions */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE             0x0001900808 /* [CFG][32] Control Modes for accesses */
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE             0x000190080c /* [CFG][32] Control Sizes for accesses */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START       0x0001900810 /* [CFG][32] Control Starting Address for accesses */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT   0x0001900814 /* [CFG][32] Control Starting Address Extension for accesses */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END         0x0001900818 /* [CFG][32] Control Ending Address for accesses */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT     0x000190081c /* [CFG][32] Control Ending Address Extension for accesses */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN             0x0001900840 /* [RO][32] Main Status of EDIS operation */
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_WRITTEN    0x0001900844 /* [RO][32] Status Count of 32-byte JWords Written */
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_READ       0x0001900848 /* [RO][32] Status Count of 32-byte JWords Read */
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_COUNT      0x000190084c /* [RO][32] Total Bit Error Count on the Interface */
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_BITS       0x0001900850 /* [RO][32] Per SCB Byte Lane Error Flags */
#define BCHP_MEMC_EDIS_0_0_STAT_CLOCK_CYCLES     0x000190085c /* [RO][32] Clock Cycle Count While Processing */
#define BCHP_MEMC_EDIS_0_0_STAT_DEBUG            0x000190087c /* [RO][32] Internal Debug State */
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_0      0x00019008a0 /* [RW][32] Generator LFSR 0 State */
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_1      0x00019008a4 /* [RW][32] Generator LFSR 1 State */
#define BCHP_MEMC_EDIS_0_0_GEN_PATTERN           0x00019008a8 /* [CFG][32] Pattern for Word Mode */

/***************************************************************************
 *REV_ID - Enhanced Device Interface Stress (EDIS) revision ID
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: REV_ID :: reserved0 [31:16] */
#define BCHP_MEMC_EDIS_0_0_REV_ID_reserved0_MASK                   0xffff0000
#define BCHP_MEMC_EDIS_0_0_REV_ID_reserved0_SHIFT                  16

/* MEMC_EDIS_0_0 :: REV_ID :: MAJOR_REV_ID [15:12] */
#define BCHP_MEMC_EDIS_0_0_REV_ID_MAJOR_REV_ID_MASK                0x0000f000
#define BCHP_MEMC_EDIS_0_0_REV_ID_MAJOR_REV_ID_SHIFT               12
#define BCHP_MEMC_EDIS_0_0_REV_ID_MAJOR_REV_ID_DEFAULT             0x0000000f

/* MEMC_EDIS_0_0 :: REV_ID :: MINOR_REV_ID [11:08] */
#define BCHP_MEMC_EDIS_0_0_REV_ID_MINOR_REV_ID_MASK                0x00000f00
#define BCHP_MEMC_EDIS_0_0_REV_ID_MINOR_REV_ID_SHIFT               8
#define BCHP_MEMC_EDIS_0_0_REV_ID_MINOR_REV_ID_DEFAULT             0x00000000

/* MEMC_EDIS_0_0 :: REV_ID :: ALL_LAYER_ID [07:04] */
#define BCHP_MEMC_EDIS_0_0_REV_ID_ALL_LAYER_ID_MASK                0x000000f0
#define BCHP_MEMC_EDIS_0_0_REV_ID_ALL_LAYER_ID_SHIFT               4
#define BCHP_MEMC_EDIS_0_0_REV_ID_ALL_LAYER_ID_DEFAULT             0x00000000

/* MEMC_EDIS_0_0 :: REV_ID :: METAL_LAYER_ID [03:00] */
#define BCHP_MEMC_EDIS_0_0_REV_ID_METAL_LAYER_ID_MASK              0x0000000f
#define BCHP_MEMC_EDIS_0_0_REV_ID_METAL_LAYER_ID_SHIFT             0
#define BCHP_MEMC_EDIS_0_0_REV_ID_METAL_LAYER_ID_DEFAULT           0x00000000

/***************************************************************************
 *CTRL_TRIG - Control Triggers for actions
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_TRIG :: reserved0 [31:05] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_reserved0_MASK                0xffffffe0
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_reserved0_SHIFT               5

/* MEMC_EDIS_0_0 :: CTRL_TRIG :: CLEAR_STATS [04:04] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CLEAR_STATS_MASK              0x00000010
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CLEAR_STATS_SHIFT             4
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CLEAR_STATS_DEFAULT           0x00000000

/* MEMC_EDIS_0_0 :: CTRL_TRIG :: CONTINUE_ACCESSES [03:03] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CONTINUE_ACCESSES_MASK        0x00000008
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CONTINUE_ACCESSES_SHIFT       3
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_CONTINUE_ACCESSES_DEFAULT     0x00000000

/* MEMC_EDIS_0_0 :: CTRL_TRIG :: STOP_ACCESSES [02:02] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_STOP_ACCESSES_MASK            0x00000004
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_STOP_ACCESSES_SHIFT           2
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_STOP_ACCESSES_DEFAULT         0x00000000

/* MEMC_EDIS_0_0 :: CTRL_TRIG :: PAUSE_ACCESSES [01:01] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_PAUSE_ACCESSES_MASK           0x00000002
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_PAUSE_ACCESSES_SHIFT          1
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_PAUSE_ACCESSES_DEFAULT        0x00000000

/* MEMC_EDIS_0_0 :: CTRL_TRIG :: START_ACCESSES [00:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_START_ACCESSES_MASK           0x00000001
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_START_ACCESSES_SHIFT          0
#define BCHP_MEMC_EDIS_0_0_CTRL_TRIG_START_ACCESSES_DEFAULT        0x00000000

/***************************************************************************
 *CTRL_MODE - Control Modes for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_MODE :: CLOCK_GATE [31:31] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_CLOCK_GATE_MASK               0x80000000
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_CLOCK_GATE_SHIFT              31
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_CLOCK_GATE_DEFAULT            0x00000001
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_CLOCK_GATE_DISABLED           0
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_CLOCK_GATE_ENABLED            1

/* MEMC_EDIS_0_0 :: CTRL_MODE :: reserved_for_eco0 [30:12] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco0_MASK        0x7ffff000
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco0_SHIFT       12
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco0_DEFAULT     0x00000000

/* MEMC_EDIS_0_0 :: CTRL_MODE :: DATA_SELECT [11:08] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_MASK              0x00000f00
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_SHIFT             8
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_DEFAULT           0x00000000
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_WORD              0
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_COUNT             1
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_DATA_SELECT_LFSR              2

/* MEMC_EDIS_0_0 :: CTRL_MODE :: reserved_for_eco1 [07:06] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco1_MASK        0x000000c0
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco1_SHIFT       6
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved_for_eco1_DEFAULT     0x00000000

/* MEMC_EDIS_0_0 :: CTRL_MODE :: PAUSE_ON_ERROR [05:05] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_PAUSE_ON_ERROR_MASK           0x00000020
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_PAUSE_ON_ERROR_SHIFT          5
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_PAUSE_ON_ERROR_DEFAULT        0x00000000

/* MEMC_EDIS_0_0 :: CTRL_MODE :: LOOP_MODE [04:04] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_LOOP_MODE_MASK                0x00000010
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_LOOP_MODE_SHIFT               4
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_LOOP_MODE_DEFAULT             0x00000000

/* MEMC_EDIS_0_0 :: CTRL_MODE :: reserved2 [03:02] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved2_MASK                0x0000000c
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_reserved2_SHIFT               2

/* MEMC_EDIS_0_0 :: CTRL_MODE :: ACCESS_MODE [01:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_MASK              0x00000003
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_SHIFT             0
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_DEFAULT           0x00000000
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_WR_ONLY           0
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_RD_ONLY           1
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_WRWR_RDRD         2
#define BCHP_MEMC_EDIS_0_0_CTRL_MODE_ACCESS_MODE_WRRD_WRRD         3

/***************************************************************************
 *CTRL_SIZE - Control Sizes for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_SIZE :: reserved0 [31:29] */
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_reserved0_MASK                0xe0000000
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_reserved0_SHIFT               29

/* MEMC_EDIS_0_0 :: CTRL_SIZE :: BURST_SIZE [28:24] */
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_BURST_SIZE_MASK               0x1f000000
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_BURST_SIZE_SHIFT              24
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_BURST_SIZE_DEFAULT            0x00000000

/* MEMC_EDIS_0_0 :: CTRL_SIZE :: STEP_SIZE [23:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_STEP_SIZE_MASK                0x00ffffff
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_STEP_SIZE_SHIFT               0
#define BCHP_MEMC_EDIS_0_0_CTRL_SIZE_STEP_SIZE_DEFAULT             0x00000000

/***************************************************************************
 *CTRL_ADDR_START - Control Starting Address for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_ADDR_START :: ADDR [31:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_ADDR_MASK               0xffffffff
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_ADDR_SHIFT              0
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_ADDR_DEFAULT            0x00000000

/***************************************************************************
 *CTRL_ADDR_START_EXT - Control Starting Address Extension for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_ADDR_START_EXT :: reserved0 [31:08] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT_reserved0_MASK      0xffffff00
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT_reserved0_SHIFT     8

/* MEMC_EDIS_0_0 :: CTRL_ADDR_START_EXT :: ADDR_EXT [07:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT_ADDR_EXT_MASK       0x000000ff
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT_ADDR_EXT_SHIFT      0
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_START_EXT_ADDR_EXT_DEFAULT    0x00000000

/***************************************************************************
 *CTRL_ADDR_END - Control Ending Address for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_ADDR_END :: ADDR [31:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_ADDR_MASK                 0xffffffff
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_ADDR_SHIFT                0
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_ADDR_DEFAULT              0x00000000

/***************************************************************************
 *CTRL_ADDR_END_EXT - Control Ending Address Extension for accesses
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: CTRL_ADDR_END_EXT :: reserved0 [31:08] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT_reserved0_MASK        0xffffff00
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT_reserved0_SHIFT       8

/* MEMC_EDIS_0_0 :: CTRL_ADDR_END_EXT :: ADDR_EXT [07:00] */
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT_ADDR_EXT_MASK         0x000000ff
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT_ADDR_EXT_SHIFT        0
#define BCHP_MEMC_EDIS_0_0_CTRL_ADDR_END_EXT_ADDR_EXT_DEFAULT      0x00000000

/***************************************************************************
 *STAT_MAIN - Main Status of EDIS operation
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_MAIN :: reserved0 [31:04] */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_reserved0_MASK                0xfffffff0
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_reserved0_SHIFT               4

/* MEMC_EDIS_0_0 :: STAT_MAIN :: READ_ERROR [03:03] */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_READ_ERROR_MASK               0x00000008
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_READ_ERROR_SHIFT              3
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_READ_ERROR_DEFAULT            0x00000000

/* MEMC_EDIS_0_0 :: STAT_MAIN :: STALLED [02:02] */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_STALLED_MASK                  0x00000004
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_STALLED_SHIFT                 2
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_STALLED_DEFAULT               0x00000000

/* MEMC_EDIS_0_0 :: STAT_MAIN :: DONE [01:01] */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_DONE_MASK                     0x00000002
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_DONE_SHIFT                    1
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_DONE_DEFAULT                  0x00000000

/* MEMC_EDIS_0_0 :: STAT_MAIN :: BUSY [00:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_BUSY_MASK                     0x00000001
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_BUSY_SHIFT                    0
#define BCHP_MEMC_EDIS_0_0_STAT_MAIN_BUSY_DEFAULT                  0x00000000

/***************************************************************************
 *STAT_WORDS_WRITTEN - Status Count of 32-byte JWords Written
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_WORDS_WRITTEN :: WORD_COUNT [31:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_WRITTEN_WORD_COUNT_MASK      0xffffffff
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_WRITTEN_WORD_COUNT_SHIFT     0
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_WRITTEN_WORD_COUNT_DEFAULT   0x00000000

/***************************************************************************
 *STAT_WORDS_READ - Status Count of 32-byte JWords Read
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_WORDS_READ :: WORD_COUNT [31:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_READ_WORD_COUNT_MASK         0xffffffff
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_READ_WORD_COUNT_SHIFT        0
#define BCHP_MEMC_EDIS_0_0_STAT_WORDS_READ_WORD_COUNT_DEFAULT      0x00000000

/***************************************************************************
 *STAT_ERROR_COUNT - Total Bit Error Count on the Interface
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_ERROR_COUNT :: COUNT [31:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_COUNT_COUNT_MASK             0xffffffff
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_COUNT_COUNT_SHIFT            0
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_COUNT_COUNT_DEFAULT          0x00000000

/***************************************************************************
 *STAT_ERROR_BITS - Per SCB Byte Lane Error Flags
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_ERROR_BITS :: BYTE_LANE_ERRORS [31:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_BITS_BYTE_LANE_ERRORS_MASK   0xffffffff
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_BITS_BYTE_LANE_ERRORS_SHIFT  0
#define BCHP_MEMC_EDIS_0_0_STAT_ERROR_BITS_BYTE_LANE_ERRORS_DEFAULT 0x00000000

/***************************************************************************
 *STAT_CLOCK_CYCLES - Clock Cycle Count While Processing
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_CLOCK_CYCLES :: COUNT [31:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_CLOCK_CYCLES_COUNT_MASK            0xffffffff
#define BCHP_MEMC_EDIS_0_0_STAT_CLOCK_CYCLES_COUNT_SHIFT           0
#define BCHP_MEMC_EDIS_0_0_STAT_CLOCK_CYCLES_COUNT_DEFAULT         0x00000000

/***************************************************************************
 *STAT_DEBUG - Internal Debug State
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: STAT_DEBUG :: MISC [31:02] */
#define BCHP_MEMC_EDIS_0_0_STAT_DEBUG_MISC_MASK                    0xfffffffc
#define BCHP_MEMC_EDIS_0_0_STAT_DEBUG_MISC_SHIFT                   2

/* MEMC_EDIS_0_0 :: STAT_DEBUG :: FSM_STATE [01:00] */
#define BCHP_MEMC_EDIS_0_0_STAT_DEBUG_FSM_STATE_MASK               0x00000003
#define BCHP_MEMC_EDIS_0_0_STAT_DEBUG_FSM_STATE_SHIFT              0

/***************************************************************************
 *GEN_LFSR_STATE_0 - Generator LFSR 0 State
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: GEN_LFSR_STATE_0 :: GEN_LFSR_STATE [31:00] */
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_0_GEN_LFSR_STATE_MASK    0xffffffff
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_0_GEN_LFSR_STATE_SHIFT   0
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_0_GEN_LFSR_STATE_DEFAULT 0x00000000

/***************************************************************************
 *GEN_LFSR_STATE_1 - Generator LFSR 1 State
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: GEN_LFSR_STATE_1 :: GEN_LFSR_STATE [31:00] */
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_1_GEN_LFSR_STATE_MASK    0xffffffff
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_1_GEN_LFSR_STATE_SHIFT   0
#define BCHP_MEMC_EDIS_0_0_GEN_LFSR_STATE_1_GEN_LFSR_STATE_DEFAULT 0x00000000

/***************************************************************************
 *GEN_PATTERN - Pattern for Word Mode
 ***************************************************************************/
/* MEMC_EDIS_0_0 :: GEN_PATTERN :: GEN_PATTERN [31:00] */
#define BCHP_MEMC_EDIS_0_0_GEN_PATTERN_GEN_PATTERN_MASK            0xffffffff
#define BCHP_MEMC_EDIS_0_0_GEN_PATTERN_GEN_PATTERN_SHIFT           0
#define BCHP_MEMC_EDIS_0_0_GEN_PATTERN_GEN_PATTERN_DEFAULT         0x00000000

#endif /* #ifndef BCHP_MEMC_EDIS_0_0_H__ */

/* End of File */
