/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Tue Oct 10 01:11:39 2017
 *                 Full Compile MD5 Checksum  ea353cbbaf7534b1acfabe87187756c5
 *                     (minus title and desc)
 *                 MD5 Checksum               bd09f6ea4577b9d8ea88a425effe4ef4
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_GIO_H__
#define BCHP_GIO_H__

/***************************************************************************
 *GIO - GPIO
 ***************************************************************************/
#define BCHP_GIO_ODEN_LO                         0x000040a500 /* [CFG][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[031:000] */
#define BCHP_GIO_DATA_LO                         0x000040a504 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[031:000] */
#define BCHP_GIO_IODIR_LO                        0x000040a508 /* [CFG][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[031:000] */
#define BCHP_GIO_EC_LO                           0x000040a50c /* [CFG][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[031:000] */
#define BCHP_GIO_EI_LO                           0x000040a510 /* [CFG][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[031:000] */
#define BCHP_GIO_MASK_LO                         0x000040a514 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[031:000] */
#define BCHP_GIO_LEVEL_LO                        0x000040a518 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[031:000] */
#define BCHP_GIO_STAT_LO                         0x000040a51c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[031:000] */
#define BCHP_GIO_ODEN_HI                         0x000040a520 /* [CFG][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[063:032] */
#define BCHP_GIO_DATA_HI                         0x000040a524 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[063:032] */
#define BCHP_GIO_IODIR_HI                        0x000040a528 /* [CFG][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[063:032] */
#define BCHP_GIO_EC_HI                           0x000040a52c /* [CFG][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[063:032] */
#define BCHP_GIO_EI_HI                           0x000040a530 /* [CFG][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[063:032] */
#define BCHP_GIO_MASK_HI                         0x000040a534 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[063:032] */
#define BCHP_GIO_LEVEL_HI                        0x000040a538 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[063:032] */
#define BCHP_GIO_STAT_HI                         0x000040a53c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[063:032] */
#define BCHP_GIO_ODEN_EXT_HI                     0x000040a540 /* [CFG][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[095:064] */
#define BCHP_GIO_DATA_EXT_HI                     0x000040a544 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[095:064] */
#define BCHP_GIO_IODIR_EXT_HI                    0x000040a548 /* [CFG][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[095:064] */
#define BCHP_GIO_EC_EXT_HI                       0x000040a54c /* [CFG][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[095:064] */
#define BCHP_GIO_EI_EXT_HI                       0x000040a550 /* [CFG][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[095:064] */
#define BCHP_GIO_MASK_EXT_HI                     0x000040a554 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[095:064] */
#define BCHP_GIO_LEVEL_EXT_HI                    0x000040a558 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[095:064] */
#define BCHP_GIO_STAT_EXT_HI                     0x000040a55c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[095:064] */
#define BCHP_GIO_ODEN_EXT2                       0x000040a560 /* [CFG][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[108:096] */
#define BCHP_GIO_DATA_EXT2                       0x000040a564 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[108:096] */
#define BCHP_GIO_IODIR_EXT2                      0x000040a568 /* [CFG][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[108:096] */
#define BCHP_GIO_EC_EXT2                         0x000040a56c /* [CFG][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[108:096] */
#define BCHP_GIO_EI_EXT2                         0x000040a570 /* [CFG][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[108:096] */
#define BCHP_GIO_MASK_EXT2                       0x000040a574 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[108:096] */
#define BCHP_GIO_LEVEL_EXT2                      0x000040a578 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[108:096] */
#define BCHP_GIO_STAT_EXT2                       0x000040a57c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[108:096] */
#define BCHP_GIO_ODEN_EXT                        0x000040a580 /* [CFG][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR SGPIO[003:000] */
#define BCHP_GIO_DATA_EXT                        0x000040a584 /* [RW][32] GENERAL PURPOSE I/O DATA FOR SGPIO[003:000] */
#define BCHP_GIO_IODIR_EXT                       0x000040a588 /* [CFG][32] GENERAL PURPOSE I/O DIRECTION FOR SGPIO[003:000] */
#define BCHP_GIO_EC_EXT                          0x000040a58c /* [CFG][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR SGPIO[003:000] */
#define BCHP_GIO_EI_EXT                          0x000040a590 /* [CFG][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR SGPIO[003:000] */
#define BCHP_GIO_MASK_EXT                        0x000040a594 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR SGPIO[003:000] */
#define BCHP_GIO_LEVEL_EXT                       0x000040a598 /* [CFG][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR SGPIO[003:000] */
#define BCHP_GIO_STAT_EXT                        0x000040a59c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR SGPIO[003:000] */

/***************************************************************************
 *ODEN_LO - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: ODEN_LO :: oden [31:00] */
#define BCHP_GIO_ODEN_LO_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_LO_oden_SHIFT                                0
#define BCHP_GIO_ODEN_LO_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_LO - GENERAL PURPOSE I/O DATA FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: DATA_LO :: data [31:00] */
#define BCHP_GIO_DATA_LO_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_LO_data_SHIFT                                0
#define BCHP_GIO_DATA_LO_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_LO - GENERAL PURPOSE I/O DIRECTION FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: IODIR_LO :: iodir [31:00] */
#define BCHP_GIO_IODIR_LO_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_LO_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_LO_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_LO - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: EC_LO :: edge_config [31:00] */
#define BCHP_GIO_EC_LO_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_LO_edge_config_SHIFT                           0
#define BCHP_GIO_EC_LO_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_LO - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: EI_LO :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_LO_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_LO_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_LO_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_LO - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: MASK_LO :: irq_mask [31:00] */
#define BCHP_GIO_MASK_LO_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_LO_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_LO_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_LO - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: LEVEL_LO :: level [31:00] */
#define BCHP_GIO_LEVEL_LO_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_LO_level_SHIFT                              0
#define BCHP_GIO_LEVEL_LO_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_LO - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[031:000]
 ***************************************************************************/
/* GIO :: STAT_LO :: irq_status [31:00] */
#define BCHP_GIO_STAT_LO_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_LO_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_LO_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: ODEN_HI :: oden [31:00] */
#define BCHP_GIO_ODEN_HI_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_HI_oden_SHIFT                                0
#define BCHP_GIO_ODEN_HI_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_HI - GENERAL PURPOSE I/O DATA FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: DATA_HI :: data [31:00] */
#define BCHP_GIO_DATA_HI_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_HI_data_SHIFT                                0
#define BCHP_GIO_DATA_HI_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_HI - GENERAL PURPOSE I/O DIRECTION FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: IODIR_HI :: iodir [31:00] */
#define BCHP_GIO_IODIR_HI_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_HI_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_HI_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: EC_HI :: edge_config [31:00] */
#define BCHP_GIO_EC_HI_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_HI_edge_config_SHIFT                           0
#define BCHP_GIO_EC_HI_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: EI_HI :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_HI_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_HI_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_HI_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_HI - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: MASK_HI :: irq_mask [31:00] */
#define BCHP_GIO_MASK_HI_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_HI_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_HI_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_HI - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: LEVEL_HI :: level [31:00] */
#define BCHP_GIO_LEVEL_HI_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_HI_level_SHIFT                              0
#define BCHP_GIO_LEVEL_HI_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[063:032]
 ***************************************************************************/
/* GIO :: STAT_HI :: irq_status [31:00] */
#define BCHP_GIO_STAT_HI_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_HI_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_HI_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_EXT_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: ODEN_EXT_HI :: oden [31:00] */
#define BCHP_GIO_ODEN_EXT_HI_oden_MASK                             0xffffffff
#define BCHP_GIO_ODEN_EXT_HI_oden_SHIFT                            0
#define BCHP_GIO_ODEN_EXT_HI_oden_DEFAULT                          0x00000000

/***************************************************************************
 *DATA_EXT_HI - GENERAL PURPOSE I/O DATA FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: DATA_EXT_HI :: data [31:00] */
#define BCHP_GIO_DATA_EXT_HI_data_MASK                             0xffffffff
#define BCHP_GIO_DATA_EXT_HI_data_SHIFT                            0
#define BCHP_GIO_DATA_EXT_HI_data_DEFAULT                          0x00000000

/***************************************************************************
 *IODIR_EXT_HI - GENERAL PURPOSE I/O DIRECTION FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: IODIR_EXT_HI :: iodir [31:00] */
#define BCHP_GIO_IODIR_EXT_HI_iodir_MASK                           0xffffffff
#define BCHP_GIO_IODIR_EXT_HI_iodir_SHIFT                          0
#define BCHP_GIO_IODIR_EXT_HI_iodir_DEFAULT                        0xffffffff

/***************************************************************************
 *EC_EXT_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: EC_EXT_HI :: edge_config [31:00] */
#define BCHP_GIO_EC_EXT_HI_edge_config_MASK                        0xffffffff
#define BCHP_GIO_EC_EXT_HI_edge_config_SHIFT                       0
#define BCHP_GIO_EC_EXT_HI_edge_config_DEFAULT                     0x00000000

/***************************************************************************
 *EI_EXT_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: EI_EXT_HI :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_MASK                   0xffffffff
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_SHIFT                  0
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_DEFAULT                0x00000000

/***************************************************************************
 *MASK_EXT_HI - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: MASK_EXT_HI :: irq_mask [31:00] */
#define BCHP_GIO_MASK_EXT_HI_irq_mask_MASK                         0xffffffff
#define BCHP_GIO_MASK_EXT_HI_irq_mask_SHIFT                        0
#define BCHP_GIO_MASK_EXT_HI_irq_mask_DEFAULT                      0x00000000

/***************************************************************************
 *LEVEL_EXT_HI - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: LEVEL_EXT_HI :: level [31:00] */
#define BCHP_GIO_LEVEL_EXT_HI_level_MASK                           0xffffffff
#define BCHP_GIO_LEVEL_EXT_HI_level_SHIFT                          0
#define BCHP_GIO_LEVEL_EXT_HI_level_DEFAULT                        0x00000000

/***************************************************************************
 *STAT_EXT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[095:064]
 ***************************************************************************/
/* GIO :: STAT_EXT_HI :: irq_status [31:00] */
#define BCHP_GIO_STAT_EXT_HI_irq_status_MASK                       0xffffffff
#define BCHP_GIO_STAT_EXT_HI_irq_status_SHIFT                      0
#define BCHP_GIO_STAT_EXT_HI_irq_status_DEFAULT                    0x00000000

/***************************************************************************
 *ODEN_EXT2 - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: ODEN_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_ODEN_EXT2_reserved0_MASK                          0xffffe000
#define BCHP_GIO_ODEN_EXT2_reserved0_SHIFT                         13

/* GIO :: ODEN_EXT2 :: oden [12:00] */
#define BCHP_GIO_ODEN_EXT2_oden_MASK                               0x00001fff
#define BCHP_GIO_ODEN_EXT2_oden_SHIFT                              0
#define BCHP_GIO_ODEN_EXT2_oden_DEFAULT                            0x00000000

/***************************************************************************
 *DATA_EXT2 - GENERAL PURPOSE I/O DATA FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: DATA_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_DATA_EXT2_reserved0_MASK                          0xffffe000
#define BCHP_GIO_DATA_EXT2_reserved0_SHIFT                         13

/* GIO :: DATA_EXT2 :: data [12:00] */
#define BCHP_GIO_DATA_EXT2_data_MASK                               0x00001fff
#define BCHP_GIO_DATA_EXT2_data_SHIFT                              0
#define BCHP_GIO_DATA_EXT2_data_DEFAULT                            0x00000000

/***************************************************************************
 *IODIR_EXT2 - GENERAL PURPOSE I/O DIRECTION FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: IODIR_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_IODIR_EXT2_reserved0_MASK                         0xffffe000
#define BCHP_GIO_IODIR_EXT2_reserved0_SHIFT                        13

/* GIO :: IODIR_EXT2 :: iodir [12:00] */
#define BCHP_GIO_IODIR_EXT2_iodir_MASK                             0x00001fff
#define BCHP_GIO_IODIR_EXT2_iodir_SHIFT                            0
#define BCHP_GIO_IODIR_EXT2_iodir_DEFAULT                          0x00001fff

/***************************************************************************
 *EC_EXT2 - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: EC_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_EC_EXT2_reserved0_MASK                            0xffffe000
#define BCHP_GIO_EC_EXT2_reserved0_SHIFT                           13

/* GIO :: EC_EXT2 :: edge_config [12:00] */
#define BCHP_GIO_EC_EXT2_edge_config_MASK                          0x00001fff
#define BCHP_GIO_EC_EXT2_edge_config_SHIFT                         0
#define BCHP_GIO_EC_EXT2_edge_config_DEFAULT                       0x00000000

/***************************************************************************
 *EI_EXT2 - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: EI_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_EI_EXT2_reserved0_MASK                            0xffffe000
#define BCHP_GIO_EI_EXT2_reserved0_SHIFT                           13

/* GIO :: EI_EXT2 :: edge_insensitive [12:00] */
#define BCHP_GIO_EI_EXT2_edge_insensitive_MASK                     0x00001fff
#define BCHP_GIO_EI_EXT2_edge_insensitive_SHIFT                    0
#define BCHP_GIO_EI_EXT2_edge_insensitive_DEFAULT                  0x00000000

/***************************************************************************
 *MASK_EXT2 - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: MASK_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_MASK_EXT2_reserved0_MASK                          0xffffe000
#define BCHP_GIO_MASK_EXT2_reserved0_SHIFT                         13

/* GIO :: MASK_EXT2 :: irq_mask [12:00] */
#define BCHP_GIO_MASK_EXT2_irq_mask_MASK                           0x00001fff
#define BCHP_GIO_MASK_EXT2_irq_mask_SHIFT                          0
#define BCHP_GIO_MASK_EXT2_irq_mask_DEFAULT                        0x00000000

/***************************************************************************
 *LEVEL_EXT2 - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: LEVEL_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_LEVEL_EXT2_reserved0_MASK                         0xffffe000
#define BCHP_GIO_LEVEL_EXT2_reserved0_SHIFT                        13

/* GIO :: LEVEL_EXT2 :: level [12:00] */
#define BCHP_GIO_LEVEL_EXT2_level_MASK                             0x00001fff
#define BCHP_GIO_LEVEL_EXT2_level_SHIFT                            0
#define BCHP_GIO_LEVEL_EXT2_level_DEFAULT                          0x00000000

/***************************************************************************
 *STAT_EXT2 - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[108:096]
 ***************************************************************************/
/* GIO :: STAT_EXT2 :: reserved0 [31:13] */
#define BCHP_GIO_STAT_EXT2_reserved0_MASK                          0xffffe000
#define BCHP_GIO_STAT_EXT2_reserved0_SHIFT                         13

/* GIO :: STAT_EXT2 :: irq_status [12:00] */
#define BCHP_GIO_STAT_EXT2_irq_status_MASK                         0x00001fff
#define BCHP_GIO_STAT_EXT2_irq_status_SHIFT                        0
#define BCHP_GIO_STAT_EXT2_irq_status_DEFAULT                      0x00000000

/***************************************************************************
 *ODEN_EXT - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: ODEN_EXT :: reserved0 [31:04] */
#define BCHP_GIO_ODEN_EXT_reserved0_MASK                           0xfffffff0
#define BCHP_GIO_ODEN_EXT_reserved0_SHIFT                          4

/* GIO :: ODEN_EXT :: oden [03:00] */
#define BCHP_GIO_ODEN_EXT_oden_MASK                                0x0000000f
#define BCHP_GIO_ODEN_EXT_oden_SHIFT                               0
#define BCHP_GIO_ODEN_EXT_oden_DEFAULT                             0x00000000

/***************************************************************************
 *DATA_EXT - GENERAL PURPOSE I/O DATA FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: DATA_EXT :: reserved0 [31:04] */
#define BCHP_GIO_DATA_EXT_reserved0_MASK                           0xfffffff0
#define BCHP_GIO_DATA_EXT_reserved0_SHIFT                          4

/* GIO :: DATA_EXT :: data [03:00] */
#define BCHP_GIO_DATA_EXT_data_MASK                                0x0000000f
#define BCHP_GIO_DATA_EXT_data_SHIFT                               0
#define BCHP_GIO_DATA_EXT_data_DEFAULT                             0x00000000

/***************************************************************************
 *IODIR_EXT - GENERAL PURPOSE I/O DIRECTION FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: IODIR_EXT :: reserved0 [31:04] */
#define BCHP_GIO_IODIR_EXT_reserved0_MASK                          0xfffffff0
#define BCHP_GIO_IODIR_EXT_reserved0_SHIFT                         4

/* GIO :: IODIR_EXT :: iodir [03:00] */
#define BCHP_GIO_IODIR_EXT_iodir_MASK                              0x0000000f
#define BCHP_GIO_IODIR_EXT_iodir_SHIFT                             0
#define BCHP_GIO_IODIR_EXT_iodir_DEFAULT                           0x0000000f

/***************************************************************************
 *EC_EXT - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: EC_EXT :: reserved0 [31:04] */
#define BCHP_GIO_EC_EXT_reserved0_MASK                             0xfffffff0
#define BCHP_GIO_EC_EXT_reserved0_SHIFT                            4

/* GIO :: EC_EXT :: edge_config [03:00] */
#define BCHP_GIO_EC_EXT_edge_config_MASK                           0x0000000f
#define BCHP_GIO_EC_EXT_edge_config_SHIFT                          0
#define BCHP_GIO_EC_EXT_edge_config_DEFAULT                        0x00000000

/***************************************************************************
 *EI_EXT - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: EI_EXT :: reserved0 [31:04] */
#define BCHP_GIO_EI_EXT_reserved0_MASK                             0xfffffff0
#define BCHP_GIO_EI_EXT_reserved0_SHIFT                            4

/* GIO :: EI_EXT :: edge_insensitive [03:00] */
#define BCHP_GIO_EI_EXT_edge_insensitive_MASK                      0x0000000f
#define BCHP_GIO_EI_EXT_edge_insensitive_SHIFT                     0
#define BCHP_GIO_EI_EXT_edge_insensitive_DEFAULT                   0x00000000

/***************************************************************************
 *MASK_EXT - GENERAL PURPOSE I/O INTERRUPT MASK FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: MASK_EXT :: reserved0 [31:04] */
#define BCHP_GIO_MASK_EXT_reserved0_MASK                           0xfffffff0
#define BCHP_GIO_MASK_EXT_reserved0_SHIFT                          4

/* GIO :: MASK_EXT :: irq_mask [03:00] */
#define BCHP_GIO_MASK_EXT_irq_mask_MASK                            0x0000000f
#define BCHP_GIO_MASK_EXT_irq_mask_SHIFT                           0
#define BCHP_GIO_MASK_EXT_irq_mask_DEFAULT                         0x00000000

/***************************************************************************
 *LEVEL_EXT - GENERAL PURPOSE I/O INTERRUPT TYPE FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: LEVEL_EXT :: reserved0 [31:04] */
#define BCHP_GIO_LEVEL_EXT_reserved0_MASK                          0xfffffff0
#define BCHP_GIO_LEVEL_EXT_reserved0_SHIFT                         4

/* GIO :: LEVEL_EXT :: level [03:00] */
#define BCHP_GIO_LEVEL_EXT_level_MASK                              0x0000000f
#define BCHP_GIO_LEVEL_EXT_level_SHIFT                             0
#define BCHP_GIO_LEVEL_EXT_level_DEFAULT                           0x00000000

/***************************************************************************
 *STAT_EXT - GENERAL PURPOSE I/O INTERRUPT STATUS FOR SGPIO[003:000]
 ***************************************************************************/
/* GIO :: STAT_EXT :: reserved0 [31:04] */
#define BCHP_GIO_STAT_EXT_reserved0_MASK                           0xfffffff0
#define BCHP_GIO_STAT_EXT_reserved0_SHIFT                          4

/* GIO :: STAT_EXT :: irq_status [03:00] */
#define BCHP_GIO_STAT_EXT_irq_status_MASK                          0x0000000f
#define BCHP_GIO_STAT_EXT_irq_status_SHIFT                         0
#define BCHP_GIO_STAT_EXT_irq_status_DEFAULT                       0x00000000

#endif /* #ifndef BCHP_GIO_H__ */

/* End of File */
