/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Tue Oct 10 01:11:44 2017
 *                 Full Compile MD5 Checksum  ea353cbbaf7534b1acfabe87187756c5
 *                     (minus title and desc)
 *                 MD5 Checksum               bd09f6ea4577b9d8ea88a425effe4ef4
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_SYSTEMPORTLITE_1_RBUF_H__
#define BCHP_SYSTEMPORTLITE_1_RBUF_H__

/***************************************************************************
 *SYSTEMPORTLITE_1_RBUF
 ***************************************************************************/
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL  0x0001400400 /* [RW][32] RBUF Control Register */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD 0x0001400404 /* [RW][32] RBUF packet Ready Threshold Register */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS   0x0001400408 /* [RO][32] RBUF Status Register */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_OVERFLOW_PACKET_DISCARD_COUNT 0x000140040c /* [RW][32] RBUF Overflow Packet Discard Count Register */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_ERROR_PACKET_COUNT 0x0001400410 /* [RW][32] RBUF Error Packet Count Register */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS 0x0001400414 /* [RW][32] RBUF Backpressure Thresholds Register */

/***************************************************************************
 *RBUF_CONTROL - RBUF Control Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: reserved0 [31:26] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_reserved0_MASK     0xfc000000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_reserved0_SHIFT    26

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: rbuf_pause_en [25:25] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rbuf_pause_en_MASK 0x02000000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rbuf_pause_en_SHIFT 25
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rbuf_pause_en_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: acpi_en [24:24] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_acpi_en_MASK       0x01000000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_acpi_en_SHIFT      24
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_acpi_en_DEFAULT    0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: rsb_swap [23:22] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_swap_MASK      0x00c00000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_swap_SHIFT     22
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_swap_DEFAULT   0x00000003

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: ok_to_send_data_mode [21:21] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_mode_MASK 0x00200000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_mode_SHIFT 21
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_mode_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: crc_replace [20:20] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_crc_replace_MASK   0x00100000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_crc_replace_SHIFT  20
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_crc_replace_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: ok_to_send_data_period [19:12] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_period_MASK 0x000ff000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_period_SHIFT 12
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_ok_to_send_data_period_DEFAULT 0x0000000c

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: resume_threshold [11:04] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_resume_threshold_MASK 0x00000ff0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_resume_threshold_SHIFT 4
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_resume_threshold_DEFAULT 0x00000008

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: bad_packet_discard_en [03:03] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_bad_packet_discard_en_MASK 0x00000008
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_bad_packet_discard_en_SHIFT 3
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_bad_packet_discard_en_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: brcm_tag_strip [02:02] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_brcm_tag_strip_MASK 0x00000004
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_brcm_tag_strip_SHIFT 2
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_brcm_tag_strip_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: 4B_align [01:01] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_4B_align_MASK      0x00000002
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_4B_align_SHIFT     1
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_4B_align_DEFAULT   0x00000001

/* SYSTEMPORTLITE_1_RBUF :: RBUF_CONTROL :: rsb_en [00:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_en_MASK        0x00000001
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_en_SHIFT       0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_CONTROL_rsb_en_DEFAULT     0x00000001

/***************************************************************************
 *RBUF_PACKET_READY_THRESHOLD - RBUF packet Ready Threshold Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_PACKET_READY_THRESHOLD :: reserved0 [31:08] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD_reserved0_MASK 0xffffff00
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD_reserved0_SHIFT 8

/* SYSTEMPORTLITE_1_RBUF :: RBUF_PACKET_READY_THRESHOLD :: pkt_rdy_threshold [07:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD_pkt_rdy_threshold_MASK 0x000000ff
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD_pkt_rdy_threshold_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_PACKET_READY_THRESHOLD_pkt_rdy_threshold_DEFAULT 0x00000080

/***************************************************************************
 *RBUF_STATUS - RBUF Status Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_STATUS :: reserved0 [31:03] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_reserved0_MASK      0xfffffff8
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_reserved0_SHIFT     3

/* SYSTEMPORTLITE_1_RBUF :: RBUF_STATUS :: acpi_intr_active [02:02] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_acpi_intr_active_MASK 0x00000004
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_acpi_intr_active_SHIFT 2
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_acpi_intr_active_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_STATUS :: mpd_intr_active [01:01] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_mpd_intr_active_MASK 0x00000002
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_mpd_intr_active_SHIFT 1
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_mpd_intr_active_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RBUF :: RBUF_STATUS :: wol_mode [00:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_wol_mode_MASK       0x00000001
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_wol_mode_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_STATUS_wol_mode_DEFAULT    0x00000000

/***************************************************************************
 *RBUF_OVERFLOW_PACKET_DISCARD_COUNT - RBUF Overflow Packet Discard Count Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_OVERFLOW_PACKET_DISCARD_COUNT :: pkt_cnt [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_OVERFLOW_PACKET_DISCARD_COUNT_pkt_cnt_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_OVERFLOW_PACKET_DISCARD_COUNT_pkt_cnt_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_OVERFLOW_PACKET_DISCARD_COUNT_pkt_cnt_DEFAULT 0x00000000

/***************************************************************************
 *RBUF_ERROR_PACKET_COUNT - RBUF Error Packet Count Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_ERROR_PACKET_COUNT :: pkt_cnt [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_ERROR_PACKET_COUNT_pkt_cnt_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_ERROR_PACKET_COUNT_pkt_cnt_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_ERROR_PACKET_COUNT_pkt_cnt_DEFAULT 0x00000000

/***************************************************************************
 *RBUF_BACKPRESSURE_THRESHOLDS - RBUF Backpressure Thresholds Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RBUF :: RBUF_BACKPRESSURE_THRESHOLDS :: reserved0 [31:20] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_reserved0_MASK 0xfff00000
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_reserved0_SHIFT 20

/* SYSTEMPORTLITE_1_RBUF :: RBUF_BACKPRESSURE_THRESHOLDS :: xoff_threshold [19:10] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xoff_threshold_MASK 0x000ffc00
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xoff_threshold_SHIFT 10
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xoff_threshold_DEFAULT 0x00000180

/* SYSTEMPORTLITE_1_RBUF :: RBUF_BACKPRESSURE_THRESHOLDS :: xon_threshold [09:00] */
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xon_threshold_MASK 0x000003ff
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xon_threshold_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RBUF_RBUF_BACKPRESSURE_THRESHOLDS_xon_threshold_DEFAULT 0x00000080

#endif /* #ifndef BCHP_SYSTEMPORTLITE_1_RBUF_H__ */

/* End of File */
