# ***************************************************************************
# Broadcom Proprietary and Confidential. (c)2017 Broadcom. All rights reserved.
#
# THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
# AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
# EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
#
# ***************************************************************************

SSBM_S += \
	common/arm-cache.c \
	ssbm/ssbm-bfw-main.c \
	ssbm/ssbm-config.S \
	ssbm/ssbm-main.c \
	ssbm/ssbm-start.S \
	ssbm/ssbm-vectors.S \
