/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Wed Jul 20 03:09:21 2016
 *                 Full Compile MD5 Checksum  a2b82ec5680f6066255d5d5e4c190ff8
 *                     (minus title and desc)
 *                 MD5 Checksum               5e375d275648c6fb0816b8b6e9d8b76e
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1066
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_AVS_RO_REGISTERS_0_H__
#define BCHP_AVS_RO_REGISTERS_0_H__

/***************************************************************************
 *AVS_RO_REGISTERS_0 - AVS RO Registers 0 Core
 ***************************************************************************/
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS 0x204d2200 /* [RO] Indicate PVT monitor sel 000(Temperature Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS 0x204d2204 /* [RO] Indicate PVT monitor sel 001(0p85V_0 Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS 0x204d2208 /* [RO] Indicate PVT monitor sel 010(0p85V_1 Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS 0x204d220c /* [RO] Indicate PVT monitor sel 011(1V_0 Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS 0x204d2210 /* [RO] Indicate PVT monitor sel 100(1V_1 Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS 0x204d2214 /* [RO] Indicate PVT monitor sel 101(1p8V Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS 0x204d2218 /* [RO] Indicate PVT monitor sel 110(3p3V Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS 0x204d221c /* [RO] Indicate PVT monitor sel 111(Testmode Monitoring) measurements data, validity of data and measurement done status */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0 0x204d2220 /* [RO] Indicate central rosc 0 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1 0x204d2224 /* [RO] Indicate central rosc 1 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2 0x204d2228 /* [RO] Indicate central rosc 2 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3 0x204d222c /* [RO] Indicate central rosc 3 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4 0x204d2230 /* [RO] Indicate central rosc 4 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5 0x204d2234 /* [RO] Indicate central rosc 5 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6 0x204d2238 /* [RO] Indicate central rosc 6 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7 0x204d223c /* [RO] Indicate central rosc 7 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8 0x204d2240 /* [RO] Indicate central rosc 8 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9 0x204d2244 /* [RO] Indicate central rosc 9 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10 0x204d2248 /* [RO] Indicate central rosc 10 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11 0x204d224c /* [RO] Indicate central rosc 11 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12 0x204d2250 /* [RO] Indicate central rosc 12 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13 0x204d2254 /* [RO] Indicate central rosc 13 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14 0x204d2258 /* [RO] Indicate central rosc 14 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15 0x204d225c /* [RO] Indicate central rosc 15 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16 0x204d2260 /* [RO] Indicate central rosc 16 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17 0x204d2264 /* [RO] Indicate central rosc 17 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18 0x204d2268 /* [RO] Indicate central rosc 18 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19 0x204d226c /* [RO] Indicate central rosc 19 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20 0x204d2270 /* [RO] Indicate central rosc 20 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21 0x204d2274 /* [RO] Indicate central rosc 21 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22 0x204d2278 /* [RO] Indicate central rosc 22 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23 0x204d227c /* [RO] Indicate central rosc 23 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24 0x204d2280 /* [RO] Indicate central rosc 24 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25 0x204d2284 /* [RO] Indicate central rosc 25 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26 0x204d2288 /* [RO] Indicate central rosc 26 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27 0x204d228c /* [RO] Indicate central rosc 27 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28 0x204d2290 /* [RO] Indicate central rosc 28 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29 0x204d2294 /* [RO] Indicate central rosc 29 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30 0x204d2298 /* [RO] Indicate central rosc 30 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31 0x204d229c /* [RO] Indicate central rosc 31 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32 0x204d22a0 /* [RO] Indicate central rosc 32 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33 0x204d22a4 /* [RO] Indicate central rosc 33 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34 0x204d22a8 /* [RO] Indicate central rosc 34 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35 0x204d22ac /* [RO] Indicate central rosc 35 measurement data and validity of data */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS 0x204d22e0 /* [RO] Represent sampled data from the central rosc's all_idl_hi_oscs and all_idl_low_oscs signals for test/debug purpose */

/***************************************************************************
 *PVT_TEMPERATURE_MNTR_STATUS - Indicate PVT monitor sel 000(Temperature Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_TEMPERATURE_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_TEMPERATURE_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_done_MASK 0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_done_SHIFT 16
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_done_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_TEMPERATURE_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_TEMPERATURE_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_TEMPERATURE_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_data_MASK 0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_data_SHIFT 0
#define BCHP_AVS_RO_REGISTERS_0_PVT_TEMPERATURE_MNTR_STATUS_data_DEFAULT 0x00000000

/***************************************************************************
 *PVT_0P85V_0_MNTR_STATUS - Indicate PVT monitor sel 001(0p85V_0 Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_0P85V_0_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_0_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_done_MASK  0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_done_SHIFT 16
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_done_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_0_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_0_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_0_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_data_MASK  0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_data_SHIFT 0
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_0_MNTR_STATUS_data_DEFAULT 0x00000000

/***************************************************************************
 *PVT_0P85V_1_MNTR_STATUS - Indicate PVT monitor sel 010(0p85V_1 Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_0P85V_1_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_1_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_done_MASK  0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_done_SHIFT 16
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_done_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_1_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_1_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_0P85V_1_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_data_MASK  0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_data_SHIFT 0
#define BCHP_AVS_RO_REGISTERS_0_PVT_0P85V_1_MNTR_STATUS_data_DEFAULT 0x00000000

/***************************************************************************
 *PVT_1V_0_MNTR_STATUS - Indicate PVT monitor sel 011(1V_0 Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_1V_0_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_1V_0_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_done_MASK     0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_done_SHIFT    16
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_done_DEFAULT  0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1V_0_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_1V_0_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1V_0_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_data_MASK     0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_data_SHIFT    0
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_0_MNTR_STATUS_data_DEFAULT  0x00000000

/***************************************************************************
 *PVT_1V_1_MNTR_STATUS - Indicate PVT monitor sel 100(1V_1 Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_1V_1_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_1V_1_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_done_MASK     0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_done_SHIFT    16
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_done_DEFAULT  0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1V_1_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_1V_1_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1V_1_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_data_MASK     0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_data_SHIFT    0
#define BCHP_AVS_RO_REGISTERS_0_PVT_1V_1_MNTR_STATUS_data_DEFAULT  0x00000000

/***************************************************************************
 *PVT_1p8V_MNTR_STATUS - Indicate PVT monitor sel 101(1p8V Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_1p8V_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_1p8V_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_done_MASK     0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_done_SHIFT    16
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_done_DEFAULT  0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1p8V_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_1p8V_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_1p8V_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_data_MASK     0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_data_SHIFT    0
#define BCHP_AVS_RO_REGISTERS_0_PVT_1p8V_MNTR_STATUS_data_DEFAULT  0x00000000

/***************************************************************************
 *PVT_3p3V_MNTR_STATUS - Indicate PVT monitor sel 110(3p3V Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_3p3V_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_3p3V_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_done_MASK     0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_done_SHIFT    16
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_done_DEFAULT  0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_3p3V_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_3p3V_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_3p3V_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_data_MASK     0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_data_SHIFT    0
#define BCHP_AVS_RO_REGISTERS_0_PVT_3p3V_MNTR_STATUS_data_DEFAULT  0x00000000

/***************************************************************************
 *PVT_TESTMODE_MNTR_STATUS - Indicate PVT monitor sel 111(Testmode Monitoring) measurements data, validity of data and measurement done status
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: PVT_TESTMODE_MNTR_STATUS :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_reserved0_MASK 0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: PVT_TESTMODE_MNTR_STATUS :: done [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_done_MASK 0x00010000
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_done_SHIFT 16
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_done_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_TESTMODE_MNTR_STATUS :: reserved1 [15:11] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_reserved1_MASK 0x0000f800
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_reserved1_SHIFT 11

/* AVS_RO_REGISTERS_0 :: PVT_TESTMODE_MNTR_STATUS :: valid_data [10:10] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_valid_data_MASK 0x00000400
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_valid_data_SHIFT 10
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_valid_data_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: PVT_TESTMODE_MNTR_STATUS :: data [09:00] */
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_data_MASK 0x000003ff
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_data_SHIFT 0
#define BCHP_AVS_RO_REGISTERS_0_PVT_TESTMODE_MNTR_STATUS_data_DEFAULT 0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_0 - Indicate central rosc 0 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_0 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_0 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_0 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_0 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_0_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_1 - Indicate central rosc 1 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_1 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_1 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_1 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_1 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_1_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_2 - Indicate central rosc 2 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_2 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_2 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_2 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_2 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_2_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_3 - Indicate central rosc 3 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_3 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_3 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_3 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_3 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_3_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_4 - Indicate central rosc 4 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_4 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_4 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_4 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_4 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_4_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_5 - Indicate central rosc 5 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_5 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_5 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_5 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_5 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_5_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_6 - Indicate central rosc 6 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_6 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_6 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_6 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_6 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_6_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_7 - Indicate central rosc 7 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_7 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_7 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_7 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_7 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_7_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_8 - Indicate central rosc 8 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_8 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_8 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_8 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_8 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_8_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_9 - Indicate central rosc 9 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_9 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_reserved0_MASK   0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_reserved0_SHIFT  17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_9 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_valid_MASK       0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_valid_SHIFT      16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_valid_DEFAULT    0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_9 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_reserved1_MASK   0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_reserved1_SHIFT  15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_9 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_data_MASK        0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_data_SHIFT       0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_9_data_DEFAULT     0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_10 - Indicate central rosc 10 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_10 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_10 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_10 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_10 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_10_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_11 - Indicate central rosc 11 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_11 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_11 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_11 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_11 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_11_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_12 - Indicate central rosc 12 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_12 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_12 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_12 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_12 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_12_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_13 - Indicate central rosc 13 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_13 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_13 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_13 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_13 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_13_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_14 - Indicate central rosc 14 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_14 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_14 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_14 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_14 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_14_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_15 - Indicate central rosc 15 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_15 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_15 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_15 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_15 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_15_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_16 - Indicate central rosc 16 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_16 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_16 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_16 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_16 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_16_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_17 - Indicate central rosc 17 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_17 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_17 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_17 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_17 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_17_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_18 - Indicate central rosc 18 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_18 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_18 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_18 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_18 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_18_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_19 - Indicate central rosc 19 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_19 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_19 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_19 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_19 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_19_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_20 - Indicate central rosc 20 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_20 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_20 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_20 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_20 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_20_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_21 - Indicate central rosc 21 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_21 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_21 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_21 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_21 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_21_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_22 - Indicate central rosc 22 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_22 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_22 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_22 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_22 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_22_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_23 - Indicate central rosc 23 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_23 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_23 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_23 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_23 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_23_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_24 - Indicate central rosc 24 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_24 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_24 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_24 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_24 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_24_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_25 - Indicate central rosc 25 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_25 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_25 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_25 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_25 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_25_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_26 - Indicate central rosc 26 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_26 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_26 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_26 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_26 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_26_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_27 - Indicate central rosc 27 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_27 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_27 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_27 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_27 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_27_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_28 - Indicate central rosc 28 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_28 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_28 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_28 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_28 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_28_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_29 - Indicate central rosc 29 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_29 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_29 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_29 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_29 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_29_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_30 - Indicate central rosc 30 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_30 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_30 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_30 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_30 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_30_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_31 - Indicate central rosc 31 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_31 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_31 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_31 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_31 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_31_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_32 - Indicate central rosc 32 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_32 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_32 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_32 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_32 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_32_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_33 - Indicate central rosc 33 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_33 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_33 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_33 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_33 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_33_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_34 - Indicate central rosc 34 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_34 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_34 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_34 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_34 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_34_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_STATUS_35 - Indicate central rosc 35 measurement data and validity of data
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_35 :: reserved0 [31:17] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_reserved0_MASK  0xfffe0000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_reserved0_SHIFT 17

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_35 :: valid [16:16] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_valid_MASK      0x00010000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_valid_SHIFT     16
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_valid_DEFAULT   0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_35 :: reserved1 [15:15] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_reserved1_MASK  0x00008000
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_reserved1_SHIFT 15

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_STATUS_35 :: data [14:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_data_MASK       0x00007fff
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_data_SHIFT      0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_STATUS_35_data_DEFAULT    0x00000000

/***************************************************************************
 *CEN_ROSC_ALL_IDL_HI_LOW_ROSCS - Represent sampled data from the central rosc's all_idl_hi_oscs and all_idl_low_oscs signals for test/debug purpose
 ***************************************************************************/
/* AVS_RO_REGISTERS_0 :: CEN_ROSC_ALL_IDL_HI_LOW_ROSCS :: reserved0 [31:02] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_reserved0_MASK 0xfffffffc
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_reserved0_SHIFT 2

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_ALL_IDL_HI_LOW_ROSCS :: all_idl_hi_oscs [01:01] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_hi_oscs_MASK 0x00000002
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_hi_oscs_SHIFT 1
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_hi_oscs_DEFAULT 0x00000000

/* AVS_RO_REGISTERS_0 :: CEN_ROSC_ALL_IDL_HI_LOW_ROSCS :: all_idl_low_oscs [00:00] */
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_low_oscs_MASK 0x00000001
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_low_oscs_SHIFT 0
#define BCHP_AVS_RO_REGISTERS_0_CEN_ROSC_ALL_IDL_HI_LOW_ROSCS_all_idl_low_oscs_DEFAULT 0x00000000

#endif /* #ifndef BCHP_AVS_RO_REGISTERS_0_H__ */

/* End of File */
