/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Sat Aug  1 03:10:08 2015
 *                 Full Compile MD5 Checksum  9095e7c50184516c43cebfda484f35c6
 *                     (minus title and desc)
 *                 MD5 Checksum               12de0e44f1435087f5630ef2cde72753
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_UPG_SPI_AON_IRQ_H__
#define BCHP_UPG_SPI_AON_IRQ_H__

/***************************************************************************
 *UPG_SPI_AON_IRQ - SPI AON  Level 2 Interrupt Enable/Status
 ***************************************************************************/
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS          0x20417480 /* [RO] CPU interrupt Status Register */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS     0x20417484 /* [RO] CPU interrupt Mask Status Register */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET        0x20417488 /* [WO] CPU interrupt Mask Set Register */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR      0x2041748c /* [WO] CPU interrupt Mask Clear Register */
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS          0x20417490 /* [RO] PCI interrupt Status Register */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS     0x20417494 /* [RO] PCI interrupt Mask Status Register */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET        0x20417498 /* [WO] PCI interrupt Mask Set Register */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR      0x2041749c /* [WO] PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: CPU_STATUS :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_reserved0_MASK             0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_reserved0_SHIFT            2

/* UPG_SPI_AON_IRQ :: CPU_STATUS :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spare_00_MASK              0x00000002
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spare_00_SHIFT             1
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spare_00_DEFAULT           0x00000000

/* UPG_SPI_AON_IRQ :: CPU_STATUS :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spi_MASK                   0x00000001
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spi_SHIFT                  0
#define BCHP_UPG_SPI_AON_IRQ_CPU_STATUS_spi_DEFAULT                0x00000000

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: CPU_MASK_STATUS :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_reserved0_MASK        0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_reserved0_SHIFT       2

/* UPG_SPI_AON_IRQ :: CPU_MASK_STATUS :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spare_00_MASK         0x00000002
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spare_00_SHIFT        1
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spare_00_DEFAULT      0x00000001

/* UPG_SPI_AON_IRQ :: CPU_MASK_STATUS :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spi_MASK              0x00000001
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spi_SHIFT             0
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_STATUS_spi_DEFAULT           0x00000001

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: CPU_MASK_SET :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_reserved0_MASK           0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_reserved0_SHIFT          2

/* UPG_SPI_AON_IRQ :: CPU_MASK_SET :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spare_00_MASK            0x00000002
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spare_00_SHIFT           1
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spare_00_DEFAULT         0x00000001

/* UPG_SPI_AON_IRQ :: CPU_MASK_SET :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spi_MASK                 0x00000001
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spi_SHIFT                0
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_SET_spi_DEFAULT              0x00000001

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: CPU_MASK_CLEAR :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_reserved0_MASK         0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_reserved0_SHIFT        2

/* UPG_SPI_AON_IRQ :: CPU_MASK_CLEAR :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spare_00_MASK          0x00000002
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spare_00_SHIFT         1
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spare_00_DEFAULT       0x00000001

/* UPG_SPI_AON_IRQ :: CPU_MASK_CLEAR :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spi_MASK               0x00000001
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spi_SHIFT              0
#define BCHP_UPG_SPI_AON_IRQ_CPU_MASK_CLEAR_spi_DEFAULT            0x00000001

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: PCI_STATUS :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_reserved0_MASK             0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_reserved0_SHIFT            2

/* UPG_SPI_AON_IRQ :: PCI_STATUS :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spare_00_MASK              0x00000002
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spare_00_SHIFT             1
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spare_00_DEFAULT           0x00000000

/* UPG_SPI_AON_IRQ :: PCI_STATUS :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spi_MASK                   0x00000001
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spi_SHIFT                  0
#define BCHP_UPG_SPI_AON_IRQ_PCI_STATUS_spi_DEFAULT                0x00000000

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: PCI_MASK_STATUS :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_reserved0_MASK        0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_reserved0_SHIFT       2

/* UPG_SPI_AON_IRQ :: PCI_MASK_STATUS :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spare_00_MASK         0x00000002
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spare_00_SHIFT        1
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spare_00_DEFAULT      0x00000001

/* UPG_SPI_AON_IRQ :: PCI_MASK_STATUS :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spi_MASK              0x00000001
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spi_SHIFT             0
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_STATUS_spi_DEFAULT           0x00000001

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: PCI_MASK_SET :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_reserved0_MASK           0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_reserved0_SHIFT          2

/* UPG_SPI_AON_IRQ :: PCI_MASK_SET :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spare_00_MASK            0x00000002
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spare_00_SHIFT           1
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spare_00_DEFAULT         0x00000001

/* UPG_SPI_AON_IRQ :: PCI_MASK_SET :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spi_MASK                 0x00000001
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spi_SHIFT                0
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_SET_spi_DEFAULT              0x00000001

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_SPI_AON_IRQ :: PCI_MASK_CLEAR :: reserved0 [31:02] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_reserved0_MASK         0xfffffffc
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_reserved0_SHIFT        2

/* UPG_SPI_AON_IRQ :: PCI_MASK_CLEAR :: spare_00 [01:01] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spare_00_MASK          0x00000002
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spare_00_SHIFT         1
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spare_00_DEFAULT       0x00000001

/* UPG_SPI_AON_IRQ :: PCI_MASK_CLEAR :: spi [00:00] */
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spi_MASK               0x00000001
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spi_SHIFT              0
#define BCHP_UPG_SPI_AON_IRQ_PCI_MASK_CLEAR_spi_DEFAULT            0x00000001

#endif /* #ifndef BCHP_UPG_SPI_AON_IRQ_H__ */

/* End of File */
