/****************************************************************************
 *     Copyright (c) 1999-2014, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *
 * THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 * AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 * EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 *
 * Date:           Generated on               Tue Jul 28 12:12:44 2015
 *                 Full Compile MD5 Checksum  dc72381f6e4c53f9fc2cd85dd2824399
 *                     (minus title and desc)
 *                 MD5 Checksum               1f44ec4386983e0b1b5b0c9bb743b1a0
 *
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     15517
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *
 *
 ***************************************************************************/

#ifndef BCHP_UPG_BSC_AON_IRQ_H__
#define BCHP_UPG_BSC_AON_IRQ_H__

/***************************************************************************
 *UPG_BSC_AON_IRQ - UPG BSC AON Level 2 Interrupt Enable/Status
 ***************************************************************************/
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS          0x20417440 /* [RO] CPU interrupt Status Register */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS     0x20417444 /* [RO] CPU interrupt Mask Status Register */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET        0x20417448 /* [WO] CPU interrupt Mask Set Register */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR      0x2041744c /* [WO] CPU interrupt Mask Clear Register */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS          0x20417450 /* [RO] PCI interrupt Status Register */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS     0x20417454 /* [RO] PCI interrupt Mask Status Register */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET        0x20417458 /* [WO] PCI interrupt Mask Set Register */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR      0x2041745c /* [WO] PCI interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: CPU_STATUS :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_reserved0_MASK             0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_reserved0_SHIFT            4

/* UPG_BSC_AON_IRQ :: CPU_STATUS :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_spare_00_MASK              0x00000008
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_spare_00_SHIFT             3
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_spare_00_DEFAULT           0x00000000

/* UPG_BSC_AON_IRQ :: CPU_STATUS :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicd_MASK                  0x00000004
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicd_SHIFT                 2
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicd_DEFAULT               0x00000000

/* UPG_BSC_AON_IRQ :: CPU_STATUS :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicc_MASK                  0x00000002
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicc_SHIFT                 1
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicc_DEFAULT               0x00000000

/* UPG_BSC_AON_IRQ :: CPU_STATUS :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicb_MASK                  0x00000001
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicb_SHIFT                 0
#define BCHP_UPG_BSC_AON_IRQ_CPU_STATUS_iicb_DEFAULT               0x00000000

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: CPU_MASK_STATUS :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_reserved0_MASK        0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_reserved0_SHIFT       4

/* UPG_BSC_AON_IRQ :: CPU_MASK_STATUS :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_spare_00_MASK         0x00000008
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_spare_00_SHIFT        3
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_spare_00_DEFAULT      0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_STATUS :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicd_MASK             0x00000004
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicd_SHIFT            2
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicd_DEFAULT          0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_STATUS :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicc_MASK             0x00000002
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicc_SHIFT            1
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicc_DEFAULT          0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_STATUS :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicb_MASK             0x00000001
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicb_SHIFT            0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_STATUS_iicb_DEFAULT          0x00000001

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: CPU_MASK_SET :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_reserved0_MASK           0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_reserved0_SHIFT          4

/* UPG_BSC_AON_IRQ :: CPU_MASK_SET :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_spare_00_MASK            0x00000008
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_spare_00_SHIFT           3
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_spare_00_DEFAULT         0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_SET :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicd_MASK                0x00000004
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicd_SHIFT               2
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicd_DEFAULT             0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_SET :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicc_MASK                0x00000002
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicc_SHIFT               1
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicc_DEFAULT             0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_SET :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicb_MASK                0x00000001
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicb_SHIFT               0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_SET_iicb_DEFAULT             0x00000001

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: CPU_MASK_CLEAR :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_reserved0_MASK         0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_reserved0_SHIFT        4

/* UPG_BSC_AON_IRQ :: CPU_MASK_CLEAR :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_spare_00_MASK          0x00000008
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_spare_00_SHIFT         3
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_spare_00_DEFAULT       0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_CLEAR :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicd_MASK              0x00000004
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicd_SHIFT             2
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicd_DEFAULT           0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_CLEAR :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicc_MASK              0x00000002
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicc_SHIFT             1
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicc_DEFAULT           0x00000001

/* UPG_BSC_AON_IRQ :: CPU_MASK_CLEAR :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicb_MASK              0x00000001
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicb_SHIFT             0
#define BCHP_UPG_BSC_AON_IRQ_CPU_MASK_CLEAR_iicb_DEFAULT           0x00000001

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: PCI_STATUS :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_reserved0_MASK             0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_reserved0_SHIFT            4

/* UPG_BSC_AON_IRQ :: PCI_STATUS :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_spare_00_MASK              0x00000008
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_spare_00_SHIFT             3
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_spare_00_DEFAULT           0x00000000

/* UPG_BSC_AON_IRQ :: PCI_STATUS :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicd_MASK                  0x00000004
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicd_SHIFT                 2
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicd_DEFAULT               0x00000000

/* UPG_BSC_AON_IRQ :: PCI_STATUS :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicc_MASK                  0x00000002
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicc_SHIFT                 1
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicc_DEFAULT               0x00000000

/* UPG_BSC_AON_IRQ :: PCI_STATUS :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicb_MASK                  0x00000001
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicb_SHIFT                 0
#define BCHP_UPG_BSC_AON_IRQ_PCI_STATUS_iicb_DEFAULT               0x00000000

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: PCI_MASK_STATUS :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_reserved0_MASK        0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_reserved0_SHIFT       4

/* UPG_BSC_AON_IRQ :: PCI_MASK_STATUS :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_spare_00_MASK         0x00000008
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_spare_00_SHIFT        3
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_spare_00_DEFAULT      0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_STATUS :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicd_MASK             0x00000004
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicd_SHIFT            2
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicd_DEFAULT          0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_STATUS :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicc_MASK             0x00000002
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicc_SHIFT            1
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicc_DEFAULT          0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_STATUS :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicb_MASK             0x00000001
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicb_SHIFT            0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_STATUS_iicb_DEFAULT          0x00000001

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: PCI_MASK_SET :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_reserved0_MASK           0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_reserved0_SHIFT          4

/* UPG_BSC_AON_IRQ :: PCI_MASK_SET :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_spare_00_MASK            0x00000008
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_spare_00_SHIFT           3
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_spare_00_DEFAULT         0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_SET :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicd_MASK                0x00000004
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicd_SHIFT               2
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicd_DEFAULT             0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_SET :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicc_MASK                0x00000002
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicc_SHIFT               1
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicc_DEFAULT             0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_SET :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicb_MASK                0x00000001
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicb_SHIFT               0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_SET_iicb_DEFAULT             0x00000001

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* UPG_BSC_AON_IRQ :: PCI_MASK_CLEAR :: reserved0 [31:04] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_reserved0_MASK         0xfffffff0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_reserved0_SHIFT        4

/* UPG_BSC_AON_IRQ :: PCI_MASK_CLEAR :: spare_00 [03:03] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_spare_00_MASK          0x00000008
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_spare_00_SHIFT         3
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_spare_00_DEFAULT       0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_CLEAR :: iicd [02:02] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicd_MASK              0x00000004
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicd_SHIFT             2
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicd_DEFAULT           0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_CLEAR :: iicc [01:01] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicc_MASK              0x00000002
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicc_SHIFT             1
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicc_DEFAULT           0x00000001

/* UPG_BSC_AON_IRQ :: PCI_MASK_CLEAR :: iicb [00:00] */
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicb_MASK              0x00000001
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicb_SHIFT             0
#define BCHP_UPG_BSC_AON_IRQ_PCI_MASK_CLEAR_iicb_DEFAULT           0x00000001

#endif /* #ifndef BCHP_UPG_BSC_AON_IRQ_H__ */

/* End of File */
