/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Oct 20 06:10:26 2016
 *                 Full Compile MD5 Checksum  a4cf01343914cbe977ff5dbbfecedfc2
 *                     (minus title and desc)
 *                 MD5 Checksum               79b3267dbc97ab78b1475c8950650765
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_DDR34_PHY_PHYBIST_0_H__
#define BCHP_DDR34_PHY_PHYBIST_0_H__

/***************************************************************************
 *DDR34_PHY_PHYBIST_0 - DDR34 self-test registers
 ***************************************************************************/
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL         0x21122000 /* [CFG][32] PhyBist Control Register */
#define BCHP_DDR34_PHY_PHYBIST_0_SEED            0x21122004 /* [CFG][32] PhyBist Seed Register */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK         0x21122008 /* [CFG][32] PhyBist Command/Address Bus Mask */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0        0x2112200c /* [CFG][32] PhyBist Data Bus Mask for Byte Lane #0 */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1        0x21122010 /* [CFG][32] PhyBist Data Bus Mask for Byte Lane #1 */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2        0x21122014 /* [CFG][32] PhyBist Data Bus Mask for Byte Lane #2 */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3        0x21122018 /* [CFG][32] PhyBist Data Bus Mask for Byte Lane #3 */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS          0x2112201c /* [RO][32] PhyBist General Status Register */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS      0x21122020 /* [RO][32] PhyBist Per-Bit Control Pad Status Register */
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS      0x21122024 /* [RO][32] PhyBist Byte Lane #0 Status Register */
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS      0x21122028 /* [RO][32] PhyBist Byte Lane #1 Status Register */
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS      0x2112202c /* [RO][32] PhyBist Byte Lane #2 Status Register */
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS      0x21122030 /* [RO][32] PhyBist Byte Lane #3 Status Register */

/***************************************************************************
 *CONTROL - PhyBist Control Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: CONTROL :: reserved0 [31:31] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_reserved0_MASK            0x80000000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_reserved0_SHIFT           31

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: PATTERN_SEL [30:29] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_PATTERN_SEL_MASK          0x60000000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_PATTERN_SEL_SHIFT         29
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_PATTERN_SEL_DEFAULT       0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_DQ_ERROR_SEL [28:25] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DQ_ERROR_SEL_MASK   0x1e000000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DQ_ERROR_SEL_SHIFT  25
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DQ_ERROR_SEL_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_BL_ERROR_SEL [24:21] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_BL_ERROR_SEL_MASK   0x01e00000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_BL_ERROR_SEL_SHIFT  21
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_BL_ERROR_SEL_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_COMMON_DRIVER_SEL [20:19] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_SEL_MASK 0x00180000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_SEL_SHIFT 19
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_SEL_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_COMMON_DRIVER [18:18] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_MASK  0x00040000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_SHIFT 18
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_COMMON_DRIVER_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_CTL_ERROR_SEL [17:13] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_SEL_MASK  0x0003e000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_SEL_SHIFT 13
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_SEL_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_DAT_ERROR [12:12] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DAT_ERROR_MASK      0x00001000
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DAT_ERROR_SHIFT     12
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_DAT_ERROR_DEFAULT   0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: FORCE_CTL_ERROR [11:11] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_MASK      0x00000800
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_SHIFT     11
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_FORCE_CTL_ERROR_DEFAULT   0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: DATA_ONLY [10:10] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_DATA_ONLY_MASK            0x00000400
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_DATA_ONLY_SHIFT           10
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_DATA_ONLY_DEFAULT         0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: CA_ONLY [09:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CA_ONLY_MASK              0x00000200
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CA_ONLY_SHIFT             9
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CA_ONLY_DEFAULT           0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: SSO [08:07] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_SSO_MASK                  0x00000180
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_SSO_SHIFT                 7
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_SSO_DEFAULT               0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: CONTINUOUS [06:06] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CONTINUOUS_MASK           0x00000040
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CONTINUOUS_SHIFT          6
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_CONTINUOUS_DEFAULT        0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: LENGTH [05:04] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_LENGTH_MASK               0x00000030
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_LENGTH_SHIFT              4
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_LENGTH_DEFAULT            0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: MODE [03:01] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_MODE_MASK                 0x0000000e
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_MODE_SHIFT                1
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_MODE_DEFAULT              0x00000000

/* DDR34_PHY_PHYBIST_0 :: CONTROL :: ENABLE [00:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_ENABLE_MASK               0x00000001
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_ENABLE_SHIFT              0
#define BCHP_DDR34_PHY_PHYBIST_0_CONTROL_ENABLE_DEFAULT            0x00000000

/***************************************************************************
 *SEED - PhyBist Seed Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: SEED :: SEED [31:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_SEED_SEED_MASK                    0xffffffff
#define BCHP_DDR34_PHY_PHYBIST_0_SEED_SEED_SHIFT                   0
#define BCHP_DDR34_PHY_PHYBIST_0_SEED_SEED_DEFAULT                 0xba5eba11

/***************************************************************************
 *CA_MASK - PhyBist Command/Address Bus Mask
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: reserved0 [31:19] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_reserved0_MASK            0xfff80000
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_reserved0_SHIFT           19

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CKE_B [18:18] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_B_MASK                0x00040000
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_B_SHIFT               18
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_B_DEFAULT             0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CS_B [17:16] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_B_MASK                 0x00030000
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_B_SHIFT                16
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_B_DEFAULT              0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CA_B [15:10] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_B_MASK                 0x0000fc00
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_B_SHIFT                10
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_B_DEFAULT              0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: RST [09:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_RST_MASK                  0x00000200
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_RST_SHIFT                 9
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_RST_DEFAULT               0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CKE_A [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_A_MASK                0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_A_SHIFT               8
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CKE_A_DEFAULT             0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CS_A [07:06] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_A_MASK                 0x000000c0
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_A_SHIFT                6
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CS_A_DEFAULT              0x00000000

/* DDR34_PHY_PHYBIST_0 :: CA_MASK :: CA_A [05:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_A_MASK                 0x0000003f
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_A_SHIFT                0
#define BCHP_DDR34_PHY_PHYBIST_0_CA_MASK_CA_A_DEFAULT              0x00000000

/***************************************************************************
 *DQ_MASK0 - PhyBist Data Bus Mask for Byte Lane #0
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: DQ_MASK0 :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_reserved0_MASK           0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_reserved0_SHIFT          9

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK0 :: DMI_MASK [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DMI_MASK_MASK            0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DMI_MASK_SHIFT           8
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DMI_MASK_DEFAULT         0x00000000

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK0 :: DQ_MASK [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DQ_MASK_MASK             0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DQ_MASK_SHIFT            0
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK0_DQ_MASK_DEFAULT          0x00000000

/***************************************************************************
 *DQ_MASK1 - PhyBist Data Bus Mask for Byte Lane #1
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: DQ_MASK1 :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_reserved0_MASK           0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_reserved0_SHIFT          9

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK1 :: DMI_MASK [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DMI_MASK_MASK            0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DMI_MASK_SHIFT           8
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DMI_MASK_DEFAULT         0x00000000

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK1 :: DQ_MASK [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DQ_MASK_MASK             0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DQ_MASK_SHIFT            0
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK1_DQ_MASK_DEFAULT          0x00000000

/***************************************************************************
 *DQ_MASK2 - PhyBist Data Bus Mask for Byte Lane #2
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: DQ_MASK2 :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_reserved0_MASK           0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_reserved0_SHIFT          9

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK2 :: DMI_MASK [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DMI_MASK_MASK            0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DMI_MASK_SHIFT           8
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DMI_MASK_DEFAULT         0x00000000

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK2 :: DQ_MASK [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DQ_MASK_MASK             0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DQ_MASK_SHIFT            0
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK2_DQ_MASK_DEFAULT          0x00000000

/***************************************************************************
 *DQ_MASK3 - PhyBist Data Bus Mask for Byte Lane #3
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: DQ_MASK3 :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_reserved0_MASK           0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_reserved0_SHIFT          9

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK3 :: DMI_MASK [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DMI_MASK_MASK            0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DMI_MASK_SHIFT           8
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DMI_MASK_DEFAULT         0x00000000

/* DDR34_PHY_PHYBIST_0 :: DQ_MASK3 :: DQ_MASK [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DQ_MASK_MASK             0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DQ_MASK_SHIFT            0
#define BCHP_DDR34_PHY_PHYBIST_0_DQ_MASK3_DQ_MASK_DEFAULT          0x00000000

/***************************************************************************
 *STATUS - PhyBist General Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: STATUS :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_reserved0_MASK             0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_reserved0_SHIFT            9

/* DDR34_PHY_PHYBIST_0 :: STATUS :: BUSY [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_BUSY_MASK                  0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_BUSY_SHIFT                 8

/* DDR34_PHY_PHYBIST_0 :: STATUS :: COM_PASS [07:07] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_COM_PASS_MASK              0x00000080
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_COM_PASS_SHIFT             7

/* DDR34_PHY_PHYBIST_0 :: STATUS :: DAT_PASS [06:06] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_DAT_PASS_MASK              0x00000040
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_DAT_PASS_SHIFT             6

/* DDR34_PHY_PHYBIST_0 :: STATUS :: CTL_B_PASS [05:05] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_B_PASS_MASK            0x00000020
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_B_PASS_SHIFT           5

/* DDR34_PHY_PHYBIST_0 :: STATUS :: CTL_A_PASS [04:04] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_A_PASS_MASK            0x00000010
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_A_PASS_SHIFT           4

/* DDR34_PHY_PHYBIST_0 :: STATUS :: COM_DONE [03:03] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_COM_DONE_MASK              0x00000008
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_COM_DONE_SHIFT             3

/* DDR34_PHY_PHYBIST_0 :: STATUS :: DAT_DONE [02:02] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_DAT_DONE_MASK              0x00000004
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_DAT_DONE_SHIFT             2

/* DDR34_PHY_PHYBIST_0 :: STATUS :: CTL_B_DONE [01:01] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_B_DONE_MASK            0x00000002
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_B_DONE_SHIFT           1

/* DDR34_PHY_PHYBIST_0 :: STATUS :: CTL_A_DONE [00:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_A_DONE_MASK            0x00000001
#define BCHP_DDR34_PHY_PHYBIST_0_STATUS_CTL_A_DONE_SHIFT           0

/***************************************************************************
 *CTL_STATUS - PhyBist Per-Bit Control Pad Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: reserved0 [31:23] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_reserved0_MASK         0xff800000
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_reserved0_SHIFT        23

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: COMMON_DRIVER_AT_FAILURE [22:20] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_DRIVER_AT_FAILURE_MASK 0x00700000
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_DRIVER_AT_FAILURE_SHIFT 20
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_DRIVER_AT_FAILURE_DEFAULT 0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: reserved1 [19:19] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_reserved1_MASK         0x00080000
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_reserved1_SHIFT        19

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: COMMON_CKE_B [18:18] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_B_MASK      0x00040000
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_B_SHIFT     18
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_B_DEFAULT   0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: CS_B [17:16] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_B_MASK              0x00030000
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_B_SHIFT             16
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_B_DEFAULT           0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: CA_B [15:10] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_B_MASK              0x0000fc00
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_B_SHIFT             10
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_B_DEFAULT           0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: COMMON_RST [09:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_RST_MASK        0x00000200
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_RST_SHIFT       9
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_RST_DEFAULT     0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: COMMON_CKE_A [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_A_MASK      0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_A_SHIFT     8
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_COMMON_CKE_A_DEFAULT   0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: CS_A [07:06] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_A_MASK              0x000000c0
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_A_SHIFT             6
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CS_A_DEFAULT           0x00000000

/* DDR34_PHY_PHYBIST_0 :: CTL_STATUS :: CA_A [05:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_A_MASK              0x0000003f
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_A_SHIFT             0
#define BCHP_DDR34_PHY_PHYBIST_0_CTL_STATUS_CA_A_DEFAULT           0x00000000

/***************************************************************************
 *BL0_STATUS - PhyBist Byte Lane #0 Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: BL0_STATUS :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_reserved0_MASK         0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_reserved0_SHIFT        9

/* DDR34_PHY_PHYBIST_0 :: BL0_STATUS :: DMI [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_DMI_MASK               0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_DMI_SHIFT              8

/* DDR34_PHY_PHYBIST_0 :: BL0_STATUS :: DQ [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_DQ_MASK                0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_BL0_STATUS_DQ_SHIFT               0

/***************************************************************************
 *BL1_STATUS - PhyBist Byte Lane #1 Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: BL1_STATUS :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_reserved0_MASK         0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_reserved0_SHIFT        9

/* DDR34_PHY_PHYBIST_0 :: BL1_STATUS :: DMI [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_DMI_MASK               0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_DMI_SHIFT              8

/* DDR34_PHY_PHYBIST_0 :: BL1_STATUS :: DQ [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_DQ_MASK                0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_BL1_STATUS_DQ_SHIFT               0

/***************************************************************************
 *BL2_STATUS - PhyBist Byte Lane #2 Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: BL2_STATUS :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_reserved0_MASK         0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_reserved0_SHIFT        9

/* DDR34_PHY_PHYBIST_0 :: BL2_STATUS :: DMI [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_DMI_MASK               0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_DMI_SHIFT              8

/* DDR34_PHY_PHYBIST_0 :: BL2_STATUS :: DQ [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_DQ_MASK                0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_BL2_STATUS_DQ_SHIFT               0

/***************************************************************************
 *BL3_STATUS - PhyBist Byte Lane #3 Status Register
 ***************************************************************************/
/* DDR34_PHY_PHYBIST_0 :: BL3_STATUS :: reserved0 [31:09] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_reserved0_MASK         0xfffffe00
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_reserved0_SHIFT        9

/* DDR34_PHY_PHYBIST_0 :: BL3_STATUS :: DMI [08:08] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_DMI_MASK               0x00000100
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_DMI_SHIFT              8

/* DDR34_PHY_PHYBIST_0 :: BL3_STATUS :: DQ [07:00] */
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_DQ_MASK                0x000000ff
#define BCHP_DDR34_PHY_PHYBIST_0_BL3_STATUS_DQ_SHIFT               0

#endif /* #ifndef BCHP_DDR34_PHY_PHYBIST_0_H__ */

/* End of File */
