/***************************************************************************
 *     Copyright (c) 2014-2015, Broadcom Corporation
 *     All Rights Reserved
 *     Confidential Property of Broadcom Corporation
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 ***************************************************************************/

#ifdef POWER_PROFILE_BOOST
#ifndef CONFIG_BCM7250
#error "BOOST profile is allowed only for 7250"
#endif
#endif

#include "fsbl-clock.h"
#include "chipid.h"

#include <bchp_common.h>
#include <bchp_clkgen.h>

#ifdef BCHP_XPT_PMU_REG_START
#include <bchp_xpt_pmu.h>
#endif

#if defined(CONFIG_BCM7250B0)
#include <bchp_aon_ctrl.h>
#endif

#if defined(CONFIG_BCM7364)
#include <bchp_avs_top_ctrl.h>
#include <bchp_dvp_hr.h>
#include <bchp_hdmi_rx_fe_0.h>
#endif

#if defined(CONFIG_BCM7439B0)
#include <bchp_sun_top_ctrl.h>
#endif

static int current_cpu_mhz = 1503; /* everybody defaults to 1.5GHz */

#ifdef BCHP_XPT_PMU_REG_START
static void adjust_xpt_clocks(void)
{
	/* disable some of submodules to reduce power consumption */
	BDEV_WR(BCHP_XPT_PMU_CLK_CTRL,
		(1 << BCHP_XPT_PMU_CLK_CTRL_TSIO_DISABLE_SHIFT) |
		(0 << BCHP_XPT_PMU_CLK_CTRL_MEMDMA_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_FULL_PID_PARSER_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_WAKEUP_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_RMX1_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_RMX0_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_MPOD_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_XPT_IO_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_PB_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_PSUB_DISABLE_SHIFT) |
		(0 << BCHP_XPT_PMU_CLK_CTRL_BUS_IF_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_PCROFFSET_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_RAVE_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_MSG_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_DPCR_DISABLE_SHIFT) |
		(0 << BCHP_XPT_PMU_CLK_CTRL_XMEMIF_216_DISABLE_SHIFT) |
		(0 << BCHP_XPT_PMU_CLK_CTRL_XMEMIF_108_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_XCBUFF_DISABLE_SHIFT) |
		(1 << BCHP_XPT_PMU_CLK_CTRL_RSBUFF_DISABLE_SHIFT) |
		(0 << BCHP_XPT_PMU_CLK_CTRL_FE_DISABLE_SHIFT));
}
#endif

#if defined(CONFIG_BCM3390)
static void bcm3390_clock_init(void)
{
	/* Select 54MHz clock for EGPHY, and run its internal PLL in
	 * fractional mode
	 */
	BDEV_WR_F(CLKGEN_EGPHY28_4PORT_33V_90O_FC_INST_CLOCK_SELECT,
		EGPHY_REFCLK_CLOCK_SELECT, 2);
	BDEV_WR_F(CLKGEN_EGPHY28_4PORT_33V_90O_FC_INST_CLOCK_SELECT,
		EGPHY_25_54_CLOCK_SELECT, 1);
}
#endif

#if defined(CONFIG_BCM7145B0)
static void bcm7145b0_clock_init(void)
{
	/* Change PLLLC to have DCO=6480MHz,
	CH1=60MHz, CH0 & CH2 are don't care */
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_DIV, PDIV, 2);
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_DIV, NDIV_INT, 120);
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1, MDIV_CH1, 54);

	/* reset LC PLL */
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_RESET, RESETD, 1);
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_RESET, RESETA, 1);

	BDEV_WR_F(CLKGEN_PLL_LC_PLL_RESET, RESETD, 0);
	BDEV_WR_F(CLKGEN_PLL_LC_PLL_RESET, RESETA, 0);

	udelay(30);

	/* GPHY to use XTAL 54MHz CMOS, and run internal
	PLL in fractional mode */
	BDEV_WR_F(CLKGEN_EGPHY28_4PORT_33V_90O_FC_INST_CLOCK_SELECT,
		EGPHY_REFCLK_CLOCK_SELECT, 2);
	BDEV_WR_F(CLKGEN_EGPHY28_4PORT_33V_90O_FC_INST_CLOCK_SELECT,
		EGPHY_25_54_CLOCK_SELECT, 1);
}
#endif /* #if defined(CONFIG_BCM7145B0) */

#if defined(CONFIG_BCM7250B0)
/* Dongle Under-clock profile (Profile = 2)
 * CPU = 873 MHz
 * Raaga DSP = 232 MHz
 * HVD CPU = 291 MHz
 * HVD core = 232 MHz
 * 2D M2MC = 232 MHz
 * 3D VC5 = 232 MHz
 * SCB = 216 MHz
 * ------
 * CPU_PLL VCO = 3492 MHz (P = 3 / N = 194)
 */
static void bcm7250b0_power_profile_dongle(void)
{
	current_cpu_mhz = 873;

	/* CPU_PLL VCO = 3492 MHz (P = 3 / N = 194)
	 * BCHP_PLL_CPU_PLL_DIV
	 *      .PDIV = 3
	 *      .NDIV_INT = 194
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_PDIV_SHIFT) |
		(194 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_NDIV_INT_SHIFT));

	/* CPU Clock = 873MHz (3492 / 4)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 4
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(4 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));
	/* Raaga Clock = 232.8 (3492 / 15)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_1
	 *      .MDIV_CH1 = 15
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_SHIFT) |
		(15 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_MDIV_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_SHIFT));
	/* HVD CPU Clock = 291 (3492 / 12)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 12
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(12 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));
	/* HVD Core Clock = 232.8 (3492 / 15)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_3
	 *      .MDIV_CH3 = 15
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_SHIFT) |
		(15 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_MDIV_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_SHIFT));
	/* M2MC Clock = 232.8 (3492 / 15)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_4
	 *      .MDIV_CH4 = 15
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_SHIFT) |
		(15 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_MDIV_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_SHIFT));
	/* 3D Clock = 232.8 (3492 / 15)
	 * BCHP_PLL_CPU_PLL_CHANNEL_CTRL_CH_5
	 *      .MDIV_CH5 = 15
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_POST_DIVIDER_HOLD_CH5_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_POST_DIVIDER_HOLD_CH5_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_PHASE_OFFSET_CH5_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_PHASE_OFFSET_CH5_SHIFT) |
		(15 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_MDIV_CH5_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_CLOCK_DIS_CH5_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_5_CLOCK_DIS_CH5_SHIFT));

	/* SCB PLL = 3888 MHz (P = 2 / N = 144, default)
	 * SCB Clock = 216 (3888 / 18)
	 * BCHP_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 18
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(18 << BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));

	/* Select the Alternate Clocks */
	BDEV_WR(BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT,
		(1 << BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT_RAAGA0_DSP_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT,
		(1 << BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT_V3D_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT,
		(1 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_SID_CLOCK_SELECT_SHIFT) |
		(1 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CPU_CLOCK_SELECT_SHIFT) |
		(1 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CORE_CLOCK_SELECT_SHIFT));
	/* Alt clock is the default for GFX_M2MC0 after reset */

	/* Powerdown AVX_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_PWRON,
		0 << BCHP_CLKGEN_PLL_AVX_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON,
		0 << BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);

	/* Powerdown RAAGA_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON,
		0 << BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON,
		0 << BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);
}

#if defined(POWER_PROFILE_BOOST) && POWER_PROFILE_BOOST
/* Performance Boost profile (Profile = 3)
 * CPU = 1710 MHz
 * Raaga DSP = 745 MHz
 * HVD CPU = 493 MHz
 * HVD core = 384 MHz
 * 2D M2MC = 576 MHz
 * 3D VC5 = 576 MHz
 * SCB = 324 MHz
 * ------
 * CPU_PLL VCO = 3420 MHz (P = 3 / N = 190)
 * RAAGA_PLL VCO = 3726 MHz (P = 2 / N = 138)
 * AVX_PLL VCO = 3006 MHz (P = 3 / N = 192)
 */
static void bcm7250b0_power_profile_boost(void)
{
	current_cpu_mhz = 1710;

	/* CPU_PLL VCO = 3420 MHz (P = 3 / N = 190)
	 * PLL_CPU_PLL_DIV
	 *      .PDIV = 3
	 *      .NDIV_INT = 190
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_PDIV_SHIFT) |
		(190 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_NDIV_INT_SHIFT));
	/* CPU Clock = 1710 (3420 / 2)
	 * PLL_CPU_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 2
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(2 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));

	/* Raaga PLL VCO = 3726 MHz (P = 2 / N = 138)
	 * PLL_RAAGA_PLL_DIV
	 *     .PDIV = 2
	 *     .NDIV_INT = 138
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_DIV,
		(2 << BCHP_CLKGEN_PLL_RAAGA_PLL_DIV_PDIV_SHIFT) |
		(138 << BCHP_CLKGEN_PLL_RAAGA_PLL_DIV_NDIV_INT_SHIFT));
	/* Raaga Clock = 745 (3726 / 5)
	 * PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 5
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(5 << BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));

	/* AVX_PLL VCO = 3456 MHz (P = 3 / N = 192)
	 * PLL_AVX_PLL_DIV
	 *     .PDIV = 3
	 *     .NDIV_INT = 192
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_AVX_PLL_DIV_PDIV_SHIFT) |
		(192 << BCHP_CLKGEN_PLL_AVX_PLL_DIV_NDIV_INT_SHIFT));
	/* HVD CPU Clock = 493 (3456 / 7)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_1
	 *      .MDIV_CH1 = 7
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_SHIFT) |
		(7 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_MDIV_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_SHIFT));
	/* HVD Core Clock = 384 (3456 / 9)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 9
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(9 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));
	/* M2MC Clock = 576 (3456 / 6)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_3
	 *      .MDIV_CH3 = 6
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_SHIFT) |
		(6 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_MDIV_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_SHIFT));
	/* 3D Clock = 576 (3456 / 6)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_4
	 *      .MDIV_CH4 = 6
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_SHIFT) |
		(6 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_MDIV_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_SHIFT));

	/* SCB Clock = 324 (3888 / 12)
	 * BCHP_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 12
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(12 << BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));

	/* Select the main clock */
	BDEV_WR(BCHP_CLKGEN_ONOFF_VEC_AIO_GFX_TOP_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_VEC_AIO_GFX_TOP_INST_CLOCK_SELECT_GFX_M2MC0_CLOCK_SELECT_SHIFT));

	#if 0
	/* Powerup AVX_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_PWRON,
		1 << BCHP_CLKGEN_PLL_AVX_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON,
		1 << BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);

	/* Powerup RAAGA_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON,
		1 << BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON,
		1 << BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);

	/* Select the default clocks */
	BDEV_WR(BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT_RAAGA0_DSP_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT_V3D_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT,
		(BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_SID_CLOCK_SELECT_DEFAULT <<
			BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_SID_CLOCK_SELECT_SHIFT) |
		(0 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CPU_CLOCK_SELECT_SHIFT) |
		(0 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CORE_CLOCK_SELECT_SHIFT));
	#endif
}
#else /* !POWER_PROFILE_BOOST */
/*
 * Standard STB profile (Profile = 1)
 * CPU = 1503 MHz
 * Raaga DSP = 648 MHz
 * HVD CPU = 429 MHz
 * HVD core = 334 MHz
 * 2D M2MC = 501 MHz
 * 3D VC5 = 501 MHz
 * SCB = 324 MHz
 * ------
 * CPU_PLL VCO = 3006 MHz (P = 3 / N = 167)
 * RAAGA_PLL VCO = 3240 MHz (P = 2 / N = 120)
 * AVX_PLL VCO = 3006 MHz (P = 3 / N = 167)
 */
static void bcm7250b0_power_profile_standard(void)
{
	/* CPU_PLL VCO = 3006 MHz (P = 3 / N = 167)
	 * PLL_CPU_PLL_DIV
	 *      .PDIV = 3
	 *      .NDIV_INT = 167
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_PDIV_SHIFT) |
		(167 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_NDIV_INT_SHIFT));
	/* CPU Clock = 1503 (3006 / 2)
	 * PLL_CPU_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 2
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(2 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));

	/* Raaga PLL VCO = 3240 MHz (P = 2 / N = 120)
	 * PLL_RAAGA_PLL_DIV
	 *     .PDIV = 2
	 *     .NDIV_INT = 120
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_DIV,
		(2 << BCHP_CLKGEN_PLL_RAAGA_PLL_DIV_PDIV_SHIFT) |
		(120 << BCHP_CLKGEN_PLL_RAAGA_PLL_DIV_NDIV_INT_SHIFT));
	/* Raaga Clock = 648 (3240 / 5)
	 * PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 5
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(5 << BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));

	/* AVX_PLL VCO = 3006 MHz (P = 3 / N = 167)
	 * PLL_AVX_PLL_DIV
	 *     .PDIV = 3
	 *     .NDIV_INT = 167
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_AVX_PLL_DIV_PDIV_SHIFT) |
		(167 << BCHP_CLKGEN_PLL_AVX_PLL_DIV_NDIV_INT_SHIFT));
	/* HVD CPU Clock = 429 (3006 / 7)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_1
	 *      .MDIV_CH1 = 7
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_SHIFT) |
		(7 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_MDIV_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_SHIFT));
	/* HVD Core Clock = 334 (3006 / 9)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 9
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(9 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));
	/* M2MC Clock = 501 (3006 / 6)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_3
	 *      .MDIV_CH3 = 6
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_SHIFT) |
		(6 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_MDIV_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_SHIFT));
	/* 3D Clock = 501 (3006 / 6)
	 * PLL_AVX_PLL_CHANNEL_CTRL_CH_4
	 *      .MDIV_CH4 = 6
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4,
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_SHIFT) |
		(6 << BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_MDIV_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_DEFAULT <<
			BCHP_CLKGEN_PLL_AVX_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_SHIFT));

	/* SCB Clock = 324 (3888 / 12)
	 * BCHP_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH2 = 12
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(12 << BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));

	/* Select the main clock */
	BDEV_WR(BCHP_CLKGEN_ONOFF_VEC_AIO_GFX_TOP_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_VEC_AIO_GFX_TOP_INST_CLOCK_SELECT_GFX_M2MC0_CLOCK_SELECT_SHIFT));

	#if 0
	/* Powerup AVX_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_PWRON,
		1 << BCHP_CLKGEN_PLL_AVX_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON,
		1 << BCHP_CLKGEN_PLL_AVX_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);

	/* Powerup RAAGA_PLL */
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON,
		1 << BCHP_CLKGEN_PLL_RAAGA_PLL_PWRON_PWRON_PLL_SHIFT);
	BDEV_WR(BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON,
		1 << BCHP_CLKGEN_PLL_RAAGA_PLL_LDO_PWRON_LDO_PWRON_PLL_SHIFT);

	/* Select the default clocks */
	BDEV_WR(BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_RAAGA_DSP_TOP_0_INST_CLOCK_SELECT_RAAGA0_DSP_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT,
		(0 << BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT_V3D_CLOCK_SELECT_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_V3D_TOP_INST_CLOCK_SELECT,
		(BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_SID_CLOCK_SELECT_DEFAULT <<
			BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_SID_CLOCK_SELECT_SHIFT) |
		(0 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CPU_CLOCK_SELECT_SHIFT) |
		(0 << BCHP_CLKGEN_ONOFF_HVD_SID0_TOP_INST_SELECT_HVD_SID0_CORE_CLOCK_SELECT_SHIFT));
	#endif
}
#endif /* POWER_PROFILE_BOOST */

/* bcm7250b0_apply_powerprofile -- powers and slows down various hardware blocks
 *
 * It might be okay for 97250SV, but the power consumption of 97250DGL
 * has to be minimized as much as possible because of its limited power
 * supply (MHL) and heat.
 *
 * Power down unnecessary hardware blocks as much as possible, and slow
 * down hardware blocks as long as they comply with the advertized
 * performance.
 */
static void bcm7250b0_apply_powerprofile(struct board_type *b, uint32_t mhl_power)
{
	/* The power saving needs be done as quickly as possible after
	 * booting, and is done in FSBL right after detecting 7250B0
	 * via "prid" of board_type because it can vary board by board.
	 * Doing it in SSBL will not work against S3.
	 *
	 * The code size of the power saving sequence should be minimal
	 * because it is included in FSBL. At the same time, executing it
	 * at the early stage of FSBL presents an opportunity to optimize
	 * the code space. It is expected that most registers would still
	 * have default values. And, it is true for registers that are
	 * accessed for the power saving sequence.
	 *
	 * Taking advantage of accessing the registers for the first time
	 * after reset, the code size can be reduced by avoiding RMW
	 * (read-modify-write) and directly writing to registers with known
	 * values. But, the code is not portable. It is specific to 7250B0.
	 * To prevent this code from being blindly copied to other platforms,
	 * keep the following #ifdef inside this function.
	 */
	const uint8_t bid_x = b->bid & 0xF0;
	const uint32_t prid_without_rev = b->prid & ~CHIPID_REV_MASK;

	/* If MHL power is present then we got our Amps via
	 * an external MHL device, so we go lower power
	 * and ignore whatever the board ID recommends.
	 */
	if (mhl_power != FSBL_RUNFLAG_MHL_BOOT_Nope) {
		bcm7250b0_power_profile_dongle();
	} else {
		switch (prid_without_rev) {
		case 0x72500000: /* 7250 */
		case 0x07250100: /* 72501 */
		default: /* standard STB profile */
#if defined(POWER_PROFILE_BOOST) && POWER_PROFILE_BOOST
			bcm7250b0_power_profile_boost();
#else
			bcm7250b0_power_profile_standard();
#endif
			break;
		case 0x07250200: /* 72502 */
			bcm7250b0_power_profile_dongle();
			break;
		}
	}

	/* On 97250CWF, the clock for the frontend chip, 3145, comes from
	 * ANA_XTAL_EXT_CML. Turn it on at 54MHz with 10mA.
	 * AON_CTRL_ANA_XTAL_EXT_CML_CONTROL
	 *      .osc_PMSM_S3_pd_buffer = 1 (power down during S3)
	 *      .osc_override_strap = 1 (no strapping)
	 *      .osc_pd_buffer = 0 (turn on)
	 *      .osc_div2_sel = 0 (54MHz)
	 *      .osc_current = default (10mA)
	 */
	if (bid_x == 0x40) {
		BDEV_WR(BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL,
			(1<<BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL_osc_PMSM_S3_pd_buffer_SHIFT) |
			(0<<BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL_osc_pd_buffer_SHIFT) |
			(0<<BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL_osc_div2_sel_SHIFT) |
			(BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL_osc_current_DEFAULT<<
				BCHP_AON_CTRL_ANA_XTAL_EXT_CML_CONTROL_osc_current_SHIFT));
	}

	/* Disable all the clocks under LC_PLL except SDIO, on channel# 5 */
	BDEV_WR(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(0<<BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));
	BDEV_WR(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1,
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_POST_DIVIDER_HOLD_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_PHASE_OFFSET_CH1_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_MDIV_CH1_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_MDIV_CH1_SHIFT) |
		(0<<BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_1_CLOCK_DIS_CH1_SHIFT));
	BDEV_WR(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(0<<BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));
	BDEV_WR(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3,
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_POST_DIVIDER_HOLD_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_PHASE_OFFSET_CH3_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_MDIV_CH3_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_MDIV_CH3_SHIFT) |
		(0<<BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_3_CLOCK_DIS_CH3_SHIFT));
	BDEV_WR(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4,
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_POST_DIVIDER_HOLD_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_PHASE_OFFSET_CH4_SHIFT) |
		(BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_MDIV_CH4_DEFAULT<<
			BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_MDIV_CH4_SHIFT) |
		(0<<BCHP_CLKGEN_PLL_LC_PLL_CHANNEL_CTRL_CH_4_CLOCK_DIS_CH4_SHIFT));
}

static void bcm7250b0_gphy_pll_init(void)
{
	/* HW7250-114: switch to 54Mhz clock */
	BDEV_WR(BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_SEL,
		(BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_SEL_EGPHY_PLL_REF_SEL_DEFAULT<<
			BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_SEL_EGPHY_PLL_REF_SEL_SHIFT) |
		(4<<BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_SEL_EGPHY_PLL_CLK_SEL_SHIFT));
	BDEV_WR(BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_DIV5,
		(1<<BCHP_CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_DIV5_EGPHY_PLL_SEL_DIV5_SHIFT));
}
#endif /* #if defined(CONFIG_BCM7250B0) */

#if defined(CONFIG_BCM7364)
/* The hardware default values set the CPU speed at 601MHz, which is
 * only proper for 73649. Other variants should run at 1.5GHz.
 */
static void bcm7364_cpu_speed_1503mhz(void)
{
	/* CPU_PLL VCO = 3006 MHz (P = 3 / N = 167)
	 * PLL_CPU_PLL_DIV
	 *      .PDIV = 3 (default)
	 *      .NDIV_INT = 167 (default)
	 */
	/* CPU Clock = 1503 (3006 / 2)
	 * PLL_CPU_PLL_CHANNEL_CTRL_CH_0
	 *      .MDIV_CH0 = 2 (default is 5)
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0,
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_POST_DIVIDER_HOLD_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_PHASE_OFFSET_CH0_SHIFT) |
		(2 << BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_MDIV_CH0_SHIFT) |
		(BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0_CLOCK_DIS_CH0_SHIFT));
}

/* The hardware default values set the SCB speed at 324MHz, which is
 * too fast for 73649.
 */
static void bcm7364_scb_speed_277mhz(void)
{
	/* SYS0_PLL VCO = 3888 MHz (P = 2 / N = 144)
	 * PLL_SYS0_PLL_DIV
	 *      .PDIV = 2 (default)
	 *      .NDIV_INT = 144 (default)
	 */
	/* SCB Clock = 277.7 (3888 / 14)
	 * PLL_SYS0_PLL_CHANNEL_CTRL_CH_2
	 *      .MDIV_CH0 = 14 (default is 12)
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2,
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_POST_DIVIDER_HOLD_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_PHASE_OFFSET_CH2_SHIFT) |
		(14 << BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_MDIV_CH2_SHIFT) |
		(BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_DEFAULT <<
			BCHP_CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_2_CLOCK_DIS_CH2_SHIFT));

}

/* HDMI RX is NOT packaged out to any of 7364 variants. It should be
 * put in lowest power consumption mode.
 */
static void bcm7364_powerdown_hdmi_rx(void)
{
	/* AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHR[SRAM_PDA_IN_DVPHR] = 1 */
	BDEV_WR(BCHP_AVS_TOP_CTRL_SRAM_POWER_GATE_IN_DVPHR, 1);

	/* HDMI_RX_FE_0_RESET_CONTROL
	 *   .LDO_PLL_POWER_DOWN = 1
	 *   .LDO_SL_POWER_DOWN = 1
	 *   .LDO_ILO_POWER_DOWN = 1
	 *   .RESISTOR_TERMINATION_POWER_DOWN = 1
	 *   .ANALOG_BIAS_POWER_DOWN = 1
	 *   .ANALOG_CHANNEL_2_POWER_DOWN = 1
	 *   .ANALOG_CHANNEL_1_POWER_DOWN = 1
	 *   .ANALOG_CHANNEL_0_POWER_DOWN = 1
	 *   .ANALOG_CHANNEL_CLOCK_POWER_DOWN = 1
	 *   .ANALOG_PLL_POWER_DOWN = 1
	 */
	BDEV_WR(BCHP_HDMI_RX_FE_0_RESET_CONTROL, 0x3FF0000);

	/* DVP_HR_POWER_CONTROL[RX_PHY_0_POWER_DOWN] = 1
	 * nothing to do, it is the default
	 */

	/* CLKGEN_ONOFF_DVP_HR_INST_CLOCK_DISABLE
	 *   .DISABLE_DVPHR_ALWAYSON_CLOCK = 1
	 * CLKGEN_ONOFF_DVP_HR_INST_CLOCK_ENABLE
	 *   .DVPHR_54_CLOCK_ENABLE = 0
	 *   .DVPHR_BVB_216_CLOCK_ENABLE = 0
	 *   .DVPHR_BVB_324_CLOCK_ENABLE = 0
	 *   .DVPHR_GISB_CLOCK_ENABLE = 0
	 * CLKGEN_ONOFF_DVP_HR_INST_CLOCK_ENABLE0
	 *   .DVPHR_108_CLOCK_ENABLE0 = 0
	 * CLKGEN_PLL_NETWORK_PLL_CHANNEL_CTRL_CH_3
	 *   .POST_DIVIDER_HOLD_CH3 = 1
	 *   .CLOCK_DIS_CH3 = 1
	 * CLKGEN_PLL_NETWORK_PLL_CHANNEL_CTRL_CH_4
	 *   .POST_DIVIDER_HOLD_CH4 = 1
	 *   .CLOCK_DIS_CH4 = 1
	 */
	BDEV_WR(BCHP_CLKGEN_ONOFF_DVP_HR_INST_CLOCK_DISABLE, 0x1);
	BDEV_WR(BCHP_CLKGEN_ONOFF_DVP_HR_INST_CLOCK_ENABLE, 0x0);
	BDEV_WR(BCHP_CLKGEN_ONOFF_DVP_HR_INST_CLOCK_ENABLE0, 0x0);
	BDEV_WR(BCHP_CLKGEN_PLL_NETWORK_PLL_CHANNEL_CTRL_CH_3, 0x409);
	BDEV_WR(BCHP_CLKGEN_PLL_NETWORK_PLL_CHANNEL_CTRL_CH_4, 0x40d);
}

static void bcm7364_gphy_pll_init(void)
{
	/* HW7364-158: change GPHY reference clock to to 54MHz channel 2 pll
	 * clock due to LC PLL issue
	 */
	BDEV_WR_F(CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_SEL,
		  EGPHY_PLL_REF_SEL, 2);
	BDEV_WR_F(CLKGEN_ONOFF_EGPHY28_1PORT_33V_90O_FC_INST_DIV5,
		  EGPHY_PLL_SEL_DIV5, 1);
}
#endif

#if defined(CONFIG_BCM7439B0)
static void bcm7439b0_cpu_speed_1719mhz(void)
{
	uint32_t lockval;

	current_cpu_mhz = 1719;

	/* enable SLOWCPU clock */
	BDEV_WR(BCHP_CLKGEN_EAGLET_TOP_INST_CLOCK_DISABLE,
		0 << BCHP_CLKGEN_EAGLET_TOP_INST_CLOCK_DISABLE_DISABLE_CPU_SLOWCPU_CLOCK_SHIFT);

	/* request to bypass PLL_CPU channel-0 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST,
		(BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_TRANSACTION_WAIT_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_TRANSACTION_WAIT_SHIFT) |
		(1 << BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_PLL_BYPASS_REQUEST_SHIFT));

	/* put pll in reset */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_RESET,
		(1 << BCHP_CLKGEN_PLL_CPU_PLL_RESET_RESETD_SHIFT) |
		(1 << BCHP_CLKGEN_PLL_CPU_PLL_RESET_RESETA_SHIFT));

	/*
	 * CPU freq = 1719 MHz
	 *
	 * CPU_PLL VCO = 3438 MHz (P = 3 / N = 191)
	 * PLL_CPU_PLL_DIV
	 *      .PDIV = 3
	 *      .NDIV_INT = 191
	 *
	 * PLL_CHANNEL_CTRL_CH0.MDIV = 2
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_DIV,
		(3 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_PDIV_SHIFT) |
		(191 << BCHP_CLKGEN_PLL_CPU_PLL_DIV_NDIV_INT_SHIFT));
	BDEV_WR_F(CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0, MDIV_CH0, 2);

	/* put pll back into normal mode */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_PLL_RESET,
		(0 << BCHP_CLKGEN_PLL_CPU_PLL_RESET_RESETD_SHIFT) |
		(0 << BCHP_CLKGEN_PLL_CPU_PLL_RESET_RESETA_SHIFT));

	/* wait for pll lock */
	do {
		lockval = BDEV_RD(BCHP_CLKGEN_PLL_CPU_PLL_LOCK_STATUS);
	} while (!(lockval & BCHP_CLKGEN_PLL_CPU_PLL_LOCK_STATUS_LOCK_MASK));

	/* remove the request to the state machine that is to switch from
	 * the fast clock to the slow backup clock
	 */
	BDEV_WR(BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST,
		(BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_TRANSACTION_WAIT_DEFAULT <<
			BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_TRANSACTION_WAIT_SHIFT) |
		(0 << BCHP_CLKGEN_PLL_CPU_GLITCHLESS_SWITCH_REQUEST_PLL_BYPASS_REQUEST_SHIFT));

	/* disable SLOWCPU clock */
	BDEV_WR(BCHP_CLKGEN_EAGLET_TOP_INST_CLOCK_DISABLE,
		1 << BCHP_CLKGEN_EAGLET_TOP_INST_CLOCK_DISABLE_DISABLE_CPU_SLOWCPU_CLOCK_SHIFT);
}
#endif

#if defined(CONFIG_BCM7445E0)
/* bcm7445e0_clock_init -- 7445E0 specific clock adjustments
 *
 * To reduce power spike at the beginning of powering up, 7445E0
 * lowered several key clocks. They should be back to nominal speeds
 * at this point since this is well after the beginning.
 */
static void bcm7445e0_clock_init(void)
{
	/* set the CPU PLL to full frequency 1.5G */
	BDEV_WR_F(CLKGEN_PLL_CPU_PLL_CHANNEL_CTRL_CH_0, MDIV_CH0, 2);

	/* set SCB to full frequency */
	BDEV_WR_F(CLKGEN_PLL_SCB_PLL_CHANNEL_CTRL_CH_0, MDIV_CH0, 9);

	/* set V3D to full frequency */
	BDEV_WR_F(CLKGEN_PLL_MOCA_PLL_CHANNEL_CTRL_CH_3, MDIV_CH3, 8);

	/* set 2 VICE CLKs to full frequency 351 MHz */
	BDEV_WR_F(CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_2, MDIV_CH2, 11);
	BDEV_WR_F(CLKGEN_PLL_RAAGA_PLL_CHANNEL_CTRL_CH_3, MDIV_CH3, 11);

	/* set 1 BVN_648 CLK to full frequency 648 MHz */
	BDEV_WR_F(CLKGEN_PLL_SYS0_PLL_CHANNEL_CTRL_CH_4, MDIV_CH4, 5);

	/* HW7445-1830: switch to the 54Mhz reference clock for the integrated
	 * GPHY to avoid its PLL from being unlocked.
	 */
	BDEV_WR_F(CLKGEN_EGPHY28_1PORT_33V_90O_FC_INST_DIV5,
		  EGPHY_PLL_SEL_DIV5, 1);
	BDEV_WR_F(CLKGEN_EGPHY28_1PORT_33V_90O_FC_INST_SEL,
		  EGPHY_PLL_REF_CLK_SEL, 2);

}
#endif /* #if defined(CONFIG_BCM7445E0) */


unsigned int get_cpu_freq_mhz(void)
{
	return current_cpu_mhz;
}

void adjust_clocks(struct board_type *b, uint32_t mhl_power)
{
	if (b == NULL)
		return;

#ifdef BCHP_XPT_PMU_REG_START
	adjust_xpt_clocks();
#endif

#if defined(CONFIG_BCM3390)
	bcm3390_clock_init();
#endif

#if defined(CONFIG_BCM7145B0)
	bcm7145b0_clock_init();
#endif

#if defined(CONFIG_BCM7250B0)
	bcm7250b0_apply_powerprofile(b, mhl_power);
	bcm7250b0_gphy_pll_init();
#endif

#if defined(CONFIG_BCM7364)
	if ((b->prid & (~CHIPID_REV_MASK)) == 0x07364900) /* 73649xx */
		/* default CPU speed, 601MHz and reduced SCB speed, 277MHz */
		bcm7364_scb_speed_277mhz();
	else /* any NON-73649xx */
		/* CPU speed, 1.5GHz and default SCB speed, 324MHz */
		bcm7364_cpu_speed_1503mhz();

	bcm7364_powerdown_hdmi_rx();
	bcm7364_gphy_pll_init();
#endif

#if defined(CONFIG_BCM7439B0)
	bcm7439b0_cpu_speed_1719mhz(); /* 1.7GHz CPU for every variant */
#endif

#if defined(CONFIG_BCM7445E0)
	bcm7445e0_clock_init();
#endif
}

