/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the terms and
 *  conditions of a separate, written license agreement executed between you and Broadcom
 *  (an "Authorized License").  Except as set forth in an Authorized License, Broadcom grants
 *  no license (express or implied), right to use, or waiver of any kind with respect to the
 *  Software, and Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 *  HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 *  NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization, constitutes the valuable trade
 *  secrets of Broadcom, and you shall use all reasonable efforts to protect the confidentiality thereof,
 *  and to use this information only in connection with your use of Broadcom integrated circuit products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *  AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *  WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO
 *  THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED WARRANTIES
 *  OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE,
 *  LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION
 *  OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING OUT OF
 *  USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *  LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT, OR
 *  EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO YOUR
 *  USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF
 *  THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF THE AMOUNT
 *  ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER IS GREATER. THESE
 *  LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF
 *  ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Sun Nov 19 01:07:18 2017
 *                 Full Compile MD5 Checksum  51b81740b386aea70724ff951c628857
 *                     (minus title and desc)
 *                 MD5 Checksum               96520679e55aabb9e30a2b8c1241ef41
 *
 * lock_release:   r_1772
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1777
 *                 unknown                    unknown
 *                 Perl Interpreter           5.014001
 *                 Operating System           linux
 *                 Script Source              projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   LOCAL projects/stbgit/bin/gen_rdb.pl
 *
 *
********************************************************************************/

#ifndef BCHP_XPT_BUS_IF_H__
#define BCHP_XPT_BUS_IF_H__

/***************************************************************************
 *XPT_BUS_IF - Data Transport Configuration Registers
 ***************************************************************************/
#define BCHP_XPT_BUS_IF_MISC_CTRL0               0x0020a00080 /* [RW][32] Data Transport Misc Control 0 Register */
#define BCHP_XPT_BUS_IF_TEST_MODE                0x0020a00084 /* [RW][32] Data transport test register */
#define BCHP_XPT_BUS_IF_REVISION                 0x0020a00088 /* [RO][32] Data Transport Revision Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG          0x0020a0008c /* [RW][32] Interrupt Status Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN       0x0020a00090 /* [RW][32] Interrupt Status Enable Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG         0x0020a00094 /* [RW][32] Interrupt Status2 Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN      0x0020a00098 /* [RW][32] Interrupt Status2 Enable Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG         0x0020a0009c /* [RW][32] Interrupt Status3 Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN      0x0020a000a0 /* [RW][32] Interrupt Status3 Enable Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG         0x0020a000a4 /* [RW][32] Interrupt Status4 Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN      0x0020a000a8 /* [RW][32] Interrupt Status4 Enable Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG         0x0020a000ac /* [RW][32] Interrupt Status5 Register */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN      0x0020a000b0 /* [RW][32] Interrupt Status5 Enable Register */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET 0x0020a000b4 /* [WO][32] Software initialization control for XPT sub-blocks */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR 0x0020a000b8 /* [WO][32] Software initialization control for XPT sub-blocks */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS 0x0020a000bc /* [RO][32] Software initialization control for XPT sub-blocks */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT 0x0020a000c0 /* [RW][32] Software initialization control for XPT sub-blocks */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG   0x0020a000d0 /* [RW][32] LCIF to XMEMIF Debug Registers */
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS            0x0020a000d4 /* [RO][32] Data Transport max number of playbacks supported */
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS          0x0020a000d8 /* [RO][32] Data Transport max number of PID parsers supported */
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS         0x0020a000dc /* [RO][32] Data Transport max number of PID channels supported excluding MEMDMA */
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS  0x0020a000e0 /* [RO][32] Data Transport max number of PID channels supported for MEMDMA */
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS          0x0020a000e4 /* [RO][32] Data Transport max number of input bands supported */
#define BCHP_XPT_BUS_IF_MAX_PCRS                 0x0020a000e8 /* [RO][32] Data Transport max number of PCRs supported */
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS        0x0020a000ec /* [RO][32] Data Transport max number of TPIT channels supported */
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS        0x0020a000f0 /* [RO][32] Data Transport max number of RAVE contexts supported */
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS         0x0020a000f4 /* [RO][32] Data Transport max number of RMX channels supported */
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS          0x0020a000f8 /* [RO][32] Data Transport max number of MSG buffers supported */
#define BCHP_XPT_BUS_IF_MAX_SCDS                 0x0020a000fc /* [RO][32] Data Transport max number of SCDs supported */

/***************************************************************************
 *MISC_CTRL0 - Data Transport Misc Control 0 Register
 ***************************************************************************/
/* XPT_BUS_IF :: MISC_CTRL0 :: reserved0 [31:07] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_reserved0_MASK                  0xffffff80
#define BCHP_XPT_BUS_IF_MISC_CTRL0_reserved0_SHIFT                 7

/* XPT_BUS_IF :: MISC_CTRL0 :: XPT_COUNTER_SCF [06:05] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_MASK            0x00000060
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_SHIFT           5
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_DEFAULT         0x00000003
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_108MHz          0
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_216MHz          1
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_270MHz          2
#define BCHP_XPT_BUS_IF_MISC_CTRL0_XPT_COUNTER_SCF_324MHz          3

/* XPT_BUS_IF :: MISC_CTRL0 :: reserved1 [04:03] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_reserved1_MASK                  0x00000018
#define BCHP_XPT_BUS_IF_MISC_CTRL0_reserved1_SHIFT                 3

/* XPT_BUS_IF :: MISC_CTRL0 :: ERROR_INT_TEST_MODE [02:02] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_ERROR_INT_TEST_MODE_MASK        0x00000004
#define BCHP_XPT_BUS_IF_MISC_CTRL0_ERROR_INT_TEST_MODE_SHIFT       2
#define BCHP_XPT_BUS_IF_MISC_CTRL0_ERROR_INT_TEST_MODE_DEFAULT     0x00000000

/* XPT_BUS_IF :: MISC_CTRL0 :: MPOD_INT_TEST_MODE [01:01] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_MPOD_INT_TEST_MODE_MASK         0x00000002
#define BCHP_XPT_BUS_IF_MISC_CTRL0_MPOD_INT_TEST_MODE_SHIFT        1
#define BCHP_XPT_BUS_IF_MISC_CTRL0_MPOD_INT_TEST_MODE_DEFAULT      0x00000000

/* XPT_BUS_IF :: MISC_CTRL0 :: LINK_LIST_DESC_ENDIAN_CTRL [00:00] */
#define BCHP_XPT_BUS_IF_MISC_CTRL0_LINK_LIST_DESC_ENDIAN_CTRL_MASK 0x00000001
#define BCHP_XPT_BUS_IF_MISC_CTRL0_LINK_LIST_DESC_ENDIAN_CTRL_SHIFT 0
#define BCHP_XPT_BUS_IF_MISC_CTRL0_LINK_LIST_DESC_ENDIAN_CTRL_DEFAULT 0x00000000

/***************************************************************************
 *TEST_MODE - Data transport test register
 ***************************************************************************/
/* XPT_BUS_IF :: TEST_MODE :: reserved0 [31:01] */
#define BCHP_XPT_BUS_IF_TEST_MODE_reserved0_MASK                   0xfffffffe
#define BCHP_XPT_BUS_IF_TEST_MODE_reserved0_SHIFT                  1

/* XPT_BUS_IF :: TEST_MODE :: PSG_SECRET_ENBLE [00:00] */
#define BCHP_XPT_BUS_IF_TEST_MODE_PSG_SECRET_ENBLE_MASK            0x00000001
#define BCHP_XPT_BUS_IF_TEST_MODE_PSG_SECRET_ENBLE_SHIFT           0
#define BCHP_XPT_BUS_IF_TEST_MODE_PSG_SECRET_ENBLE_DEFAULT         0x00000000

/***************************************************************************
 *REVISION - Data Transport Revision Register
 ***************************************************************************/
/* XPT_BUS_IF :: REVISION :: reserved0 [31:16] */
#define BCHP_XPT_BUS_IF_REVISION_reserved0_MASK                    0xffff0000
#define BCHP_XPT_BUS_IF_REVISION_reserved0_SHIFT                   16

/* XPT_BUS_IF :: REVISION :: MAJOR_REV_NUMBER [15:08] */
#define BCHP_XPT_BUS_IF_REVISION_MAJOR_REV_NUMBER_MASK             0x0000ff00
#define BCHP_XPT_BUS_IF_REVISION_MAJOR_REV_NUMBER_SHIFT            8
#define BCHP_XPT_BUS_IF_REVISION_MAJOR_REV_NUMBER_DEFAULT          0x00000040

/* XPT_BUS_IF :: REVISION :: MINOR_REV_NUMBER [07:00] */
#define BCHP_XPT_BUS_IF_REVISION_MINOR_REV_NUMBER_MASK             0x000000ff
#define BCHP_XPT_BUS_IF_REVISION_MINOR_REV_NUMBER_SHIFT            0

/***************************************************************************
 *INTR_STATUS_REG - Interrupt Status Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS_REG :: reserved0 [31:28] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_reserved0_MASK             0xf0000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_reserved0_SHIFT            28

/* XPT_BUS_IF :: INTR_STATUS_REG :: RSBUFF_TB_ERR_INTR [27:27] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_TB_ERR_INTR_MASK    0x08000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_TB_ERR_INTR_SHIFT   27
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_TB_ERR_INTR_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG :: RSBUFF_PTR_OOR_INTR [26:26] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_PTR_OOR_INTR_MASK   0x04000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_PTR_OOR_INTR_SHIFT  26
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_PTR_OOR_INTR_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG :: XCBUFF_PTR_OOR_INTR [25:25] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_PTR_OOR_INTR_MASK   0x02000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_PTR_OOR_INTR_SHIFT  25
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_PTR_OOR_INTR_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG :: RSBUFF_OVERFLFLOW_INTR [24:24] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_OVERFLFLOW_INTR_MASK 0x01000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_OVERFLFLOW_INTR_SHIFT 24
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_RSBUFF_OVERFLFLOW_INTR_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG :: XCBUFF_OVERFLOW_INTR [23:23] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_OVERFLOW_INTR_MASK  0x00800000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_OVERFLOW_INTR_SHIFT 23
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_XCBUFF_OVERFLOW_INTR_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG :: reserved1 [22:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_reserved1_MASK             0x007fffff
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_reserved1_SHIFT            0

/***************************************************************************
 *INTR_STATUS_REG_EN - Interrupt Status Enable Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: reserved0 [31:28] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_reserved0_MASK          0xf0000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_reserved0_SHIFT         28

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: RSBUFF_TB_ERR_INTR_EN [27:27] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_TB_ERR_INTR_EN_MASK 0x08000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_TB_ERR_INTR_EN_SHIFT 27
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_TB_ERR_INTR_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: RSBUFF_PTR_OOR_INTR_EN [26:26] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_PTR_OOR_INTR_EN_MASK 0x04000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_PTR_OOR_INTR_EN_SHIFT 26
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_PTR_OOR_INTR_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: XCBUFF_PTR_OOR_INTR_EN [25:25] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_PTR_OOR_INTR_EN_MASK 0x02000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_PTR_OOR_INTR_EN_SHIFT 25
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_PTR_OOR_INTR_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: RSBUFF_OVERFLFLOW_INTR_EN [24:24] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_OVERFLFLOW_INTR_EN_MASK 0x01000000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_OVERFLFLOW_INTR_EN_SHIFT 24
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_RSBUFF_OVERFLFLOW_INTR_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: XCBUFF_OVERFLOW_INTR_EN [23:23] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_OVERFLOW_INTR_EN_MASK 0x00800000
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_OVERFLOW_INTR_EN_SHIFT 23
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_XCBUFF_OVERFLOW_INTR_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS_REG_EN :: reserved1 [22:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_reserved1_MASK          0x007fffff
#define BCHP_XPT_BUS_IF_INTR_STATUS_REG_EN_reserved1_SHIFT         0

/***************************************************************************
 *INTR_STATUS2_REG - Interrupt Status2 Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS2_REG :: reserved0 [31:03] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_reserved0_MASK            0xfffffff8
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_reserved0_SHIFT           3

/* XPT_BUS_IF :: INTR_STATUS2_REG :: CA_ERR_INT [02:02] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CA_ERR_INT_MASK           0x00000004
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CA_ERR_INT_SHIFT          2
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CA_ERR_INT_DEFAULT        0x00000000

/* XPT_BUS_IF :: INTR_STATUS2_REG :: CP_DEC_ERR_INT [01:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_DEC_ERR_INT_MASK       0x00000002
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_DEC_ERR_INT_SHIFT      1
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_DEC_ERR_INT_DEFAULT    0x00000000

/* XPT_BUS_IF :: INTR_STATUS2_REG :: CP_ENC_ERR_INT [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_ENC_ERR_INT_MASK       0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_ENC_ERR_INT_SHIFT      0
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_CP_ENC_ERR_INT_DEFAULT    0x00000000

/***************************************************************************
 *INTR_STATUS2_REG_EN - Interrupt Status2 Enable Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS2_REG_EN :: reserved0 [31:03] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_reserved0_MASK         0xfffffff8
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_reserved0_SHIFT        3

/* XPT_BUS_IF :: INTR_STATUS2_REG_EN :: CA_ERR_INT_EN [02:02] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CA_ERR_INT_EN_MASK     0x00000004
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CA_ERR_INT_EN_SHIFT    2
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CA_ERR_INT_EN_DEFAULT  0x00000000

/* XPT_BUS_IF :: INTR_STATUS2_REG_EN :: CP_DEC_ERR_INT_EN [01:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_DEC_ERR_INT_EN_MASK 0x00000002
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_DEC_ERR_INT_EN_SHIFT 1
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_DEC_ERR_INT_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS2_REG_EN :: CP_ENC_ERR_INT_EN [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_ENC_ERR_INT_EN_MASK 0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_ENC_ERR_INT_EN_SHIFT 0
#define BCHP_XPT_BUS_IF_INTR_STATUS2_REG_EN_CP_ENC_ERR_INT_EN_DEFAULT 0x00000000

/***************************************************************************
 *INTR_STATUS3_REG - Interrupt Status3 Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS3_REG :: reserved0 [31:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_reserved0_MASK            0xfffffffe
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_reserved0_SHIFT           1

/* XPT_BUS_IF :: INTR_STATUS3_REG :: MPOD_EXTRACTOR_CRC_ERROR [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_MPOD_EXTRACTOR_CRC_ERROR_MASK 0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_MPOD_EXTRACTOR_CRC_ERROR_SHIFT 0
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_MPOD_EXTRACTOR_CRC_ERROR_DEFAULT 0x00000000

/***************************************************************************
 *INTR_STATUS3_REG_EN - Interrupt Status3 Enable Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS3_REG_EN :: reserved0 [31:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN_reserved0_MASK         0xfffffffe
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN_reserved0_SHIFT        1

/* XPT_BUS_IF :: INTR_STATUS3_REG_EN :: MPOD_EXTRACTOR_CRC_ERROR_EN [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN_MPOD_EXTRACTOR_CRC_ERROR_EN_MASK 0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN_MPOD_EXTRACTOR_CRC_ERROR_EN_SHIFT 0
#define BCHP_XPT_BUS_IF_INTR_STATUS3_REG_EN_MPOD_EXTRACTOR_CRC_ERROR_EN_DEFAULT 0x00000000

/***************************************************************************
 *INTR_STATUS4_REG - Interrupt Status4 Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS4_REG :: reserved0 [31:28] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_reserved0_MASK            0xf0000000
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_reserved0_SHIFT           28

/* XPT_BUS_IF :: INTR_STATUS4_REG :: GISB_BRIDGE [27:27] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_GISB_BRIDGE_MASK          0x08000000
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_GISB_BRIDGE_SHIFT         27
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_GISB_BRIDGE_DEFAULT       0x00000000

/* XPT_BUS_IF :: INTR_STATUS4_REG :: reserved1 [26:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_reserved1_MASK            0x07ffffff
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_reserved1_SHIFT           0

/***************************************************************************
 *INTR_STATUS4_REG_EN - Interrupt Status4 Enable Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS4_REG_EN :: reserved0 [31:28] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_reserved0_MASK         0xf0000000
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_reserved0_SHIFT        28

/* XPT_BUS_IF :: INTR_STATUS4_REG_EN :: GISB_BRIDGE_EN [27:27] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_GISB_BRIDGE_EN_MASK    0x08000000
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_GISB_BRIDGE_EN_SHIFT   27
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_GISB_BRIDGE_EN_DEFAULT 0x00000000

/* XPT_BUS_IF :: INTR_STATUS4_REG_EN :: reserved1 [26:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_reserved1_MASK         0x07ffffff
#define BCHP_XPT_BUS_IF_INTR_STATUS4_REG_EN_reserved1_SHIFT        0

/***************************************************************************
 *INTR_STATUS5_REG - Interrupt Status5 Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS5_REG :: reserved0 [31:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_reserved0_MASK            0xfffffffe
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_reserved0_SHIFT           1

/* XPT_BUS_IF :: INTR_STATUS5_REG :: WRCHECKER_INT [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_WRCHECKER_INT_MASK        0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_WRCHECKER_INT_SHIFT       0
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_WRCHECKER_INT_DEFAULT     0x00000000

/***************************************************************************
 *INTR_STATUS5_REG_EN - Interrupt Status5 Enable Register
 ***************************************************************************/
/* XPT_BUS_IF :: INTR_STATUS5_REG_EN :: reserved0 [31:01] */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN_reserved0_MASK         0xfffffffe
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN_reserved0_SHIFT        1

/* XPT_BUS_IF :: INTR_STATUS5_REG_EN :: WRCHECKER_INT [00:00] */
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN_WRCHECKER_INT_MASK     0x00000001
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN_WRCHECKER_INT_SHIFT    0
#define BCHP_XPT_BUS_IF_INTR_STATUS5_REG_EN_WRCHECKER_INT_DEFAULT  0x00000000

/***************************************************************************
 *SUB_MODULE_SOFT_INIT_SET - Software initialization control for XPT sub-blocks
 ***************************************************************************/
/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_SET :: reserved0 [31:02] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_reserved0_MASK    0xfffffffc
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_reserved0_SHIFT   2

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_SET :: MEMDMA_MCPB_SOFT_INIT_SET [01:01] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_MEMDMA_MCPB_SOFT_INIT_SET_MASK 0x00000002
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_MEMDMA_MCPB_SOFT_INIT_SET_SHIFT 1
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_MEMDMA_MCPB_SOFT_INIT_SET_DEFAULT 0x00000000

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_SET :: XPT_MCPB_SOFT_INIT_SET [00:00] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_XPT_MCPB_SOFT_INIT_SET_MASK 0x00000001
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_XPT_MCPB_SOFT_INIT_SET_SHIFT 0
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_SET_XPT_MCPB_SOFT_INIT_SET_DEFAULT 0x00000000

/***************************************************************************
 *SUB_MODULE_SOFT_INIT_CLEAR - Software initialization control for XPT sub-blocks
 ***************************************************************************/
/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_CLEAR :: reserved0 [31:02] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_reserved0_MASK  0xfffffffc
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_reserved0_SHIFT 2

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_CLEAR :: MEMDMA_MCPB_SOFT_INIT_CLEAR [01:01] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_MEMDMA_MCPB_SOFT_INIT_CLEAR_MASK 0x00000002
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_MEMDMA_MCPB_SOFT_INIT_CLEAR_SHIFT 1
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_MEMDMA_MCPB_SOFT_INIT_CLEAR_DEFAULT 0x00000000

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_CLEAR :: XPT_MCPB_SOFT_INIT_CLEAR [00:00] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_XPT_MCPB_SOFT_INIT_CLEAR_MASK 0x00000001
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_XPT_MCPB_SOFT_INIT_CLEAR_SHIFT 0
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_CLEAR_XPT_MCPB_SOFT_INIT_CLEAR_DEFAULT 0x00000000

/***************************************************************************
 *SUB_MODULE_SOFT_INIT_STATUS - Software initialization control for XPT sub-blocks
 ***************************************************************************/
/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_STATUS :: reserved0 [31:02] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_reserved0_MASK 0xfffffffc
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_reserved0_SHIFT 2

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_STATUS :: MEMDMA_MCPB_SOFT_INIT_STATUS [01:01] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_MEMDMA_MCPB_SOFT_INIT_STATUS_MASK 0x00000002
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_MEMDMA_MCPB_SOFT_INIT_STATUS_SHIFT 1
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_MEMDMA_MCPB_SOFT_INIT_STATUS_DEFAULT 0x00000000

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_STATUS :: XPT_MCPB_SOFT_INIT_STATUS [00:00] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_XPT_MCPB_SOFT_INIT_STATUS_MASK 0x00000001
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_XPT_MCPB_SOFT_INIT_STATUS_SHIFT 0
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_STATUS_XPT_MCPB_SOFT_INIT_STATUS_DEFAULT 0x00000000

/***************************************************************************
 *SUB_MODULE_SOFT_INIT_DO_MEM_INIT - Software initialization control for XPT sub-blocks
 ***************************************************************************/
/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_DO_MEM_INIT :: reserved0 [31:02] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_reserved0_MASK 0xfffffffc
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_reserved0_SHIFT 2

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_DO_MEM_INIT :: MEMDMA_MCPB_SOFT_INIT_DO_MEM_INIT [01:01] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_MEMDMA_MCPB_SOFT_INIT_DO_MEM_INIT_MASK 0x00000002
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_MEMDMA_MCPB_SOFT_INIT_DO_MEM_INIT_SHIFT 1
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_MEMDMA_MCPB_SOFT_INIT_DO_MEM_INIT_DEFAULT 0x00000001

/* XPT_BUS_IF :: SUB_MODULE_SOFT_INIT_DO_MEM_INIT :: XPT_MCPB_SOFT_INIT_DO_MEM_INIT [00:00] */
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_XPT_MCPB_SOFT_INIT_DO_MEM_INIT_MASK 0x00000001
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_XPT_MCPB_SOFT_INIT_DO_MEM_INIT_SHIFT 0
#define BCHP_XPT_BUS_IF_SUB_MODULE_SOFT_INIT_DO_MEM_INIT_XPT_MCPB_SOFT_INIT_DO_MEM_INIT_DEFAULT 0x00000001

/***************************************************************************
 *XMEMIF_WR_LC_DEBUG_REG - LCIF to XMEMIF Debug Registers
 ***************************************************************************/
/* XPT_BUS_IF :: XMEMIF_WR_LC_DEBUG_REG :: reserved0 [31:05] */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_reserved0_MASK      0xffffffe0
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_reserved0_SHIFT     5

/* XPT_BUS_IF :: XMEMIF_WR_LC_DEBUG_REG :: RSBUFF_WR_DEBUG_REG [04:04] */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RSBUFF_WR_DEBUG_REG_MASK 0x00000010
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RSBUFF_WR_DEBUG_REG_SHIFT 4
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RSBUFF_WR_DEBUG_REG_DEFAULT 0x00000000

/* XPT_BUS_IF :: XMEMIF_WR_LC_DEBUG_REG :: XCBUFF_WR_DEBUG_REG [03:03] */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_XCBUFF_WR_DEBUG_REG_MASK 0x00000008
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_XCBUFF_WR_DEBUG_REG_SHIFT 3
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_XCBUFF_WR_DEBUG_REG_DEFAULT 0x00000000

/* XPT_BUS_IF :: XMEMIF_WR_LC_DEBUG_REG :: MSG_DEBUG_REG [02:02] */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_MSG_DEBUG_REG_MASK  0x00000004
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_MSG_DEBUG_REG_SHIFT 2
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_MSG_DEBUG_REG_DEFAULT 0x00000000

/* XPT_BUS_IF :: XMEMIF_WR_LC_DEBUG_REG :: RAVE_DEBUG_REG [01:00] */
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RAVE_DEBUG_REG_MASK 0x00000003
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RAVE_DEBUG_REG_SHIFT 0
#define BCHP_XPT_BUS_IF_XMEMIF_WR_LC_DEBUG_REG_RAVE_DEBUG_REG_DEFAULT 0x00000000

/***************************************************************************
 *MAX_PLAYBACKS - Data Transport max number of playbacks supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_PLAYBACKS :: reserved0 [31:06] */
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS_reserved0_MASK               0xffffffc0
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS_reserved0_SHIFT              6

/* XPT_BUS_IF :: MAX_PLAYBACKS :: MAX_PLAYBACKS [05:00] */
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS_MAX_PLAYBACKS_MASK           0x0000003f
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS_MAX_PLAYBACKS_SHIFT          0
#define BCHP_XPT_BUS_IF_MAX_PLAYBACKS_MAX_PLAYBACKS_DEFAULT        0x00000010

/***************************************************************************
 *MAX_PID_PARSERS - Data Transport max number of PID parsers supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_PID_PARSERS :: reserved0 [31:06] */
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS_reserved0_MASK             0xffffffc0
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS_reserved0_SHIFT            6

/* XPT_BUS_IF :: MAX_PID_PARSERS :: MAX_PID_PARSERS [05:00] */
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS_MAX_PID_PARSERS_MASK       0x0000003f
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS_MAX_PID_PARSERS_SHIFT      0
#define BCHP_XPT_BUS_IF_MAX_PID_PARSERS_MAX_PID_PARSERS_DEFAULT    0x00000004

/***************************************************************************
 *MAX_PID_CHANNELS - Data Transport max number of PID channels supported excluding MEMDMA
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_PID_CHANNELS :: reserved0 [31:12] */
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS_reserved0_MASK            0xfffff000
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS_reserved0_SHIFT           12

/* XPT_BUS_IF :: MAX_PID_CHANNELS :: MAX_PID_CHANNELS [11:00] */
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS_MAX_PID_CHANNELS_MASK     0x00000fff
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS_MAX_PID_CHANNELS_SHIFT    0
#define BCHP_XPT_BUS_IF_MAX_PID_CHANNELS_MAX_PID_CHANNELS_DEFAULT  0x00000100

/***************************************************************************
 *MEMDMA_MAX_PID_CHANNELS - Data Transport max number of PID channels supported for MEMDMA
 ***************************************************************************/
/* XPT_BUS_IF :: MEMDMA_MAX_PID_CHANNELS :: reserved0 [31:12] */
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS_reserved0_MASK     0xfffff000
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS_reserved0_SHIFT    12

/* XPT_BUS_IF :: MEMDMA_MAX_PID_CHANNELS :: MAX_PID_CHANNELS [11:00] */
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS_MAX_PID_CHANNELS_MASK 0x00000fff
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS_MAX_PID_CHANNELS_SHIFT 0
#define BCHP_XPT_BUS_IF_MEMDMA_MAX_PID_CHANNELS_MAX_PID_CHANNELS_DEFAULT 0x00000100

/***************************************************************************
 *MAX_INPUT_BANDS - Data Transport max number of input bands supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_INPUT_BANDS :: reserved0 [31:05] */
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS_reserved0_MASK             0xffffffe0
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS_reserved0_SHIFT            5

/* XPT_BUS_IF :: MAX_INPUT_BANDS :: MAX_INPUT_BANDS [04:00] */
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS_MAX_INPUT_BANDS_MASK       0x0000001f
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS_MAX_INPUT_BANDS_SHIFT      0
#define BCHP_XPT_BUS_IF_MAX_INPUT_BANDS_MAX_INPUT_BANDS_DEFAULT    0x00000005

/***************************************************************************
 *MAX_PCRS - Data Transport max number of PCRs supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_PCRS :: reserved0 [31:04] */
#define BCHP_XPT_BUS_IF_MAX_PCRS_reserved0_MASK                    0xfffffff0
#define BCHP_XPT_BUS_IF_MAX_PCRS_reserved0_SHIFT                   4

/* XPT_BUS_IF :: MAX_PCRS :: MAX_PCRS [03:00] */
#define BCHP_XPT_BUS_IF_MAX_PCRS_MAX_PCRS_MASK                     0x0000000f
#define BCHP_XPT_BUS_IF_MAX_PCRS_MAX_PCRS_SHIFT                    0
#define BCHP_XPT_BUS_IF_MAX_PCRS_MAX_PCRS_DEFAULT                  0x00000002

/***************************************************************************
 *MAX_TPIT_CHANNELS - Data Transport max number of TPIT channels supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_TPIT_CHANNELS :: reserved0 [31:05] */
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS_reserved0_MASK           0xffffffe0
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS_reserved0_SHIFT          5

/* XPT_BUS_IF :: MAX_TPIT_CHANNELS :: MAX_TPIT_CHANNELS [04:00] */
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS_MAX_TPIT_CHANNELS_MASK   0x0000001f
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS_MAX_TPIT_CHANNELS_SHIFT  0
#define BCHP_XPT_BUS_IF_MAX_TPIT_CHANNELS_MAX_TPIT_CHANNELS_DEFAULT 0x00000008

/***************************************************************************
 *MAX_RAVE_CONTEXTS - Data Transport max number of RAVE contexts supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_RAVE_CONTEXTS :: reserved0 [31:08] */
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS_reserved0_MASK           0xffffff00
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS_reserved0_SHIFT          8

/* XPT_BUS_IF :: MAX_RAVE_CONTEXTS :: MAX_RAVE_CONTEXTS [07:00] */
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS_MAX_RAVE_CONTEXTS_MASK   0x000000ff
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS_MAX_RAVE_CONTEXTS_SHIFT  0
#define BCHP_XPT_BUS_IF_MAX_RAVE_CONTEXTS_MAX_RAVE_CONTEXTS_DEFAULT 0x00000010

/***************************************************************************
 *MAX_RMX_CHANNELS - Data Transport max number of RMX channels supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_RMX_CHANNELS :: reserved0 [31:04] */
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS_reserved0_MASK            0xfffffff0
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS_reserved0_SHIFT           4

/* XPT_BUS_IF :: MAX_RMX_CHANNELS :: MAX_RMX_CHANNELS [03:00] */
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS_MAX_RMX_CHANNELS_MASK     0x0000000f
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS_MAX_RMX_CHANNELS_SHIFT    0
#define BCHP_XPT_BUS_IF_MAX_RMX_CHANNELS_MAX_RMX_CHANNELS_DEFAULT  0x00000000

/***************************************************************************
 *MAX_MSG_BUFFERS - Data Transport max number of MSG buffers supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_MSG_BUFFERS :: reserved0 [31:09] */
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS_reserved0_MASK             0xfffffe00
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS_reserved0_SHIFT            9

/* XPT_BUS_IF :: MAX_MSG_BUFFERS :: MAX_MSG_BUFFERS [08:00] */
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS_MAX_MSG_BUFFERS_MASK       0x000001ff
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS_MAX_MSG_BUFFERS_SHIFT      0
#define BCHP_XPT_BUS_IF_MAX_MSG_BUFFERS_MAX_MSG_BUFFERS_DEFAULT    0x00000000

/***************************************************************************
 *MAX_SCDS - Data Transport max number of SCDs supported
 ***************************************************************************/
/* XPT_BUS_IF :: MAX_SCDS :: reserved0 [31:09] */
#define BCHP_XPT_BUS_IF_MAX_SCDS_reserved0_MASK                    0xfffffe00
#define BCHP_XPT_BUS_IF_MAX_SCDS_reserved0_SHIFT                   9

/* XPT_BUS_IF :: MAX_SCDS :: MAX_SCDS [08:00] */
#define BCHP_XPT_BUS_IF_MAX_SCDS_MAX_SCDS_MASK                     0x000001ff
#define BCHP_XPT_BUS_IF_MAX_SCDS_MAX_SCDS_SHIFT                    0
#define BCHP_XPT_BUS_IF_MAX_SCDS_MAX_SCDS_DEFAULT                  0x00000018

#endif /* #ifndef BCHP_XPT_BUS_IF_H__ */

/* End of File */
