/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Dec  1 06:46:28 2016
 *                 Full Compile MD5 Checksum  20bceb797972bbbfe6886f688dd76df1
 *                     (minus title and desc)
 *                 MD5 Checksum               60da5b9432d9a6239bf2f04b2e62b119
 *
 * lock_release:   r_1099
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_SYSTEMPORTLITE_1_RXCHK_H__
#define BCHP_SYSTEMPORTLITE_1_RXCHK_H__

/***************************************************************************
 *SYSTEMPORTLITE_1_RXCHK
 ***************************************************************************/
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL      0x01400300 /* [RW][32] RXCHK Control Register */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_0   0x01400304 /* [RW][32] RXCHK BRCM Tag Register for match0 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_1   0x01400308 /* [RW][32] RXCHK BRCM Tag Register for match1 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_2   0x0140030c /* [RW][32] RXCHK BRCM Tag Register for match2 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_3   0x01400310 /* [RW][32] RXCHK BRCM Tag Register for match3 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_4   0x01400314 /* [RW][32] RXCHK BRCM Tag Register for match4 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_5   0x01400318 /* [RW][32] RXCHK BRCM Tag Register for match5 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_6   0x0140031c /* [RW][32] RXCHK BRCM Tag Register for match6 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_7   0x01400320 /* [RW][32] RXCHK BRCM Tag Register for match7 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_0 0x01400324 /* [RW][32] RXCHK BRCM Tag Mask Register for match0 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_1 0x01400328 /* [RW][32] RXCHK BRCM Tag Mask Register for match1 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_2 0x0140032c /* [RW][32] RXCHK BRCM Tag Mask Register for match2 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_3 0x01400330 /* [RW][32] RXCHK BRCM Tag Mask Register for match3 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_4 0x01400334 /* [RW][32] RXCHK BRCM Tag Mask Register for match4 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_5 0x01400338 /* [RW][32] RXCHK BRCM Tag Mask Register for match5 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_6 0x0140033c /* [RW][32] RXCHK BRCM Tag Mask Register for match6 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_7 0x01400340 /* [RW][32] RXCHK BRCM Tag Mask Register for match7 */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS 0x01400344 /* [RW][32] RXCHK BRCM Tag Match Status Register */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE    0x01400348 /* [RW][32] RXCHK Ethertype Register */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BAD_CHECKSUM_PACKET_DISCARD_COUNTER 0x0140034c /* [RW][32] RXCHK Bad Checksum Packet Discard Counter */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_OTHER_PACKET_DISCARD_COUNTER 0x01400350 /* [RW][32] RXCHK Other Packet Discard Counter */

/***************************************************************************
 *CONTROL - RXCHK Control Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: reserved0 [31:25] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_reserved0_MASK         0xfe000000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_reserved0_SHIFT        25

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: USE_IPV6DATALEN [24:24] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV6DATALEN_MASK   0x01000000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV6DATALEN_SHIFT  24
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV6DATALEN_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: USE_IPV4DATALEN [23:23] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV4DATALEN_MASK   0x00800000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV4DATALEN_SHIFT  23
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_USE_IPV4DATALEN_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: PARSE_AUTH [22:22] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_AUTH_MASK        0x00400000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_AUTH_SHIFT       22
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_AUTH_DEFAULT     0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: MAC_RX_ERR_ACT [21:21] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_MAC_RX_ERR_ACT_MASK    0x00200000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_MAC_RX_ERR_ACT_SHIFT   21
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_MAC_RX_ERR_ACT_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: L3_HDR_ERR_ACT [20:20] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L3_HDR_ERR_ACT_MASK    0x00100000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L3_HDR_ERR_ACT_SHIFT   20
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L3_HDR_ERR_ACT_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: L2_HDR_ERR_ACT [19:19] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L2_HDR_ERR_ACT_MASK    0x00080000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L2_HDR_ERR_ACT_SHIFT   19
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_L2_HDR_ERR_ACT_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: UNEXPECTED_ETHTYPE_ACT [18:18] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_UNEXPECTED_ETHTYPE_ACT_MASK 0x00040000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_UNEXPECTED_ETHTYPE_ACT_SHIFT 18
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_UNEXPECTED_ETHTYPE_ACT_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: IPV6_DUP_EXTHDR_ACT [17:17] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_ACT_MASK 0x00020000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_ACT_SHIFT 17
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_ACT_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: IPV6_DUP_EXTHDR_EN [16:16] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_EN_MASK 0x00010000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_EN_SHIFT 16
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_IPV6_DUP_EXTHDR_EN_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: INCOMPLETE_PACKET_ACT [15:15] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_INCOMPLETE_PACKET_ACT_MASK 0x00008000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_INCOMPLETE_PACKET_ACT_SHIFT 15
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_INCOMPLETE_PACKET_ACT_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: STRUCT_VIOL_ACT [14:14] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_ACT_MASK   0x00004000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_ACT_SHIFT  14
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_ACT_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: STRUCT_VIOL_EN [13:13] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_EN_MASK    0x00002000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_EN_SHIFT   13
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_STRUCT_VIOL_EN_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: PARSE_TUNNELED_IP [12:12] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_TUNNELED_IP_MASK 0x00001000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_TUNNELED_IP_SHIFT 12
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_PARSE_TUNNELED_IP_DEFAULT 0x00000001

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: BRCM_TAG_MATCH_EN [11:04] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_MATCH_EN_MASK 0x00000ff0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_MATCH_EN_SHIFT 4
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_MATCH_EN_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: BRCM_TAG_EN [03:03] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_EN_MASK       0x00000008
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_EN_SHIFT      3
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BRCM_TAG_EN_DEFAULT    0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: BAD_CHKSUM_DISCARD_EN [02:02] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BAD_CHKSUM_DISCARD_EN_MASK 0x00000004
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BAD_CHKSUM_DISCARD_EN_SHIFT 2
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_BAD_CHKSUM_DISCARD_EN_DEFAULT 0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: SKIP_FCS [01:01] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_SKIP_FCS_MASK          0x00000002
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_SKIP_FCS_SHIFT         1
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_SKIP_FCS_DEFAULT       0x00000000

/* SYSTEMPORTLITE_1_RXCHK :: CONTROL :: RCHK_EN [00:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_RCHK_EN_MASK           0x00000001
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_RCHK_EN_SHIFT          0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_CONTROL_RCHK_EN_DEFAULT        0x00000000

/***************************************************************************
 *BRCM_TAG_0 - RXCHK BRCM Tag Register for match0
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_0 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_0_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_0_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_0_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_1 - RXCHK BRCM Tag Register for match1
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_1 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_1_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_1_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_1_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_2 - RXCHK BRCM Tag Register for match2
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_2 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_2_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_2_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_2_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_3 - RXCHK BRCM Tag Register for match3
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_3 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_3_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_3_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_3_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_4 - RXCHK BRCM Tag Register for match4
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_4 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_4_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_4_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_4_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_5 - RXCHK BRCM Tag Register for match5
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_5 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_5_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_5_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_5_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_6 - RXCHK BRCM Tag Register for match6
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_6 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_6_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_6_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_6_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_7 - RXCHK BRCM Tag Register for match7
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_7 :: BRCM_TAG [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_7_BRCM_TAG_MASK       0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_7_BRCM_TAG_SHIFT      0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_7_BRCM_TAG_DEFAULT    0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_0 - RXCHK BRCM Tag Mask Register for match0
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_0 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_0_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_0_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_0_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_1 - RXCHK BRCM Tag Mask Register for match1
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_1 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_1_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_1_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_1_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_2 - RXCHK BRCM Tag Mask Register for match2
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_2 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_2_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_2_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_2_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_3 - RXCHK BRCM Tag Mask Register for match3
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_3 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_3_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_3_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_3_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_4 - RXCHK BRCM Tag Mask Register for match4
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_4 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_4_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_4_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_4_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_5 - RXCHK BRCM Tag Mask Register for match5
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_5 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_5_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_5_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_5_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_6 - RXCHK BRCM Tag Mask Register for match6
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_6 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_6_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_6_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_6_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MASK_7 - RXCHK BRCM Tag Mask Register for match7
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MASK_7 :: BRCM_TAG_MASK [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_7_BRCM_TAG_MASK_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_7_BRCM_TAG_MASK_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MASK_7_BRCM_TAG_MASK_DEFAULT 0x00000000

/***************************************************************************
 *BRCM_TAG_MATCH_STATUS - RXCHK BRCM Tag Match Status Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MATCH_STATUS :: reserved0 [31:08] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS_reserved0_MASK 0xffffff00
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS_reserved0_SHIFT 8

/* SYSTEMPORTLITE_1_RXCHK :: BRCM_TAG_MATCH_STATUS :: BRCM_TAG_MATCH [07:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS_BRCM_TAG_MATCH_MASK 0x000000ff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS_BRCM_TAG_MATCH_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BRCM_TAG_MATCH_STATUS_BRCM_TAG_MATCH_DEFAULT 0x00000000

/***************************************************************************
 *ETHERTYPE - RXCHK Ethertype Register
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: ETHERTYPE :: OUTER_ETH_TYPE [31:16] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_OUTER_ETH_TYPE_MASK  0xffff0000
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_OUTER_ETH_TYPE_SHIFT 16
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_OUTER_ETH_TYPE_DEFAULT 0x000088a8

/* SYSTEMPORTLITE_1_RXCHK :: ETHERTYPE :: INNER_ETH_TYPE [15:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_INNER_ETH_TYPE_MASK  0x0000ffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_INNER_ETH_TYPE_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_ETHERTYPE_INNER_ETH_TYPE_DEFAULT 0x00008100

/***************************************************************************
 *BAD_CHECKSUM_PACKET_DISCARD_COUNTER - RXCHK Bad Checksum Packet Discard Counter
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: BAD_CHECKSUM_PACKET_DISCARD_COUNTER :: PKT_CNT [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BAD_CHECKSUM_PACKET_DISCARD_COUNTER_PKT_CNT_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BAD_CHECKSUM_PACKET_DISCARD_COUNTER_PKT_CNT_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_BAD_CHECKSUM_PACKET_DISCARD_COUNTER_PKT_CNT_DEFAULT 0x00000000

/***************************************************************************
 *OTHER_PACKET_DISCARD_COUNTER - RXCHK Other Packet Discard Counter
 ***************************************************************************/
/* SYSTEMPORTLITE_1_RXCHK :: OTHER_PACKET_DISCARD_COUNTER :: PKT_CNT [31:00] */
#define BCHP_SYSTEMPORTLITE_1_RXCHK_OTHER_PACKET_DISCARD_COUNTER_PKT_CNT_MASK 0xffffffff
#define BCHP_SYSTEMPORTLITE_1_RXCHK_OTHER_PACKET_DISCARD_COUNTER_PKT_CNT_SHIFT 0
#define BCHP_SYSTEMPORTLITE_1_RXCHK_OTHER_PACKET_DISCARD_COUNTER_PKT_CNT_DEFAULT 0x00000000

#endif /* #ifndef BCHP_SYSTEMPORTLITE_1_RXCHK_H__ */

/* End of File */
