/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Dec  1 06:47:05 2016
 *                 Full Compile MD5 Checksum  20bceb797972bbbfe6886f688dd76df1
 *                     (minus title and desc)
 *                 MD5 Checksum               60da5b9432d9a6239bf2f04b2e62b119
 *
 * lock_release:   r_1099
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_MEMC_L2_1_2_H__
#define BCHP_MEMC_L2_1_2_H__

/***************************************************************************
 *MEMC_L2_1_2 - MEMSYS L2_2 Interrupt Controller Registers
 ***************************************************************************/
#define BCHP_MEMC_L2_1_2_CPU_STATUS              0x01b03400 /* [RO][32] CPU interrupt Status Register */
#define BCHP_MEMC_L2_1_2_CPU_SET                 0x01b03404 /* [WO][32] CPU interrupt Set Register */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR               0x01b03408 /* [WO][32] CPU interrupt Clear Register */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS         0x01b0340c /* [RO][32] CPU interrupt Mask Status Register */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET            0x01b03410 /* [WO][32] CPU interrupt Mask Set Register */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR          0x01b03414 /* [WO][32] CPU interrupt Mask Clear Register */
#define BCHP_MEMC_L2_1_2_PCI_STATUS              0x01b03418 /* [RO][32] PCI interrupt Status Register */
#define BCHP_MEMC_L2_1_2_PCI_SET                 0x01b0341c /* [WO][32] PCI interrupt Set Register */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR               0x01b03420 /* [WO][32] PCI interrupt Clear Register */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS         0x01b03424 /* [RO][32] PCI interrupt Mask Status Register */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET            0x01b03428 /* [WO][32] PCI interrupt Mask Set Register */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR          0x01b0342c /* [WO][32] PCI interrupt Mask Clear Register */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS             0x01b03430 /* [RO][32] SCPU interrupt Status Register */
#define BCHP_MEMC_L2_1_2_SCPU_SET                0x01b03434 /* [WO][32] SCPU interrupt Set Register */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR              0x01b03438 /* [WO][32] SCPU interrupt Clear Register */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS        0x01b0343c /* [RO][32] SCPU interrupt Mask Status Register */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET           0x01b03440 /* [WO][32] SCPU interrupt Mask Set Register */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR         0x01b03444 /* [WO][32] SCPU interrupt Mask Clear Register */

/***************************************************************************
 *CPU_STATUS - CPU interrupt Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_STATUS :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved0_MASK                 0xff800000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved0_SHIFT                23

/* MEMC_L2_1_2 :: CPU_STATUS :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_V3_SCRAM_MASK_FAULT_MASK       0x00400000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_V3_SCRAM_MASK_FAULT_SHIFT      22
#define BCHP_MEMC_L2_1_2_CPU_STATUS_V3_SCRAM_MASK_FAULT_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DTU_INTEGRITY_ERR_INTR_MASK    0x00200000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT   21
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_RGR_BRIDGE_INTR_MASK           0x00100000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_RGR_BRIDGE_INTR_SHIFT          20
#define BCHP_MEMC_L2_1_2_CPU_STATUS_RGR_BRIDGE_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DFI_ERROR_MASK                 0x00080000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DFI_ERROR_SHIFT                19
#define BCHP_MEMC_L2_1_2_CPU_STATUS_DFI_ERROR_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SM_TIMEOUT_INTR_MASK           0x00040000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SM_TIMEOUT_INTR_SHIFT          18
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SM_TIMEOUT_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_WRDATA_ERR_MASK            0x00020000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_WRDATA_ERR_SHIFT           17
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_WRDATA_ERR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_TRANSID_MISMATCH_MASK      0x00010000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_TRANSID_MISMATCH_SHIFT     16
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT   0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SCB_VIOL_MASK                  0x00008000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SCB_VIOL_SHIFT                 15
#define BCHP_MEMC_L2_1_2_CPU_STATUS_SCB_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved1_MASK                 0x00006000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved1_SHIFT                13

/* MEMC_L2_1_2 :: CPU_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_AXI_VIOL_MASK                  0x00001000
#define BCHP_MEMC_L2_1_2_CPU_STATUS_AXI_VIOL_SHIFT                 12
#define BCHP_MEMC_L2_1_2_CPU_STATUS_AXI_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved2_MASK                 0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved2_SHIFT                10

/* MEMC_L2_1_2 :: CPU_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_MCP_VIOL_MASK                  0x00000300
#define BCHP_MEMC_L2_1_2_CPU_STATUS_MCP_VIOL_SHIFT                 8
#define BCHP_MEMC_L2_1_2_CPU_STATUS_MCP_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: CPU_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved3_MASK                 0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_STATUS_reserved3_SHIFT                4

/* MEMC_L2_1_2 :: CPU_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_STATUS_PFRI_VIOL_MASK                 0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_STATUS_PFRI_VIOL_SHIFT                0
#define BCHP_MEMC_L2_1_2_CPU_STATUS_PFRI_VIOL_DEFAULT              0x00000000

/***************************************************************************
 *CPU_SET - CPU interrupt Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_SET :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved0_MASK                    0xff800000
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved0_SHIFT                   23

/* MEMC_L2_1_2 :: CPU_SET :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_CPU_SET_V3_SCRAM_MASK_FAULT_MASK          0x00400000
#define BCHP_MEMC_L2_1_2_CPU_SET_V3_SCRAM_MASK_FAULT_SHIFT         22
#define BCHP_MEMC_L2_1_2_CPU_SET_V3_SCRAM_MASK_FAULT_DEFAULT       0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_SET_DTU_INTEGRITY_ERR_INTR_MASK       0x00200000
#define BCHP_MEMC_L2_1_2_CPU_SET_DTU_INTEGRITY_ERR_INTR_SHIFT      21
#define BCHP_MEMC_L2_1_2_CPU_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_SET_RGR_BRIDGE_INTR_MASK              0x00100000
#define BCHP_MEMC_L2_1_2_CPU_SET_RGR_BRIDGE_INTR_SHIFT             20
#define BCHP_MEMC_L2_1_2_CPU_SET_RGR_BRIDGE_INTR_DEFAULT           0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_SET_DFI_ERROR_MASK                    0x00080000
#define BCHP_MEMC_L2_1_2_CPU_SET_DFI_ERROR_SHIFT                   19
#define BCHP_MEMC_L2_1_2_CPU_SET_DFI_ERROR_DEFAULT                 0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_SET_SM_TIMEOUT_INTR_MASK              0x00040000
#define BCHP_MEMC_L2_1_2_CPU_SET_SM_TIMEOUT_INTR_SHIFT             18
#define BCHP_MEMC_L2_1_2_CPU_SET_SM_TIMEOUT_INTR_DEFAULT           0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_WRDATA_ERR_MASK               0x00020000
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_WRDATA_ERR_SHIFT              17
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_WRDATA_ERR_DEFAULT            0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_TRANSID_MISMATCH_MASK         0x00010000
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_TRANSID_MISMATCH_SHIFT        16
#define BCHP_MEMC_L2_1_2_CPU_SET_SEQ_TRANSID_MISMATCH_DEFAULT      0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_SET_SCB_VIOL_MASK                     0x00008000
#define BCHP_MEMC_L2_1_2_CPU_SET_SCB_VIOL_SHIFT                    15
#define BCHP_MEMC_L2_1_2_CPU_SET_SCB_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved1_MASK                    0x00006000
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved1_SHIFT                   13

/* MEMC_L2_1_2 :: CPU_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_SET_AXI_VIOL_MASK                     0x00001000
#define BCHP_MEMC_L2_1_2_CPU_SET_AXI_VIOL_SHIFT                    12
#define BCHP_MEMC_L2_1_2_CPU_SET_AXI_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved2_MASK                    0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved2_SHIFT                   10

/* MEMC_L2_1_2 :: CPU_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_SET_MCP_VIOL_MASK                     0x00000300
#define BCHP_MEMC_L2_1_2_CPU_SET_MCP_VIOL_SHIFT                    8
#define BCHP_MEMC_L2_1_2_CPU_SET_MCP_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: CPU_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved3_MASK                    0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_SET_reserved3_SHIFT                   4

/* MEMC_L2_1_2 :: CPU_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_SET_PFRI_VIOL_MASK                    0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_SET_PFRI_VIOL_SHIFT                   0
#define BCHP_MEMC_L2_1_2_CPU_SET_PFRI_VIOL_DEFAULT                 0x00000000

/***************************************************************************
 *CPU_CLEAR - CPU interrupt Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_CLEAR :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved0_MASK                  0xff800000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved0_SHIFT                 23

/* MEMC_L2_1_2 :: CPU_CLEAR :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_V3_SCRAM_MASK_FAULT_MASK        0x00400000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_V3_SCRAM_MASK_FAULT_SHIFT       22
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_V3_SCRAM_MASK_FAULT_DEFAULT     0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK     0x00200000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT    21
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT  0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_RGR_BRIDGE_INTR_MASK            0x00100000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_RGR_BRIDGE_INTR_SHIFT           20
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_RGR_BRIDGE_INTR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DFI_ERROR_MASK                  0x00080000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DFI_ERROR_SHIFT                 19
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_DFI_ERROR_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SM_TIMEOUT_INTR_MASK            0x00040000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SM_TIMEOUT_INTR_SHIFT           18
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SM_TIMEOUT_INTR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_WRDATA_ERR_MASK             0x00020000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_WRDATA_ERR_SHIFT            17
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_WRDATA_ERR_DEFAULT          0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_TRANSID_MISMATCH_MASK       0x00010000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT      16
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SCB_VIOL_MASK                   0x00008000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SCB_VIOL_SHIFT                  15
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_SCB_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved1_MASK                  0x00006000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved1_SHIFT                 13

/* MEMC_L2_1_2 :: CPU_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_AXI_VIOL_MASK                   0x00001000
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_AXI_VIOL_SHIFT                  12
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_AXI_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved2_MASK                  0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved2_SHIFT                 10

/* MEMC_L2_1_2 :: CPU_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_MCP_VIOL_MASK                   0x00000300
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_MCP_VIOL_SHIFT                  8
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_MCP_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: CPU_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved3_MASK                  0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_reserved3_SHIFT                 4

/* MEMC_L2_1_2 :: CPU_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_PFRI_VIOL_MASK                  0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_PFRI_VIOL_SHIFT                 0
#define BCHP_MEMC_L2_1_2_CPU_CLEAR_PFRI_VIOL_DEFAULT               0x00000000

/***************************************************************************
 *CPU_MASK_STATUS - CPU interrupt Mask Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved0_MASK            0xffc00000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved0_SHIFT           22

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_RGR_BRIDGE_INTR_MASK      0x00100000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_RGR_BRIDGE_INTR_SHIFT     20
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_RGR_BRIDGE_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DFI_ERROR_MASK            0x00080000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DFI_ERROR_SHIFT           19
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_DFI_ERROR_DEFAULT         0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SM_TIMEOUT_INTR_MASK      0x00040000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SM_TIMEOUT_INTR_SHIFT     18
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SM_TIMEOUT_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_WRDATA_ERR_MASK       0x00020000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_WRDATA_ERR_SHIFT      17
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_WRDATA_ERR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_MASK 0x00010000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SCB_VIOL_MASK             0x00008000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SCB_VIOL_SHIFT            15
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_SCB_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved1_MASK            0x00006000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved1_SHIFT           13

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_AXI_VIOL_MASK             0x00001000
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_AXI_VIOL_SHIFT            12
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_AXI_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved2_MASK            0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved2_SHIFT           10

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_MCP_VIOL_MASK             0x00000300
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_MCP_VIOL_SHIFT            8
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_MCP_VIOL_DEFAULT          0x00000003

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved3_MASK            0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_reserved3_SHIFT           4

/* MEMC_L2_1_2 :: CPU_MASK_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_PFRI_VIOL_MASK            0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_PFRI_VIOL_SHIFT           0
#define BCHP_MEMC_L2_1_2_CPU_MASK_STATUS_PFRI_VIOL_DEFAULT         0x0000000f

/***************************************************************************
 *CPU_MASK_SET - CPU interrupt Mask Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_MASK_SET :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved0_MASK               0xffc00000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved0_SHIFT              22

/* MEMC_L2_1_2 :: CPU_MASK_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_MASK  0x00200000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_RGR_BRIDGE_INTR_MASK         0x00100000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_RGR_BRIDGE_INTR_SHIFT        20
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_RGR_BRIDGE_INTR_DEFAULT      0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DFI_ERROR_MASK               0x00080000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DFI_ERROR_SHIFT              19
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_DFI_ERROR_DEFAULT            0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SM_TIMEOUT_INTR_MASK         0x00040000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SM_TIMEOUT_INTR_SHIFT        18
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SM_TIMEOUT_INTR_DEFAULT      0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_WRDATA_ERR_MASK          0x00020000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_WRDATA_ERR_SHIFT         17
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_WRDATA_ERR_DEFAULT       0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_TRANSID_MISMATCH_MASK    0x00010000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_TRANSID_MISMATCH_SHIFT   16
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SCB_VIOL_MASK                0x00008000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SCB_VIOL_SHIFT               15
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_SCB_VIOL_DEFAULT             0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved1_MASK               0x00006000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved1_SHIFT              13

/* MEMC_L2_1_2 :: CPU_MASK_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_AXI_VIOL_MASK                0x00001000
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_AXI_VIOL_SHIFT               12
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_AXI_VIOL_DEFAULT             0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved2_MASK               0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved2_SHIFT              10

/* MEMC_L2_1_2 :: CPU_MASK_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_MCP_VIOL_MASK                0x00000300
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_MCP_VIOL_SHIFT               8
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_MCP_VIOL_DEFAULT             0x00000003

/* MEMC_L2_1_2 :: CPU_MASK_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved3_MASK               0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_reserved3_SHIFT              4

/* MEMC_L2_1_2 :: CPU_MASK_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_PFRI_VIOL_MASK               0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_PFRI_VIOL_SHIFT              0
#define BCHP_MEMC_L2_1_2_CPU_MASK_SET_PFRI_VIOL_DEFAULT            0x0000000f

/***************************************************************************
 *CPU_MASK_CLEAR - CPU interrupt Mask Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved0_MASK             0xffc00000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved0_SHIFT            22

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_RGR_BRIDGE_INTR_MASK       0x00100000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_RGR_BRIDGE_INTR_SHIFT      20
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_RGR_BRIDGE_INTR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DFI_ERROR_MASK             0x00080000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DFI_ERROR_SHIFT            19
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_DFI_ERROR_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SM_TIMEOUT_INTR_MASK       0x00040000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SM_TIMEOUT_INTR_SHIFT      18
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SM_TIMEOUT_INTR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_WRDATA_ERR_MASK        0x00020000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_WRDATA_ERR_SHIFT       17
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_WRDATA_ERR_DEFAULT     0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_MASK  0x00010000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SCB_VIOL_MASK              0x00008000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SCB_VIOL_SHIFT             15
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_SCB_VIOL_DEFAULT           0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved1_MASK             0x00006000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved1_SHIFT            13

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_AXI_VIOL_MASK              0x00001000
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_AXI_VIOL_SHIFT             12
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_AXI_VIOL_DEFAULT           0x00000001

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved2_MASK             0x00000c00
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved2_SHIFT            10

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_MCP_VIOL_MASK              0x00000300
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_MCP_VIOL_SHIFT             8
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_MCP_VIOL_DEFAULT           0x00000003

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved3_MASK             0x000000f0
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_reserved3_SHIFT            4

/* MEMC_L2_1_2 :: CPU_MASK_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_PFRI_VIOL_MASK             0x0000000f
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_PFRI_VIOL_SHIFT            0
#define BCHP_MEMC_L2_1_2_CPU_MASK_CLEAR_PFRI_VIOL_DEFAULT          0x0000000f

/***************************************************************************
 *PCI_STATUS - PCI interrupt Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_STATUS :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved0_MASK                 0xff800000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved0_SHIFT                23

/* MEMC_L2_1_2 :: PCI_STATUS :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_V3_SCRAM_MASK_FAULT_MASK       0x00400000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_V3_SCRAM_MASK_FAULT_SHIFT      22
#define BCHP_MEMC_L2_1_2_PCI_STATUS_V3_SCRAM_MASK_FAULT_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DTU_INTEGRITY_ERR_INTR_MASK    0x00200000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT   21
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_RGR_BRIDGE_INTR_MASK           0x00100000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_RGR_BRIDGE_INTR_SHIFT          20
#define BCHP_MEMC_L2_1_2_PCI_STATUS_RGR_BRIDGE_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DFI_ERROR_MASK                 0x00080000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DFI_ERROR_SHIFT                19
#define BCHP_MEMC_L2_1_2_PCI_STATUS_DFI_ERROR_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SM_TIMEOUT_INTR_MASK           0x00040000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SM_TIMEOUT_INTR_SHIFT          18
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SM_TIMEOUT_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_WRDATA_ERR_MASK            0x00020000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_WRDATA_ERR_SHIFT           17
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_WRDATA_ERR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_TRANSID_MISMATCH_MASK      0x00010000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_TRANSID_MISMATCH_SHIFT     16
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT   0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SCB_VIOL_MASK                  0x00008000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SCB_VIOL_SHIFT                 15
#define BCHP_MEMC_L2_1_2_PCI_STATUS_SCB_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved1_MASK                 0x00006000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved1_SHIFT                13

/* MEMC_L2_1_2 :: PCI_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_AXI_VIOL_MASK                  0x00001000
#define BCHP_MEMC_L2_1_2_PCI_STATUS_AXI_VIOL_SHIFT                 12
#define BCHP_MEMC_L2_1_2_PCI_STATUS_AXI_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved2_MASK                 0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved2_SHIFT                10

/* MEMC_L2_1_2 :: PCI_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_MCP_VIOL_MASK                  0x00000300
#define BCHP_MEMC_L2_1_2_PCI_STATUS_MCP_VIOL_SHIFT                 8
#define BCHP_MEMC_L2_1_2_PCI_STATUS_MCP_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: PCI_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved3_MASK                 0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_STATUS_reserved3_SHIFT                4

/* MEMC_L2_1_2 :: PCI_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_STATUS_PFRI_VIOL_MASK                 0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_STATUS_PFRI_VIOL_SHIFT                0
#define BCHP_MEMC_L2_1_2_PCI_STATUS_PFRI_VIOL_DEFAULT              0x00000000

/***************************************************************************
 *PCI_SET - PCI interrupt Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_SET :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved0_MASK                    0xff800000
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved0_SHIFT                   23

/* MEMC_L2_1_2 :: PCI_SET :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_PCI_SET_V3_SCRAM_MASK_FAULT_MASK          0x00400000
#define BCHP_MEMC_L2_1_2_PCI_SET_V3_SCRAM_MASK_FAULT_SHIFT         22
#define BCHP_MEMC_L2_1_2_PCI_SET_V3_SCRAM_MASK_FAULT_DEFAULT       0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_SET_DTU_INTEGRITY_ERR_INTR_MASK       0x00200000
#define BCHP_MEMC_L2_1_2_PCI_SET_DTU_INTEGRITY_ERR_INTR_SHIFT      21
#define BCHP_MEMC_L2_1_2_PCI_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_SET_RGR_BRIDGE_INTR_MASK              0x00100000
#define BCHP_MEMC_L2_1_2_PCI_SET_RGR_BRIDGE_INTR_SHIFT             20
#define BCHP_MEMC_L2_1_2_PCI_SET_RGR_BRIDGE_INTR_DEFAULT           0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_SET_DFI_ERROR_MASK                    0x00080000
#define BCHP_MEMC_L2_1_2_PCI_SET_DFI_ERROR_SHIFT                   19
#define BCHP_MEMC_L2_1_2_PCI_SET_DFI_ERROR_DEFAULT                 0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_SET_SM_TIMEOUT_INTR_MASK              0x00040000
#define BCHP_MEMC_L2_1_2_PCI_SET_SM_TIMEOUT_INTR_SHIFT             18
#define BCHP_MEMC_L2_1_2_PCI_SET_SM_TIMEOUT_INTR_DEFAULT           0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_WRDATA_ERR_MASK               0x00020000
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_WRDATA_ERR_SHIFT              17
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_WRDATA_ERR_DEFAULT            0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_TRANSID_MISMATCH_MASK         0x00010000
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_TRANSID_MISMATCH_SHIFT        16
#define BCHP_MEMC_L2_1_2_PCI_SET_SEQ_TRANSID_MISMATCH_DEFAULT      0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_SET_SCB_VIOL_MASK                     0x00008000
#define BCHP_MEMC_L2_1_2_PCI_SET_SCB_VIOL_SHIFT                    15
#define BCHP_MEMC_L2_1_2_PCI_SET_SCB_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved1_MASK                    0x00006000
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved1_SHIFT                   13

/* MEMC_L2_1_2 :: PCI_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_SET_AXI_VIOL_MASK                     0x00001000
#define BCHP_MEMC_L2_1_2_PCI_SET_AXI_VIOL_SHIFT                    12
#define BCHP_MEMC_L2_1_2_PCI_SET_AXI_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved2_MASK                    0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved2_SHIFT                   10

/* MEMC_L2_1_2 :: PCI_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_SET_MCP_VIOL_MASK                     0x00000300
#define BCHP_MEMC_L2_1_2_PCI_SET_MCP_VIOL_SHIFT                    8
#define BCHP_MEMC_L2_1_2_PCI_SET_MCP_VIOL_DEFAULT                  0x00000000

/* MEMC_L2_1_2 :: PCI_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved3_MASK                    0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_SET_reserved3_SHIFT                   4

/* MEMC_L2_1_2 :: PCI_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_SET_PFRI_VIOL_MASK                    0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_SET_PFRI_VIOL_SHIFT                   0
#define BCHP_MEMC_L2_1_2_PCI_SET_PFRI_VIOL_DEFAULT                 0x00000000

/***************************************************************************
 *PCI_CLEAR - PCI interrupt Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_CLEAR :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved0_MASK                  0xff800000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved0_SHIFT                 23

/* MEMC_L2_1_2 :: PCI_CLEAR :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_V3_SCRAM_MASK_FAULT_MASK        0x00400000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_V3_SCRAM_MASK_FAULT_SHIFT       22
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_V3_SCRAM_MASK_FAULT_DEFAULT     0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK     0x00200000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT    21
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT  0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_RGR_BRIDGE_INTR_MASK            0x00100000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_RGR_BRIDGE_INTR_SHIFT           20
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_RGR_BRIDGE_INTR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DFI_ERROR_MASK                  0x00080000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DFI_ERROR_SHIFT                 19
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_DFI_ERROR_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SM_TIMEOUT_INTR_MASK            0x00040000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SM_TIMEOUT_INTR_SHIFT           18
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SM_TIMEOUT_INTR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_WRDATA_ERR_MASK             0x00020000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_WRDATA_ERR_SHIFT            17
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_WRDATA_ERR_DEFAULT          0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_TRANSID_MISMATCH_MASK       0x00010000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT      16
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SCB_VIOL_MASK                   0x00008000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SCB_VIOL_SHIFT                  15
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_SCB_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved1_MASK                  0x00006000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved1_SHIFT                 13

/* MEMC_L2_1_2 :: PCI_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_AXI_VIOL_MASK                   0x00001000
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_AXI_VIOL_SHIFT                  12
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_AXI_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved2_MASK                  0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved2_SHIFT                 10

/* MEMC_L2_1_2 :: PCI_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_MCP_VIOL_MASK                   0x00000300
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_MCP_VIOL_SHIFT                  8
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_MCP_VIOL_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: PCI_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved3_MASK                  0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_reserved3_SHIFT                 4

/* MEMC_L2_1_2 :: PCI_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_PFRI_VIOL_MASK                  0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_PFRI_VIOL_SHIFT                 0
#define BCHP_MEMC_L2_1_2_PCI_CLEAR_PFRI_VIOL_DEFAULT               0x00000000

/***************************************************************************
 *PCI_MASK_STATUS - PCI interrupt Mask Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved0_MASK            0xffc00000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved0_SHIFT           22

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_RGR_BRIDGE_INTR_MASK      0x00100000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_RGR_BRIDGE_INTR_SHIFT     20
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_RGR_BRIDGE_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DFI_ERROR_MASK            0x00080000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DFI_ERROR_SHIFT           19
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_DFI_ERROR_DEFAULT         0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SM_TIMEOUT_INTR_MASK      0x00040000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SM_TIMEOUT_INTR_SHIFT     18
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SM_TIMEOUT_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_WRDATA_ERR_MASK       0x00020000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_WRDATA_ERR_SHIFT      17
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_WRDATA_ERR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_TRANSID_MISMATCH_MASK 0x00010000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SCB_VIOL_MASK             0x00008000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SCB_VIOL_SHIFT            15
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_SCB_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved1_MASK            0x00006000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved1_SHIFT           13

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_AXI_VIOL_MASK             0x00001000
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_AXI_VIOL_SHIFT            12
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_AXI_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved2_MASK            0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved2_SHIFT           10

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_MCP_VIOL_MASK             0x00000300
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_MCP_VIOL_SHIFT            8
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_MCP_VIOL_DEFAULT          0x00000003

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved3_MASK            0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_reserved3_SHIFT           4

/* MEMC_L2_1_2 :: PCI_MASK_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_PFRI_VIOL_MASK            0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_PFRI_VIOL_SHIFT           0
#define BCHP_MEMC_L2_1_2_PCI_MASK_STATUS_PFRI_VIOL_DEFAULT         0x0000000f

/***************************************************************************
 *PCI_MASK_SET - PCI interrupt Mask Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_MASK_SET :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved0_MASK               0xffc00000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved0_SHIFT              22

/* MEMC_L2_1_2 :: PCI_MASK_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DTU_INTEGRITY_ERR_INTR_MASK  0x00200000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_RGR_BRIDGE_INTR_MASK         0x00100000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_RGR_BRIDGE_INTR_SHIFT        20
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_RGR_BRIDGE_INTR_DEFAULT      0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DFI_ERROR_MASK               0x00080000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DFI_ERROR_SHIFT              19
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_DFI_ERROR_DEFAULT            0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SM_TIMEOUT_INTR_MASK         0x00040000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SM_TIMEOUT_INTR_SHIFT        18
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SM_TIMEOUT_INTR_DEFAULT      0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_WRDATA_ERR_MASK          0x00020000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_WRDATA_ERR_SHIFT         17
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_WRDATA_ERR_DEFAULT       0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_TRANSID_MISMATCH_MASK    0x00010000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_TRANSID_MISMATCH_SHIFT   16
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SCB_VIOL_MASK                0x00008000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SCB_VIOL_SHIFT               15
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_SCB_VIOL_DEFAULT             0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved1_MASK               0x00006000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved1_SHIFT              13

/* MEMC_L2_1_2 :: PCI_MASK_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_AXI_VIOL_MASK                0x00001000
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_AXI_VIOL_SHIFT               12
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_AXI_VIOL_DEFAULT             0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved2_MASK               0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved2_SHIFT              10

/* MEMC_L2_1_2 :: PCI_MASK_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_MCP_VIOL_MASK                0x00000300
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_MCP_VIOL_SHIFT               8
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_MCP_VIOL_DEFAULT             0x00000003

/* MEMC_L2_1_2 :: PCI_MASK_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved3_MASK               0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_reserved3_SHIFT              4

/* MEMC_L2_1_2 :: PCI_MASK_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_PFRI_VIOL_MASK               0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_PFRI_VIOL_SHIFT              0
#define BCHP_MEMC_L2_1_2_PCI_MASK_SET_PFRI_VIOL_DEFAULT            0x0000000f

/***************************************************************************
 *PCI_MASK_CLEAR - PCI interrupt Mask Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved0_MASK             0xffc00000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved0_SHIFT            22

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_RGR_BRIDGE_INTR_MASK       0x00100000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_RGR_BRIDGE_INTR_SHIFT      20
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_RGR_BRIDGE_INTR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DFI_ERROR_MASK             0x00080000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DFI_ERROR_SHIFT            19
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_DFI_ERROR_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SM_TIMEOUT_INTR_MASK       0x00040000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SM_TIMEOUT_INTR_SHIFT      18
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SM_TIMEOUT_INTR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_WRDATA_ERR_MASK        0x00020000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_WRDATA_ERR_SHIFT       17
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_WRDATA_ERR_DEFAULT     0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_TRANSID_MISMATCH_MASK  0x00010000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SCB_VIOL_MASK              0x00008000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SCB_VIOL_SHIFT             15
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_SCB_VIOL_DEFAULT           0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved1_MASK             0x00006000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved1_SHIFT            13

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_AXI_VIOL_MASK              0x00001000
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_AXI_VIOL_SHIFT             12
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_AXI_VIOL_DEFAULT           0x00000001

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved2_MASK             0x00000c00
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved2_SHIFT            10

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_MCP_VIOL_MASK              0x00000300
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_MCP_VIOL_SHIFT             8
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_MCP_VIOL_DEFAULT           0x00000003

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved3_MASK             0x000000f0
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_reserved3_SHIFT            4

/* MEMC_L2_1_2 :: PCI_MASK_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_PFRI_VIOL_MASK             0x0000000f
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_PFRI_VIOL_SHIFT            0
#define BCHP_MEMC_L2_1_2_PCI_MASK_CLEAR_PFRI_VIOL_DEFAULT          0x0000000f

/***************************************************************************
 *SCPU_STATUS - SCPU interrupt Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_STATUS :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved0_MASK                0xff800000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved0_SHIFT               23

/* MEMC_L2_1_2 :: SCPU_STATUS :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_V3_SCRAM_MASK_FAULT_MASK      0x00400000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_V3_SCRAM_MASK_FAULT_SHIFT     22
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_V3_SCRAM_MASK_FAULT_DEFAULT   0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DTU_INTEGRITY_ERR_INTR_MASK   0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT  21
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_RGR_BRIDGE_INTR_MASK          0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_RGR_BRIDGE_INTR_SHIFT         20
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_RGR_BRIDGE_INTR_DEFAULT       0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DFI_ERROR_MASK                0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DFI_ERROR_SHIFT               19
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_DFI_ERROR_DEFAULT             0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SM_TIMEOUT_INTR_MASK          0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SM_TIMEOUT_INTR_SHIFT         18
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SM_TIMEOUT_INTR_DEFAULT       0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_WRDATA_ERR_MASK           0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_WRDATA_ERR_SHIFT          17
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_WRDATA_ERR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_TRANSID_MISMATCH_MASK     0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_TRANSID_MISMATCH_SHIFT    16
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT  0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SCB_VIOL_MASK                 0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SCB_VIOL_SHIFT                15
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_SCB_VIOL_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved1_MASK                0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved1_SHIFT               13

/* MEMC_L2_1_2 :: SCPU_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_AXI_VIOL_MASK                 0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_AXI_VIOL_SHIFT                12
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_AXI_VIOL_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved2_MASK                0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved2_SHIFT               10

/* MEMC_L2_1_2 :: SCPU_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_MCP_VIOL_MASK                 0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_MCP_VIOL_SHIFT                8
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_MCP_VIOL_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: SCPU_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved3_MASK                0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_reserved3_SHIFT               4

/* MEMC_L2_1_2 :: SCPU_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_PFRI_VIOL_MASK                0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_PFRI_VIOL_SHIFT               0
#define BCHP_MEMC_L2_1_2_SCPU_STATUS_PFRI_VIOL_DEFAULT             0x00000000

/***************************************************************************
 *SCPU_SET - SCPU interrupt Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_SET :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved0_MASK                   0xff800000
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved0_SHIFT                  23

/* MEMC_L2_1_2 :: SCPU_SET :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_V3_SCRAM_MASK_FAULT_MASK         0x00400000
#define BCHP_MEMC_L2_1_2_SCPU_SET_V3_SCRAM_MASK_FAULT_SHIFT        22
#define BCHP_MEMC_L2_1_2_SCPU_SET_V3_SCRAM_MASK_FAULT_DEFAULT      0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_DTU_INTEGRITY_ERR_INTR_MASK      0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_SET_DTU_INTEGRITY_ERR_INTR_SHIFT     21
#define BCHP_MEMC_L2_1_2_SCPU_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT   0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_RGR_BRIDGE_INTR_MASK             0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_SET_RGR_BRIDGE_INTR_SHIFT            20
#define BCHP_MEMC_L2_1_2_SCPU_SET_RGR_BRIDGE_INTR_DEFAULT          0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_DFI_ERROR_MASK                   0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_SET_DFI_ERROR_SHIFT                  19
#define BCHP_MEMC_L2_1_2_SCPU_SET_DFI_ERROR_DEFAULT                0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_SM_TIMEOUT_INTR_MASK             0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_SET_SM_TIMEOUT_INTR_SHIFT            18
#define BCHP_MEMC_L2_1_2_SCPU_SET_SM_TIMEOUT_INTR_DEFAULT          0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_WRDATA_ERR_MASK              0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_WRDATA_ERR_SHIFT             17
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_WRDATA_ERR_DEFAULT           0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_TRANSID_MISMATCH_MASK        0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_TRANSID_MISMATCH_SHIFT       16
#define BCHP_MEMC_L2_1_2_SCPU_SET_SEQ_TRANSID_MISMATCH_DEFAULT     0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_SCB_VIOL_MASK                    0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_SET_SCB_VIOL_SHIFT                   15
#define BCHP_MEMC_L2_1_2_SCPU_SET_SCB_VIOL_DEFAULT                 0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved1_MASK                   0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved1_SHIFT                  13

/* MEMC_L2_1_2 :: SCPU_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_AXI_VIOL_MASK                    0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_SET_AXI_VIOL_SHIFT                   12
#define BCHP_MEMC_L2_1_2_SCPU_SET_AXI_VIOL_DEFAULT                 0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved2_MASK                   0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved2_SHIFT                  10

/* MEMC_L2_1_2 :: SCPU_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_MCP_VIOL_MASK                    0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_SET_MCP_VIOL_SHIFT                   8
#define BCHP_MEMC_L2_1_2_SCPU_SET_MCP_VIOL_DEFAULT                 0x00000000

/* MEMC_L2_1_2 :: SCPU_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved3_MASK                   0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_SET_reserved3_SHIFT                  4

/* MEMC_L2_1_2 :: SCPU_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_SET_PFRI_VIOL_MASK                   0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_SET_PFRI_VIOL_SHIFT                  0
#define BCHP_MEMC_L2_1_2_SCPU_SET_PFRI_VIOL_DEFAULT                0x00000000

/***************************************************************************
 *SCPU_CLEAR - SCPU interrupt Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_CLEAR :: reserved0 [31:23] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved0_MASK                 0xff800000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved0_SHIFT                23

/* MEMC_L2_1_2 :: SCPU_CLEAR :: V3_SCRAM_MASK_FAULT [22:22] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_V3_SCRAM_MASK_FAULT_MASK       0x00400000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_V3_SCRAM_MASK_FAULT_SHIFT      22
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_V3_SCRAM_MASK_FAULT_DEFAULT    0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK    0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT   21
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_RGR_BRIDGE_INTR_MASK           0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_RGR_BRIDGE_INTR_SHIFT          20
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_RGR_BRIDGE_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DFI_ERROR_MASK                 0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DFI_ERROR_SHIFT                19
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_DFI_ERROR_DEFAULT              0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SM_TIMEOUT_INTR_MASK           0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SM_TIMEOUT_INTR_SHIFT          18
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SM_TIMEOUT_INTR_DEFAULT        0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_WRDATA_ERR_MASK            0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_WRDATA_ERR_SHIFT           17
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_WRDATA_ERR_DEFAULT         0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_TRANSID_MISMATCH_MASK      0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT     16
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT   0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SCB_VIOL_MASK                  0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SCB_VIOL_SHIFT                 15
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_SCB_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved1_MASK                 0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved1_SHIFT                13

/* MEMC_L2_1_2 :: SCPU_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_AXI_VIOL_MASK                  0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_AXI_VIOL_SHIFT                 12
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_AXI_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved2_MASK                 0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved2_SHIFT                10

/* MEMC_L2_1_2 :: SCPU_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_MCP_VIOL_MASK                  0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_MCP_VIOL_SHIFT                 8
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_MCP_VIOL_DEFAULT               0x00000000

/* MEMC_L2_1_2 :: SCPU_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved3_MASK                 0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_reserved3_SHIFT                4

/* MEMC_L2_1_2 :: SCPU_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_PFRI_VIOL_MASK                 0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_PFRI_VIOL_SHIFT                0
#define BCHP_MEMC_L2_1_2_SCPU_CLEAR_PFRI_VIOL_DEFAULT              0x00000000

/***************************************************************************
 *SCPU_MASK_STATUS - SCPU interrupt Mask Status Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved0_MASK           0xffc00000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved0_SHIFT          22

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_RGR_BRIDGE_INTR_MASK     0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_RGR_BRIDGE_INTR_SHIFT    20
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_RGR_BRIDGE_INTR_DEFAULT  0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DFI_ERROR_MASK           0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DFI_ERROR_SHIFT          19
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_DFI_ERROR_DEFAULT        0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SM_TIMEOUT_INTR_MASK     0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SM_TIMEOUT_INTR_SHIFT    18
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SM_TIMEOUT_INTR_DEFAULT  0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_WRDATA_ERR_MASK      0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_WRDATA_ERR_SHIFT     17
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_WRDATA_ERR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_MASK 0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SCB_VIOL_MASK            0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SCB_VIOL_SHIFT           15
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_SCB_VIOL_DEFAULT         0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved1_MASK           0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved1_SHIFT          13

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_AXI_VIOL_MASK            0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_AXI_VIOL_SHIFT           12
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_AXI_VIOL_DEFAULT         0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved2_MASK           0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved2_SHIFT          10

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_MCP_VIOL_MASK            0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_MCP_VIOL_SHIFT           8
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_MCP_VIOL_DEFAULT         0x00000003

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved3_MASK           0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_reserved3_SHIFT          4

/* MEMC_L2_1_2 :: SCPU_MASK_STATUS :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_PFRI_VIOL_MASK           0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_PFRI_VIOL_SHIFT          0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_STATUS_PFRI_VIOL_DEFAULT        0x0000000f

/***************************************************************************
 *SCPU_MASK_SET - SCPU interrupt Mask Set Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_MASK_SET :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved0_MASK              0xffc00000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved0_SHIFT             22

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_RGR_BRIDGE_INTR_MASK        0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_RGR_BRIDGE_INTR_SHIFT       20
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_RGR_BRIDGE_INTR_DEFAULT     0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DFI_ERROR_MASK              0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DFI_ERROR_SHIFT             19
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_DFI_ERROR_DEFAULT           0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SM_TIMEOUT_INTR_MASK        0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SM_TIMEOUT_INTR_SHIFT       18
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SM_TIMEOUT_INTR_DEFAULT     0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_WRDATA_ERR_MASK         0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_WRDATA_ERR_SHIFT        17
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_WRDATA_ERR_DEFAULT      0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_TRANSID_MISMATCH_MASK   0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_TRANSID_MISMATCH_SHIFT  16
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SCB_VIOL_MASK               0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SCB_VIOL_SHIFT              15
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_SCB_VIOL_DEFAULT            0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved1_MASK              0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved1_SHIFT             13

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_AXI_VIOL_MASK               0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_AXI_VIOL_SHIFT              12
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_AXI_VIOL_DEFAULT            0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved2_MASK              0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved2_SHIFT             10

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_MCP_VIOL_MASK               0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_MCP_VIOL_SHIFT              8
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_MCP_VIOL_DEFAULT            0x00000003

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved3_MASK              0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_reserved3_SHIFT             4

/* MEMC_L2_1_2 :: SCPU_MASK_SET :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_PFRI_VIOL_MASK              0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_PFRI_VIOL_SHIFT             0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_SET_PFRI_VIOL_DEFAULT           0x0000000f

/***************************************************************************
 *SCPU_MASK_CLEAR - SCPU interrupt Mask Clear Register
 ***************************************************************************/
/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: reserved0 [31:22] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved0_MASK            0xffc00000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved0_SHIFT           22

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: DTU_INTEGRITY_ERR_INTR [21:21] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_MASK 0x00200000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_SHIFT 21
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DTU_INTEGRITY_ERR_INTR_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: RGR_BRIDGE_INTR [20:20] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_RGR_BRIDGE_INTR_MASK      0x00100000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_RGR_BRIDGE_INTR_SHIFT     20
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_RGR_BRIDGE_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: DFI_ERROR [19:19] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DFI_ERROR_MASK            0x00080000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DFI_ERROR_SHIFT           19
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_DFI_ERROR_DEFAULT         0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: SM_TIMEOUT_INTR [18:18] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SM_TIMEOUT_INTR_MASK      0x00040000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SM_TIMEOUT_INTR_SHIFT     18
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SM_TIMEOUT_INTR_DEFAULT   0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: SEQ_WRDATA_ERR [17:17] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_WRDATA_ERR_MASK       0x00020000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_WRDATA_ERR_SHIFT      17
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_WRDATA_ERR_DEFAULT    0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: SEQ_TRANSID_MISMATCH [16:16] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_MASK 0x00010000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_SHIFT 16
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SEQ_TRANSID_MISMATCH_DEFAULT 0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: SCB_VIOL [15:15] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SCB_VIOL_MASK             0x00008000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SCB_VIOL_SHIFT            15
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_SCB_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: reserved1 [14:13] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved1_MASK            0x00006000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved1_SHIFT           13

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: AXI_VIOL [12:12] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_AXI_VIOL_MASK             0x00001000
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_AXI_VIOL_SHIFT            12
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_AXI_VIOL_DEFAULT          0x00000001

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: reserved2 [11:10] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved2_MASK            0x00000c00
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved2_SHIFT           10

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: MCP_VIOL [09:08] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_MCP_VIOL_MASK             0x00000300
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_MCP_VIOL_SHIFT            8
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_MCP_VIOL_DEFAULT          0x00000003

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: reserved3 [07:04] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved3_MASK            0x000000f0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_reserved3_SHIFT           4

/* MEMC_L2_1_2 :: SCPU_MASK_CLEAR :: PFRI_VIOL [03:00] */
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_PFRI_VIOL_MASK            0x0000000f
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_PFRI_VIOL_SHIFT           0
#define BCHP_MEMC_L2_1_2_SCPU_MASK_CLEAR_PFRI_VIOL_DEFAULT         0x0000000f

#endif /* #ifndef BCHP_MEMC_L2_1_2_H__ */

/* End of File */
