/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Wed Dec 21 06:13:49 2016
 *                 Full Compile MD5 Checksum  2edd384c1405a388347db27089ee12b7
 *                     (minus title and desc)
 *                 MD5 Checksum               6e5ced4da0f0f15efb4ae46ce86e004a
 *
 * lock_release:   r_1099
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_MEMC_DTU_CONFIG_0_H__
#define BCHP_MEMC_DTU_CONFIG_0_H__

/***************************************************************************
 *MEMC_DTU_CONFIG_0 - MEMSYS DTU Configuration Registers
 ***************************************************************************/
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID            0x01909000 /* [RO][32] DRAM Translation Unit (DTU) revision ID */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_BUS_PAGES    0x01909010 /* [RO][32] Number of Implemented Bus Pages */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_DEVICE_PAGES 0x01909014 /* [RO][32] Number of Implemented Device Pages */
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RW          0x01909038 /* [RW][32] Spare register for read-write control ECOs */
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RO          0x0190903c /* [RO][32] Spare register for read-only status ECOs */
#define BCHP_MEMC_DTU_CONFIG_0_INIT              0x01909040 /* [RW][32] Initialize Trigger */
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS       0x01909044 /* [RO][32] Initialize Status */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD            0x01909048 /* [RW][32] Reload Control */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS     0x0190904c /* [RO][32] Reload Status */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE         0x01909050 /* [RW][32] Translate Control */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS  0x01909054 /* [RO][32] Translate Status */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED      0x01909080 /* [RO][32] Count of Mapped Bus Pages */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED       0x01909084 /* [RO][32] Count of Owned Bus Pages */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING   0x01909088 /* [RO][32] Count of Scrubbing Bus Pages */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS 0x0190908c /* [RO][32] Count of correctable integrity failures */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS 0x01909090 /* [RO][32] Count of uncorrectable integrity failures */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG   0x019090c0 /* [RW][32] Scrubber client configuration */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_BUS_PAGE 0x019090c4 /* [RO][32] Scrubber current Bus Map entry */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE    0x019090c8 /* [RW][32] Scrubber state */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_COUNT    0x019090cc /* [RO][32] Scrubber total count of Bus Map entries completed */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_DEBUG    0x019090d0 /* [RO][32] Scrubber HW state bits */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_CLEAR     0x01909100 /* [WO][32] Failed command: clear held information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO      0x01909104 /* [RO][32] Failed command: general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO 0x01909108 /* [RO][32] Failed command: table entry general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES 0x0190910c /* [RO][32] Failed command: table entry page information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_SYNDROME 0x01909110 /* [RO][32] Failed command: table entry syndrome bits */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_CLEAR  0x01909140 /* [WO][32] Failed client access: clear held information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO   0x01909144 /* [RO][32] Failed client access: general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO 0x01909148 /* [RO][32] Failed client access: table entry general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES 0x0190914c /* [RO][32] Failed client access: table entry page information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_SYNDROME 0x01909150 /* [RO][32] Failed client access: table entry syndrome bits */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_CLEAR   0x01909180 /* [WO][32] Failed entry integrity: clear held information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO    0x01909184 /* [RO][32] Failed entry integrity: general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO 0x01909188 /* [RO][32] Failed entry integrity: table entry general information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES 0x0190918c /* [RO][32] Failed entry integrity: table entry page information */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_SYNDROME 0x01909190 /* [RO][32] Failed entry integrity: table entry syndrome bits */

/***************************************************************************
 *REV_ID - DRAM Translation Unit (DTU) revision ID
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: REV_ID :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_reserved0_MASK               0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_reserved0_SHIFT              16

/* MEMC_DTU_CONFIG_0 :: REV_ID :: MAJOR_REV_ID [15:12] */
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MAJOR_REV_ID_MASK            0x0000f000
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MAJOR_REV_ID_SHIFT           12
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MAJOR_REV_ID_DEFAULT         0x00000001

/* MEMC_DTU_CONFIG_0 :: REV_ID :: MINOR_REV_ID [11:08] */
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MINOR_REV_ID_MASK            0x00000f00
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MINOR_REV_ID_SHIFT           8
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_MINOR_REV_ID_DEFAULT         0x00000001

/* MEMC_DTU_CONFIG_0 :: REV_ID :: ALL_LAYER_ID [07:04] */
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_ALL_LAYER_ID_MASK            0x000000f0
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_ALL_LAYER_ID_SHIFT           4
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_ALL_LAYER_ID_DEFAULT         0x00000000

/* MEMC_DTU_CONFIG_0 :: REV_ID :: METAL_LAYER_ID [03:00] */
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_METAL_LAYER_ID_MASK          0x0000000f
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_METAL_LAYER_ID_SHIFT         0
#define BCHP_MEMC_DTU_CONFIG_0_REV_ID_METAL_LAYER_ID_DEFAULT       0x00000000

/***************************************************************************
 *SIZE_BUS_PAGES - Number of Implemented Bus Pages
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SIZE_BUS_PAGES :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_BUS_PAGES_reserved0_MASK       0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_BUS_PAGES_reserved0_SHIFT      16

/* MEMC_DTU_CONFIG_0 :: SIZE_BUS_PAGES :: SIZE_BUS_PAGES [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_BUS_PAGES_SIZE_BUS_PAGES_MASK  0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_BUS_PAGES_SIZE_BUS_PAGES_SHIFT 0

/***************************************************************************
 *SIZE_DEVICE_PAGES - Number of Implemented Device Pages
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SIZE_DEVICE_PAGES :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_DEVICE_PAGES_reserved0_MASK    0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_DEVICE_PAGES_reserved0_SHIFT   16

/* MEMC_DTU_CONFIG_0 :: SIZE_DEVICE_PAGES :: SIZE_DEVICE_PAGES [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_DEVICE_PAGES_SIZE_DEVICE_PAGES_MASK 0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_SIZE_DEVICE_PAGES_SIZE_DEVICE_PAGES_SHIFT 0

/***************************************************************************
 *SPARE_RW - Spare register for read-write control ECOs
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SPARE_RW :: SPARE_CTRL [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RW_SPARE_CTRL_MASK            0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RW_SPARE_CTRL_SHIFT           0
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RW_SPARE_CTRL_DEFAULT         0x00000000

/***************************************************************************
 *SPARE_RO - Spare register for read-only status ECOs
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SPARE_RO :: SPARE_STAT [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RO_SPARE_STAT_MASK            0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RO_SPARE_STAT_SHIFT           0
#define BCHP_MEMC_DTU_CONFIG_0_SPARE_RO_SPARE_STAT_DEFAULT         0x00000000

/***************************************************************************
 *INIT - Initialize Trigger
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: INIT :: reserved0 [31:08] */
#define BCHP_MEMC_DTU_CONFIG_0_INIT_reserved0_MASK                 0xffffff00
#define BCHP_MEMC_DTU_CONFIG_0_INIT_reserved0_SHIFT                8

/* MEMC_DTU_CONFIG_0 :: INIT :: INIT [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_INIT_INIT_MASK                      0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_INIT_INIT_SHIFT                     0
#define BCHP_MEMC_DTU_CONFIG_0_INIT_INIT_DEFAULT                   0x00000055
#define BCHP_MEMC_DTU_CONFIG_0_INIT_INIT_IDLE                      85
#define BCHP_MEMC_DTU_CONFIG_0_INIT_INIT_INIT                      174

/***************************************************************************
 *INIT_STATUS - Initialize Status
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: INIT_STATUS :: reserved0 [31:02] */
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_reserved0_MASK          0xfffffffc
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_reserved0_SHIFT         2

/* MEMC_DTU_CONFIG_0 :: INIT_STATUS :: INITIALIZATION [01:00] */
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_MASK     0x00000003
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_SHIFT    0
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_DEFAULT  0x00000000
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_IDLE     0
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_BUSY     1
#define BCHP_MEMC_DTU_CONFIG_0_INIT_STATUS_INITIALIZATION_DONE     2

/***************************************************************************
 *RELOAD - Reload Control
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: RELOAD :: reserved0 [31:08] */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_reserved0_MASK               0xffffff00
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_reserved0_SHIFT              8

/* MEMC_DTU_CONFIG_0 :: RELOAD :: RELOAD [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_RELOAD_MASK                  0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_RELOAD_SHIFT                 0
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_RELOAD_DEFAULT               0x00000055
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_RELOAD_ENABLE                85
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_RELOAD_DISABLE               174

/***************************************************************************
 *RELOAD_STATUS - Reload Status
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: RELOAD_STATUS :: reserved0 [31:01] */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_reserved0_MASK        0xfffffffe
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_reserved0_SHIFT       1

/* MEMC_DTU_CONFIG_0 :: RELOAD_STATUS :: RELOADING [00:00] */
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_RELOADING_MASK        0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_RELOADING_SHIFT       0
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_RELOADING_DEFAULT     0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_RELOADING_DISABLED    0
#define BCHP_MEMC_DTU_CONFIG_0_RELOAD_STATUS_RELOADING_ENABLED     1

/***************************************************************************
 *TRANSLATE - Translate Control
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: TRANSLATE :: reserved0 [31:08] */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_reserved0_MASK            0xffffff00
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_reserved0_SHIFT           8

/* MEMC_DTU_CONFIG_0 :: TRANSLATE :: ENABLE [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_MASK               0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_SHIFT              0
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_DEFAULT            0x000000c3
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_UNSET              195
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_ENABLE             85
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_ENABLE_DISABLE            174

/***************************************************************************
 *TRANSLATE_STATUS - Translate Status
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: TRANSLATE_STATUS :: reserved0 [31:01] */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_reserved0_MASK     0xfffffffe
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_reserved0_SHIFT    1

/* MEMC_DTU_CONFIG_0 :: TRANSLATE_STATUS :: ENABLED [00:00] */
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_ENABLED_MASK       0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_ENABLED_SHIFT      0
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_ENABLED_DEFAULT    0x00000000
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_ENABLED_DISABLED   0
#define BCHP_MEMC_DTU_CONFIG_0_TRANSLATE_STATUS_ENABLED_ENABLED    1

/***************************************************************************
 *COUNT_MAPPED - Count of Mapped Bus Pages
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: COUNT_MAPPED :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED_reserved0_MASK         0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED_reserved0_SHIFT        16

/* MEMC_DTU_CONFIG_0 :: COUNT_MAPPED :: COUNT [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED_COUNT_MASK             0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED_COUNT_SHIFT            0
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_MAPPED_COUNT_DEFAULT          0x00000000

/***************************************************************************
 *COUNT_OWNED - Count of Owned Bus Pages
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: COUNT_OWNED :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED_reserved0_MASK          0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED_reserved0_SHIFT         16

/* MEMC_DTU_CONFIG_0 :: COUNT_OWNED :: COUNT [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED_COUNT_MASK              0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED_COUNT_SHIFT             0
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_OWNED_COUNT_DEFAULT           0x00000000

/***************************************************************************
 *COUNT_SCRUBBING - Count of Scrubbing Bus Pages
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: COUNT_SCRUBBING :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING_reserved0_MASK      0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING_reserved0_SHIFT     16

/* MEMC_DTU_CONFIG_0 :: COUNT_SCRUBBING :: COUNT [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING_COUNT_MASK          0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING_COUNT_SHIFT         0
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_SCRUBBING_COUNT_DEFAULT       0x00000000

/***************************************************************************
 *COUNT_INTEG_CORRECTS - Count of correctable integrity failures
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: COUNT_INTEG_CORRECTS :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS_reserved0_MASK 0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS_reserved0_SHIFT 16

/* MEMC_DTU_CONFIG_0 :: COUNT_INTEG_CORRECTS :: COUNT [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS_COUNT_MASK     0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS_COUNT_SHIFT    0
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_CORRECTS_COUNT_DEFAULT  0x00000000

/***************************************************************************
 *COUNT_INTEG_FAILS - Count of uncorrectable integrity failures
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: COUNT_INTEG_FAILS :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS_reserved0_MASK    0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS_reserved0_SHIFT   16

/* MEMC_DTU_CONFIG_0 :: COUNT_INTEG_FAILS :: COUNT [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS_COUNT_MASK        0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS_COUNT_SHIFT       0
#define BCHP_MEMC_DTU_CONFIG_0_COUNT_INTEG_FAILS_COUNT_DEFAULT     0x00000000

/***************************************************************************
 *SCRUBBER_CONFIG - Scrubber client configuration
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SCRUBBER_CONFIG :: reserved0 [31:26] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_reserved0_MASK      0xfc000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_reserved0_SHIFT     26

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_CONFIG :: BURST_SIZE [25:24] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_MASK     0x03000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_SHIFT    24
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_DEFAULT  0x00000002
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_BYTES_128 0
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_BYTES_256 1
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_BYTES_512 2
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_BURST_SIZE_BYTES_1024 3

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_CONFIG :: reserved1 [23:08] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_reserved1_MASK      0x00ffff00
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_reserved1_SHIFT     8

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_CONFIG :: PATTERN_BYTE [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_PATTERN_BYTE_MASK   0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_PATTERN_BYTE_SHIFT  0
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_CONFIG_PATTERN_BYTE_DEFAULT 0x00000000

/***************************************************************************
 *SCRUBBER_BUS_PAGE - Scrubber current Bus Map entry
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SCRUBBER_BUS_PAGE :: reserved0 [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_BUS_PAGE_reserved0_MASK    0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_BUS_PAGE_reserved0_SHIFT   16

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_BUS_PAGE :: BUS_PAGE [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_BUS_PAGE_BUS_PAGE_MASK     0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_BUS_PAGE_BUS_PAGE_SHIFT    0

/***************************************************************************
 *SCRUBBER_STATE - Scrubber state
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: STATE [31:30] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_MASK           0xc0000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_SHIFT          30
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_DEFAULT        0x00000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_IDLE           0
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_SEARCHING      1
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_STATE_SCRUBBING      2

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: reserved0 [29:26] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_reserved0_MASK       0x3c000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_reserved0_SHIFT      26

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: SCRUB_INVALID_PAGE [25:25] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUB_INVALID_PAGE_MASK 0x02000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUB_INVALID_PAGE_SHIFT 25
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUB_INVALID_PAGE_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: SCRUBBER_WRAP [24:24] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUBBER_WRAP_MASK   0x01000000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUBBER_WRAP_SHIFT  24
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_SCRUBBER_WRAP_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: reserved1 [23:22] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_reserved1_MASK       0x00c00000
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_reserved1_SHIFT      22

/* MEMC_DTU_CONFIG_0 :: SCRUBBER_STATE :: OFFSET [21:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_OFFSET_MASK          0x003fffff
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_STATE_OFFSET_SHIFT         0

/***************************************************************************
 *SCRUBBER_COUNT - Scrubber total count of Bus Map entries completed
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SCRUBBER_COUNT :: COUNT [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_COUNT_COUNT_MASK           0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_COUNT_COUNT_SHIFT          0
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_COUNT_COUNT_DEFAULT        0x00000000

/***************************************************************************
 *SCRUBBER_DEBUG - Scrubber HW state bits
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: SCRUBBER_DEBUG :: DEBUG [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_DEBUG_DEBUG_MASK           0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_SCRUBBER_DEBUG_DEBUG_SHIFT          0

/***************************************************************************
 *ERR_CMD_CLEAR - Failed command: clear held information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_CMD_CLEAR :: reserved0 [31:01] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_CLEAR_reserved0_MASK        0xfffffffe
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_CLEAR_reserved0_SHIFT       1

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_CLEAR :: CLEAR [00:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_CLEAR_CLEAR_MASK            0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_CLEAR_CLEAR_SHIFT           0

/***************************************************************************
 *ERR_CMD_INFO - Failed command: general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: VALID_ERR [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_VALID_ERR_MASK         0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_VALID_ERR_SHIFT        31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_VALID_ERR_DEFAULT      0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: INTEGRITY_FAULT [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_INTEGRITY_FAULT_MASK   0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_INTEGRITY_FAULT_SHIFT  30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_INTEGRITY_FAULT_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: CMD_TYPE [29:27] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_MASK          0x38000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_SHIFT         27
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_DEFAULT       0x00000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_NOP       0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_MAP       1
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_UNMAP     2
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_SETOWN    3
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_UNSETOWN  4
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_SCRUB     5
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_RFU6      6
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_TYPE_CMD_RFU7      7

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: reserved0 [26:24] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_reserved0_MASK         0x07000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_reserved0_SHIFT        24

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: CMD_PARAM [23:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_PARAM_MASK         0x00ffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_PARAM_SHIFT        8
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CMD_PARAM_DEFAULT      0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_INFO :: CLIENT_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CLIENT_ID_MASK         0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CLIENT_ID_SHIFT        0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_INFO_CLIENT_ID_DEFAULT      0x00000000

/***************************************************************************
 *ERR_CMD_ENTRY_INFO - Failed command: table entry general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_INFO :: VALID_MAP [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_MAP_MASK   0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_MAP_SHIFT  31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_MAP_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_INFO :: VALID_OWNER [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_OWNER_MASK 0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_OWNER_SHIFT 30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_VALID_OWNER_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_INFO :: SCRUB [29:29] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_SCRUB_MASK       0x20000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_SCRUB_SHIFT      29
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_SCRUB_DEFAULT    0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_INFO :: reserved0 [28:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_reserved0_MASK   0x1fffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_reserved0_SHIFT  8

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_INFO :: OWNER_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_OWNER_ID_MASK    0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_OWNER_ID_SHIFT   0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_INFO_OWNER_ID_DEFAULT 0x00000000

/***************************************************************************
 *ERR_CMD_ENTRY_PAGES - Failed command: table entry page information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_PAGES :: DEVICE_PAGE [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_DEVICE_PAGE_MASK 0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_DEVICE_PAGE_SHIFT 16
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_DEVICE_PAGE_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_PAGES :: BUS_PAGE [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_BUS_PAGE_MASK   0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_BUS_PAGE_SHIFT  0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_PAGES_BUS_PAGE_DEFAULT 0x00000000

/***************************************************************************
 *ERR_CMD_ENTRY_SYNDROME - Failed command: table entry syndrome bits
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_CMD_ENTRY_SYNDROME :: SYNDROME [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_SYNDROME_SYNDROME_MASK 0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_SYNDROME_SYNDROME_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_CMD_ENTRY_SYNDROME_SYNDROME_DEFAULT 0x00000000

/***************************************************************************
 *ERR_ACCESS_CLEAR - Failed client access: clear held information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_CLEAR :: reserved0 [31:01] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_CLEAR_reserved0_MASK     0xfffffffe
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_CLEAR_reserved0_SHIFT    1

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_CLEAR :: CLEAR [00:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_CLEAR_CLEAR_MASK         0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_CLEAR_CLEAR_SHIFT        0

/***************************************************************************
 *ERR_ACCESS_INFO - Failed client access: general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_INFO :: VALID_ERR [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_VALID_ERR_MASK      0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_VALID_ERR_SHIFT     31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_VALID_ERR_DEFAULT   0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_INFO :: INTEGRITY_FAULT [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_INTEGRITY_FAULT_MASK 0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_INTEGRITY_FAULT_SHIFT 30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_INTEGRITY_FAULT_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_INFO :: reserved0 [29:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_reserved0_MASK      0x3fffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_reserved0_SHIFT     8

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_INFO :: CLIENT_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_CLIENT_ID_MASK      0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_CLIENT_ID_SHIFT     0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_INFO_CLIENT_ID_DEFAULT   0x00000000

/***************************************************************************
 *ERR_ACCESS_ENTRY_INFO - Failed client access: table entry general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_INFO :: VALID_MAP [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_MAP_MASK 0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_MAP_SHIFT 31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_MAP_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_INFO :: VALID_OWNER [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_OWNER_MASK 0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_OWNER_SHIFT 30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_VALID_OWNER_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_INFO :: SCRUB [29:29] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_SCRUB_MASK    0x20000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_SCRUB_SHIFT   29
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_SCRUB_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_INFO :: reserved0 [28:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_reserved0_MASK 0x1fffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_reserved0_SHIFT 8

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_INFO :: OWNER_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_OWNER_ID_MASK 0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_OWNER_ID_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_INFO_OWNER_ID_DEFAULT 0x00000000

/***************************************************************************
 *ERR_ACCESS_ENTRY_PAGES - Failed client access: table entry page information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_PAGES :: DEVICE_PAGE [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_DEVICE_PAGE_MASK 0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_DEVICE_PAGE_SHIFT 16
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_DEVICE_PAGE_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_PAGES :: BUS_PAGE [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_BUS_PAGE_MASK 0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_BUS_PAGE_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_PAGES_BUS_PAGE_DEFAULT 0x00000000

/***************************************************************************
 *ERR_ACCESS_ENTRY_SYNDROME - Failed client access: table entry syndrome bits
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_ACCESS_ENTRY_SYNDROME :: SYNDROME [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_SYNDROME_SYNDROME_MASK 0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_SYNDROME_SYNDROME_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_ACCESS_ENTRY_SYNDROME_SYNDROME_DEFAULT 0x00000000

/***************************************************************************
 *ERR_INTEG_CLEAR - Failed entry integrity: clear held information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_CLEAR :: reserved0 [31:01] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_CLEAR_reserved0_MASK      0xfffffffe
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_CLEAR_reserved0_SHIFT     1

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_CLEAR :: CLEAR [00:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_CLEAR_CLEAR_MASK          0x00000001
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_CLEAR_CLEAR_SHIFT         0

/***************************************************************************
 *ERR_INTEG_INFO - Failed entry integrity: general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_INFO :: VALID_ERR [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_VALID_ERR_MASK       0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_VALID_ERR_SHIFT      31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_VALID_ERR_DEFAULT    0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_INFO :: INTEGRITY_FAULT [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_INTEGRITY_FAULT_MASK 0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_INTEGRITY_FAULT_SHIFT 30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_INTEGRITY_FAULT_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_INFO :: SOURCE [29:27] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_MASK          0x38000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_SHIFT         27
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_DEFAULT       0x00000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_DRAM_ACCESS   0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_GISB_CMD      1
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_GISB_READ     2
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_SCRUBBER_READ 3
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_ERR_SRC_RFU4  4
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_ERR_SRC_RFU5  5
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_ERR_SRC_RFU6  6
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_SOURCE_ERR_SRC_RFU7  7

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_INFO :: reserved0 [26:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_reserved0_MASK       0x07ffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_reserved0_SHIFT      8

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_INFO :: CLIENT_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_CLIENT_ID_MASK       0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_CLIENT_ID_SHIFT      0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_INFO_CLIENT_ID_DEFAULT    0x00000000

/***************************************************************************
 *ERR_INTEG_ENTRY_INFO - Failed entry integrity: table entry general information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_INFO :: VALID_MAP [31:31] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_MAP_MASK 0x80000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_MAP_SHIFT 31
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_MAP_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_INFO :: VALID_OWNER [30:30] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_OWNER_MASK 0x40000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_OWNER_SHIFT 30
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_VALID_OWNER_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_INFO :: SCRUB [29:29] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_SCRUB_MASK     0x20000000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_SCRUB_SHIFT    29
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_SCRUB_DEFAULT  0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_INFO :: reserved0 [28:08] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_reserved0_MASK 0x1fffff00
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_reserved0_SHIFT 8

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_INFO :: OWNER_ID [07:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_OWNER_ID_MASK  0x000000ff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_OWNER_ID_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_INFO_OWNER_ID_DEFAULT 0x00000000

/***************************************************************************
 *ERR_INTEG_ENTRY_PAGES - Failed entry integrity: table entry page information
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_PAGES :: DEVICE_PAGE [31:16] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_DEVICE_PAGE_MASK 0xffff0000
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_DEVICE_PAGE_SHIFT 16
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_DEVICE_PAGE_DEFAULT 0x00000000

/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_PAGES :: BUS_PAGE [15:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_BUS_PAGE_MASK 0x0000ffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_BUS_PAGE_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_PAGES_BUS_PAGE_DEFAULT 0x00000000

/***************************************************************************
 *ERR_INTEG_ENTRY_SYNDROME - Failed entry integrity: table entry syndrome bits
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: ERR_INTEG_ENTRY_SYNDROME :: SYNDROME [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_SYNDROME_SYNDROME_MASK 0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_SYNDROME_SYNDROME_SHIFT 0
#define BCHP_MEMC_DTU_CONFIG_0_ERR_INTEG_ENTRY_SYNDROME_SYNDROME_DEFAULT 0x00000000

/***************************************************************************
 *DEVICE_STATE%i - Device State Memory
 ***************************************************************************/
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_ARRAY_BASE            0x01909400
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_ARRAY_START           0
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_ARRAY_END             63
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_ARRAY_ELEMENT_SIZE    32

/***************************************************************************
 *DEVICE_STATE%i - Device State Memory
 ***************************************************************************/
/* MEMC_DTU_CONFIG_0 :: DEVICE_STATEi :: VALID_PAGES [31:00] */
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_VALID_PAGES_MASK      0xffffffff
#define BCHP_MEMC_DTU_CONFIG_0_DEVICE_STATEi_VALID_PAGES_SHIFT     0


#endif /* #ifndef BCHP_MEMC_DTU_CONFIG_0_H__ */

/* End of File */
