/***************************************************************************
 *     Copyright (c) 2012-2017, Broadcom
 *     All Rights Reserved
 *     Confidential Property of Broadcom
 *
 *  THIS SOFTWARE MAY ONLY BE USED SUBJECT TO AN EXECUTED SOFTWARE LICENSE
 *  AGREEMENT  BETWEEN THE USER AND BROADCOM.  YOU HAVE NO RIGHT TO USE OR
 *  EXPLOIT THIS MATERIAL EXCEPT SUBJECT TO THE TERMS OF SUCH AN AGREEMENT.
 *
 ***************************************************************************/

/***************************************************************************
*
* This file is generated by generate_pmap_file.pl for supporting platforms.
*
* This file contains a list of PMAPs and the corresponding register settings
*
***************************************************************************/

#ifndef BCHP_PMAP_PRIV_H__
#define BCHP_PMAP_PRIV_H__

#define AVS_RDB_DATE 20161101 /* %y%m%d */
#define AVS_RDB_TIME 1430 /* %h%m */

struct pmapParameters {
	uint16_t ndiv_int;
	uint8_t pdiv;
	uint8_t mdiv_p0;
	uint8_t mdiv_p1;
	uint8_t mdiv_p2;
	uint8_t mdiv_p3;
	uint8_t mdiv_p4;
	unsigned int num_domains;
	char *desc;
} pmapParameters;

#ifndef AVS_ONCE
#define AVS_ONCE
static const struct pmapParameters pmapTable[] = {
	{ .ndiv_int = 200, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 9, .num_domains = 2, .desc = "PMap0"},
	{ .ndiv_int = 222, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 10, .num_domains = 2, .desc = "PMap1"},
	{ .ndiv_int = 167, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 8, .num_domains = 2, .desc = "PMap2"},
	{ .ndiv_int = 206, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 9, .num_domains = 2, .desc = "PMap3"},
	{ .ndiv_int = 200, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 9, .num_domains = 1, .desc = "PMap4"},
	{ .ndiv_int = 222, .pdiv = 3, .mdiv_p0 = 2, .mdiv_p1 = 3, .mdiv_p2 = 4,
	  .mdiv_p3 = 6, .mdiv_p4 = 10, .num_domains = 1, .desc = "PMap5"},
};

static const int PMAP_MAX = sizeof(pmapTable)/sizeof(pmapTable[0]);
#endif
#endif
