/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Dec  1 06:16:27 2016
 *                 Full Compile MD5 Checksum  d77d353b4fd33f3b3eb763c0ec6d13e9
 *                     (minus title and desc)
 *                 MD5 Checksum               b9f56ca31bb855d1e4c37875f6b45457
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_GIO_H__
#define BCHP_GIO_H__

/***************************************************************************
 *GIO - GPIO
 ***************************************************************************/
#define BCHP_GIO_ODEN_LO                         0x2040a500 /* [RW][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[31:0] */
#define BCHP_GIO_DATA_LO                         0x2040a504 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[31:0] */
#define BCHP_GIO_IODIR_LO                        0x2040a508 /* [RW][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[31:0] */
#define BCHP_GIO_EC_LO                           0x2040a50c /* [RW][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[31:0] */
#define BCHP_GIO_EI_LO                           0x2040a510 /* [RW][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[31:0] */
#define BCHP_GIO_MASK_LO                         0x2040a514 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[31:0] */
#define BCHP_GIO_LEVEL_LO                        0x2040a518 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[31:0] */
#define BCHP_GIO_STAT_LO                         0x2040a51c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[31:0] */
#define BCHP_GIO_ODEN_HI                         0x2040a520 /* [RW][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[63:32] */
#define BCHP_GIO_DATA_HI                         0x2040a524 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[63:32] */
#define BCHP_GIO_IODIR_HI                        0x2040a528 /* [RW][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[63:32] */
#define BCHP_GIO_EC_HI                           0x2040a52c /* [RW][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[63:32] */
#define BCHP_GIO_EI_HI                           0x2040a530 /* [RW][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[63:32] */
#define BCHP_GIO_MASK_HI                         0x2040a534 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[63:32] */
#define BCHP_GIO_LEVEL_HI                        0x2040a538 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[63:32] */
#define BCHP_GIO_STAT_HI                         0x2040a53c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[63:32] */
#define BCHP_GIO_ODEN_EXT_HI                     0x2040a540 /* [RW][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[82:64] */
#define BCHP_GIO_DATA_EXT_HI                     0x2040a544 /* [RW][32] GENERAL PURPOSE I/O DATA FOR GPIO[82:64] */
#define BCHP_GIO_IODIR_EXT_HI                    0x2040a548 /* [RW][32] GENERAL PURPOSE I/O DIRECTION FOR GPIO[82:64] */
#define BCHP_GIO_EC_EXT_HI                       0x2040a54c /* [RW][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[82:64] */
#define BCHP_GIO_EI_EXT_HI                       0x2040a550 /* [RW][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[82:64] */
#define BCHP_GIO_MASK_EXT_HI                     0x2040a554 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[82:64] */
#define BCHP_GIO_LEVEL_EXT_HI                    0x2040a558 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[82:64] */
#define BCHP_GIO_STAT_EXT_HI                     0x2040a55c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[82:64] */
#define BCHP_GIO_ODEN_EXT                        0x2040a560 /* [RW][32] GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR SGPIO[1:0] */
#define BCHP_GIO_DATA_EXT                        0x2040a564 /* [RW][32] GENERAL PURPOSE I/O DATA FOR SGPIO[1:0] */
#define BCHP_GIO_IODIR_EXT                       0x2040a568 /* [RW][32] GENERAL PURPOSE I/O DIRECTION FOR SGPIO[1:0] */
#define BCHP_GIO_EC_EXT                          0x2040a56c /* [RW][32] GENERAL PURPOSE I/O EDGE CONFIGURATION FOR SGPIO[1:0] */
#define BCHP_GIO_EI_EXT                          0x2040a570 /* [RW][32] GENERAL PURPOSE I/O EDGE INSENSITIVE FOR SGPIO[1:0] */
#define BCHP_GIO_MASK_EXT                        0x2040a574 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT MASK FOR SGPIO[1:0] */
#define BCHP_GIO_LEVEL_EXT                       0x2040a578 /* [RW][32] GENERAL PURPOSE I/O INTERRUPT TYPE FOR SGPIO[1:0] */
#define BCHP_GIO_STAT_EXT                        0x2040a57c /* [RW][32] GENERAL PURPOSE I/O INTERRUPT STATUS FOR SGPIO[1:0] */

/***************************************************************************
 *ODEN_LO - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: ODEN_LO :: oden [31:00] */
#define BCHP_GIO_ODEN_LO_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_LO_oden_SHIFT                                0
#define BCHP_GIO_ODEN_LO_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_LO - GENERAL PURPOSE I/O DATA FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: DATA_LO :: data [31:00] */
#define BCHP_GIO_DATA_LO_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_LO_data_SHIFT                                0
#define BCHP_GIO_DATA_LO_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_LO - GENERAL PURPOSE I/O DIRECTION FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: IODIR_LO :: iodir [31:00] */
#define BCHP_GIO_IODIR_LO_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_LO_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_LO_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_LO - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: EC_LO :: edge_config [31:00] */
#define BCHP_GIO_EC_LO_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_LO_edge_config_SHIFT                           0
#define BCHP_GIO_EC_LO_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_LO - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: EI_LO :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_LO_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_LO_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_LO_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_LO - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: MASK_LO :: irq_mask [31:00] */
#define BCHP_GIO_MASK_LO_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_LO_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_LO_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_LO - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: LEVEL_LO :: level [31:00] */
#define BCHP_GIO_LEVEL_LO_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_LO_level_SHIFT                              0
#define BCHP_GIO_LEVEL_LO_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_LO - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[31:0]
 ***************************************************************************/
/* GIO :: STAT_LO :: irq_status [31:00] */
#define BCHP_GIO_STAT_LO_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_LO_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_LO_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: ODEN_HI :: oden [31:00] */
#define BCHP_GIO_ODEN_HI_oden_MASK                                 0xffffffff
#define BCHP_GIO_ODEN_HI_oden_SHIFT                                0
#define BCHP_GIO_ODEN_HI_oden_DEFAULT                              0x00000000

/***************************************************************************
 *DATA_HI - GENERAL PURPOSE I/O DATA FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: DATA_HI :: data [31:00] */
#define BCHP_GIO_DATA_HI_data_MASK                                 0xffffffff
#define BCHP_GIO_DATA_HI_data_SHIFT                                0
#define BCHP_GIO_DATA_HI_data_DEFAULT                              0x00000000

/***************************************************************************
 *IODIR_HI - GENERAL PURPOSE I/O DIRECTION FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: IODIR_HI :: iodir [31:00] */
#define BCHP_GIO_IODIR_HI_iodir_MASK                               0xffffffff
#define BCHP_GIO_IODIR_HI_iodir_SHIFT                              0
#define BCHP_GIO_IODIR_HI_iodir_DEFAULT                            0xffffffff

/***************************************************************************
 *EC_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: EC_HI :: edge_config [31:00] */
#define BCHP_GIO_EC_HI_edge_config_MASK                            0xffffffff
#define BCHP_GIO_EC_HI_edge_config_SHIFT                           0
#define BCHP_GIO_EC_HI_edge_config_DEFAULT                         0x00000000

/***************************************************************************
 *EI_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: EI_HI :: edge_insensitive [31:00] */
#define BCHP_GIO_EI_HI_edge_insensitive_MASK                       0xffffffff
#define BCHP_GIO_EI_HI_edge_insensitive_SHIFT                      0
#define BCHP_GIO_EI_HI_edge_insensitive_DEFAULT                    0x00000000

/***************************************************************************
 *MASK_HI - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: MASK_HI :: irq_mask [31:00] */
#define BCHP_GIO_MASK_HI_irq_mask_MASK                             0xffffffff
#define BCHP_GIO_MASK_HI_irq_mask_SHIFT                            0
#define BCHP_GIO_MASK_HI_irq_mask_DEFAULT                          0x00000000

/***************************************************************************
 *LEVEL_HI - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: LEVEL_HI :: level [31:00] */
#define BCHP_GIO_LEVEL_HI_level_MASK                               0xffffffff
#define BCHP_GIO_LEVEL_HI_level_SHIFT                              0
#define BCHP_GIO_LEVEL_HI_level_DEFAULT                            0x00000000

/***************************************************************************
 *STAT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[63:32]
 ***************************************************************************/
/* GIO :: STAT_HI :: irq_status [31:00] */
#define BCHP_GIO_STAT_HI_irq_status_MASK                           0xffffffff
#define BCHP_GIO_STAT_HI_irq_status_SHIFT                          0
#define BCHP_GIO_STAT_HI_irq_status_DEFAULT                        0x00000000

/***************************************************************************
 *ODEN_EXT_HI - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: ODEN_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_ODEN_EXT_HI_reserved0_MASK                        0xfff80000
#define BCHP_GIO_ODEN_EXT_HI_reserved0_SHIFT                       19

/* GIO :: ODEN_EXT_HI :: oden [18:00] */
#define BCHP_GIO_ODEN_EXT_HI_oden_MASK                             0x0007ffff
#define BCHP_GIO_ODEN_EXT_HI_oden_SHIFT                            0
#define BCHP_GIO_ODEN_EXT_HI_oden_DEFAULT                          0x00000000

/***************************************************************************
 *DATA_EXT_HI - GENERAL PURPOSE I/O DATA FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: DATA_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_DATA_EXT_HI_reserved0_MASK                        0xfff80000
#define BCHP_GIO_DATA_EXT_HI_reserved0_SHIFT                       19

/* GIO :: DATA_EXT_HI :: data [18:00] */
#define BCHP_GIO_DATA_EXT_HI_data_MASK                             0x0007ffff
#define BCHP_GIO_DATA_EXT_HI_data_SHIFT                            0
#define BCHP_GIO_DATA_EXT_HI_data_DEFAULT                          0x00000000

/***************************************************************************
 *IODIR_EXT_HI - GENERAL PURPOSE I/O DIRECTION FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: IODIR_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_IODIR_EXT_HI_reserved0_MASK                       0xfff80000
#define BCHP_GIO_IODIR_EXT_HI_reserved0_SHIFT                      19

/* GIO :: IODIR_EXT_HI :: iodir [18:00] */
#define BCHP_GIO_IODIR_EXT_HI_iodir_MASK                           0x0007ffff
#define BCHP_GIO_IODIR_EXT_HI_iodir_SHIFT                          0
#define BCHP_GIO_IODIR_EXT_HI_iodir_DEFAULT                        0x0007ffff

/***************************************************************************
 *EC_EXT_HI - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: EC_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_EC_EXT_HI_reserved0_MASK                          0xfff80000
#define BCHP_GIO_EC_EXT_HI_reserved0_SHIFT                         19

/* GIO :: EC_EXT_HI :: edge_config [18:00] */
#define BCHP_GIO_EC_EXT_HI_edge_config_MASK                        0x0007ffff
#define BCHP_GIO_EC_EXT_HI_edge_config_SHIFT                       0
#define BCHP_GIO_EC_EXT_HI_edge_config_DEFAULT                     0x00000000

/***************************************************************************
 *EI_EXT_HI - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: EI_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_EI_EXT_HI_reserved0_MASK                          0xfff80000
#define BCHP_GIO_EI_EXT_HI_reserved0_SHIFT                         19

/* GIO :: EI_EXT_HI :: edge_insensitive [18:00] */
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_MASK                   0x0007ffff
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_SHIFT                  0
#define BCHP_GIO_EI_EXT_HI_edge_insensitive_DEFAULT                0x00000000

/***************************************************************************
 *MASK_EXT_HI - GENERAL PURPOSE I/O INTERRUPT MASK FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: MASK_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_MASK_EXT_HI_reserved0_MASK                        0xfff80000
#define BCHP_GIO_MASK_EXT_HI_reserved0_SHIFT                       19

/* GIO :: MASK_EXT_HI :: irq_mask [18:00] */
#define BCHP_GIO_MASK_EXT_HI_irq_mask_MASK                         0x0007ffff
#define BCHP_GIO_MASK_EXT_HI_irq_mask_SHIFT                        0
#define BCHP_GIO_MASK_EXT_HI_irq_mask_DEFAULT                      0x00000000

/***************************************************************************
 *LEVEL_EXT_HI - GENERAL PURPOSE I/O INTERRUPT TYPE FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: LEVEL_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_LEVEL_EXT_HI_reserved0_MASK                       0xfff80000
#define BCHP_GIO_LEVEL_EXT_HI_reserved0_SHIFT                      19

/* GIO :: LEVEL_EXT_HI :: level [18:00] */
#define BCHP_GIO_LEVEL_EXT_HI_level_MASK                           0x0007ffff
#define BCHP_GIO_LEVEL_EXT_HI_level_SHIFT                          0
#define BCHP_GIO_LEVEL_EXT_HI_level_DEFAULT                        0x00000000

/***************************************************************************
 *STAT_EXT_HI - GENERAL PURPOSE I/O INTERRUPT STATUS FOR GPIO[82:64]
 ***************************************************************************/
/* GIO :: STAT_EXT_HI :: reserved0 [31:19] */
#define BCHP_GIO_STAT_EXT_HI_reserved0_MASK                        0xfff80000
#define BCHP_GIO_STAT_EXT_HI_reserved0_SHIFT                       19

/* GIO :: STAT_EXT_HI :: irq_status [18:00] */
#define BCHP_GIO_STAT_EXT_HI_irq_status_MASK                       0x0007ffff
#define BCHP_GIO_STAT_EXT_HI_irq_status_SHIFT                      0
#define BCHP_GIO_STAT_EXT_HI_irq_status_DEFAULT                    0x00000000

/***************************************************************************
 *ODEN_EXT - GENERAL PURPOSE I/O OPEN DRAIN ENABLE FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: ODEN_EXT :: reserved0 [31:02] */
#define BCHP_GIO_ODEN_EXT_reserved0_MASK                           0xfffffffc
#define BCHP_GIO_ODEN_EXT_reserved0_SHIFT                          2

/* GIO :: ODEN_EXT :: oden [01:00] */
#define BCHP_GIO_ODEN_EXT_oden_MASK                                0x00000003
#define BCHP_GIO_ODEN_EXT_oden_SHIFT                               0
#define BCHP_GIO_ODEN_EXT_oden_DEFAULT                             0x00000000

/***************************************************************************
 *DATA_EXT - GENERAL PURPOSE I/O DATA FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: DATA_EXT :: reserved0 [31:02] */
#define BCHP_GIO_DATA_EXT_reserved0_MASK                           0xfffffffc
#define BCHP_GIO_DATA_EXT_reserved0_SHIFT                          2

/* GIO :: DATA_EXT :: data [01:00] */
#define BCHP_GIO_DATA_EXT_data_MASK                                0x00000003
#define BCHP_GIO_DATA_EXT_data_SHIFT                               0
#define BCHP_GIO_DATA_EXT_data_DEFAULT                             0x00000000

/***************************************************************************
 *IODIR_EXT - GENERAL PURPOSE I/O DIRECTION FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: IODIR_EXT :: reserved0 [31:02] */
#define BCHP_GIO_IODIR_EXT_reserved0_MASK                          0xfffffffc
#define BCHP_GIO_IODIR_EXT_reserved0_SHIFT                         2

/* GIO :: IODIR_EXT :: iodir [01:00] */
#define BCHP_GIO_IODIR_EXT_iodir_MASK                              0x00000003
#define BCHP_GIO_IODIR_EXT_iodir_SHIFT                             0
#define BCHP_GIO_IODIR_EXT_iodir_DEFAULT                           0x00000003

/***************************************************************************
 *EC_EXT - GENERAL PURPOSE I/O EDGE CONFIGURATION FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: EC_EXT :: reserved0 [31:02] */
#define BCHP_GIO_EC_EXT_reserved0_MASK                             0xfffffffc
#define BCHP_GIO_EC_EXT_reserved0_SHIFT                            2

/* GIO :: EC_EXT :: edge_config [01:00] */
#define BCHP_GIO_EC_EXT_edge_config_MASK                           0x00000003
#define BCHP_GIO_EC_EXT_edge_config_SHIFT                          0
#define BCHP_GIO_EC_EXT_edge_config_DEFAULT                        0x00000000

/***************************************************************************
 *EI_EXT - GENERAL PURPOSE I/O EDGE INSENSITIVE FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: EI_EXT :: reserved0 [31:02] */
#define BCHP_GIO_EI_EXT_reserved0_MASK                             0xfffffffc
#define BCHP_GIO_EI_EXT_reserved0_SHIFT                            2

/* GIO :: EI_EXT :: edge_insensitive [01:00] */
#define BCHP_GIO_EI_EXT_edge_insensitive_MASK                      0x00000003
#define BCHP_GIO_EI_EXT_edge_insensitive_SHIFT                     0
#define BCHP_GIO_EI_EXT_edge_insensitive_DEFAULT                   0x00000000

/***************************************************************************
 *MASK_EXT - GENERAL PURPOSE I/O INTERRUPT MASK FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: MASK_EXT :: reserved0 [31:02] */
#define BCHP_GIO_MASK_EXT_reserved0_MASK                           0xfffffffc
#define BCHP_GIO_MASK_EXT_reserved0_SHIFT                          2

/* GIO :: MASK_EXT :: irq_mask [01:00] */
#define BCHP_GIO_MASK_EXT_irq_mask_MASK                            0x00000003
#define BCHP_GIO_MASK_EXT_irq_mask_SHIFT                           0
#define BCHP_GIO_MASK_EXT_irq_mask_DEFAULT                         0x00000000

/***************************************************************************
 *LEVEL_EXT - GENERAL PURPOSE I/O INTERRUPT TYPE FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: LEVEL_EXT :: reserved0 [31:02] */
#define BCHP_GIO_LEVEL_EXT_reserved0_MASK                          0xfffffffc
#define BCHP_GIO_LEVEL_EXT_reserved0_SHIFT                         2

/* GIO :: LEVEL_EXT :: level [01:00] */
#define BCHP_GIO_LEVEL_EXT_level_MASK                              0x00000003
#define BCHP_GIO_LEVEL_EXT_level_SHIFT                             0
#define BCHP_GIO_LEVEL_EXT_level_DEFAULT                           0x00000000

/***************************************************************************
 *STAT_EXT - GENERAL PURPOSE I/O INTERRUPT STATUS FOR SGPIO[1:0]
 ***************************************************************************/
/* GIO :: STAT_EXT :: reserved0 [31:02] */
#define BCHP_GIO_STAT_EXT_reserved0_MASK                           0xfffffffc
#define BCHP_GIO_STAT_EXT_reserved0_SHIFT                          2

/* GIO :: STAT_EXT :: irq_status [01:00] */
#define BCHP_GIO_STAT_EXT_irq_status_MASK                          0x00000003
#define BCHP_GIO_STAT_EXT_irq_status_SHIFT                         0
#define BCHP_GIO_STAT_EXT_irq_status_DEFAULT                       0x00000000

#endif /* #ifndef BCHP_GIO_H__ */

/* End of File */
