/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Dec  1 06:16:57 2016
 *                 Full Compile MD5 Checksum  d77d353b4fd33f3b3eb763c0ec6d13e9
 *                     (minus title and desc)
 *                 MD5 Checksum               b9f56ca31bb855d1e4c37875f6b45457
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_SDIO_0_HOST_H__
#define BCHP_SDIO_0_HOST_H__

/***************************************************************************
 *SDIO_0_HOST - SDIO (CARD0/EMMC0) Host Registers
 ***************************************************************************/
#define BCHP_SDIO_0_HOST_SDMA                    0x20200000 /* [RW][32] System DMA Address Register */
#define BCHP_SDIO_0_HOST_BLOCK                   0x20200004 /* [RW][32] Block Reset and Count Register */
#define BCHP_SDIO_0_HOST_ARGUMENT                0x20200008 /* [RW][32] Argument Register */
#define BCHP_SDIO_0_HOST_CMD_MODE                0x2020000c /* [RW][32] Command and Mode Register */
#define BCHP_SDIO_0_HOST_RESP_01                 0x20200010 /* [RO][32] Response Word 0 and 1 */
#define BCHP_SDIO_0_HOST_RESP_23                 0x20200014 /* [RO][32] Response Word 2 and 3 */
#define BCHP_SDIO_0_HOST_RESP_45                 0x20200018 /* [RO][32] Response Word 4 and 5 */
#define BCHP_SDIO_0_HOST_RESP_67                 0x2020001c /* [RO][32] Response Word 6 and 7 */
#define BCHP_SDIO_0_HOST_BUFFDATA                0x20200020 /* [RW][32] Buffer Data Port for PIO Tranfers */
#define BCHP_SDIO_0_HOST_STATE                   0x20200024 /* [RO][32] Present State of Controller */
#define BCHP_SDIO_0_HOST_CTRL_SET0               0x20200028 /* [RW][32] SD Standard Control Registers for Host, Power, BlockGap, WakeUp */
#define BCHP_SDIO_0_HOST_CTRL_SET1               0x2020002c /* [RW][32] SD Standard Control Registers for Clock, Timeout, Resets */
#define BCHP_SDIO_0_HOST_INT_STATUS              0x20200030 /* [RW][32] Interrupt Status for Normal and Error conditions */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA          0x20200034 /* [RW][32] Interrupt Enables for Normal and Error conditions */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA          0x20200038 /* [RW][32] Interrupt Signal Enables for Normal and Error conditions */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT          0x2020003c /* [RW][32] Auto Cmd12 Error Status */
#define BCHP_SDIO_0_HOST_CAPABLE                 0x20200040 /* [RO][32] Host Controller Capabilities to Software */
#define BCHP_SDIO_0_HOST_CAPABLE_1               0x20200044 /* [RO][32] Future Host Controller Capabilities to Software */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE           0x20200048 /* [RO][32] Host Controller Power Capabilities to Software */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_RSVD      0x2020004c /* [RO][32] Future Host Controller Power Capabilities to Software */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS            0x20200050 /* [RW][32] Force Events on Error Status Bits */
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT           0x20200054 /* [RO][32] ADMA Error Status Bits */
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_LO         0x20200058 /* [RW][32] ADMA System Address Low Bits */
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_HI         0x2020005c /* [RO][32] ADMA System Address High Bits */
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT     0x20200060 /* [RO][32] Preset Values for init and default speed */
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED       0x20200064 /* [RO][32] Preset Values for high speed and SDR12 */
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50         0x20200068 /* [RO][32] Preset Values for SDR25 and SDR50 */
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50     0x2020006c /* [RO][32] Preset Values for SDR104 and DDR50 */
#define BCHP_SDIO_0_HOST_BOOT_TIMEOUT            0x20200070 /* [RW][32] DAT line inactivity timeout on boot */
#define BCHP_SDIO_0_HOST_DEBUG_SELECT            0x20200074 /* [WO][32] Debug probe output selection */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL         0x202000e0 /* [RW][32] shared bus control */
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT           0x202000f0 /* [RW][32] SPI Interrupt support */
#define BCHP_SDIO_0_HOST_VERSION_STATUS          0x202000fc /* [RO][32] Controller Version and Slot Status */

/***************************************************************************
 *SDMA - System DMA Address Register
 ***************************************************************************/
/* SDIO_0_HOST :: SDMA :: ADDRESS [31:00] */
#define BCHP_SDIO_0_HOST_SDMA_ADDRESS_MASK                         0xffffffff
#define BCHP_SDIO_0_HOST_SDMA_ADDRESS_SHIFT                        0
#define BCHP_SDIO_0_HOST_SDMA_ADDRESS_DEFAULT                      0x00000000

/***************************************************************************
 *BLOCK - Block Reset and Count Register
 ***************************************************************************/
/* SDIO_0_HOST :: BLOCK :: TRANSFER_BLOCK_COUNT [31:16] */
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_COUNT_MASK           0xffff0000
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_COUNT_SHIFT          16
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_COUNT_DEFAULT        0x00000000

/* SDIO_0_HOST :: BLOCK :: TRANSFER_BLOCK_SIZE_MSB [15:15] */
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_MSB_MASK        0x00008000
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_MSB_SHIFT       15
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_MSB_DEFAULT     0x00000000

/* SDIO_0_HOST :: BLOCK :: HOST_BUFFER_SIZE [14:12] */
#define BCHP_SDIO_0_HOST_BLOCK_HOST_BUFFER_SIZE_MASK               0x00007000
#define BCHP_SDIO_0_HOST_BLOCK_HOST_BUFFER_SIZE_SHIFT              12
#define BCHP_SDIO_0_HOST_BLOCK_HOST_BUFFER_SIZE_DEFAULT            0x00000000

/* SDIO_0_HOST :: BLOCK :: TRANSFER_BLOCK_SIZE [11:00] */
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_MASK            0x00000fff
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_SHIFT           0
#define BCHP_SDIO_0_HOST_BLOCK_TRANSFER_BLOCK_SIZE_DEFAULT         0x00000000

/***************************************************************************
 *ARGUMENT - Argument Register
 ***************************************************************************/
/* SDIO_0_HOST :: ARGUMENT :: CMD_ARG1 [31:00] */
#define BCHP_SDIO_0_HOST_ARGUMENT_CMD_ARG1_MASK                    0xffffffff
#define BCHP_SDIO_0_HOST_ARGUMENT_CMD_ARG1_SHIFT                   0
#define BCHP_SDIO_0_HOST_ARGUMENT_CMD_ARG1_DEFAULT                 0x00000000

/***************************************************************************
 *CMD_MODE - Command and Mode Register
 ***************************************************************************/
/* SDIO_0_HOST :: CMD_MODE :: reserved0 [31:30] */
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved0_MASK                   0xc0000000
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved0_SHIFT                  30

/* SDIO_0_HOST :: CMD_MODE :: CMD_INDEX [29:24] */
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_MASK                   0x3f000000
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_SHIFT                  24
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_DEFAULT                0x00000000

/* SDIO_0_HOST :: CMD_MODE :: CMD_TYPE [23:22] */
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_TYPE_MASK                    0x00c00000
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_TYPE_SHIFT                   22
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_TYPE_DEFAULT                 0x00000000

/* SDIO_0_HOST :: CMD_MODE :: DATA_PRESENT [21:21] */
#define BCHP_SDIO_0_HOST_CMD_MODE_DATA_PRESENT_MASK                0x00200000
#define BCHP_SDIO_0_HOST_CMD_MODE_DATA_PRESENT_SHIFT               21
#define BCHP_SDIO_0_HOST_CMD_MODE_DATA_PRESENT_DEFAULT             0x00000000

/* SDIO_0_HOST :: CMD_MODE :: CMD_INDEX_CHECK [20:20] */
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_CHECK_MASK             0x00100000
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_CHECK_SHIFT            20
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_INDEX_CHECK_DEFAULT          0x00000000

/* SDIO_0_HOST :: CMD_MODE :: CMD_CRC_CHECK [19:19] */
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_CRC_CHECK_MASK               0x00080000
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_CRC_CHECK_SHIFT              19
#define BCHP_SDIO_0_HOST_CMD_MODE_CMD_CRC_CHECK_DEFAULT            0x00000000

/* SDIO_0_HOST :: CMD_MODE :: reserved1 [18:18] */
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved1_MASK                   0x00040000
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved1_SHIFT                  18

/* SDIO_0_HOST :: CMD_MODE :: RESPONSE_TYPE [17:16] */
#define BCHP_SDIO_0_HOST_CMD_MODE_RESPONSE_TYPE_MASK               0x00030000
#define BCHP_SDIO_0_HOST_CMD_MODE_RESPONSE_TYPE_SHIFT              16
#define BCHP_SDIO_0_HOST_CMD_MODE_RESPONSE_TYPE_DEFAULT            0x00000000

/* SDIO_0_HOST :: CMD_MODE :: reserved2 [15:07] */
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved2_MASK                   0x0000ff80
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved2_SHIFT                  7

/* SDIO_0_HOST :: CMD_MODE :: reserved_for_eco3 [06:06] */
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved_for_eco3_MASK           0x00000040
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved_for_eco3_SHIFT          6
#define BCHP_SDIO_0_HOST_CMD_MODE_reserved_for_eco3_DEFAULT        0x00000000

/* SDIO_0_HOST :: CMD_MODE :: MULTI_BLOCK [05:05] */
#define BCHP_SDIO_0_HOST_CMD_MODE_MULTI_BLOCK_MASK                 0x00000020
#define BCHP_SDIO_0_HOST_CMD_MODE_MULTI_BLOCK_SHIFT                5
#define BCHP_SDIO_0_HOST_CMD_MODE_MULTI_BLOCK_DEFAULT              0x00000000

/* SDIO_0_HOST :: CMD_MODE :: TRANFER_WRITE [04:04] */
#define BCHP_SDIO_0_HOST_CMD_MODE_TRANFER_WRITE_MASK               0x00000010
#define BCHP_SDIO_0_HOST_CMD_MODE_TRANFER_WRITE_SHIFT              4
#define BCHP_SDIO_0_HOST_CMD_MODE_TRANFER_WRITE_DEFAULT            0x00000000

/* SDIO_0_HOST :: CMD_MODE :: AUTO_CMD_ENA [03:02] */
#define BCHP_SDIO_0_HOST_CMD_MODE_AUTO_CMD_ENA_MASK                0x0000000c
#define BCHP_SDIO_0_HOST_CMD_MODE_AUTO_CMD_ENA_SHIFT               2
#define BCHP_SDIO_0_HOST_CMD_MODE_AUTO_CMD_ENA_DEFAULT             0x00000000

/* SDIO_0_HOST :: CMD_MODE :: BLOCK_COUNT_ENABLE [01:01] */
#define BCHP_SDIO_0_HOST_CMD_MODE_BLOCK_COUNT_ENABLE_MASK          0x00000002
#define BCHP_SDIO_0_HOST_CMD_MODE_BLOCK_COUNT_ENABLE_SHIFT         1
#define BCHP_SDIO_0_HOST_CMD_MODE_BLOCK_COUNT_ENABLE_DEFAULT       0x00000000

/* SDIO_0_HOST :: CMD_MODE :: DMA_ENABLE [00:00] */
#define BCHP_SDIO_0_HOST_CMD_MODE_DMA_ENABLE_MASK                  0x00000001
#define BCHP_SDIO_0_HOST_CMD_MODE_DMA_ENABLE_SHIFT                 0
#define BCHP_SDIO_0_HOST_CMD_MODE_DMA_ENABLE_DEFAULT               0x00000000

/***************************************************************************
 *RESP_01 - Response Word 0 and 1
 ***************************************************************************/
/* SDIO_0_HOST :: RESP_01 :: RESP_HI [31:16] */
#define BCHP_SDIO_0_HOST_RESP_01_RESP_HI_MASK                      0xffff0000
#define BCHP_SDIO_0_HOST_RESP_01_RESP_HI_SHIFT                     16
#define BCHP_SDIO_0_HOST_RESP_01_RESP_HI_DEFAULT                   0x00000000

/* SDIO_0_HOST :: RESP_01 :: RESP_LO [15:00] */
#define BCHP_SDIO_0_HOST_RESP_01_RESP_LO_MASK                      0x0000ffff
#define BCHP_SDIO_0_HOST_RESP_01_RESP_LO_SHIFT                     0
#define BCHP_SDIO_0_HOST_RESP_01_RESP_LO_DEFAULT                   0x00000000

/***************************************************************************
 *RESP_23 - Response Word 2 and 3
 ***************************************************************************/
/* SDIO_0_HOST :: RESP_23 :: RESP_HI [31:16] */
#define BCHP_SDIO_0_HOST_RESP_23_RESP_HI_MASK                      0xffff0000
#define BCHP_SDIO_0_HOST_RESP_23_RESP_HI_SHIFT                     16
#define BCHP_SDIO_0_HOST_RESP_23_RESP_HI_DEFAULT                   0x00000000

/* SDIO_0_HOST :: RESP_23 :: RESP_LO [15:00] */
#define BCHP_SDIO_0_HOST_RESP_23_RESP_LO_MASK                      0x0000ffff
#define BCHP_SDIO_0_HOST_RESP_23_RESP_LO_SHIFT                     0
#define BCHP_SDIO_0_HOST_RESP_23_RESP_LO_DEFAULT                   0x00000000

/***************************************************************************
 *RESP_45 - Response Word 4 and 5
 ***************************************************************************/
/* SDIO_0_HOST :: RESP_45 :: RESP_HI [31:16] */
#define BCHP_SDIO_0_HOST_RESP_45_RESP_HI_MASK                      0xffff0000
#define BCHP_SDIO_0_HOST_RESP_45_RESP_HI_SHIFT                     16
#define BCHP_SDIO_0_HOST_RESP_45_RESP_HI_DEFAULT                   0x00000000

/* SDIO_0_HOST :: RESP_45 :: RESP_LO [15:00] */
#define BCHP_SDIO_0_HOST_RESP_45_RESP_LO_MASK                      0x0000ffff
#define BCHP_SDIO_0_HOST_RESP_45_RESP_LO_SHIFT                     0
#define BCHP_SDIO_0_HOST_RESP_45_RESP_LO_DEFAULT                   0x00000000

/***************************************************************************
 *RESP_67 - Response Word 6 and 7
 ***************************************************************************/
/* SDIO_0_HOST :: RESP_67 :: RESP_HI [31:16] */
#define BCHP_SDIO_0_HOST_RESP_67_RESP_HI_MASK                      0xffff0000
#define BCHP_SDIO_0_HOST_RESP_67_RESP_HI_SHIFT                     16
#define BCHP_SDIO_0_HOST_RESP_67_RESP_HI_DEFAULT                   0x00000000

/* SDIO_0_HOST :: RESP_67 :: RESP_LO [15:00] */
#define BCHP_SDIO_0_HOST_RESP_67_RESP_LO_MASK                      0x0000ffff
#define BCHP_SDIO_0_HOST_RESP_67_RESP_LO_SHIFT                     0
#define BCHP_SDIO_0_HOST_RESP_67_RESP_LO_DEFAULT                   0x00000000

/***************************************************************************
 *BUFFDATA - Buffer Data Port for PIO Tranfers
 ***************************************************************************/
/* SDIO_0_HOST :: BUFFDATA :: PORT [31:00] */
#define BCHP_SDIO_0_HOST_BUFFDATA_PORT_MASK                        0xffffffff
#define BCHP_SDIO_0_HOST_BUFFDATA_PORT_SHIFT                       0
#define BCHP_SDIO_0_HOST_BUFFDATA_PORT_DEFAULT                     0x00000000

/***************************************************************************
 *STATE - Present State of Controller
 ***************************************************************************/
/* SDIO_0_HOST :: STATE :: reserved0 [31:29] */
#define BCHP_SDIO_0_HOST_STATE_reserved0_MASK                      0xe0000000
#define BCHP_SDIO_0_HOST_STATE_reserved0_SHIFT                     29

/* SDIO_0_HOST :: STATE :: LINE_7TO4 [28:25] */
#define BCHP_SDIO_0_HOST_STATE_LINE_7TO4_MASK                      0x1e000000
#define BCHP_SDIO_0_HOST_STATE_LINE_7TO4_SHIFT                     25
#define BCHP_SDIO_0_HOST_STATE_LINE_7TO4_DEFAULT                   0x0000000f

/* SDIO_0_HOST :: STATE :: LINE_CMD [24:24] */
#define BCHP_SDIO_0_HOST_STATE_LINE_CMD_MASK                       0x01000000
#define BCHP_SDIO_0_HOST_STATE_LINE_CMD_SHIFT                      24
#define BCHP_SDIO_0_HOST_STATE_LINE_CMD_DEFAULT                    0x00000001

/* SDIO_0_HOST :: STATE :: LINE_3TO0 [23:20] */
#define BCHP_SDIO_0_HOST_STATE_LINE_3TO0_MASK                      0x00f00000
#define BCHP_SDIO_0_HOST_STATE_LINE_3TO0_SHIFT                     20
#define BCHP_SDIO_0_HOST_STATE_LINE_3TO0_DEFAULT                   0x0000000f

/* SDIO_0_HOST :: STATE :: WP_LEVEL [19:19] */
#define BCHP_SDIO_0_HOST_STATE_WP_LEVEL_MASK                       0x00080000
#define BCHP_SDIO_0_HOST_STATE_WP_LEVEL_SHIFT                      19

/* SDIO_0_HOST :: STATE :: CD_LEVEL [18:18] */
#define BCHP_SDIO_0_HOST_STATE_CD_LEVEL_MASK                       0x00040000
#define BCHP_SDIO_0_HOST_STATE_CD_LEVEL_SHIFT                      18

/* SDIO_0_HOST :: STATE :: CD_STABLE [17:17] */
#define BCHP_SDIO_0_HOST_STATE_CD_STABLE_MASK                      0x00020000
#define BCHP_SDIO_0_HOST_STATE_CD_STABLE_SHIFT                     17

/* SDIO_0_HOST :: STATE :: CARD_INSERTED [16:16] */
#define BCHP_SDIO_0_HOST_STATE_CARD_INSERTED_MASK                  0x00010000
#define BCHP_SDIO_0_HOST_STATE_CARD_INSERTED_SHIFT                 16

/* SDIO_0_HOST :: STATE :: reserved1 [15:12] */
#define BCHP_SDIO_0_HOST_STATE_reserved1_MASK                      0x0000f000
#define BCHP_SDIO_0_HOST_STATE_reserved1_SHIFT                     12

/* SDIO_0_HOST :: STATE :: BUFF_RDEN [11:11] */
#define BCHP_SDIO_0_HOST_STATE_BUFF_RDEN_MASK                      0x00000800
#define BCHP_SDIO_0_HOST_STATE_BUFF_RDEN_SHIFT                     11
#define BCHP_SDIO_0_HOST_STATE_BUFF_RDEN_DEFAULT                   0x00000000

/* SDIO_0_HOST :: STATE :: BUFF_WREN [10:10] */
#define BCHP_SDIO_0_HOST_STATE_BUFF_WREN_MASK                      0x00000400
#define BCHP_SDIO_0_HOST_STATE_BUFF_WREN_SHIFT                     10
#define BCHP_SDIO_0_HOST_STATE_BUFF_WREN_DEFAULT                   0x00000000

/* SDIO_0_HOST :: STATE :: RD_ACTIVE [09:09] */
#define BCHP_SDIO_0_HOST_STATE_RD_ACTIVE_MASK                      0x00000200
#define BCHP_SDIO_0_HOST_STATE_RD_ACTIVE_SHIFT                     9
#define BCHP_SDIO_0_HOST_STATE_RD_ACTIVE_DEFAULT                   0x00000000

/* SDIO_0_HOST :: STATE :: WR_ACTIVE [08:08] */
#define BCHP_SDIO_0_HOST_STATE_WR_ACTIVE_MASK                      0x00000100
#define BCHP_SDIO_0_HOST_STATE_WR_ACTIVE_SHIFT                     8
#define BCHP_SDIO_0_HOST_STATE_WR_ACTIVE_DEFAULT                   0x00000000

/* SDIO_0_HOST :: STATE :: reserved2 [07:04] */
#define BCHP_SDIO_0_HOST_STATE_reserved2_MASK                      0x000000f0
#define BCHP_SDIO_0_HOST_STATE_reserved2_SHIFT                     4

/* SDIO_0_HOST :: STATE :: RE_TUNING_REQUEST [03:03] */
#define BCHP_SDIO_0_HOST_STATE_RE_TUNING_REQUEST_MASK              0x00000008
#define BCHP_SDIO_0_HOST_STATE_RE_TUNING_REQUEST_SHIFT             3
#define BCHP_SDIO_0_HOST_STATE_RE_TUNING_REQUEST_DEFAULT           0x00000000

/* SDIO_0_HOST :: STATE :: DAT_ACTIVE [02:02] */
#define BCHP_SDIO_0_HOST_STATE_DAT_ACTIVE_MASK                     0x00000004
#define BCHP_SDIO_0_HOST_STATE_DAT_ACTIVE_SHIFT                    2
#define BCHP_SDIO_0_HOST_STATE_DAT_ACTIVE_DEFAULT                  0x00000000

/* SDIO_0_HOST :: STATE :: CMD_INHIBIT_DAT [01:01] */
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_DAT_MASK                0x00000002
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_DAT_SHIFT               1
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_DAT_DEFAULT             0x00000000

/* SDIO_0_HOST :: STATE :: CMD_INHIBIT_CMD [00:00] */
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_CMD_MASK                0x00000001
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_CMD_SHIFT               0
#define BCHP_SDIO_0_HOST_STATE_CMD_INHIBIT_CMD_DEFAULT             0x00000000

/***************************************************************************
 *CTRL_SET0 - SD Standard Control Registers for Host, Power, BlockGap, WakeUp
 ***************************************************************************/
/* SDIO_0_HOST :: CTRL_SET0 :: reserved0 [31:27] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_reserved0_MASK                  0xf8000000
#define BCHP_SDIO_0_HOST_CTRL_SET0_reserved0_SHIFT                 27

/* SDIO_0_HOST :: CTRL_SET0 :: WAKE_ON_REMOVAL [26:26] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_REMOVAL_MASK            0x04000000
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_REMOVAL_SHIFT           26
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_REMOVAL_DEFAULT         0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: WAKE_ON_INSERTION [25:25] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INSERTION_MASK          0x02000000
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INSERTION_SHIFT         25
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INSERTION_DEFAULT       0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: WAKE_ON_INTERRUPT [24:24] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INTERRUPT_MASK          0x01000000
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INTERRUPT_SHIFT         24
#define BCHP_SDIO_0_HOST_CTRL_SET0_WAKE_ON_INTERRUPT_DEFAULT       0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: BOOT_ACK [23:23] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_ACK_MASK                   0x00800000
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_ACK_SHIFT                  23
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_ACK_DEFAULT                0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: ALT_BOOT_EN [22:22] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_ALT_BOOT_EN_MASK                0x00400000
#define BCHP_SDIO_0_HOST_CTRL_SET0_ALT_BOOT_EN_SHIFT               22
#define BCHP_SDIO_0_HOST_CTRL_SET0_ALT_BOOT_EN_DEFAULT             0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: BOOT_EN [21:21] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_EN_MASK                    0x00200000
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_EN_SHIFT                   21
#define BCHP_SDIO_0_HOST_CTRL_SET0_BOOT_EN_DEFAULT                 0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: SPI_MODE [20:20] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_SPI_MODE_MASK                   0x00100000
#define BCHP_SDIO_0_HOST_CTRL_SET0_SPI_MODE_SHIFT                  20
#define BCHP_SDIO_0_HOST_CTRL_SET0_SPI_MODE_DEFAULT                0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: INT_AT_BLOCK_GAP [19:19] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_INT_AT_BLOCK_GAP_MASK           0x00080000
#define BCHP_SDIO_0_HOST_CTRL_SET0_INT_AT_BLOCK_GAP_SHIFT          19
#define BCHP_SDIO_0_HOST_CTRL_SET0_INT_AT_BLOCK_GAP_DEFAULT        0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: READ_WAIT_CTRL [18:18] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_READ_WAIT_CTRL_MASK             0x00040000
#define BCHP_SDIO_0_HOST_CTRL_SET0_READ_WAIT_CTRL_SHIFT            18
#define BCHP_SDIO_0_HOST_CTRL_SET0_READ_WAIT_CTRL_DEFAULT          0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: CONTINUE_REQUESTS [17:17] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_CONTINUE_REQUESTS_MASK          0x00020000
#define BCHP_SDIO_0_HOST_CTRL_SET0_CONTINUE_REQUESTS_SHIFT         17
#define BCHP_SDIO_0_HOST_CTRL_SET0_CONTINUE_REQUESTS_DEFAULT       0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: STOP_AT_BLOCK_GAP [16:16] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_STOP_AT_BLOCK_GAP_MASK          0x00010000
#define BCHP_SDIO_0_HOST_CTRL_SET0_STOP_AT_BLOCK_GAP_SHIFT         16
#define BCHP_SDIO_0_HOST_CTRL_SET0_STOP_AT_BLOCK_GAP_DEFAULT       0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: reserved1 [15:13] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_reserved1_MASK                  0x0000e000
#define BCHP_SDIO_0_HOST_CTRL_SET0_reserved1_SHIFT                 13

/* SDIO_0_HOST :: CTRL_SET0 :: HW_RESET [12:12] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_HW_RESET_MASK                   0x00001000
#define BCHP_SDIO_0_HOST_CTRL_SET0_HW_RESET_SHIFT                  12
#define BCHP_SDIO_0_HOST_CTRL_SET0_HW_RESET_DEFAULT                0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: SD_BUS_VOLTAGE_SELECT [11:09] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_VOLTAGE_SELECT_MASK      0x00000e00
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_VOLTAGE_SELECT_SHIFT     9
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_VOLTAGE_SELECT_DEFAULT   0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: SD_BUS_POWER [08:08] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_POWER_MASK               0x00000100
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_POWER_SHIFT              8
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_BUS_POWER_DEFAULT            0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: CARD_DETECT_SELECT [07:07] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_SELECT_MASK         0x00000080
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_SELECT_SHIFT        7
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_SELECT_DEFAULT      0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: CARD_DETECT_TEST [06:06] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_TEST_MASK           0x00000040
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_TEST_SHIFT          6
#define BCHP_SDIO_0_HOST_CTRL_SET0_CARD_DETECT_TEST_DEFAULT        0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: SD_8BIT_MODE [05:05] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_8BIT_MODE_MASK               0x00000020
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_8BIT_MODE_SHIFT              5
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_8BIT_MODE_DEFAULT            0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: DMA_SELECT [04:03] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_DMA_SELECT_MASK                 0x00000018
#define BCHP_SDIO_0_HOST_CTRL_SET0_DMA_SELECT_SHIFT                3
#define BCHP_SDIO_0_HOST_CTRL_SET0_DMA_SELECT_DEFAULT              0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: HIGH_SPEED_ENABLE [02:02] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_HIGH_SPEED_ENABLE_MASK          0x00000004
#define BCHP_SDIO_0_HOST_CTRL_SET0_HIGH_SPEED_ENABLE_SHIFT         2
#define BCHP_SDIO_0_HOST_CTRL_SET0_HIGH_SPEED_ENABLE_DEFAULT       0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: SD_4BIT_MODE [01:01] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_4BIT_MODE_MASK               0x00000002
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_4BIT_MODE_SHIFT              1
#define BCHP_SDIO_0_HOST_CTRL_SET0_SD_4BIT_MODE_DEFAULT            0x00000000

/* SDIO_0_HOST :: CTRL_SET0 :: LED_CONTROL [00:00] */
#define BCHP_SDIO_0_HOST_CTRL_SET0_LED_CONTROL_MASK                0x00000001
#define BCHP_SDIO_0_HOST_CTRL_SET0_LED_CONTROL_SHIFT               0
#define BCHP_SDIO_0_HOST_CTRL_SET0_LED_CONTROL_DEFAULT             0x00000000

/***************************************************************************
 *CTRL_SET1 - SD Standard Control Registers for Clock, Timeout, Resets
 ***************************************************************************/
/* SDIO_0_HOST :: CTRL_SET1 :: reserved0 [31:27] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved0_MASK                  0xf8000000
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved0_SHIFT                 27

/* SDIO_0_HOST :: CTRL_SET1 :: SOFT_RESET_DAT [26:26] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_DAT_MASK             0x04000000
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_DAT_SHIFT            26
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_DAT_DEFAULT          0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: SOFT_RESET_CMD [25:25] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CMD_MASK             0x02000000
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CMD_SHIFT            25
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CMD_DEFAULT          0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: SOFT_RESET_CORE [24:24] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CORE_MASK            0x01000000
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CORE_SHIFT           24
#define BCHP_SDIO_0_HOST_CTRL_SET1_SOFT_RESET_CORE_DEFAULT         0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: reserved1 [23:20] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved1_MASK                  0x00f00000
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved1_SHIFT                 20

/* SDIO_0_HOST :: CTRL_SET1 :: TIMEOUT_COUNT [19:16] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_TIMEOUT_COUNT_MASK              0x000f0000
#define BCHP_SDIO_0_HOST_CTRL_SET1_TIMEOUT_COUNT_SHIFT             16
#define BCHP_SDIO_0_HOST_CTRL_SET1_TIMEOUT_COUNT_DEFAULT           0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: FREQ_CTRL [15:08] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_FREQ_CTRL_MASK                  0x0000ff00
#define BCHP_SDIO_0_HOST_CTRL_SET1_FREQ_CTRL_SHIFT                 8
#define BCHP_SDIO_0_HOST_CTRL_SET1_FREQ_CTRL_DEFAULT               0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: MS_CLK_FREQ [07:06] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_MS_CLK_FREQ_MASK                0x000000c0
#define BCHP_SDIO_0_HOST_CTRL_SET1_MS_CLK_FREQ_SHIFT               6
#define BCHP_SDIO_0_HOST_CTRL_SET1_MS_CLK_FREQ_DEFAULT             0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: CLK_GEN_SEL [05:05] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_CLK_GEN_SEL_MASK                0x00000020
#define BCHP_SDIO_0_HOST_CTRL_SET1_CLK_GEN_SEL_SHIFT               5
#define BCHP_SDIO_0_HOST_CTRL_SET1_CLK_GEN_SEL_DEFAULT             0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: reserved2 [04:03] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved2_MASK                  0x00000018
#define BCHP_SDIO_0_HOST_CTRL_SET1_reserved2_SHIFT                 3

/* SDIO_0_HOST :: CTRL_SET1 :: SD_CLK_ENA [02:02] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_SD_CLK_ENA_MASK                 0x00000004
#define BCHP_SDIO_0_HOST_CTRL_SET1_SD_CLK_ENA_SHIFT                2
#define BCHP_SDIO_0_HOST_CTRL_SET1_SD_CLK_ENA_DEFAULT              0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: INTERNAL_CLK_STABLE [01:01] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_STABLE_MASK        0x00000002
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_STABLE_SHIFT       1
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_STABLE_DEFAULT     0x00000000

/* SDIO_0_HOST :: CTRL_SET1 :: INTERNAL_CLK_ENA [00:00] */
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_ENA_MASK           0x00000001
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_ENA_SHIFT          0
#define BCHP_SDIO_0_HOST_CTRL_SET1_INTERNAL_CLK_ENA_DEFAULT        0x00000000

/***************************************************************************
 *INT_STATUS - Interrupt Status for Normal and Error conditions
 ***************************************************************************/
/* SDIO_0_HOST :: INT_STATUS :: reserved0 [31:29] */
#define BCHP_SDIO_0_HOST_INT_STATUS_reserved0_MASK                 0xe0000000
#define BCHP_SDIO_0_HOST_INT_STATUS_reserved0_SHIFT                29

/* SDIO_0_HOST :: INT_STATUS :: TARGET_RESP_ERR_INT [28:28] */
#define BCHP_SDIO_0_HOST_INT_STATUS_TARGET_RESP_ERR_INT_MASK       0x10000000
#define BCHP_SDIO_0_HOST_INT_STATUS_TARGET_RESP_ERR_INT_SHIFT      28
#define BCHP_SDIO_0_HOST_INT_STATUS_TARGET_RESP_ERR_INT_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_STATUS :: reserved1 [27:27] */
#define BCHP_SDIO_0_HOST_INT_STATUS_reserved1_MASK                 0x08000000
#define BCHP_SDIO_0_HOST_INT_STATUS_reserved1_SHIFT                27

/* SDIO_0_HOST :: INT_STATUS :: TUNE_ERR [26:26] */
#define BCHP_SDIO_0_HOST_INT_STATUS_TUNE_ERR_MASK                  0x04000000
#define BCHP_SDIO_0_HOST_INT_STATUS_TUNE_ERR_SHIFT                 26
#define BCHP_SDIO_0_HOST_INT_STATUS_TUNE_ERR_DEFAULT               0x00000000

/* SDIO_0_HOST :: INT_STATUS :: ADMA_ERR_INT [25:25] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ADMA_ERR_INT_MASK              0x02000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ADMA_ERR_INT_SHIFT             25
#define BCHP_SDIO_0_HOST_INT_STATUS_ADMA_ERR_INT_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_STATUS :: AUTO_CMD_ERR_INT [24:24] */
#define BCHP_SDIO_0_HOST_INT_STATUS_AUTO_CMD_ERR_INT_MASK          0x01000000
#define BCHP_SDIO_0_HOST_INT_STATUS_AUTO_CMD_ERR_INT_SHIFT         24
#define BCHP_SDIO_0_HOST_INT_STATUS_AUTO_CMD_ERR_INT_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CURRENT_LIMIT_ERR_INT [23:23] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CURRENT_LIMIT_ERR_INT_MASK     0x00800000
#define BCHP_SDIO_0_HOST_INT_STATUS_CURRENT_LIMIT_ERR_INT_SHIFT    23
#define BCHP_SDIO_0_HOST_INT_STATUS_CURRENT_LIMIT_ERR_INT_DEFAULT  0x00000000

/* SDIO_0_HOST :: INT_STATUS :: DATA_END_BIT_ERR_INT [22:22] */
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_END_BIT_ERR_INT_MASK      0x00400000
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_END_BIT_ERR_INT_SHIFT     22
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_END_BIT_ERR_INT_DEFAULT   0x00000000

/* SDIO_0_HOST :: INT_STATUS :: DATA_CRC_ERR_INT [21:21] */
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_CRC_ERR_INT_MASK          0x00200000
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_CRC_ERR_INT_SHIFT         21
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_CRC_ERR_INT_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS :: DATA_TIMEOUT_ERR_INT [20:20] */
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_TIMEOUT_ERR_INT_MASK      0x00100000
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_TIMEOUT_ERR_INT_SHIFT     20
#define BCHP_SDIO_0_HOST_INT_STATUS_DATA_TIMEOUT_ERR_INT_DEFAULT   0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CMD_INDEX_ERR_INT [19:19] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_INDEX_ERR_INT_MASK         0x00080000
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_INDEX_ERR_INT_SHIFT        19
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_INDEX_ERR_INT_DEFAULT      0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CMD_END_BIT_ERR_INT [18:18] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_END_BIT_ERR_INT_MASK       0x00040000
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_END_BIT_ERR_INT_SHIFT      18
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_END_BIT_ERR_INT_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CMD_CRC_ERR_INT [17:17] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_CRC_ERR_INT_MASK           0x00020000
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_CRC_ERR_INT_SHIFT          17
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_CRC_ERR_INT_DEFAULT        0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CMD_TIMEOUT_ERR_INT [16:16] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_TIMEOUT_ERR_INT_MASK       0x00010000
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_TIMEOUT_ERR_INT_SHIFT      16
#define BCHP_SDIO_0_HOST_INT_STATUS_CMD_TIMEOUT_ERR_INT_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_STATUS :: ERROR_INT [15:15] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ERROR_INT_MASK                 0x00008000
#define BCHP_SDIO_0_HOST_INT_STATUS_ERROR_INT_SHIFT                15
#define BCHP_SDIO_0_HOST_INT_STATUS_ERROR_INT_DEFAULT              0x00000000

/* SDIO_0_HOST :: INT_STATUS :: BOOT_TERM_INT [14:14] */
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_TERM_INT_MASK             0x00004000
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_TERM_INT_SHIFT            14
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_TERM_INT_DEFAULT          0x00000000

/* SDIO_0_HOST :: INT_STATUS :: BOOT_ACK_RCV_INT [13:13] */
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_ACK_RCV_INT_MASK          0x00002000
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_ACK_RCV_INT_SHIFT         13
#define BCHP_SDIO_0_HOST_INT_STATUS_BOOT_ACK_RCV_INT_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS :: RETUNE_EVENT [12:12] */
#define BCHP_SDIO_0_HOST_INT_STATUS_RETUNE_EVENT_MASK              0x00001000
#define BCHP_SDIO_0_HOST_INT_STATUS_RETUNE_EVENT_SHIFT             12
#define BCHP_SDIO_0_HOST_INT_STATUS_RETUNE_EVENT_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_STATUS :: INT_C [11:11] */
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_C_MASK                     0x00000800
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_C_SHIFT                    11
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_C_DEFAULT                  0x00000000

/* SDIO_0_HOST :: INT_STATUS :: INT_B [10:10] */
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_B_MASK                     0x00000400
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_B_SHIFT                    10
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_B_DEFAULT                  0x00000000

/* SDIO_0_HOST :: INT_STATUS :: INT_A [09:09] */
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_A_MASK                     0x00000200
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_A_SHIFT                    9
#define BCHP_SDIO_0_HOST_INT_STATUS_INT_A_DEFAULT                  0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CARD_INT [08:08] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CARD_INT_MASK                  0x00000100
#define BCHP_SDIO_0_HOST_INT_STATUS_CARD_INT_SHIFT                 8
#define BCHP_SDIO_0_HOST_INT_STATUS_CARD_INT_DEFAULT               0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CAR_REMOVAL_INT [07:07] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_REMOVAL_INT_MASK           0x00000080
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_REMOVAL_INT_SHIFT          7
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_REMOVAL_INT_DEFAULT        0x00000000

/* SDIO_0_HOST :: INT_STATUS :: CAR_INSERT_INT [06:06] */
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_INSERT_INT_MASK            0x00000040
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_INSERT_INT_SHIFT           6
#define BCHP_SDIO_0_HOST_INT_STATUS_CAR_INSERT_INT_DEFAULT         0x00000000

/* SDIO_0_HOST :: INT_STATUS :: BUFFER_READ_INT [05:05] */
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_READ_INT_MASK           0x00000020
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_READ_INT_SHIFT          5
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_READ_INT_DEFAULT        0x00000000

/* SDIO_0_HOST :: INT_STATUS :: BUFFER_WRITE_INT [04:04] */
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_WRITE_INT_MASK          0x00000010
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_WRITE_INT_SHIFT         4
#define BCHP_SDIO_0_HOST_INT_STATUS_BUFFER_WRITE_INT_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS :: DMA_INT [03:03] */
#define BCHP_SDIO_0_HOST_INT_STATUS_DMA_INT_MASK                   0x00000008
#define BCHP_SDIO_0_HOST_INT_STATUS_DMA_INT_SHIFT                  3
#define BCHP_SDIO_0_HOST_INT_STATUS_DMA_INT_DEFAULT                0x00000000

/* SDIO_0_HOST :: INT_STATUS :: BLOCK_GAP_INT [02:02] */
#define BCHP_SDIO_0_HOST_INT_STATUS_BLOCK_GAP_INT_MASK             0x00000004
#define BCHP_SDIO_0_HOST_INT_STATUS_BLOCK_GAP_INT_SHIFT            2
#define BCHP_SDIO_0_HOST_INT_STATUS_BLOCK_GAP_INT_DEFAULT          0x00000000

/* SDIO_0_HOST :: INT_STATUS :: TRANSFER_COMPLETE_INT [01:01] */
#define BCHP_SDIO_0_HOST_INT_STATUS_TRANSFER_COMPLETE_INT_MASK     0x00000002
#define BCHP_SDIO_0_HOST_INT_STATUS_TRANSFER_COMPLETE_INT_SHIFT    1
#define BCHP_SDIO_0_HOST_INT_STATUS_TRANSFER_COMPLETE_INT_DEFAULT  0x00000000

/* SDIO_0_HOST :: INT_STATUS :: COMMAND_COMPLETE_INT [00:00] */
#define BCHP_SDIO_0_HOST_INT_STATUS_COMMAND_COMPLETE_INT_MASK      0x00000001
#define BCHP_SDIO_0_HOST_INT_STATUS_COMMAND_COMPLETE_INT_SHIFT     0
#define BCHP_SDIO_0_HOST_INT_STATUS_COMMAND_COMPLETE_INT_DEFAULT   0x00000000

/***************************************************************************
 *INT_STATUS_ENA - Interrupt Enables for Normal and Error conditions
 ***************************************************************************/
/* SDIO_0_HOST :: INT_STATUS_ENA :: reserved0 [31:30] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved0_MASK             0xc0000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved0_SHIFT            30

/* SDIO_0_HOST :: INT_STATUS_ENA :: reserved_for_eco1 [29:29] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved_for_eco1_MASK     0x20000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved_for_eco1_SHIFT    29
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved_for_eco1_DEFAULT  0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: TARGET_RESP_ERR_INT_ENA [28:28] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TARGET_RESP_ERR_INT_ENA_MASK 0x10000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TARGET_RESP_ERR_INT_ENA_SHIFT 28
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TARGET_RESP_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: reserved2 [27:27] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved2_MASK             0x08000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved2_SHIFT            27

/* SDIO_0_HOST :: INT_STATUS_ENA :: TUNE_ERR_STAT_EN [26:26] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TUNE_ERR_STAT_EN_MASK      0x04000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TUNE_ERR_STAT_EN_SHIFT     26
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TUNE_ERR_STAT_EN_DEFAULT   0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: ADMA_ERR_INT_ENA [25:25] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_ADMA_ERR_INT_ENA_MASK      0x02000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_ADMA_ERR_INT_ENA_SHIFT     25
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_ADMA_ERR_INT_ENA_DEFAULT   0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: AUTO_CMD12_ERR_INT_ENA [24:24] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_AUTO_CMD12_ERR_INT_ENA_MASK 0x01000000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_AUTO_CMD12_ERR_INT_ENA_SHIFT 24
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_AUTO_CMD12_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CURRENT_LIMIT_ERR_INT_ENA [23:23] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CURRENT_LIMIT_ERR_INT_ENA_MASK 0x00800000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CURRENT_LIMIT_ERR_INT_ENA_SHIFT 23
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CURRENT_LIMIT_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: DATA_END_BIT_ERR_INT_ENA [22:22] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_END_BIT_ERR_INT_ENA_MASK 0x00400000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_END_BIT_ERR_INT_ENA_SHIFT 22
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_END_BIT_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: DATA_CRC_ERR_INT_ENA [21:21] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_CRC_ERR_INT_ENA_MASK  0x00200000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_CRC_ERR_INT_ENA_SHIFT 21
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_CRC_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: DATA_TIMEOUT_ERR_INT_ENA [20:20] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_TIMEOUT_ERR_INT_ENA_MASK 0x00100000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_TIMEOUT_ERR_INT_ENA_SHIFT 20
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DATA_TIMEOUT_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CMD_INDEX_ERR_INT_ENA [19:19] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_INDEX_ERR_INT_ENA_MASK 0x00080000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_INDEX_ERR_INT_ENA_SHIFT 19
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_INDEX_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CMD_END_BIT_ERR_INT_ENA [18:18] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_END_BIT_ERR_INT_ENA_MASK 0x00040000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_END_BIT_ERR_INT_ENA_SHIFT 18
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_END_BIT_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CMD_CRC_ERR_INT_ENA [17:17] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_CRC_ERR_INT_ENA_MASK   0x00020000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_CRC_ERR_INT_ENA_SHIFT  17
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_CRC_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CMD_TIMEOUT_ERR_INT_ENA [16:16] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_TIMEOUT_ERR_INT_ENA_MASK 0x00010000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_TIMEOUT_ERR_INT_ENA_SHIFT 16
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CMD_TIMEOUT_ERR_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: reserved3 [15:15] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved3_MASK             0x00008000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_reserved3_SHIFT            15

/* SDIO_0_HOST :: INT_STATUS_ENA :: BOOT_TERM_EN [14:14] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_TERM_EN_MASK          0x00004000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_TERM_EN_SHIFT         14
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_TERM_EN_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: BOOT_ACK_RCV_EN [13:13] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_ACK_RCV_EN_MASK       0x00002000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_ACK_RCV_EN_SHIFT      13
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BOOT_ACK_RCV_EN_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: RETUNE_EVENT_EN [12:12] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_RETUNE_EVENT_EN_MASK       0x00001000
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_RETUNE_EVENT_EN_SHIFT      12
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_RETUNE_EVENT_EN_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: INT_C_EN [11:11] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_C_EN_MASK              0x00000800
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_C_EN_SHIFT             11
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_C_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: INT_B_EN [10:10] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_B_EN_MASK              0x00000400
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_B_EN_SHIFT             10
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_B_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: INT_A_EN [09:09] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_A_EN_MASK              0x00000200
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_A_EN_SHIFT             9
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_INT_A_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CARD_INT_ENA [08:08] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CARD_INT_ENA_MASK          0x00000100
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CARD_INT_ENA_SHIFT         8
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CARD_INT_ENA_DEFAULT       0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CAR_REMOVAL_INT_ENA [07:07] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_REMOVAL_INT_ENA_MASK   0x00000080
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_REMOVAL_INT_ENA_SHIFT  7
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_REMOVAL_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: CAR_INSERT_INT_ENA [06:06] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_INSERT_INT_ENA_MASK    0x00000040
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_INSERT_INT_ENA_SHIFT   6
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_CAR_INSERT_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: BUFFER_READ_INT_ENA [05:05] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_READ_INT_ENA_MASK   0x00000020
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_READ_INT_ENA_SHIFT  5
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_READ_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: BUFFER_WRITE_INT_ENA [04:04] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_WRITE_INT_ENA_MASK  0x00000010
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_WRITE_INT_ENA_SHIFT 4
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BUFFER_WRITE_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: DMA_INT_ENA [03:03] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DMA_INT_ENA_MASK           0x00000008
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DMA_INT_ENA_SHIFT          3
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_DMA_INT_ENA_DEFAULT        0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: BLOCK_GAP_INT_ENA [02:02] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BLOCK_GAP_INT_ENA_MASK     0x00000004
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BLOCK_GAP_INT_ENA_SHIFT    2
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_BLOCK_GAP_INT_ENA_DEFAULT  0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: TRANSFER_COMPLETE_INT_ENA [01:01] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TRANSFER_COMPLETE_INT_ENA_MASK 0x00000002
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TRANSFER_COMPLETE_INT_ENA_SHIFT 1
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_TRANSFER_COMPLETE_INT_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_STATUS_ENA :: COMMAND_COMPLETE_INT_ENA [00:00] */
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_COMMAND_COMPLETE_INT_ENA_MASK 0x00000001
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_COMMAND_COMPLETE_INT_ENA_SHIFT 0
#define BCHP_SDIO_0_HOST_INT_STATUS_ENA_COMMAND_COMPLETE_INT_ENA_DEFAULT 0x00000000

/***************************************************************************
 *INT_SIGNAL_ENA - Interrupt Signal Enables for Normal and Error conditions
 ***************************************************************************/
/* SDIO_0_HOST :: INT_SIGNAL_ENA :: reserved0 [31:30] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved0_MASK             0xc0000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved0_SHIFT            30

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: reserved_for_eco1 [29:29] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved_for_eco1_MASK     0x20000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved_for_eco1_SHIFT    29
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved_for_eco1_DEFAULT  0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: TARGET_RESP_ERR_INT_SIG_ENA [28:28] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TARGET_RESP_ERR_INT_SIG_ENA_MASK 0x10000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TARGET_RESP_ERR_INT_SIG_ENA_SHIFT 28
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TARGET_RESP_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: reserved2 [27:27] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved2_MASK             0x08000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved2_SHIFT            27

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: TUNE_ERR_SIG_EN [26:26] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TUNE_ERR_SIG_EN_MASK       0x04000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TUNE_ERR_SIG_EN_SHIFT      26
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TUNE_ERR_SIG_EN_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: ADMA_ERR_INT_SIG_ENA [25:25] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_ADMA_ERR_INT_SIG_ENA_MASK  0x02000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_ADMA_ERR_INT_SIG_ENA_SHIFT 25
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_ADMA_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: AUTO_CMD12_ERR_INT_SIG_ENA [24:24] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_AUTO_CMD12_ERR_INT_SIG_ENA_MASK 0x01000000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_AUTO_CMD12_ERR_INT_SIG_ENA_SHIFT 24
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_AUTO_CMD12_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CURRENT_LIMIT_ERR_INT_SIG_ENA [23:23] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CURRENT_LIMIT_ERR_INT_SIG_ENA_MASK 0x00800000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CURRENT_LIMIT_ERR_INT_SIG_ENA_SHIFT 23
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CURRENT_LIMIT_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: DATA_END_BIT_ERR_INT_SIG_ENA [22:22] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_END_BIT_ERR_INT_SIG_ENA_MASK 0x00400000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_END_BIT_ERR_INT_SIG_ENA_SHIFT 22
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_END_BIT_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: DATA_CRC_ERR_INT_SIG_ENA [21:21] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_CRC_ERR_INT_SIG_ENA_MASK 0x00200000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_CRC_ERR_INT_SIG_ENA_SHIFT 21
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_CRC_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: DATA_TIMEOUT_ERR_INT_SIG_ENA [20:20] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_TIMEOUT_ERR_INT_SIG_ENA_MASK 0x00100000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_TIMEOUT_ERR_INT_SIG_ENA_SHIFT 20
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DATA_TIMEOUT_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CMD_INDEX_ERR_INT_SIG_ENA [19:19] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_INDEX_ERR_INT_SIG_ENA_MASK 0x00080000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_INDEX_ERR_INT_SIG_ENA_SHIFT 19
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_INDEX_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CMD_END_BIT_ERR_INT_SIG_ENA [18:18] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_END_BIT_ERR_INT_SIG_ENA_MASK 0x00040000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_END_BIT_ERR_INT_SIG_ENA_SHIFT 18
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_END_BIT_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CMD_CRC_ERR_INT_SIG_ENA [17:17] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_CRC_ERR_INT_SIG_ENA_MASK 0x00020000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_CRC_ERR_INT_SIG_ENA_SHIFT 17
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_CRC_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CMD_TIMEOUT_ERR_INT_SIG_ENA [16:16] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_TIMEOUT_ERR_INT_SIG_ENA_MASK 0x00010000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_TIMEOUT_ERR_INT_SIG_ENA_SHIFT 16
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CMD_TIMEOUT_ERR_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: reserved3 [15:15] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved3_MASK             0x00008000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_reserved3_SHIFT            15

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: BOOT_TERM_INT_SIG_ENA [14:14] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_TERM_INT_SIG_ENA_MASK 0x00004000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_TERM_INT_SIG_ENA_SHIFT 14
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_TERM_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: BOOT_ACK_RCV_INT_SIG_ENA [13:13] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_ACK_RCV_INT_SIG_ENA_MASK 0x00002000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_ACK_RCV_INT_SIG_ENA_SHIFT 13
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BOOT_ACK_RCV_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: RETUNE_EVENT_EN [12:12] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_RETUNE_EVENT_EN_MASK       0x00001000
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_RETUNE_EVENT_EN_SHIFT      12
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_RETUNE_EVENT_EN_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: INT_C_EN [11:11] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_C_EN_MASK              0x00000800
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_C_EN_SHIFT             11
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_C_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: INT_B_EN [10:10] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_B_EN_MASK              0x00000400
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_B_EN_SHIFT             10
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_B_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: INT_A_EN [09:09] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_A_EN_MASK              0x00000200
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_A_EN_SHIFT             9
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_INT_A_EN_DEFAULT           0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CARD_INT_SIG_ENA [08:08] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CARD_INT_SIG_ENA_MASK      0x00000100
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CARD_INT_SIG_ENA_SHIFT     8
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CARD_INT_SIG_ENA_DEFAULT   0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CAR_REMOVAL_INT_SIG_ENA [07:07] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_REMOVAL_INT_SIG_ENA_MASK 0x00000080
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_REMOVAL_INT_SIG_ENA_SHIFT 7
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_REMOVAL_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: CAR_INSERT_INT_SIG_ENA [06:06] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_INSERT_INT_SIG_ENA_MASK 0x00000040
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_INSERT_INT_SIG_ENA_SHIFT 6
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_CAR_INSERT_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: BUFFER_READ_INT_SIG_ENA [05:05] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_READ_INT_SIG_ENA_MASK 0x00000020
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_READ_INT_SIG_ENA_SHIFT 5
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_READ_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: BUFFER_WRITE_INT_SIG_ENA [04:04] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_WRITE_INT_SIG_ENA_MASK 0x00000010
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_WRITE_INT_SIG_ENA_SHIFT 4
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BUFFER_WRITE_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: DMA_INT_SIG_ENA [03:03] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DMA_INT_SIG_ENA_MASK       0x00000008
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DMA_INT_SIG_ENA_SHIFT      3
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_DMA_INT_SIG_ENA_DEFAULT    0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: BLOCK_GAP_INT_SIG_ENA [02:02] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BLOCK_GAP_INT_SIG_ENA_MASK 0x00000004
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BLOCK_GAP_INT_SIG_ENA_SHIFT 2
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_BLOCK_GAP_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: TRANSFER_COMPLETE_INT_SIG_ENA [01:01] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TRANSFER_COMPLETE_INT_SIG_ENA_MASK 0x00000002
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TRANSFER_COMPLETE_INT_SIG_ENA_SHIFT 1
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_TRANSFER_COMPLETE_INT_SIG_ENA_DEFAULT 0x00000000

/* SDIO_0_HOST :: INT_SIGNAL_ENA :: COMMAND_COMPLETE_INT_SIG_ENA [00:00] */
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_COMMAND_COMPLETE_INT_SIG_ENA_MASK 0x00000001
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_COMMAND_COMPLETE_INT_SIG_ENA_SHIFT 0
#define BCHP_SDIO_0_HOST_INT_SIGNAL_ENA_COMMAND_COMPLETE_INT_SIG_ENA_DEFAULT 0x00000000

/***************************************************************************
 *AUTOCMD12_STAT - Auto Cmd12 Error Status
 ***************************************************************************/
/* SDIO_0_HOST :: AUTOCMD12_STAT :: PRESENT_VALUE_EN [31:31] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_PRESENT_VALUE_EN_MASK      0x80000000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_PRESENT_VALUE_EN_SHIFT     31
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_PRESENT_VALUE_EN_DEFAULT   0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: ASYNC_INT_EN [30:30] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_ASYNC_INT_EN_MASK          0x40000000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_ASYNC_INT_EN_SHIFT         30
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_ASYNC_INT_EN_DEFAULT       0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: reserved0 [29:24] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved0_MASK             0x3f000000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved0_SHIFT            24

/* SDIO_0_HOST :: AUTOCMD12_STAT :: SAMPLE_CLK_SEL [23:23] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_SAMPLE_CLK_SEL_MASK        0x00800000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_SAMPLE_CLK_SEL_SHIFT       23
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_SAMPLE_CLK_SEL_DEFAULT     0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: EXECUTE_TUNE [22:22] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_EXECUTE_TUNE_MASK          0x00400000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_EXECUTE_TUNE_SHIFT         22
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_EXECUTE_TUNE_DEFAULT       0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: DRIVER_STRENGTH [21:20] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_DRIVER_STRENGTH_MASK       0x00300000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_DRIVER_STRENGTH_SHIFT      20
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_DRIVER_STRENGTH_DEFAULT    0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: 1P8_SIG_EN [19:19] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_1P8_SIG_EN_MASK            0x00080000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_1P8_SIG_EN_SHIFT           19
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_1P8_SIG_EN_DEFAULT         0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: UHS_MODE [18:16] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_UHS_MODE_MASK              0x00070000
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_UHS_MODE_SHIFT             16
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_UHS_MODE_DEFAULT           0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: reserved1 [15:08] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved1_MASK             0x0000ff00
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved1_SHIFT            8

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD12_NOT_ISSUED [07:07] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_ISSUED_MASK      0x00000080
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_ISSUED_SHIFT     7
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_ISSUED_DEFAULT   0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: reserved2 [06:05] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved2_MASK             0x00000060
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_reserved2_SHIFT            5

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD_INDEX_ERR [04:04] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_INDEX_ERR_MASK         0x00000010
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_INDEX_ERR_SHIFT        4
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_INDEX_ERR_DEFAULT      0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD_END_ERR [03:03] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_END_ERR_MASK           0x00000008
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_END_ERR_SHIFT          3
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_END_ERR_DEFAULT        0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD_CRC_ERR [02:02] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_CRC_ERR_MASK           0x00000004
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_CRC_ERR_SHIFT          2
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_CRC_ERR_DEFAULT        0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD_TIMEOUT_ERR [01:01] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_TIMEOUT_ERR_MASK       0x00000002
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_TIMEOUT_ERR_SHIFT      1
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD_TIMEOUT_ERR_DEFAULT    0x00000000

/* SDIO_0_HOST :: AUTOCMD12_STAT :: CMD12_NOT_EXEC_ERR [00:00] */
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_EXEC_ERR_MASK    0x00000001
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_EXEC_ERR_SHIFT   0
#define BCHP_SDIO_0_HOST_AUTOCMD12_STAT_CMD12_NOT_EXEC_ERR_DEFAULT 0x00000000

/***************************************************************************
 *CAPABLE - Host Controller Capabilities to Software
 ***************************************************************************/
/* SDIO_0_HOST :: CAPABLE :: SLOT_TYPE [31:30] */
#define BCHP_SDIO_0_HOST_CAPABLE_SLOT_TYPE_MASK                    0xc0000000
#define BCHP_SDIO_0_HOST_CAPABLE_SLOT_TYPE_SHIFT                   30

/* SDIO_0_HOST :: CAPABLE :: INT_MODE [29:29] */
#define BCHP_SDIO_0_HOST_CAPABLE_INT_MODE_MASK                     0x20000000
#define BCHP_SDIO_0_HOST_CAPABLE_INT_MODE_SHIFT                    29

/* SDIO_0_HOST :: CAPABLE :: SYS_BUS_64BIT [28:28] */
#define BCHP_SDIO_0_HOST_CAPABLE_SYS_BUS_64BIT_MASK                0x10000000
#define BCHP_SDIO_0_HOST_CAPABLE_SYS_BUS_64BIT_SHIFT               28

/* SDIO_0_HOST :: CAPABLE :: reserved0 [27:27] */
#define BCHP_SDIO_0_HOST_CAPABLE_reserved0_MASK                    0x08000000
#define BCHP_SDIO_0_HOST_CAPABLE_reserved0_SHIFT                   27

/* SDIO_0_HOST :: CAPABLE :: VOLTAGE_1P8V [26:26] */
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_1P8V_MASK                 0x04000000
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_1P8V_SHIFT                26

/* SDIO_0_HOST :: CAPABLE :: VOLTAGE_3P0V [25:25] */
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_3P0V_MASK                 0x02000000
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_3P0V_SHIFT                25

/* SDIO_0_HOST :: CAPABLE :: VOLTAGE_3P3V [24:24] */
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_3P3V_MASK                 0x01000000
#define BCHP_SDIO_0_HOST_CAPABLE_VOLTAGE_3P3V_SHIFT                24

/* SDIO_0_HOST :: CAPABLE :: SUSPEND_RESUME [23:23] */
#define BCHP_SDIO_0_HOST_CAPABLE_SUSPEND_RESUME_MASK               0x00800000
#define BCHP_SDIO_0_HOST_CAPABLE_SUSPEND_RESUME_SHIFT              23

/* SDIO_0_HOST :: CAPABLE :: SDMA [22:22] */
#define BCHP_SDIO_0_HOST_CAPABLE_SDMA_MASK                         0x00400000
#define BCHP_SDIO_0_HOST_CAPABLE_SDMA_SHIFT                        22

/* SDIO_0_HOST :: CAPABLE :: HIGH_SPEED [21:21] */
#define BCHP_SDIO_0_HOST_CAPABLE_HIGH_SPEED_MASK                   0x00200000
#define BCHP_SDIO_0_HOST_CAPABLE_HIGH_SPEED_SHIFT                  21

/* SDIO_0_HOST :: CAPABLE :: reserved1 [20:20] */
#define BCHP_SDIO_0_HOST_CAPABLE_reserved1_MASK                    0x00100000
#define BCHP_SDIO_0_HOST_CAPABLE_reserved1_SHIFT                   20

/* SDIO_0_HOST :: CAPABLE :: ADMA2 [19:19] */
#define BCHP_SDIO_0_HOST_CAPABLE_ADMA2_MASK                        0x00080000
#define BCHP_SDIO_0_HOST_CAPABLE_ADMA2_SHIFT                       19

/* SDIO_0_HOST :: CAPABLE :: EXTENDED_MEDIA [18:18] */
#define BCHP_SDIO_0_HOST_CAPABLE_EXTENDED_MEDIA_MASK               0x00040000
#define BCHP_SDIO_0_HOST_CAPABLE_EXTENDED_MEDIA_SHIFT              18

/* SDIO_0_HOST :: CAPABLE :: MAX_BLOCK_LEN [17:16] */
#define BCHP_SDIO_0_HOST_CAPABLE_MAX_BLOCK_LEN_MASK                0x00030000
#define BCHP_SDIO_0_HOST_CAPABLE_MAX_BLOCK_LEN_SHIFT               16

/* SDIO_0_HOST :: CAPABLE :: BASE_CLK_FREQ [15:08] */
#define BCHP_SDIO_0_HOST_CAPABLE_BASE_CLK_FREQ_MASK                0x0000ff00
#define BCHP_SDIO_0_HOST_CAPABLE_BASE_CLK_FREQ_SHIFT               8

/* SDIO_0_HOST :: CAPABLE :: TIMEOUT_UNIT [07:07] */
#define BCHP_SDIO_0_HOST_CAPABLE_TIMEOUT_UNIT_MASK                 0x00000080
#define BCHP_SDIO_0_HOST_CAPABLE_TIMEOUT_UNIT_SHIFT                7

/* SDIO_0_HOST :: CAPABLE :: reserved2 [06:06] */
#define BCHP_SDIO_0_HOST_CAPABLE_reserved2_MASK                    0x00000040
#define BCHP_SDIO_0_HOST_CAPABLE_reserved2_SHIFT                   6

/* SDIO_0_HOST :: CAPABLE :: TIMEOUT_CLK_FREQ [05:00] */
#define BCHP_SDIO_0_HOST_CAPABLE_TIMEOUT_CLK_FREQ_MASK             0x0000003f
#define BCHP_SDIO_0_HOST_CAPABLE_TIMEOUT_CLK_FREQ_SHIFT            0

/***************************************************************************
 *CAPABLE_1 - Future Host Controller Capabilities to Software
 ***************************************************************************/
/* SDIO_0_HOST :: CAPABLE_1 :: reserved0 [31:26] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved0_MASK                  0xfc000000
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved0_SHIFT                 26

/* SDIO_0_HOST :: CAPABLE_1 :: SPI_BLOCK_MODE [25:25] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_SPI_BLOCK_MODE_MASK             0x02000000
#define BCHP_SDIO_0_HOST_CAPABLE_1_SPI_BLOCK_MODE_SHIFT            25

/* SDIO_0_HOST :: CAPABLE_1 :: SPI_MODE [24:24] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_SPI_MODE_MASK                   0x01000000
#define BCHP_SDIO_0_HOST_CAPABLE_1_SPI_MODE_SHIFT                  24

/* SDIO_0_HOST :: CAPABLE_1 :: CLK_MULT [23:16] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_CLK_MULT_MASK                   0x00ff0000
#define BCHP_SDIO_0_HOST_CAPABLE_1_CLK_MULT_SHIFT                  16

/* SDIO_0_HOST :: CAPABLE_1 :: RETUNING_MODE [15:14] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_RETUNING_MODE_MASK              0x0000c000
#define BCHP_SDIO_0_HOST_CAPABLE_1_RETUNING_MODE_SHIFT             14

/* SDIO_0_HOST :: CAPABLE_1 :: TUNE_SDR50 [13:13] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_TUNE_SDR50_MASK                 0x00002000
#define BCHP_SDIO_0_HOST_CAPABLE_1_TUNE_SDR50_SHIFT                13

/* SDIO_0_HOST :: CAPABLE_1 :: reserved1 [12:12] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved1_MASK                  0x00001000
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved1_SHIFT                 12

/* SDIO_0_HOST :: CAPABLE_1 :: TIME_RETUNE [11:08] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_TIME_RETUNE_MASK                0x00000f00
#define BCHP_SDIO_0_HOST_CAPABLE_1_TIME_RETUNE_SHIFT               8

/* SDIO_0_HOST :: CAPABLE_1 :: reserved2 [07:07] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved2_MASK                  0x00000080
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved2_SHIFT                 7

/* SDIO_0_HOST :: CAPABLE_1 :: DRIVER_D [06:06] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_D_MASK                   0x00000040
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_D_SHIFT                  6

/* SDIO_0_HOST :: CAPABLE_1 :: DRIVER_C [05:05] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_C_MASK                   0x00000020
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_C_SHIFT                  5

/* SDIO_0_HOST :: CAPABLE_1 :: DRIVER_A [04:04] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_A_MASK                   0x00000010
#define BCHP_SDIO_0_HOST_CAPABLE_1_DRIVER_A_SHIFT                  4

/* SDIO_0_HOST :: CAPABLE_1 :: reserved3 [03:03] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved3_MASK                  0x00000008
#define BCHP_SDIO_0_HOST_CAPABLE_1_reserved3_SHIFT                 3

/* SDIO_0_HOST :: CAPABLE_1 :: DDR50 [02:02] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_DDR50_MASK                      0x00000004
#define BCHP_SDIO_0_HOST_CAPABLE_1_DDR50_SHIFT                     2

/* SDIO_0_HOST :: CAPABLE_1 :: SDR104 [01:01] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_SDR104_MASK                     0x00000002
#define BCHP_SDIO_0_HOST_CAPABLE_1_SDR104_SHIFT                    1

/* SDIO_0_HOST :: CAPABLE_1 :: SDR50 [00:00] */
#define BCHP_SDIO_0_HOST_CAPABLE_1_SDR50_MASK                      0x00000001
#define BCHP_SDIO_0_HOST_CAPABLE_1_SDR50_SHIFT                     0

/***************************************************************************
 *POWER_CAPABLE - Host Controller Power Capabilities to Software
 ***************************************************************************/
/* SDIO_0_HOST :: POWER_CAPABLE :: reserved0 [31:24] */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_reserved0_MASK              0xff000000
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_reserved0_SHIFT             24

/* SDIO_0_HOST :: POWER_CAPABLE :: MAX_CURRENT_1P8V [23:16] */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_1P8V_MASK       0x00ff0000
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_1P8V_SHIFT      16
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_1P8V_DEFAULT    0x00000000

/* SDIO_0_HOST :: POWER_CAPABLE :: MAX_CURRENT_3P0V [15:08] */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P0V_MASK       0x0000ff00
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P0V_SHIFT      8
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P0V_DEFAULT    0x00000000

/* SDIO_0_HOST :: POWER_CAPABLE :: MAX_CURRENT_3P3V [07:00] */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P3V_MASK       0x000000ff
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P3V_SHIFT      0
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_MAX_CURRENT_3P3V_DEFAULT    0x00000001

/***************************************************************************
 *POWER_CAPABLE_RSVD - Future Host Controller Power Capabilities to Software
 ***************************************************************************/
/* SDIO_0_HOST :: POWER_CAPABLE_RSVD :: POWERCAPS_RSVD [31:00] */
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_RSVD_POWERCAPS_RSVD_MASK    0xffffffff
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_RSVD_POWERCAPS_RSVD_SHIFT   0
#define BCHP_SDIO_0_HOST_POWER_CAPABLE_RSVD_POWERCAPS_RSVD_DEFAULT 0x00000000

/***************************************************************************
 *FORCE_EVENTS - Force Events on Error Status Bits
 ***************************************************************************/
/* SDIO_0_HOST :: FORCE_EVENTS :: reserved0 [31:30] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved0_MASK               0xc0000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved0_SHIFT              30

/* SDIO_0_HOST :: FORCE_EVENTS :: rsvd_0 [29:29] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_rsvd_0_MASK                  0x20000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_rsvd_0_SHIFT                 29

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_TARGET_RESP_ERR_INT [28:28] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_TARGET_RESP_ERR_INT_MASK 0x10000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_TARGET_RESP_ERR_INT_SHIFT 28
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_TARGET_RESP_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: reserved1 [27:26] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved1_MASK               0x0c000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved1_SHIFT              26

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_ADMA_ERR_INT [25:25] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_ADMA_ERR_INT_MASK      0x02000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_ADMA_ERR_INT_SHIFT     25
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_ADMA_ERR_INT_DEFAULT   0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_AUTO_CMD_ERR_INT [24:24] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_AUTO_CMD_ERR_INT_MASK  0x01000000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_AUTO_CMD_ERR_INT_SHIFT 24
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_AUTO_CMD_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CURRENT_LIMIT_ERR_INT [23:23] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CURRENT_LIMIT_ERR_INT_MASK 0x00800000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CURRENT_LIMIT_ERR_INT_SHIFT 23
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CURRENT_LIMIT_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_DATA_END_BIT_ERR_INT [22:22] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_END_BIT_ERR_INT_MASK 0x00400000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_END_BIT_ERR_INT_SHIFT 22
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_END_BIT_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_DATA_CRC_ERR_INT [21:21] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_CRC_ERR_INT_MASK  0x00200000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_CRC_ERR_INT_SHIFT 21
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_CRC_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_DATA_TIMEOUT_ERR_INT [20:20] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_TIMEOUT_ERR_INT_MASK 0x00100000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_TIMEOUT_ERR_INT_SHIFT 20
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_DATA_TIMEOUT_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_INDEX_ERR_INT [19:19] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_INT_MASK 0x00080000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_INT_SHIFT 19
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_END_BIT_ERR_INT [18:18] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_BIT_ERR_INT_MASK 0x00040000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_BIT_ERR_INT_SHIFT 18
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_BIT_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_CRC_ERR_INT [17:17] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_INT_MASK   0x00020000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_INT_SHIFT  17
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_TIMEOUT_ERR_INT [16:16] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_INT_MASK 0x00010000
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_INT_SHIFT 16
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_INT_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: reserved2 [15:08] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved2_MASK               0x0000ff00
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved2_SHIFT              8

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD12_NOT_ISSUED [07:07] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD12_NOT_ISSUED_MASK  0x00000080
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD12_NOT_ISSUED_SHIFT 7
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD12_NOT_ISSUED_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: reserved3 [06:05] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved3_MASK               0x00000060
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_reserved3_SHIFT              5

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_INDEX_ERR [04:04] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_MASK     0x00000010
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_SHIFT    4
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_INDEX_ERR_DEFAULT  0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_END_ERR [03:03] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_ERR_MASK       0x00000008
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_ERR_SHIFT      3
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_END_ERR_DEFAULT    0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_CRC_ERR [02:02] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_MASK       0x00000004
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_SHIFT      2
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_CRC_ERR_DEFAULT    0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_TIMEOUT_ERR [01:01] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_MASK   0x00000002
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_SHIFT  1
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_TIMEOUT_ERR_DEFAULT 0x00000000

/* SDIO_0_HOST :: FORCE_EVENTS :: FORCE_CMD_NOT_EXEC_ERR [00:00] */
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_NOT_EXEC_ERR_MASK  0x00000001
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_NOT_EXEC_ERR_SHIFT 0
#define BCHP_SDIO_0_HOST_FORCE_EVENTS_FORCE_CMD_NOT_EXEC_ERR_DEFAULT 0x00000000

/***************************************************************************
 *ADMA_ERR_STAT - ADMA Error Status Bits
 ***************************************************************************/
/* SDIO_0_HOST :: ADMA_ERR_STAT :: reserved0 [31:03] */
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_reserved0_MASK              0xfffffff8
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_reserved0_SHIFT             3

/* SDIO_0_HOST :: ADMA_ERR_STAT :: LENGTH_MATCH_ERR [02:02] */
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_LENGTH_MATCH_ERR_MASK       0x00000004
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_LENGTH_MATCH_ERR_SHIFT      2
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_LENGTH_MATCH_ERR_DEFAULT    0x00000000

/* SDIO_0_HOST :: ADMA_ERR_STAT :: STATE_ERR [01:00] */
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_STATE_ERR_MASK              0x00000003
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_STATE_ERR_SHIFT             0
#define BCHP_SDIO_0_HOST_ADMA_ERR_STAT_STATE_ERR_DEFAULT           0x00000000

/***************************************************************************
 *ADMA_SYSADDR_LO - ADMA System Address Low Bits
 ***************************************************************************/
/* SDIO_0_HOST :: ADMA_SYSADDR_LO :: ADMA_SYSADDR_LO [31:00] */
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_LO_ADMA_SYSADDR_LO_MASK      0xffffffff
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_LO_ADMA_SYSADDR_LO_SHIFT     0
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_LO_ADMA_SYSADDR_LO_DEFAULT   0x00000000

/***************************************************************************
 *ADMA_SYSADDR_HI - ADMA System Address High Bits
 ***************************************************************************/
/* SDIO_0_HOST :: ADMA_SYSADDR_HI :: ADMA_SYSADDR_HI [31:00] */
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_HI_ADMA_SYSADDR_HI_MASK      0xffffffff
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_HI_ADMA_SYSADDR_HI_SHIFT     0
#define BCHP_SDIO_0_HOST_ADMA_SYSADDR_HI_ADMA_SYSADDR_HI_DEFAULT   0x00000000

/***************************************************************************
 *PRESET_INIT_DEFAULT - Preset Values for init and default speed
 ***************************************************************************/
/* SDIO_0_HOST :: PRESET_INIT_DEFAULT :: PRESET_DEFAULT_SPEED [31:16] */
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_DEFAULT_SPEED_MASK 0xffff0000
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_DEFAULT_SPEED_SHIFT 16
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_DEFAULT_SPEED_DEFAULT 0x00000002

/* SDIO_0_HOST :: PRESET_INIT_DEFAULT :: PRESET_INIT [15:00] */
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_INIT_MASK      0x0000ffff
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_INIT_SHIFT     0
#define BCHP_SDIO_0_HOST_PRESET_INIT_DEFAULT_PRESET_INIT_DEFAULT   0x00000080

/***************************************************************************
 *PRESET_HIGH_SPEED - Preset Values for high speed and SDR12
 ***************************************************************************/
/* SDIO_0_HOST :: PRESET_HIGH_SPEED :: PRESET_SDR12 [31:16] */
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_SDR12_MASK       0xffff0000
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_SDR12_SHIFT      16
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_SDR12_DEFAULT    0x00000002

/* SDIO_0_HOST :: PRESET_HIGH_SPEED :: PRESET_HIGH_SPEED [15:00] */
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_HIGH_SPEED_MASK  0x0000ffff
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_HIGH_SPEED_SHIFT 0
#define BCHP_SDIO_0_HOST_PRESET_HIGH_SPEED_PRESET_HIGH_SPEED_DEFAULT 0x00000001

/***************************************************************************
 *PRESET_SDR25_50 - Preset Values for SDR25 and SDR50
 ***************************************************************************/
/* SDIO_0_HOST :: PRESET_SDR25_50 :: PRESET_SDR50 [31:16] */
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR50_MASK         0xffff0000
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR50_SHIFT        16
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR50_DEFAULT      0x00000000

/* SDIO_0_HOST :: PRESET_SDR25_50 :: PRESET_SDR25 [15:00] */
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR25_MASK         0x0000ffff
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR25_SHIFT        0
#define BCHP_SDIO_0_HOST_PRESET_SDR25_50_PRESET_SDR25_DEFAULT      0x00000001

/***************************************************************************
 *PRESET_SDR104_DDR50 - Preset Values for SDR104 and DDR50
 ***************************************************************************/
/* SDIO_0_HOST :: PRESET_SDR104_DDR50 :: PRESET_DDR50 [31:16] */
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_DDR50_MASK     0xffff0000
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_DDR50_SHIFT    16
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_DDR50_DEFAULT  0x00000001

/* SDIO_0_HOST :: PRESET_SDR104_DDR50 :: PRESET_SDR104 [15:00] */
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_SDR104_MASK    0x0000ffff
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_SDR104_SHIFT   0
#define BCHP_SDIO_0_HOST_PRESET_SDR104_DDR50_PRESET_SDR104_DEFAULT 0x00000000

/***************************************************************************
 *BOOT_TIMEOUT - DAT line inactivity timeout on boot
 ***************************************************************************/
/* SDIO_0_HOST :: BOOT_TIMEOUT :: BOOT_TIMEOUT [31:00] */
#define BCHP_SDIO_0_HOST_BOOT_TIMEOUT_BOOT_TIMEOUT_MASK            0xffffffff
#define BCHP_SDIO_0_HOST_BOOT_TIMEOUT_BOOT_TIMEOUT_SHIFT           0
#define BCHP_SDIO_0_HOST_BOOT_TIMEOUT_BOOT_TIMEOUT_DEFAULT         0x00000000

/***************************************************************************
 *DEBUG_SELECT - Debug probe output selection
 ***************************************************************************/
/* SDIO_0_HOST :: DEBUG_SELECT :: reserved0 [31:01] */
#define BCHP_SDIO_0_HOST_DEBUG_SELECT_reserved0_MASK               0xfffffffe
#define BCHP_SDIO_0_HOST_DEBUG_SELECT_reserved0_SHIFT              1

/* SDIO_0_HOST :: DEBUG_SELECT :: DEBUG_SEL [00:00] */
#define BCHP_SDIO_0_HOST_DEBUG_SELECT_DEBUG_SEL_MASK               0x00000001
#define BCHP_SDIO_0_HOST_DEBUG_SELECT_DEBUG_SEL_SHIFT              0
#define BCHP_SDIO_0_HOST_DEBUG_SELECT_DEBUG_SEL_DEFAULT            0x00000000

/***************************************************************************
 *SHARED_BUS_CTRL - shared bus control
 ***************************************************************************/
/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved0 [31:31] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved0_MASK            0x80000000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved0_SHIFT           31

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: BACK_END_PWR_CTRL [30:24] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BACK_END_PWR_CTRL_MASK    0x7f000000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BACK_END_PWR_CTRL_SHIFT   24
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BACK_END_PWR_CTRL_DEFAULT 0x00000000

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved1 [23:23] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved1_MASK            0x00800000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved1_SHIFT           23

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: INT_PIN_SEL [22:20] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_INT_PIN_SEL_MASK          0x00700000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_INT_PIN_SEL_SHIFT         20
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_INT_PIN_SEL_DEFAULT       0x00000000

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved2 [19:19] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved2_MASK            0x00080000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved2_SHIFT           19

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: CLK_PIN_SEL [18:16] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_CLK_PIN_SEL_MASK          0x00070000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_CLK_PIN_SEL_SHIFT         16
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_CLK_PIN_SEL_DEFAULT       0x00000000

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved3 [15:15] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved3_MASK            0x00008000
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved3_SHIFT           15

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: BUS_WIDTH_PRESET [14:08] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BUS_WIDTH_PRESET_MASK     0x00007f00
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BUS_WIDTH_PRESET_SHIFT    8
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_BUS_WIDTH_PRESET_DEFAULT  0x00000000

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved4 [07:06] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved4_MASK            0x000000c0
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved4_SHIFT           6

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: NUM_INT_PINS [05:04] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_INT_PINS_MASK         0x00000030
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_INT_PINS_SHIFT        4
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_INT_PINS_DEFAULT      0x00000000

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: reserved5 [03:03] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved5_MASK            0x00000008
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_reserved5_SHIFT           3

/* SDIO_0_HOST :: SHARED_BUS_CTRL :: NUM_CLK_PINS [02:00] */
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_CLK_PINS_MASK         0x00000007
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_CLK_PINS_SHIFT        0
#define BCHP_SDIO_0_HOST_SHARED_BUS_CTRL_NUM_CLK_PINS_DEFAULT      0x00000000

/***************************************************************************
 *SPI_INTERRUPT - SPI Interrupt support
 ***************************************************************************/
/* SDIO_0_HOST :: SPI_INTERRUPT :: reserved0 [31:08] */
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT_reserved0_MASK              0xffffff00
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT_reserved0_SHIFT             8

/* SDIO_0_HOST :: SPI_INTERRUPT :: SPI_INT [07:00] */
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT_SPI_INT_MASK                0x000000ff
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT_SPI_INT_SHIFT               0
#define BCHP_SDIO_0_HOST_SPI_INTERRUPT_SPI_INT_DEFAULT             0x00000000

/***************************************************************************
 *VERSION_STATUS - Controller Version and Slot Status
 ***************************************************************************/
/* SDIO_0_HOST :: VERSION_STATUS :: VENDOR_VERSION [31:24] */
#define BCHP_SDIO_0_HOST_VERSION_STATUS_VENDOR_VERSION_MASK        0xff000000
#define BCHP_SDIO_0_HOST_VERSION_STATUS_VENDOR_VERSION_SHIFT       24
#define BCHP_SDIO_0_HOST_VERSION_STATUS_VENDOR_VERSION_DEFAULT     0x00000010

/* SDIO_0_HOST :: VERSION_STATUS :: CONTROLLER_VERSION [23:16] */
#define BCHP_SDIO_0_HOST_VERSION_STATUS_CONTROLLER_VERSION_MASK    0x00ff0000
#define BCHP_SDIO_0_HOST_VERSION_STATUS_CONTROLLER_VERSION_SHIFT   16
#define BCHP_SDIO_0_HOST_VERSION_STATUS_CONTROLLER_VERSION_DEFAULT 0x00000002

/* SDIO_0_HOST :: VERSION_STATUS :: reserved0 [15:08] */
#define BCHP_SDIO_0_HOST_VERSION_STATUS_reserved0_MASK             0x0000ff00
#define BCHP_SDIO_0_HOST_VERSION_STATUS_reserved0_SHIFT            8

/* SDIO_0_HOST :: VERSION_STATUS :: SLOT_INTS [07:00] */
#define BCHP_SDIO_0_HOST_VERSION_STATUS_SLOT_INTS_MASK             0x000000ff
#define BCHP_SDIO_0_HOST_VERSION_STATUS_SLOT_INTS_SHIFT            0
#define BCHP_SDIO_0_HOST_VERSION_STATUS_SLOT_INTS_DEFAULT          0x00000000

#endif /* #ifndef BCHP_SDIO_0_HOST_H__ */

/* End of File */
