/********************************************************************************
 * Broadcom Proprietary and Confidential. (c)2016 Broadcom. All rights reserved.
 *
 * This program is the proprietary software of Broadcom and/or its
 * licensors, and may only be used, duplicated, modified or distributed pursuant
 * to the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and Broadcom
 * expressly reserves all rights in and to the Software and all intellectual
 * property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE, THEN YOU
 * HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD IMMEDIATELY
 * NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1. This program, including its structure, sequence and organization,
 *    constitutes the valuable trade secrets of Broadcom, and you shall use all
 *    reasonable efforts to protect the confidentiality thereof, and to use
 *    this information only in connection with your use of Broadcom integrated
 *    circuit products.
 *
 * 2. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED "AS IS"
 *    AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS OR
 *    WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT
 *    TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL IMPLIED
 *    WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *    PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *    ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 *    THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3. TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR ITS
 *    LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL, INDIRECT,
 *    OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY RELATING TO
 *    YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN
 *    ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS
 *    OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1, WHICHEVER
 *    IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY FAILURE OF
 *    ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Module Description:
 *                     DO NOT EDIT THIS FILE DIRECTLY
 *
 * This module was generated magically with RDB from a source description
 * file. You must edit the source file for changes to be made to this file.
 *
 * The launch point for all information concerning RDB is found at:
 *   http://bcgbu.broadcom.com/RDB/SitePages/Home.aspx
 *
 * Date:           Generated on               Thu Dec  1 06:16:38 2016
 *                 Full Compile MD5 Checksum  d77d353b4fd33f3b3eb763c0ec6d13e9
 *                     (minus title and desc)
 *                 MD5 Checksum               b9f56ca31bb855d1e4c37875f6b45457
 *
 * lock_release:   n/a
 * Compiled with:  RDB Utility                combo_header.pl
 *                 RDB.pm                     1139
 *                 unknown                    unknown
 *                 Perl Interpreter           5.008008
 *                 Operating System           linux
 *                 Script Source              /projects/stbgit/bin/gen_rdb.pl
 *                 DVTSWVER                   n/a
 *
 *
********************************************************************************/

#ifndef BCHP_GENET_0_RBUF_H__
#define BCHP_GENET_0_RBUF_H__

/***************************************************************************
 *GENET_0_RBUF
 ***************************************************************************/
#define BCHP_GENET_0_RBUF_CNTRL                  0x20480300 /* [RW][32] RX Buffer Control Register */
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD           0x20480308 /* [RW][32] RX Buffer Packet Ready Threshold Register */
#define BCHP_GENET_0_RBUF_STATUS                 0x2048030c /* [RO][32] RX Buffer Status Register */
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL        0x20480310 /* [RW][32] RX Buffer Endianess Control Register */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL            0x20480314 /* [RW][32] RX Raw Checksum Control Register */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23          0x20480334 /* [RW][32] RXC Extraction Offset Register 23 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22          0x20480338 /* [RW][32] RXC Extraction Offset Register 22 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21          0x2048033c /* [RW][32] RXC Extraction Offset Register 21 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20          0x20480340 /* [RW][32] RXC Extraction Offset Register 20 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19          0x20480344 /* [RW][32] RXC Extraction Offset Register 19 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18          0x20480348 /* [RW][32] RXC Extraction Offset Register 18 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17          0x2048034c /* [RW][32] RXC Extraction Offset Register 17 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16          0x20480350 /* [RW][32] RXC Extraction Offset Register 16 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15          0x20480354 /* [RW][32] RXC Extraction Offset Register 15 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14          0x20480358 /* [RW][32] RXC Extraction Offset Register 14 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13          0x2048035c /* [RW][32] RXC Extraction Offset Register 13 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12          0x20480360 /* [RW][32] RXC Extraction Offset Register 12 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11          0x20480364 /* [RW][32] RXC Extraction Offset Register 11 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10          0x20480368 /* [RW][32] RXC Extraction Offset Register 10 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9           0x2048036c /* [RW][32] RXC Extraction Offset Register 9 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8           0x20480370 /* [RW][32] RXC Extraction Offset Register 8 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7           0x20480374 /* [RW][32] RXC Extraction Offset Register 7 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6           0x20480378 /* [RW][32] RXC Extraction Offset Register 6 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5           0x2048037c /* [RW][32] RXC Extraction Offset Register 5 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4           0x20480380 /* [RW][32] RXC Extraction Offset Register 4 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3           0x20480384 /* [RW][32] RXC Extraction Offset Register 3 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2           0x20480388 /* [RW][32] RXC Extraction Offset Register 2 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1           0x2048038c /* [RW][32] RXC Extraction Offset Register 1 */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0           0x20480390 /* [RW][32] RXC Extraction Offset Register 0 */
#define BCHP_GENET_0_RBUF_OVFL_PKT_CNT           0x20480394 /* [RO][32] RBUF Overflow Count Register */
#define BCHP_GENET_0_RBUF_ERR_CNT                0x20480398 /* [RO][32] Discard Error Packet Counter */
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL           0x2048039c /* [RW][32] RBUF Energy Control Register */
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL          0x204803a0 /* [RW][32] Pseudo Dual SRAM Control */
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL         0x204803a4 /* [RW][32] GENET Test MUX Control Register */
#define BCHP_GENET_0_RBUF_SPARE_REG_0            0x204803a8 /* [RW][32] GENET Spare Register 0 */
#define BCHP_GENET_0_RBUF_SPARE_REG_1            0x204803ac /* [RW][32] GENET Spare Register 1 */
#define BCHP_GENET_0_RBUF_SPARE_REG_2            0x204803b0 /* [RW][32] GENET Spare Register 2 */
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL         0x204803b4 /* [RW][32] GENET Transmit Buffer Size Control Register */

/***************************************************************************
 *CNTRL - RX Buffer Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: CNTRL :: reserved0 [31:20] */
#define BCHP_GENET_0_RBUF_CNTRL_reserved0_MASK                     0xfff00000
#define BCHP_GENET_0_RBUF_CNTRL_reserved0_SHIFT                    20

/* GENET_0_RBUF :: CNTRL :: ok_to_send_data_period [19:12] */
#define BCHP_GENET_0_RBUF_CNTRL_ok_to_send_data_period_MASK        0x000ff000
#define BCHP_GENET_0_RBUF_CNTRL_ok_to_send_data_period_SHIFT       12
#define BCHP_GENET_0_RBUF_CNTRL_ok_to_send_data_period_DEFAULT     0x0000000c

/* GENET_0_RBUF :: CNTRL :: reserved1 [11:11] */
#define BCHP_GENET_0_RBUF_CNTRL_reserved1_MASK                     0x00000800
#define BCHP_GENET_0_RBUF_CNTRL_reserved1_SHIFT                    11

/* GENET_0_RBUF :: CNTRL :: resume_threshold [10:03] */
#define BCHP_GENET_0_RBUF_CNTRL_resume_threshold_MASK              0x000007f8
#define BCHP_GENET_0_RBUF_CNTRL_resume_threshold_SHIFT             3
#define BCHP_GENET_0_RBUF_CNTRL_resume_threshold_DEFAULT           0x00000008

/* GENET_0_RBUF :: CNTRL :: bad_packet_discard_en [02:02] */
#define BCHP_GENET_0_RBUF_CNTRL_bad_packet_discard_en_MASK         0x00000004
#define BCHP_GENET_0_RBUF_CNTRL_bad_packet_discard_en_SHIFT        2
#define BCHP_GENET_0_RBUF_CNTRL_bad_packet_discard_en_DEFAULT      0x00000000

/* GENET_0_RBUF :: CNTRL :: align_2B [01:01] */
#define BCHP_GENET_0_RBUF_CNTRL_align_2B_MASK                      0x00000002
#define BCHP_GENET_0_RBUF_CNTRL_align_2B_SHIFT                     1
#define BCHP_GENET_0_RBUF_CNTRL_align_2B_DEFAULT                   0x00000000

/* GENET_0_RBUF :: CNTRL :: status_64B_en [00:00] */
#define BCHP_GENET_0_RBUF_CNTRL_status_64B_en_MASK                 0x00000001
#define BCHP_GENET_0_RBUF_CNTRL_status_64B_en_SHIFT                0
#define BCHP_GENET_0_RBUF_CNTRL_status_64B_en_DEFAULT              0x00000000

/***************************************************************************
 *PKT_RDY_THLD - RX Buffer Packet Ready Threshold Register
 ***************************************************************************/
/* GENET_0_RBUF :: PKT_RDY_THLD :: reserved0 [31:08] */
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD_reserved0_MASK              0xffffff00
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD_reserved0_SHIFT             8

/* GENET_0_RBUF :: PKT_RDY_THLD :: rbuf_pkt_rdy_thld [07:00] */
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD_rbuf_pkt_rdy_thld_MASK      0x000000ff
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD_rbuf_pkt_rdy_thld_SHIFT     0
#define BCHP_GENET_0_RBUF_PKT_RDY_THLD_rbuf_pkt_rdy_thld_DEFAULT   0x00000080

/***************************************************************************
 *STATUS - RX Buffer Status Register
 ***************************************************************************/
/* GENET_0_RBUF :: STATUS :: reserved0 [31:03] */
#define BCHP_GENET_0_RBUF_STATUS_reserved0_MASK                    0xfffffff8
#define BCHP_GENET_0_RBUF_STATUS_reserved0_SHIFT                   3

/* GENET_0_RBUF :: STATUS :: acpi_intr_active [02:02] */
#define BCHP_GENET_0_RBUF_STATUS_acpi_intr_active_MASK             0x00000004
#define BCHP_GENET_0_RBUF_STATUS_acpi_intr_active_SHIFT            2

/* GENET_0_RBUF :: STATUS :: mpd_intr_active [01:01] */
#define BCHP_GENET_0_RBUF_STATUS_mpd_intr_active_MASK              0x00000002
#define BCHP_GENET_0_RBUF_STATUS_mpd_intr_active_SHIFT             1

/* GENET_0_RBUF :: STATUS :: wol_mode [00:00] */
#define BCHP_GENET_0_RBUF_STATUS_wol_mode_MASK                     0x00000001
#define BCHP_GENET_0_RBUF_STATUS_wol_mode_SHIFT                    0

/***************************************************************************
 *ENDIANESS_CNTRL - RX Buffer Endianess Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: ENDIANESS_CNTRL :: reserved0 [31:03] */
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_reserved0_MASK           0xfffffff8
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_reserved0_SHIFT          3

/* GENET_0_RBUF :: ENDIANESS_CNTRL :: swap_en [02:02] */
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_swap_en_MASK             0x00000004
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_swap_en_SHIFT            2
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_swap_en_DEFAULT          0x00000001

/* GENET_0_RBUF :: ENDIANESS_CNTRL :: reserved1 [01:00] */
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_reserved1_MASK           0x00000003
#define BCHP_GENET_0_RBUF_ENDIANESS_CNTRL_reserved1_SHIFT          0

/***************************************************************************
 *RXCHK_CNTRL - RX Raw Checksum Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: RXCHK_CNTRL :: reserved0 [31:07] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_reserved0_MASK               0xffffff80
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_reserved0_SHIFT              7

/* GENET_0_RBUF :: RXCHK_CNTRL :: use_ipv4datagram_len [06:06] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_use_ipv4datagram_len_MASK    0x00000040
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_use_ipv4datagram_len_SHIFT   6
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_use_ipv4datagram_len_DEFAULT 0x00000000

/* GENET_0_RBUF :: RXCHK_CNTRL :: L3_parse_dis [05:05] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_L3_parse_dis_MASK            0x00000020
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_L3_parse_dis_SHIFT           5
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_L3_parse_dis_DEFAULT         0x00000000

/* GENET_0_RBUF :: RXCHK_CNTRL :: skip_fcs [04:04] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_skip_fcs_MASK                0x00000010
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_skip_fcs_SHIFT               4
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_skip_fcs_DEFAULT             0x00000000

/* GENET_0_RBUF :: RXCHK_CNTRL :: reserved1 [03:01] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_reserved1_MASK               0x0000000e
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_reserved1_SHIFT              1

/* GENET_0_RBUF :: RXCHK_CNTRL :: rxchk_en [00:00] */
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_rxchk_en_MASK                0x00000001
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_rxchk_en_SHIFT               0
#define BCHP_GENET_0_RBUF_RXCHK_CNTRL_rxchk_en_DEFAULT             0x00000000

/***************************************************************************
 *RXC_OFFSET_23 - RXC Extraction Offset Register 23
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_23 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_23 :: extr_offset_47 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_47_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_47_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_47_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_23 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_23 :: extr_offset_46 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_46_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_46_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_23_extr_offset_46_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_22 - RXC Extraction Offset Register 22
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_22 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_22 :: extr_offset_45 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_45_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_45_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_45_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_22 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_22 :: extr_offset_44 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_44_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_44_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_22_extr_offset_44_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_21 - RXC Extraction Offset Register 21
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_21 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_21 :: extr_offset_43 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_43_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_43_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_43_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_21 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_21 :: extr_offset_42 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_42_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_42_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_21_extr_offset_42_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_20 - RXC Extraction Offset Register 20
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_20 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_20 :: extr_offset_41 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_41_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_41_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_41_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_20 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_20 :: extr_offset_40 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_40_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_40_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_20_extr_offset_40_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_19 - RXC Extraction Offset Register 19
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_19 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_19 :: extr_offset_39 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_39_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_39_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_39_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_19 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_19 :: extr_offset_38 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_38_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_38_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_19_extr_offset_38_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_18 - RXC Extraction Offset Register 18
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_18 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_18 :: extr_offset_37 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_37_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_37_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_37_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_18 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_18 :: extr_offset_36 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_36_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_36_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_18_extr_offset_36_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_17 - RXC Extraction Offset Register 17
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_17 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_17 :: extr_offset_35 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_35_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_35_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_35_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_17 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_17 :: extr_offset_34 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_34_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_34_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_17_extr_offset_34_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_16 - RXC Extraction Offset Register 16
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_16 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_16 :: extr_offset_33 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_33_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_33_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_33_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_16 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_16 :: extr_offset_32 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_32_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_32_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_16_extr_offset_32_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_15 - RXC Extraction Offset Register 15
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_15 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_15 :: extr_offset_31 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_31_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_31_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_31_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_15 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_15 :: extr_offset_30 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_30_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_30_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_15_extr_offset_30_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_14 - RXC Extraction Offset Register 14
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_14 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_14 :: extr_offset_29 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_29_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_29_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_29_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_14 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_14 :: extr_offset_28 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_28_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_28_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_14_extr_offset_28_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_13 - RXC Extraction Offset Register 13
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_13 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_13 :: extr_offset_27 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_27_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_27_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_27_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_13 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_13 :: extr_offset_26 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_26_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_26_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_13_extr_offset_26_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_12 - RXC Extraction Offset Register 12
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_12 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_12 :: extr_offset_25 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_25_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_25_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_25_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_12 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_12 :: extr_offset_24 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_24_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_24_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_12_extr_offset_24_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_11 - RXC Extraction Offset Register 11
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_11 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_11 :: extr_offset_23 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_23_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_23_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_23_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_11 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_11 :: extr_offset_22 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_22_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_22_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_11_extr_offset_22_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_10 - RXC Extraction Offset Register 10
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_10 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_reserved0_MASK             0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_reserved0_SHIFT            27

/* GENET_0_RBUF :: RXC_OFFSET_10 :: extr_offset_21 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_21_MASK        0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_21_SHIFT       16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_21_DEFAULT     0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_10 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_reserved1_MASK             0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_reserved1_SHIFT            11

/* GENET_0_RBUF :: RXC_OFFSET_10 :: extr_offset_20 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_20_MASK        0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_20_SHIFT       0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_10_extr_offset_20_DEFAULT     0x00000000

/***************************************************************************
 *RXC_OFFSET_9 - RXC Extraction Offset Register 9
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_9 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_9 :: extr_offset_19 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_19_MASK         0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_19_SHIFT        16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_19_DEFAULT      0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_9 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_9 :: extr_offset_18 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_18_MASK         0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_18_SHIFT        0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_9_extr_offset_18_DEFAULT      0x00000000

/***************************************************************************
 *RXC_OFFSET_8 - RXC Extraction Offset Register 8
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_8 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_8 :: extr_offset_17 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_17_MASK         0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_17_SHIFT        16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_17_DEFAULT      0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_8 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_8 :: extr_offset_16 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_16_MASK         0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_16_SHIFT        0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_8_extr_offset_16_DEFAULT      0x00000000

/***************************************************************************
 *RXC_OFFSET_7 - RXC Extraction Offset Register 7
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_7 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_7 :: extr_offset_15 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_15_MASK         0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_15_SHIFT        16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_15_DEFAULT      0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_7 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_7 :: extr_offset_14 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_14_MASK         0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_14_SHIFT        0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_7_extr_offset_14_DEFAULT      0x00000000

/***************************************************************************
 *RXC_OFFSET_6 - RXC Extraction Offset Register 6
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_6 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_6 :: extr_offset_13 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_13_MASK         0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_13_SHIFT        16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_13_DEFAULT      0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_6 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_6 :: extr_offset_12 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_12_MASK         0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_12_SHIFT        0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_6_extr_offset_12_DEFAULT      0x00000000

/***************************************************************************
 *RXC_OFFSET_5 - RXC Extraction Offset Register 5
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_5 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_5 :: extr_offset_11 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_11_MASK         0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_11_SHIFT        16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_11_DEFAULT      0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_5 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_5 :: extr_offset_10 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_10_MASK         0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_10_SHIFT        0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_5_extr_offset_10_DEFAULT      0x00000000

/***************************************************************************
 *RXC_OFFSET_4 - RXC Extraction Offset Register 4
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_4 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_4 :: extr_offset_9 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_9_MASK          0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_9_SHIFT         16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_9_DEFAULT       0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_4 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_4 :: extr_offset_8 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_8_MASK          0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_8_SHIFT         0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_4_extr_offset_8_DEFAULT       0x00000000

/***************************************************************************
 *RXC_OFFSET_3 - RXC Extraction Offset Register 3
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_3 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_3 :: extr_offset_7 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_7_MASK          0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_7_SHIFT         16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_7_DEFAULT       0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_3 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_3 :: extr_offset_6 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_6_MASK          0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_6_SHIFT         0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_3_extr_offset_6_DEFAULT       0x00000000

/***************************************************************************
 *RXC_OFFSET_2 - RXC Extraction Offset Register 2
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_2 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_2 :: extr_offset_5 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_5_MASK          0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_5_SHIFT         16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_5_DEFAULT       0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_2 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_2 :: extr_offset_4 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_4_MASK          0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_4_SHIFT         0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_2_extr_offset_4_DEFAULT       0x00000000

/***************************************************************************
 *RXC_OFFSET_1 - RXC Extraction Offset Register 1
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_1 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_1 :: extr_offset_3 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_3_MASK          0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_3_SHIFT         16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_3_DEFAULT       0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_1 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_1 :: extr_offset_2 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_2_MASK          0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_2_SHIFT         0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_1_extr_offset_2_DEFAULT       0x00000000

/***************************************************************************
 *RXC_OFFSET_0 - RXC Extraction Offset Register 0
 ***************************************************************************/
/* GENET_0_RBUF :: RXC_OFFSET_0 :: reserved0 [31:27] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_reserved0_MASK              0xf8000000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_reserved0_SHIFT             27

/* GENET_0_RBUF :: RXC_OFFSET_0 :: extr_offset_1 [26:16] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_1_MASK          0x07ff0000
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_1_SHIFT         16
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_1_DEFAULT       0x00000000

/* GENET_0_RBUF :: RXC_OFFSET_0 :: reserved1 [15:11] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_reserved1_MASK              0x0000f800
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_reserved1_SHIFT             11

/* GENET_0_RBUF :: RXC_OFFSET_0 :: extr_offset_0 [10:00] */
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_0_MASK          0x000007ff
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_0_SHIFT         0
#define BCHP_GENET_0_RBUF_RXC_OFFSET_0_extr_offset_0_DEFAULT       0x00000000

/***************************************************************************
 *OVFL_PKT_CNT - RBUF Overflow Count Register
 ***************************************************************************/
/* GENET_0_RBUF :: OVFL_PKT_CNT :: rbuf_overflow_count [31:00] */
#define BCHP_GENET_0_RBUF_OVFL_PKT_CNT_rbuf_overflow_count_MASK    0xffffffff
#define BCHP_GENET_0_RBUF_OVFL_PKT_CNT_rbuf_overflow_count_SHIFT   0
#define BCHP_GENET_0_RBUF_OVFL_PKT_CNT_rbuf_overflow_count_DEFAULT 0x00000000

/***************************************************************************
 *ERR_CNT - Discard Error Packet Counter
 ***************************************************************************/
/* GENET_0_RBUF :: ERR_CNT :: error_packet_counter [31:00] */
#define BCHP_GENET_0_RBUF_ERR_CNT_error_packet_counter_MASK        0xffffffff
#define BCHP_GENET_0_RBUF_ERR_CNT_error_packet_counter_SHIFT       0
#define BCHP_GENET_0_RBUF_ERR_CNT_error_packet_counter_DEFAULT     0x00000000

/***************************************************************************
 *ENERGY_CNTRL - RBUF Energy Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: ENERGY_CNTRL :: reserved0 [31:02] */
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_reserved0_MASK              0xfffffffc
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_reserved0_SHIFT             2

/* GENET_0_RBUF :: ENERGY_CNTRL :: pm_en [01:01] */
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_pm_en_MASK                  0x00000002
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_pm_en_SHIFT                 1
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_pm_en_DEFAULT               0x00000000

/* GENET_0_RBUF :: ENERGY_CNTRL :: eee_en [00:00] */
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_eee_en_MASK                 0x00000001
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_eee_en_SHIFT                0
#define BCHP_GENET_0_RBUF_ENERGY_CNTRL_eee_en_DEFAULT              0x00000000

/***************************************************************************
 *PD_SRAM_CNTRL - Pseudo Dual SRAM Control
 ***************************************************************************/
/* GENET_0_RBUF :: PD_SRAM_CNTRL :: reserved0 [31:16] */
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_reserved0_MASK             0xffff0000
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_reserved0_SHIFT            16

/* GENET_0_RBUF :: PD_SRAM_CNTRL :: umac_dma_tx_mbist_tm [15:08] */
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_tx_mbist_tm_MASK  0x0000ff00
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_tx_mbist_tm_SHIFT 8
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_tx_mbist_tm_DEFAULT 0x00000000

/* GENET_0_RBUF :: PD_SRAM_CNTRL :: umac_dma_rx_mbist_tm [07:00] */
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_rx_mbist_tm_MASK  0x000000ff
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_rx_mbist_tm_SHIFT 0
#define BCHP_GENET_0_RBUF_PD_SRAM_CNTRL_umac_dma_rx_mbist_tm_DEFAULT 0x00000000

/***************************************************************************
 *TEST_MUX_CNTRL - GENET Test MUX Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: TEST_MUX_CNTRL :: reserved0 [31:03] */
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL_reserved0_MASK            0xfffffff8
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL_reserved0_SHIFT           3

/* GENET_0_RBUF :: TEST_MUX_CNTRL :: tmux_sel [02:00] */
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL_tmux_sel_MASK             0x00000007
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL_tmux_sel_SHIFT            0
#define BCHP_GENET_0_RBUF_TEST_MUX_CNTRL_tmux_sel_DEFAULT          0x00000000

/***************************************************************************
 *SPARE_REG_0 - GENET Spare Register 0
 ***************************************************************************/
/* GENET_0_RBUF :: SPARE_REG_0 :: spare_word [31:00] */
#define BCHP_GENET_0_RBUF_SPARE_REG_0_spare_word_MASK              0xffffffff
#define BCHP_GENET_0_RBUF_SPARE_REG_0_spare_word_SHIFT             0
#define BCHP_GENET_0_RBUF_SPARE_REG_0_spare_word_DEFAULT           0x00000000

/***************************************************************************
 *SPARE_REG_1 - GENET Spare Register 1
 ***************************************************************************/
/* GENET_0_RBUF :: SPARE_REG_1 :: spare_word [31:00] */
#define BCHP_GENET_0_RBUF_SPARE_REG_1_spare_word_MASK              0xffffffff
#define BCHP_GENET_0_RBUF_SPARE_REG_1_spare_word_SHIFT             0
#define BCHP_GENET_0_RBUF_SPARE_REG_1_spare_word_DEFAULT           0x00000000

/***************************************************************************
 *SPARE_REG_2 - GENET Spare Register 2
 ***************************************************************************/
/* GENET_0_RBUF :: SPARE_REG_2 :: spare_word [31:00] */
#define BCHP_GENET_0_RBUF_SPARE_REG_2_spare_word_MASK              0xffffffff
#define BCHP_GENET_0_RBUF_SPARE_REG_2_spare_word_SHIFT             0
#define BCHP_GENET_0_RBUF_SPARE_REG_2_spare_word_DEFAULT           0x00000000

/***************************************************************************
 *TBUF_SIZE_CNTL - GENET Transmit Buffer Size Control Register
 ***************************************************************************/
/* GENET_0_RBUF :: TBUF_SIZE_CNTL :: spare_word [31:02] */
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_spare_word_MASK           0xfffffffc
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_spare_word_SHIFT          2
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_spare_word_DEFAULT        0x00000000

/* GENET_0_RBUF :: TBUF_SIZE_CNTL :: cfg_tbuf_size_2_or_3 [01:01] */
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_2_or_3_MASK 0x00000002
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_2_or_3_SHIFT 1
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_2_or_3_DEFAULT 0x00000000

/* GENET_0_RBUF :: TBUF_SIZE_CNTL :: cfg_tbuf_size_not_64 [00:00] */
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_not_64_MASK 0x00000001
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_not_64_SHIFT 0
#define BCHP_GENET_0_RBUF_TBUF_SIZE_CNTL_cfg_tbuf_size_not_64_DEFAULT 0x00000000

#endif /* #ifndef BCHP_GENET_0_RBUF_H__ */

/* End of File */
